### ISSUE TITLE
peer_connection.obj : error LNK2019

### ISSUE THREAD

**Issue by tjhappy** [microsoft/MixedReality-WebRTC#102]
Hi,
I builded external\webrtc-uwp-sdk  .
I am getting a build error after pulling the lastest master .
I used my  webrtc.lib.
I am using Visual Studio 2019 v16.3.4. I am not upgrading to a newer toolset or windows sdk when I'm loading the solution.

Error,just x64

1>------ Rebuild All started: Project: Microsoft.MixedReality.WebRTC.Native.Win32, Configuration: Debug x64 ------
1>pch.cpp
1>api.cpp
1>audio_frame_observer.cpp
1>data_channel.cpp
1>peer_connection.cpp
1>video_frame_observer.cpp
1>sdp_utils.cpp
1>str.cpp
1>Generating Code...
1>   Creating library ..\..\..\..\bin\Win32\x64\Debug\Microsoft.MixedReality.WebRTC.Native.lib and object ..\..\..\..\bin\Win32\x64\Debug\Microsoft.MixedReality.WebRTC.Native.exp
1>peer_connection.obj : error LNK2019: unresolved external symbol "class std::optional<enum webrtc::SdpType> __cdecl webrtc::SdpTypeFromString(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?SdpTypeFromString@webrtc@@YA?AV?$optional@W4SdpType@webrtc@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@@Z) referenced in function "public: bool __cdecl Microsoft::MixedReality::WebRTC::PeerConnection::SetRemoteDescription(char const *,char const *)" (?SetRemoteDescription@PeerConnection@WebRTC@MixedReality@Microsoft@@QEAA_NPEBD0@Z)
1>..\..\..\..\bin\Win32\x64\Debug\Microsoft.MixedReality.WebRTC.Native.dll : fatal error LNK1120: 1 unresolved externals
1>Done building project "Microsoft.MixedReality.WebRTC.Native.Win32.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by djee-ms** [comment]
Hi @tjhappy,

This is a mismatch between `webrtc.lib` and `Microsoft.MixedReality.WebRTC.Native.dll`; one of them has been compiled with C++17, the other not. As a result one of them uses `std::optional` and the other `absl::optional`, which are not binary compatible.

If you look at `build.ps1` it is passing the `--cpp17` flag to `gn`/`ninja`:
https://github.com/microsoft/MixedReality-WebRTC/blob/fff8fbdf9f24a5e133211d4fd15dd77f7ac19135/tools/build/build.ps1#L110

The solution also has the `/std:cpp17` flag:
https://github.com/microsoft/MixedReality-WebRTC/blob/fff8fbdf9f24a5e133211d4fd15dd77f7ac19135/libs/Microsoft.MixedReality.WebRTC.Native/src/win32/Microsoft.MixedReality.WebRTC.Native.Win32.vcxproj#L91
https://github.com/microsoft/MixedReality-WebRTC/blob/fff8fbdf9f24a5e133211d4fd15dd77f7ac19135/libs/Microsoft.MixedReality.WebRTC.Native/src/uwp/Microsoft.MixedReality.WebRTC.Native.UWP.vcxproj#L106

So I am guessing this may be an error on your side while compiling one or the other?

**Comment by tjhappy** [comment]
Thanks.
I compiled with PS and got the right results. Previously, I used "call Python" $(projectdir).. \.. \.. \.. \.. \.. \ scripts \ run. Py "- a prepare build - t webrtc - P win -- CPUs $(platformtarget) - C $(configuration) - nocolor -- nowrapper -- cpp17“， Got the mistake.

**Comment by djee-ms** [comment]
Not sure why it happened, but glad that's fixed for you!
