### ISSUE TITLE
Can work on .NET Framework ? 

### ISSUE THREAD

**Issue by dsp85103** [microsoft/MixedReality-WebRTC#113]
I try install MixedReality-WebRTC by nuget in my case what window form application depends on .net framework 4.6. 
But I couldn't using Microsoft.MixedReality library.
Is it possible?

**Comment by djee-ms** [comment]
I don't know. We do not support .NET Framework officially, and there is no plan to do so.
See https://github.com/dotnet/standard/issues/481 for issues about consuming .NET Standard 2.0 NuGet packages from a .NET Framework project.

**Comment by dsp85103** [comment]
Thank for ur reply. 
I'll keep research. If I resolve that. I'll report here. 👌

**Comment by djee-ms** [comment]
I am closing this issue because we have no other ask and no plan to support .NET Framework. We do support .NET Standard/Core instead, which is hopefully the way going forward.
