### ISSUE TITLE
HoloLens 1 - Single eye rendering

### ISSUE THREAD

**Issue by CabbageWarrior** [microsoft/MixedReality-WebRTC#117]
Hi everybody,
I followed the entire tutorial for the Unity integration and everything is working well.

When I built on HoloLens, however, I noticed that the video players were rendering only on the left eye.

The solution I found on the internet was about a couple of instructions to add to the `YUVFeedShaderUnlit` shader:

![Shader](https://user-images.githubusercontent.com/27804302/67940929-debbd100-fbd4-11e9-99e3-ef3abdddc4d4.png)

I hope this message is helpful and I have not made any implementation errors. Otherwise, please let me know how to fix this little problem.

Greetings!
Riccardo

**Comment by eirikhollis** [comment]
Duplicate of #110

**Comment by CabbageWarrior** [comment]
Thank you very much! Sorry but I didn't find that post during my research.
