### ISSUE TITLE
dataChannel.BufferingChanged is never fired

### ISSUE THREAD

**Issue by jahnotto** [microsoft/MixedReality-WebRTC#119]
I am listening to dataChannel.BufferingChanged in order to ensure that I don't flood the message buffer. However, this event is never fired.

Perhaps I misunderstand -- is it only fired if I'm reaching the buffer limit?

I'm using MR-WebRTC 1.0.

**Comment by djee-ms** [comment]
Are you sending data fast enough to have buffering at all? If I remember correctly by default if the data can be sent immediately then it's not buffered, so there is no reason to do so and the event is not fired.

**Comment by jahnotto** [comment]
Ok, that should explain it. I'm sending fairly small messages 30-40 times per second.
