### ISSUE TITLE
Release build fails due to WrapperGlue issues while Debug build is successful

### ISSUE THREAD

**Issue by aleneum** [microsoft/MixedReality-WebRTC#125]
With a freshly cloned repository iI get the following error when building `Microsoft.MixedReality.WebRTC.Native.UWP` as `Release`:

```
The object or library file 'D:\workspace\wrtc\packages\Microsoft.MixedReality.WebRTC.Native.Core.WinRT.x64.Release.1.0.1
\build\native\..\..\lib\native\lib\uap10.0\x64\Release\Org.WebRtc.WrapperGlue.lib'
was created with an older compiler than other objects; rebuild old objects and libraries
```
This error appears for all architectures (`x86`, `x64`, `ARM`) with the related package path.
Interestingly, the `Debug` build succeeds [1]. The `Debug` artifacts also work as expected in a Unity project. I tried to manually update nuget packages but the result stays the same. 

--

[1]: Well, initially it fails with a metric ton of output but running the build job again seems to 'solve' it. Also I have to build the `x64` version before the `x86` build can succeed. The later issue seems to be related to the test target.

**Comment by djee-ms** [comment]
@aleneum what compiler are you using?

The [1] issue is about the inability to add an architecture-specific dependency to the C# test project, which requires the native C++ DLL to run. Instead an architecture is randomly picked up (x64 here). Building x64 makes the DLL appear, so the C# test project later builds in all other configs. This is less than ideal, but we didn't find a way to work around that so far. All other build errors should be related to that one missing DLL.

**Comment by aleneum** [comment]
> what compiler are you using?

`19.23.28107` and Platform Toolset `v142` (Visual Studio `16.3.9`) (detailed build log: [Microsoft.MixedReality.WebRTC.Native.UWP_x64_Release.txt](https://github.com/microsoft/MixedReality-WebRTC/files/3864797/Microsoft.MixedReality.WebRTC.Native.UWP_x64_Release.txt))

> Building x64 makes the DLL appear, so the C# test project later builds in all other configs. This is less than ideal, but we didn't find a way to work around that so far.

Imho, this is just a minor inconvenience. Thanks to your documentation and responses to previous issues it hasn't been hard to work around this one.

> All other build errors should be related to that one missing DLL.

yeah, `Debug` builts work fine after the `x64` DLL has been compiled. Do you have an idea what causes the `Release` builts to fail with the 'old compiler' error? Both , `Release` and `Debug` builts of `Org.WebRtc.WrapperGlue.lib` in `Microsoft.MixedReality.WebRTC.Native.Core.WinRT.x64.<variant>.1.0.1` have similar creation dates and (probably) are built with a similar tool chain, aren't they?

**Comment by djee-ms** [comment]
Yes they're all built with Visual Studio 2017, so I assume VS 2019 introduced somewhere some incompatibility. I'm guessing the reason Debug works and not Release is hinted here (/LTCG):
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1047?view=vs-2019

**Comment by djee-ms** [comment]
I just realized I am using v141, which the current default in the `Microsoft.MixedReality.WebRTC.sln`. This is why I couldn't notice that bug earlier. Do you require v142, or can you work around for now using v141?

**Comment by djee-ms** [comment]
Actually we currently cannot upgrade the underlying code to build with VS2019 because it is not supported by the Google build system. So it's unfortunate but it seems there's no way to fix that and make the project buildable with VS2019.

**Comment by aleneum** [comment]
> Yes they're all built with Visual Studio 2017, so I assume VS 2019 introduced somewhere some incompatibility. I'm guessing the reason Debug works and not Release is hinted here (/LTCG)

I see. Thanks for the info!

> So it's unfortunate but it seems there's no way to fix that and make the project buildable with VS2019.

Fair enough. I stitched together a Unity package with the pre-compiled Nuget packages as described in the [documentation](https://microsoft.github.io/MixedReality-WebRTC/manual/installation.html#unity-integration) which works fine for now. I can confirm the much better performance of Release builds in contrast to Debug builds. I will give v141 a try since there are a lot HoloLens/MRTK tools/projects out there that require it.

Thank you for your feedback and your work on this project 👍 !

**Comment by aleneum** [comment]
Just a quick remark: WebRTC compiles fine with Visual Studio 2019 and v141. Just make sure to install the optional features `Universal Windows Platform development -> C++ (v141) Universal Platform tools` and (maybe not necessary) `Desktop development with C++ -> MSVC v141 - VS 2017 C++ x64/x86 build tools` (Visual Studio installer and chose `Modify`). You probably have to reboot before v141 is detected correctly. I also changed the minimal version of `TestAppUwp` from `1803 (Build 17134)` to `1809 (Build 17763)` (can be done by right-clicking the `TestAppUwp` project and choosing `Properties`) without issues.
