### ISSUE TITLE
Not working AEC(Acoustic Echo Canceler) for Window desktop

### ISSUE THREAD

**Issue by parancode** [microsoft/MixedReality-WebRTC#127]
Default MixedReality-WebRTC Library use not working AEC.
Especially on laptops without headsets.
Each one was tested in a different room.

So, I added the under code.

apm_ = webrtc::AudioProcessingBuilder().Create();

webrtc::AudioProcessing::Config config;
config.echo_canceller.enabled = true;
config.echo_canceller.mobile_mode = false;
config.high_pass_filter.enabled = true;
config.gain_controller2.enabled = true;
apm_->ApplyConfig(config);

apm_->echo_cancellation()->set_suppression_level(
webrtc::EchoCancellation::kModerateSuppression);
apm_->echo_cancellation()->enable_metrics(true);
apm_->echo_cancellation()->Enable(true);
apm_->echo_control_mobile()->Enable(false);
apm_->set_stream_delay_ms(0);
apm_->noise_suppression()->set_level(webrtc::NoiseSuppression::Level::kVeryHigh);
apm_->noise_suppression()->Enable(true);
apm_->gain_control()->set_analog_level_limits(0, 255);
apm_->gain_control()->set_mode(webrtc::GainControl::Mode::kAdaptiveAnalog);
apm_->gain_control()->Enable(true);
apm_->voice_detection()->Enable(true);
apm_->voice_detection()->set_likelihood(webrtc::VoiceDetection::kModerateLikelihood);
apm_->high_pass_filter()->Enable(true);
apm_->Initialize();

Doesn't work though.

**Comment by jameszhong2008** [comment]
@parancode Did you solved this issue by adding above code? I come across the same question.
