### ISSUE TITLE
Upgrade to WebRTC m75

### ISSUE THREAD

**Issue by djee-ms** [microsoft/MixedReality-WebRTC#13]
The WebRTC UWP team finished their upgrade to m75 and are now providing a branch for it. This notably includes support for ARM64.

**Comment by eirikhollis** [comment]
Any updates on this? ARM64 would be a welcome improvement.

**Comment by djee-ms** [comment]
Upgrading to m75 is unlikely to ever happen at this stage, as that branch is unmaintained and is getting old. Bt we want to get ARM64 support via Google's master branch instead. However currently there is no UWP video/audio capture there, so that blocks us from upgrading. We have another Microsoft team working on UWP support, so hopefully when they merge their work we can move forward with the upgrade. See _e.g._ https://webrtc-review.googlesource.com/c/src/+/167021 for the on-going work.

**Comment by djee-ms** [comment]
Closing as we will not do that upgrade.
