### ISSUE TITLE
AddDataChannelAsync results in InvalidOperationException

### ISSUE THREAD

**Issue by michael-house** [microsoft/MixedReality-WebRTC#145]
I'm attempting to create a connection between peers and open a data channel. Both peers fire their 
`Connected` events, and ICE candidates are exchanged. Both peers show `Initialized` and `Connected` to be true.
However, when then calling `AddDataChannelAsync("Main", true, true);`, I catch an InvalidOperationException. The fully expanded aggregate exceptions included below.

[From the source](https://github.com/microsoft/MixedReality-WebRTC/blob/83119150dbce530a281c0be12bb231a8fadbc7f2/libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs#L1111),
`/// <exception xref="InvalidOperationException">The peer connection is not intialized.</exception>
/// <exception xref="InvalidOperationException">SCTP not negotiated.</exception>`

Appears to describe two different possible exceptions of the type I'm seeing. Based on the state of things, I'm fairly sure it's not the first. The second is something I'm not sure how confirm as I didn't see any documentation on how to specifically negotiate. 

Perhaps it's the SCTP configuration or something else not in the documentation. Any idea on next steps for this?

> InvalidOperationException: Operation is not valid due to the current state of the object.
Microsoft.MixedReality.WebRTC.Interop.Utils.ThrowOnErrorCode (System.UInt32 res) (at <c56b6ea76b85487f9304292eaf9f9d89>:0)
Microsoft.MixedReality.WebRTC.PeerConnection+<>c__DisplayClass84_0.<AddDataChannelAsyncImpl>b__0 () (at <c56b6ea76b85487f9304292eaf9f9d89>:0)
System.Threading.Tasks.Task`1[TResult].InnerInvoke () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Threading.Tasks.Task.Execute () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
Microsoft.MixedReality.WebRTC.PeerConnection+<AddDataChannelAsyncImpl>d__84.MoveNext () (at <c56b6ea76b85487f9304292eaf9f9d89>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
Microsoft.MixedReality.WebRTC.PeerConnection+<AddDataChannelAsync>d__83.MoveNext () (at <c56b6ea76b85487f9304292eaf9f9d89>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
ObjectTheory.Core.Universal.Common.Networking.WebRTC.WebRTCPeer+<AddMainDataChannel>d__26.MoveNext () (at Assets/Core/OT.Core.Universal/Common/Networking/WebRTC/WebRTCPeer.cs:207)
UnityEngine.Debug:LogException(Exception, Object)

>ObjectTheory.Core.Unity.Common.Logging.UnityDebugLogger:LogException(String, Exception, Object) (at Assets/Core/OT.Core.Unity/Scripts/Common/Logging/UnityDebugLogger.cs:24)
ObjectTheory.Core.Universal.Common.Logging.<>c__DisplayClass10_0:<LogException>b__0(ILogger) (at Assets/Core/OT.Core.Universal/Common/Logging/LogManager.cs:89)
System.Collections.Generic.List`1:ForEach(Action`1)
ObjectTheory.Core.Universal.Common.Logging.LogManager:LogException(String, Exception, Object, Boolean) (at Assets/Core/OT.Core.Universal/Common/Logging/LogManager.cs:89)
ObjectTheory.Core.Universal.Common.Networking.WebRTC.<AddMainDataChannel>d__26:MoveNext() (at Assets/Core/OT.Core.Universal/Common/Networking/WebRTC/WebRTCPeer.cs:214)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
Microsoft.MixedReality.WebRTC.<AddDataChannelAsync>d__83:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetException(Exception)
Microsoft.MixedReality.WebRTC.<AddDataChannelAsyncImpl>d__84:MoveNext()
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

**Comment by djee-ms** [comment]
Hi @michael-house,
`SCTP not negotiated.` means you open a data channel after negotiating an SDP session without SCTP negotiation. This is an unfortunate limitation of the Google implementation. If you use data channels at all, you need to open at least 1 data channel **before** you connect to the remote peer, so that the SCTP negotiation is done and SSL certificates etc. are negotiated. Otherwise any subsequent opening fails because it's too late to do that negotiation. This is unfortunately not really well documenting as I see looking for comments now. I will see how we can improve that. See [this comment in TestAppUWP](https://github.com/microsoft/MixedReality-WebRTC/blob/83119150dbce530a281c0be12bb231a8fadbc7f2/examples/TestAppUwp/MainPage.xaml.cs#L499-L502) about the error.

**Comment by michael-house** [comment]
Hi @djee-ms, thanks for the response. This means I need to:

1. Initialize PeerConnection
2. AddDataChannelAsync
3. Create connection (create offer or reply)

Right? Do I create the data channel on the offering peer, the answering peer, both or does it matter?

**Comment by michael-house** [comment]
I've tried in the order I suggested above, still the same exception.

Perhaps I wasn't clear: "SCTP not negotiated" was just one of the other exception possibilities I was seeing from the documentation. It's not the error text I am receiving. Maybe 'Operation is not valid due to the current state of the object' is the expected description for that exception, you know better than me.

So, attempting to create a data channel before the peer is connected still results in the exception: 
>InvalidOperationException: Operation is not valid due to the current state of the object.

**Comment by djee-ms** [comment]
1. `PeerConnection.InitializeAsync()`
2. `PeerConnection.AddDataChannelAsync()`
3. `PeerConnection.CreateOffer()`

Note that in step 3. doing a `CreateAnswer()` is an error and will not work. You need to call `AddDataChannelAsync()` before `CreateOffer()`, which means you need to do it on the caller side (not the callee side). Also if you use out-of-band channels (explicit ID) then you need to add the data channel on both sides. For in-band channels (generated ID) the channel will be automatically created on the callee. If you want to have a look at an example, the TestAppUWP example app is doing just that as linked above.

**Comment by michael-house** [comment]
Excellent, thanks Jerome, everything is working now as expected. It would be nice if the exception was a bit more clear, like saying `SCTP not negotiated` instead of `Operation is not valid due to the current state of the object.`. Thanks for all your hard work.

**Comment by djee-ms** [comment]
`AddDataChannelAsync()` should now throw a specific `SctpNotNegotiatedException` for this common misuse case. Also added a test for it to make sure this works.
