### ISSUE TITLE
No ICE Gathering event fired

### ISSUE THREAD

**Issue by drejx** [microsoft/MixedReality-WebRTC#146]
In the current SDK there is no event which tells the user when ICE gathering has completed.  This can cause issues if an application wishes to wait for ICE gathering to be complete before advancing further.  

Based on the remarks in the IceConnectionState enum it seems it's grouped into the IceConnectionState enums:

```
namespace Microsoft.MixedReality.WebRTC
{
    //
    // Summary:
    //     State of an ICE connection.
    //
    // Remarks:
    //     Due to the underlying implementation, this is currently a mix of the RTPIceGatheringState
    //     and the RTPPeerConnectionState from the WebRTC 1.0 standard.
    public enum IceConnectionState
    {
        //
        // Summary:
        //     Newly created ICE connection. This is the starting state.
        New = 0,
        //
        // Summary:
        //     ICE connection received an offer, but transports are not writable yet.
        Checking = 1,
        ....
        <snip>
```

But the `PeerConnection.IceStateChanged` event is not fired during ICE gathering (i.e. right after the initial CreateOffer(), where SetLocalDescription() is internally called).

Looking a bit closer the `IceConnectionState` enum is actually a 1:1 mapping to `RTCIceConnectionState` and doesn't have any `RTCIceGatheringState`, so maybe the code comment is unintended?

Note that I've been migrating an application from [webrtc-uwp-sdk](https://github.com/webrtc-uwp/webrtc-uwp-sdk) to the MixedReality-SDK and in the former there is an ICE Gathering event which gets fired and the final event is `RTCIceGatheringState_complete`.  This event is also fired in standard javascript implementations (Chrome/Firefox) so believe it might be a bug in the MixedReality-SDK.

Cheers,
Andrej

**Comment by djee-ms** [comment]
The comments are correct. The IceGatheringState event is not implemented.

**Comment by djee-ms** [comment]
Fixed. I added an example use in TestAppUWP, under the remote video you can see a new "ICE gathering" state in addition of the already existing "ICE connection" state.

**Comment by djee-ms** [comment]
Yes and as I pointed this comment is correct, this is an implementation "design"/"issue" from the Google code, which is fixed in a later Google milestone, but in the one we use (M71) this is like this, and the comment is an almost exact copy of the one found in the Google code.

**Comment by drejx** [comment]
Tested the new `IceGatheringStateChanged` event and it works great, thanks again :)

Regarding the IceConnectionState enum being a mix of IceGatheringState/IceConnectionState I wasn't aware it came directly from the m71 codebase, good to know.  I made my comment based on pure observation.

Cheers,
Andrej

**Comment by djee-ms** [comment]
Yes this is confusing, I don't know why Google did that. This is fixed in a later milestone so hopefully this will go away and match the WebRTC 1.0 Standard once we upgraded to a later Google milestone.
