### ISSUE TITLE
WebRTC.Native.Win32 change output from a .dll file to .exe

### ISSUE THREAD

**Issue by polhaghverdian** [microsoft/MixedReality-WebRTC#147]
Hi,

Is it possible to change the output from an .dll to .exe. when compiling?

I tried changing in the settings "configuration type" from .dll to .exe, but does not work.

https://imgur.com/Zu80uMF

**Comment by djee-ms** [comment]
Sorry @polhaghverdian this is never possible. A library and an executable are 2 different things. You cannot convert a shared library to an executable.

**Comment by polhaghverdian** [comment]
> 
> 
> Sorry @polhaghverdian this is never possible. A library and an executable are 2 different things. You cannot convert a shared library to an executable.

I dont want to convert, but to run it as an executable instead. The project seems to produce .dll file instead.

**Comment by stephenatwork** [comment]
@polhaghverdian to convert from dll into an exe, you'll need to supply an entry point such as main() yourself. Usually though, you would link the webrtc dll against your application instead. Is there some reason you don't want to take that approach?

**Comment by polhaghverdian** [comment]
@stephenatwork I dont see it necessary to have an dynamic library, which complicates development, and debugging in my case. I could give a try but am convinced this wont be optimal. I need to have a project for the actual application and one for the library.

**Comment by djee-ms** [comment]
@polhaghverdian are you saying you want static linking? It is not clear to us what you are trying to achieve here, can you describe your use case please?

**Comment by polhaghverdian** [comment]
@djee-ms  Exactly am trying to achieve Static Linking ( Statically Linked Executable )

**Comment by djee-ms** [comment]
Ok then this is not currently supported. In v2.0 we plan to change the C++ interop layer, which currently has issues due to crossing DLL boundaries, and still have a DLL but make the C++ library statically linked by default (and using the DLL internally only), see the discussion on #123. Until then I'm afraid there's no simple solution.

**Comment by polhaghverdian** [comment]
@djee-ms 
@stephenatwork 

Thank you!
