### ISSUE TITLE
Unity Build Error:IL2CPP error for type 'Microsoft.MixedReality.WebRTC.Unity.SceneVideoSource' in SceneVideoSource.cs

### ISSUE THREAD

**Issue by Boo0317** [microsoft/MixedReality-WebRTC#164]
`Failed running C:\Program Files\Unity\Unity 2018.3.0\Editor\Data\il2cpp/build/il2cpp.exe --convert-to-cpp --emit-null-checks --enable-array-bounds-check --dotnetprofile="unityaot" --map-file-parser="C:\Program Files\Unity\Unity 2018.3.0\Editor\Data\Tools\MapFileParser\MapFileParser.exe" --directory="D:\MixedRealityWebRTC\libs\Microsoft.MixedReality.WebRTC.Unity\Temp\StagingArea\Data\Managed" --generatedcppdir="D:\MixedRealityWebRTC\libs\Microsoft.MixedReality.WebRTC.Unity\Temp\StagingArea\Il2CppOutputProject\Source\il2cppOutput" 

stdout:
IL2CPP error for type 'Microsoft.MixedReality.WebRTC.Unity.SceneVideoSource' in D:\MixedRealityWebRTC\libs\Microsoft.MixedReality.WebRTC.Unity\Assets\Microsoft.MixedReality.WebRTC.Unity\Scripts\Media\SceneVideoSource.cs:76
Additional information: Invalid method 'null' found in vtable for 'Microsoft.MixedReality.WebRTC.Unity.SceneVideoSource'
il2cpp.exe didn't catch exception: System.Exception: Invalid method 'null' found in vtable for 'Microsoft.MixedReality.WebRTC.Unity.SceneVideoSource'
   �� Unity.IL2CPP.Metadata.VTableBuilder.ValidateAllMethodSlots(TypeDefinition typeDefinition, IEnumerable`1 slots)
   �� Unity.IL2CPP.Metadata.VTableBuilder.VTableForType(TypeDefinition typeDefinition, Dictionary`2 interfaceOffsets, Int32 currentSlot)
   �� Unity.IL2CPP.Metadata.VTableBuilder.VTableFor(TypeReference typeReference, TypeResolver resolver)
   �� Unity.IL2CPP.Metadata.MetadataCollector.AddVTables(IEnumerable`1 types)
   �� Unity.IL2CPP.Metadata.MetadataCollector.AddAssemblies(ICollection`1 assemblies)
   �� Unity.IL2CPP.AssemblyConverter.Apply()
   �� Unity.IL2CPP.AssemblyConverter.ConvertAssemblies(IEnumerable`1 assemblyDirectories, IEnumerable`1 explicitAssemblies, NPath outputDir, NPath dataFolder, NPath symbolsFolder, NPath executableAssembiesFolder, NPath monoLibFolder, NPath monoEtcFolder, NPath[] searchDirectories, String entryAssemblyName, NPath[] extraTypesFiles)
   �� il2cpp.Program.DoRun(String[] args)
   �� il2cpp.Program.Run(String[] args)
   �� il2cpp.Program.Main(String[] args)
stderr:

δ��������쳣:  System.Exception: Invalid method 'null' found in vtable for 'Microsoft.MixedReality.WebRTC.Unity.SceneVideoSource'
   �� Unity.IL2CPP.Metadata.VTableBuilder.ValidateAllMethodSlots(TypeDefinition typeDefinition, IEnumerable`1 slots)
   �� Unity.IL2CPP.Metadata.VTableBuilder.VTableForType(TypeDefinition typeDefinition, Dictionary`2 interfaceOffsets, Int32 currentSlot)
   �� Unity.IL2CPP.Metadata.VTableBuilder.VTableFor(TypeReference typeReference, TypeResolver resolver)
   �� Unity.IL2CPP.Metadata.MetadataCollector.AddVTables(IEnumerable`1 types)
   �� Unity.IL2CPP.Metadata.MetadataCollector.AddAssemblies(ICollection`1 assemblies)
   �� Unity.IL2CPP.AssemblyConverter.Apply()
   �� Unity.IL2CPP.AssemblyConverter.ConvertAssemblies(IEnumerable`1 assemblyDirectories, IEnumerable`1 explicitAssemblies, NPath outputDir, NPath dataFolder, NPath symbolsFolder, NPath executableAssembiesFolder, NPath monoLibFolder, NPath monoEtcFolder, NPath[] searchDirectories, String entryAssemblyName, NPath[] extraTypesFiles)
   �� il2cpp.Program.DoRun(String[] args)
   �� il2cpp.Program.Run(String[] args)
   �� il2cpp.Program.Main(String[] args)`
![1578734568(1)](https://user-images.githubusercontent.com/33243304/72202164-5ccf0a80-3497-11ea-8228-59e78b871f94.jpg)

This is the strangest question I've ever had.And no help was found.

**Comment by djee-ms** [comment]
Hi @Boo0317, I have never seen this with Unity, and this looks like an IL2CPP error in code generation, as I would expect from the error message that finding a NULL method in the vtable should never happen with any code provided the codegen is correct. In any case, I doubt we will be able to provide any help. I suggest contacting Unity to try to learn more about the error. Also maybe make sure you are not running with stale DLLs (try to rebuild the Temp/Library folders?).

**Comment by Boo0317** [comment]
I delete **CustomVideoSource.cs** and **SceneVideoSource.cs**,it can build success.I haven't used screen capture yet.But I have other problem ,when HoloLens 1 receive an offer from Unity Editor,the HoloLens crashed.Here is the exception message :"Exception thrown at 0x774E76A8 (Microsoft.MixedReality.WebRTC.Native.dll) in MixedRealityWebRTCUnityDemo.exe: 0xC0000005: Access violation reading location 0x00000010. "
![1578915442(1)](https://user-images.githubusercontent.com/33243304/72253495-a3119e80-363c-11ea-99fe-382405b63176.jpg)
It seem that someting wrong when **webrtc::RemoteAudioSource::OnData(struct webrtc::AudioSinkInterface::Data const &)** from the screenshot.
The attachment is the offer message.
[offer0.txt](https://github.com/microsoft/MixedReality-WebRTC/files/4053363/offer0.txt)

**Comment by djee-ms** [comment]
Some object is NULL. What's the callstack?

**Comment by djee-ms** [comment]
@Boo0317 can I just confirm how you set up your Unity project? In particular, did you use the NuGet packages of MixedReality-WebRTC, or rebuilt the Visual Studio solution? There has been some amount of confusion recently, which could result in some mismatch in the code and missing entry points, and explain those errors. See #166 and #168 for details.

**Comment by Boo0317** [comment]
ok，I updated the webrtc-uwp-sdk and it worked well.
