### ISSUE TITLE
Initializing MediaCapture fails when SpectatorView has been used before

### ISSUE THREAD

**Issue by aleneum** [microsoft/MixedReality-WebRTC#175]
I try to use WebRTC together with [SpectatorView](https://github.com/microsoft/MixedReality-SpectatorView). Together as in "as part of the same **Unity** app", not at the same time. It seems that when one service has initialized the MediaCapture, the other one cannot do it afterwards unless I restart the app. SpectatorView needs temporary access to the camera to track ArUco markers. The camera is released after synchronization and the handle is disposed. However, when `PeerConnection` tries to initialize the device after SpectatorView released the media capture, exceptions are thrown. When I use WebRTC first, SpectatorView cannot initialize marker tracking. Even when all GameObjects related to WebRTC have been destroyed. Both services work fine in conjunction with Vuforia though. I can switch back and forth without any issues.

### System

* Unity: 2019.2.19f1
* WebRTC: 73b69d7da6c74cb02b97e5ec1a627e7ce07eba55
* SpectatorView: https://github.com/microsoft/MixedReality-SpectatorView/commit/8f7d76c9de6542a5fb4c0b4889efbb4916bfb481
* HoloLens: 17763.973.x86fre.rs5_release_svc_prod1.200103-1310

I also filed that issue in the SpectatorView project (https://github.com/microsoft/MixedReality-SpectatorView/issues/322) with a detailled debug log.

**Comment by aleneum** [comment]
I updated the above mentioned issue with a recent 'minimal' example which reproduces the error.

**Comment by djee-ms** [comment]
Thanks @aleneum. Yes I am aware that at the moment the MediaCapture is locked by the local video track. I will have to talk with @chrisfromwork about this to understand the details and how we can share the MediaCapture between the two projects.

**Comment by djee-ms** [comment]
Discussed with @chrisfromwork, initial thoughts are that SpectatorView is not initializing MediaCapture from the UI thread, which might cause the issue.

**Comment by fibann** [comment]
Closing as this is not an issue with MR-WebRTC (see https://github.com/microsoft/MixedReality-SpectatorView/issues/322).
