### ISSUE TITLE
OnIceGatheringStateChanged Event in Nuget 1.0.2

### ISSUE THREAD

**Issue by bzdaunt** [microsoft/MixedReality-WebRTC#178]
I'm not seeing the OnIceGatheringStateChanged event  of PeerConnection in the Nuget 1.0.2 version. Is it in the plans to include this or has it been phased out? Sorry if I've missed any notes regarding so. It seems like it would be very handy to have when crafting your own signaling so you know when it's safe to send the entire Ice list.

**Comment by djee-ms** [comment]
The `master` branch, and so the next version (2.0) has this event:
https://github.com/microsoft/MixedReality-WebRTC/blob/0ad9423ac856d1426cb043404ecedf93e85406c6/libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs#L639

The change was added by c634bb29fad0bfa747110a411e4c0b1b0f627111. There is no plan at the moment to backport that change to the `release/1.0` branch, although this is not very difficult to apply I think. Can you please describe the use case which would make use of this event? I am not sure I understand what you mean by "it's safe to send the entire Ice list". Do you mean ignoring `IceCandidateReadyToSend`, and only sending ICE candidates once in a batch? Note that this will delay I think the connection, as the peers will generally start to connect before ICE gathering is finished. Why not send ICE candidates as they become ready?

**Comment by bzdaunt** [comment]
Thanks! Version 2.0 Will be just fine. It’s not a critical requirement. I am implementing a more primitive "signaling” scheme using Azure Functions and a sql table to store the Offers and Answers. It’s not real time, of course, until the connection is made. So, once all the ICE Candidates have been found, it updates the table with the full SDP once – rather than executing an http trigger each time a candidate is found. Right now I’m just using a simple timer after a CreateOff()/CreateAnswer().

**Comment by djee-ms** [comment]
Understood, thanks for the feedback. I'll close this issue then, and you can use the existing signal on `master` if you recompile the project instead of using the NuGet packages.
