### ISSUE TITLE
Null reference exception in AddLocalVideoTrackAsync

### ISSUE THREAD

**Issue by sipsorcery** [microsoft/MixedReality-WebRTC#179]
If the `settings` parameter is left as its default value of `null` a null reference exception will occur when accessing [settings.trackName])https://github.com/microsoft/MixedReality-WebRTC/blob/0ad9423ac856d1426cb043404ecedf93e85406c6/libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs#L1083).

**Comment by djee-ms** [comment]
Yep, my bad, will fix! Thanks @sipsorcery :+1:

**Comment by djee-ms** [comment]
Fixed, and added some unit tests to avoid regression.
