### ISSUE TITLE
Hearing local stream Audio on the local Peer (Hololens)

### ISSUE THREAD

**Issue by Dryra** [microsoft/MixedReality-WebRTC#183]
Hello, 
I noticed just today, that when I deploy to the Hololens1, and make a peer connection, with video and Audio, that I hear the local audio stream on the Hololens itself, not an echo from two devices next to each other, but like a audio feedback. So when I talk, I hear myselft through the Hololens.

In Unity though, I can't hear the remote audio stream nor the local audio stream, but I can send audio stream to the remote peer (Android client).
Is this somehow related to: https://github.com/microsoft/MixedReality-WebRTC/issues/92 ? or can I be doing something wrong between the peers that I'm sending and receiving on the same peer at the same time..?

this is my SDP Offer from the Hololens: 
`o=- 1955572326964500000 2 IN IP4 127.0.0.1
    s=-
    t=0 0
    a=group:BUNDLE 0 1
    a=msid-semantic: WMS 102
    m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
    c=IN IP4 0.0.0.0
    a=rtcp:9 IN IP4 0.0.0.0
    a=ice-ufrag:u9vR
    a=ice-pwd:kkgOOHfuUIsKfngijM+CESqQ
    a=ice-options:trickle renomination
    a=fingerprint:sha-256 CD:C3:BC:E1:EF:29:1B:97:E4:D1:97:BB:5B:9A:0C:AF:8B:F7:DF:12:11:20:74:0F:29:93:84:6E:87:D7:E1:24
    a=setup:active
    a=mid:0
    a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
    a=sendrecv
    a=rtcp-mux
    a=rtpmap:111 opus/48000/2
    a=rtcp-fb:111 transport-cc
    a=fmtp:111 minptime=10;useinbandfec=1
    a=rtpmap:103 ISAC/16000
    a=rtpmap:104 ISAC/32000
    a=rtpmap:9 G722/8000
    a=rtpmap:102 ILBC/8000
    a=rtpmap:0 PCMU/8000
    a=rtpmap:8 PCMA/8000
    a=rtpmap:106 CN/32000
    a=rtpmap:105 CN/16000
    a=rtpmap:13 CN/8000
    a=rtpmap:110 telephone-event/48000
    a=rtpmap:112 telephone-event/32000
    a=rtpmap:113 telephone-event/16000
    a=rtpmap:126 telephone-event/8000
    a=ssrc:3362097699 cname:bAVVzKgB1+7NLexk
    a=ssrc:3362097699 msid:102 101
    a=ssrc:3362097699 mslabel:102
    a=ssrc:3362097699 label:101
    m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 127 124 125
    c=IN IP4 0.0.0.0
    a=rtcp:9 IN IP4 0.0.0.0
    a=ice-ufrag:u9vR
    a=ice-pwd:kkgOOHfuUIsKfngijM+CESqQ
    a=ice-options:trickle renomination
    a=fingerprint:sha-256 CD:C3:BC:E1:EF:29:1B:97:E4:D1:97:BB:5B:9A:0C:AF:8B:F7:DF:12:11:20:74:0F:29:93:84:6E:87:D7:E1:24
    a=setup:active
    a=mid:1
    a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
    a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
    a=extmap:4 urn:3gpp:video-orientation
    a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
    a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
    a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
    a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
    a=extmap:10 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
    a=sendrecv
    a=rtcp-mux
    a=rtcp-rsize
    a=rtpmap:96 VP8/90000
    a=rtcp-fb:96 goog-remb
    a=rtcp-fb:96 transport-cc
    a=rtcp-fb:96 ccm fir
    a=rtcp-fb:96 nack
    a=rtcp-fb:96 nack pli
    a=rtpmap:97 rtx/90000
    a=fmtp:97 apt=96
    a=rtpmap:98 VP9/90000
    a=rtcp-fb:98 goog-remb
    a=rtcp-fb:98 transport-cc
    a=rtcp-fb:98 ccm fir
    a=rtcp-fb:98 nack
    a=rtcp-fb:98 nack pli
    a=rtpmap:99 rtx/90000
    a=fmtp:99 apt=98
    a=rtpmap:127 red/90000
    a=rtpmap:124 rtx/90000
    a=fmtp:124 apt=127
    a=rtpmap:125 ulpfec/90000
    a=ssrc-group:FID 2109796915 3584280555
    a=ssrc:2109796915 cname:bAVVzKgB1+7NLexk
    a=ssrc:2109796915 msid:102 100
    a=ssrc:2109796915 mslabel:102
    a=ssrc:2109796915 label:100
    a=ssrc:3584280555 cname:bAVVzKgB1+7NLexk
    a=ssrc:3584280555 msid:102 100
    a=ssrc:3584280555 mslabel:102
    a=ssrc:3584280555 label:100`

Thank you!

**Comment by djee-ms** [comment]
Hi @Dryra,

Your offer has one audio and one video tracks. Currently the audio is automatically captured from the device's microphone and sent to the remote peer, which automatically plays it back to the device's speakers. There is little control over it, and little chance to get things wrong. So I don't think #92 is related.

I have never experienced this on HoloLens 1, so I am a bit surprised. I would be more inclined to think that you made a mistake and are sending back from Android the same audio you are receiving from HL1, or there is some form of acoustic echo as we found echo cancellation doesn't seem to be enabled by default (#157). The fact audio doesn't play back in the Unity editor may be unrelated and may be a bug, or another misconfig. Since you are using a custom client (Android) that we don't know about, it's difficult to tell. Can you at least please paste the SDP answer so we can check if there is anything suspicious?

**Comment by Dryra** [comment]
Hello @djee-ms, 
thank you very much for your answer, I'm gonna have to check the Android client and what i'ts sending and doing, maybe it is really playing back the same audio. 
For the Unity not playing the remote sound, I can live with it at the moment and will inspect later on.
We received the Hololens2 today so I'm gonna also test this on the Hololens2 and see.

This is the SDP Answer that I'm getting from the Android Client:

o=- 6830962430417420463 2 IN IP4 127.0.0.1
    s=-
    t=0 0
    a=group:BUNDLE 0 1
    a=msid-semantic: WMS 102
    m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
    c=IN IP4 0.0.0.0
    a=rtcp:9 IN IP4 0.0.0.0
    a=ice-ufrag:N1/w
    a=ice-pwd:qCM9qYNXv+EJZnkb25CXz1KI
    a=ice-options:trickle renomination
    a=fingerprint:sha-256 BE:5A:3F:9A:4F:C6:46:31:8E:3C:4F:E7:8D:1B:CB:46:60:F9:F3:36:2A:15:9F:BB:F3:09:62:1E:9F:D7:49:72
    a=setup:active
    a=mid:0
    a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
    a=sendrecv
    a=rtcp-mux
    a=rtpmap:111 opus/48000/2
    a=rtcp-fb:111 transport-cc
    a=fmtp:111 minptime=10;useinbandfec=1
    a=rtpmap:103 ISAC/16000
    a=rtpmap:104 ISAC/32000
    a=rtpmap:9 G722/8000
    a=rtpmap:102 ILBC/8000
    a=rtpmap:0 PCMU/8000
    a=rtpmap:8 PCMA/8000
    a=rtpmap:106 CN/32000
    a=rtpmap:105 CN/16000
    a=rtpmap:13 CN/8000
    a=rtpmap:110 telephone-event/48000
    a=rtpmap:112 telephone-event/32000
    a=rtpmap:113 telephone-event/16000
    a=rtpmap:126 telephone-event/8000
    a=ssrc:556297389 cname:p/dhCtQHc73fFVX4
    a=ssrc:556297389 msid:102 101
    a=ssrc:556297389 mslabel:102
    a=ssrc:556297389 label:101
    m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 127 124 125
    c=IN IP4 0.0.0.0
    a=rtcp:9 IN IP4 0.0.0.0
    a=ice-ufrag:N1/w
    a=ice-pwd:qCM9qYNXv+EJZnkb25CXz1KI
    a=ice-options:trickle renomination
    a=fingerprint:sha-256 BE:5A:3F:9A:4F:C6:46:31:8E:3C:4F:E7:8D:1B:CB:46:60:F9:F3:36:2A:15:9F:BB:F3:09:62:1E:9F:D7:49:72
    a=setup:active
    a=mid:1
    a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
    a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
    a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
    a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
    a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
    a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
    a=extmap:10 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
    a=sendrecv
    a=rtcp-mux
    a=rtcp-rsize
    a=rtpmap:96 VP8/90000
    a=rtcp-fb:96 goog-remb
    a=rtcp-fb:96 transport-cc
    a=rtcp-fb:96 ccm fir
    a=rtcp-fb:96 nack
    a=rtcp-fb:96 nack pli
    a=rtpmap:97 rtx/90000
    a=fmtp:97 apt=96
    a=rtpmap:98 VP9/90000
    a=rtcp-fb:98 goog-remb
    a=rtcp-fb:98 transport-cc
    a=rtcp-fb:98 ccm fir
    a=rtcp-fb:98 nack
    a=rtcp-fb:98 nack pli
    a=rtpmap:99 rtx/90000
    a=fmtp:99 apt=98
    a=rtpmap:127 red/90000
    a=rtpmap:124 rtx/90000
    a=fmtp:124 apt=127
    a=rtpmap:125 ulpfec/90000
    a=ssrc-group:FID 3341798931 1499129292
    a=ssrc:3341798931 cname:p/dhCtQHc73fFVX4
    a=ssrc:3341798931 msid:102 100
    a=ssrc:3341798931 mslabel:102
    a=ssrc:3341798931 label:100
    a=ssrc:1499129292 cname:p/dhCtQHc73fFVX4
    a=ssrc:1499129292 msid:102 100
    a=ssrc:1499129292 mslabel:102
    a=ssrc:1499129292 label:100


Thank you very much for your help!

**Comment by Dryra** [comment]
Hello, after further investigation, looks like the echo cancellation constraint from Google in the Android client was not working as expected, or not working at all.
Closing as not related to mixed-reality webrtc library! Thank you for your time though!
