### ISSUE TITLE
_nativePeer.CreateAnswer() doesn't create an answer

### ISSUE THREAD

**Issue by cferlita** [microsoft/MixedReality-WebRTC#185]
I am trying to stream a WebRTC stream from Ant Media using a websocket signaler in Unity. I get an offer from Ant Media and make a call to _nativePeer.SetRemoteDescription with the offer, then I call _nativePeer.CreateAnswer() but I never get an answer message from the PeerConnection to send bak to the server.

The sdp offer I get is:
v=0
o=- 8067863999104612704 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS ARDAMS
m=audio 9 UDP/TLS/RTP/SAVPF 111 110
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:H57C
a=ice-pwd:BPq5h3MjkanrOW0DVIkqiaGP
a=ice-options:trickle renomination
a=fingerprint:sha-256 2B:A3:16:20:8E:29:B4:DA:DD:35:9C:0D:3B:27:F6:C2:30:DC:AA:F4:26:C1:F0:DB:5A:39:65:6F:20:C9:B0:E9
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:110 telephone-event/48000
a=ssrc:2745443612 cname:QWeB7twFB/0oII22
a=ssrc:2745443612 msid:ARDAMS ARDAMSa0
a=ssrc:2745443612 mslabel:ARDAMS
a=ssrc:2745443612 label:ARDAMSa0
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:H57C
a=ice-pwd:BPq5h3MjkanrOW0DVIkqiaGP
a=ice-options:trickle renomination
a=fingerprint:sha-256 2B:A3:16:20:8E:29:B4:DA:DD:35:9C:0D:3B:27:F6:C2:30:DC:AA:F4:26:C1:F0:DB:5A:39:65:6F:20:C9:B0:E9
a=setup:actpass
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=sendrecv
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 red/90000
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 ulpfec/90000
a=ssrc-group:FID 3679662712 336064468
a=ssrc:3679662712 cname:QWeB7twFB/0oII22
a=ssrc:3679662712 msid:ARDAMS ARDAMSv0
a=ssrc:3679662712 mslabel:ARDAMS
a=ssrc:3679662712 label:ARDAMSv0
a=ssrc:336064468 cname:QWeB7twFB/0oII22
a=ssrc:336064468 msid:ARDAMS ARDAMSv0
a=ssrc:336064468 mslabel:ARDAMS
a=ssrc:336064468 label:ARDAMSv0

Any insights into why I am not getting the answer would be appreciated.

**Comment by djee-ms** [comment]
Hi @cferlita,
Are you using the Unity editor in this example? Your offer seems to come from the Ant server because it doesn't look like a typical Google one, and it offers H.264 video by default, which will not work on the Editor since it's a Desktop process with no H.264 support. Therefore `SetRemoteDescription()` will fail, and obviously then `CreateAnswer()` too. H.264 is only supported on UWP at the moment.

**Comment by cferlita** [comment]
Yes, I am using the Unity Editor and the offer is coming from the Ant Server. You have confirmed my suspicions.
Thanks for the response .

**Comment by djee-ms** [comment]
You're welcome. I assume this was the problem then, so closing this issue. Feel free to reopen if that was not the case or if there is something else.

**Comment by cferlita** [comment]
One last question, what is the video format supported by the Unity Desktop? Is it H245 or H265? I need to check with Ant Media to see if we can change it on their side.

**Comment by djee-ms** [comment]
Neither. It's VP8 or VP9 generally, or some more esoteric ones. You can check by creating an offer from the Unity Editor and see what's offered by the implementation.

**Comment by cferlita** [comment]
Thanks, looking at the offer yesterday, I figured that out.
