### ISSUE TITLE
Peers connected but not sending audio (sample Hello, C# world! (Desktop))

### ISSUE THREAD

**Issue by enriquemptedcas** [microsoft/MixedReality-WebRTC#192]
Hi there,

I'm trying to use the Hello, C# world! (Desktop) example for later integrating the WebRTC in my application.
The situation is that I can run two different process and the peers connect succesfully. The one who acts as a server even prints in the console the number of received frames.
However, the audio data seems to be empty, as I have checked the memory location and it is all filled with 0's.

Any idea? Maybe my setup or configuration is wrong. I would appreciate your help.

**Comment by sipsorcery** [comment]
Do you mean this [example](https://github.com/microsoft/MixedReality-WebRTC/tree/master/examples/TestNetCoreConsole) or is there another one buried somewhere?

When you say "connect successfully" do you know how far the connection gets:
 - The signalling?
 - The initial STUN exchange?
 - The DTLS handshake?
 - RTP (most likely not getting a connection here if there's no audio)?

If the log messages aren't helping then another option is to use Wireshark and do a UDP capture on the loopback interface. If your machine is busy you might have to do a port range filter (I normally see Chromium use ports above 50000).

Here's the capture I get when running the example app from #184.

![webrtc_wireshark](https://user-images.githubusercontent.com/197660/75182832-1842ba00-5739-11ea-9778-688212a13ce8.png)

**Comment by djee-ms** [comment]
I assume you correctly started with the `--audio` flag if you see the number of frames, right?

**Comment by fibann** [comment]
Audio capture seems to be broken on Win32 - it might work for some but it doesn't on all the platforms I have tested. This seems to be an issue with the WebRTC-UWP audio capture implementation, and should be fixed if we switch to the WinRTC implementation.

**Comment by fibann** [comment]
It seems audio capture now works when using ADM2 (#507)
