### ISSUE TITLE
WIndows Standalone Build calling UWP Hololens Build

### ISSUE THREAD

**Issue by astaikos316** [microsoft/MixedReality-WebRTC#216]
I am having an issue where I have built an app, one side I have compiled and build as a windows standalone app in Unity giving me an .exe and have the other end built as UWP and loaded on a Hololens.  When I start a call from the tablet to the Hololens, there are no issues.  When I start the call from the Hololens to the tablet, that is when I notice that the call never fully completes, i.e. I never see an answer sent from the tablet.  I have noticed similar behavior working on a side project with a windows standalone build and trying the android stack.  I can't quite pinpoint the problem because if I run 2 UWP builds, one on a PC and one on a Hololens, I can call either way.  If I run 2 windows standalone apps on two different machines, I can call either way.  Any recoomendations would be greatly appreciated.

**Comment by djee-ms** [comment]
Things to look out for:
- Desktop doesn't support H.264, so could fail video codec negotiation with UWP; check by forcing VP8 for example.
- If there is no answer, this generally indicates as I commented on #193 that either the offer was refused (_e.g._ codec not supported), or received at a wrong time (peer connection not expecting one), or that the answer itself failed to generate because `CreateAnswer()` was called before `SetRemoteDescriptionAsync()` completed.

Also:
- Can you please paste the SDP offer?
- Does the problem only occur with our app(s), or can you reproduce with _e.g._ the Unity Editor (Desktop) and the TestAppUWP sample app (UWP)?

**Comment by astaikos316** [comment]
Here is the SDP offer and ICE messages that are sent when I initiate the call from the Hololens UWP to the Tablet:

{ MessageType: 1,
  Data:
   'v=0\r\no=- 3308825660643262117 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1 2\r\na=msid-semantic: WMS local_av_stream\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:881S\r\na=ice-pwd:Mnb7KKZDxxU5iZSILmGhzGk7\r\na=ice-options:trickle\r\na=fingerprint:sha-256 25:0D:81:A4:CC:5C:A6:FE:49:51:3E:D2:2C:3A:A5:FF:C8:AA:B9:F9:B8:68:38:D6:AF:B2:18:60:61:64:7B:D3\r\na=setup:actpass\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=sendrecv\r\na=msid:local_av_stream local_audio\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:102 ILBC/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\na=ssrc:1108281535 cname:vWE++UzN/io06W5o\r\na=ssrc:1108281535 msid:local_av_stream local_audio\r\na=ssrc:1108281535 mslabel:local_av_stream\r\na=ssrc:1108281535 label:local_audio\r\nm=video 9 UDP/TLS/RTP/SAVPF 100\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:881S\r\na=ice-pwd:Mnb7KKZDxxU5iZSILmGhzGk7\r\na=ice-options:trickle\r\na=fingerprint:sha-256 25:0D:81:A4:CC:5C:A6:FE:49:51:3E:D2:2C:3A:A5:FF:C8:AA:B9:F9:B8:68:38:D6:AF:B2:18:60:61:64:7B:D3\r\na=setup:actpass\r\na=mid:1\r\na=extmap:2 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:4 urn:3gpp:video-orientation\r\na=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:10 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07\r\na=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=sendrecv\r\na=msid:local_av_stream local_video\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:100 H264/90000\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=fmtp:100 packetization-mode=1\r\na=ssrc-group:FID 319731521 4034863097\r\na=ssrc:319731521 cname:vWE++UzN/io06W5o\r\na=ssrc:319731521 msid:local_av_stream local_video\r\na=ssrc:319731521 mslabel:local_av_stream\r\na=ssrc:319731521 label:local_video\r\na=ssrc:4034863097 cname:vWE++UzN/io06W5o\r\na=ssrc:4034863097 msid:local_av_stream local_video\r\na=ssrc:4034863097 mslabel:local_av_stream\r\na=ssrc:4034863097 label:local_video\r\nm=application 9 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:881S\r\na=ice-pwd:Mnb7KKZDxxU5iZSILmGhzGk7\r\na=ice-options:trickle\r\na=fingerprint:sha-256 25:0D:81:A4:CC:5C:A6:FE:49:51:3E:D2:2C:3A:A5:FF:C8:AA:B9:F9:B8:68:38:D6:AF:B2:18:60:61:64:7B:D3\r\na=setup:actpass\r\na=mid:2\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n',
  IceDataSeparator: '',
  name: 'Tablet' }
Sending offer to:  Tablet
{ MessageType: 3,
  Data:
   'candidate:2205430794 1 udp 2122260223 192.168.1.25 60699 typ host generation 0 ufrag 881S network-id 1 network-cost 10|0|0',
  IceDataSeparator: '|',
  name: 'Tablet' }
Sending candidate to:  Tablet
{ MessageType: 3,
  Data:
   'candidate:2205430794 1 udp 2122260223 192.168.1.25 60700 typ host generation 0 ufrag 881S network-id 1 network-cost 10|1|1',
  IceDataSeparator: '|',
  name: 'Tablet' }
Sending candidate to:  Tablet
{ MessageType: 3,
  Data:
   'candidate:2205430794 1 udp 2122260223 192.168.1.25 60701 typ host generation 0 ufrag 881S network-id 1 network-cost 10|2|2',
  IceDataSeparator: '|',
  name: 'Tablet' }
Sending candidate to:  Tablet
{ MessageType: 3,
  Data:
   'candidate:3455568122 1 tcp 1518280447 192.168.1.25 50109 typ host tcptype passive generation 0 ufrag 881S network-id 1 network-cost 10|0|0',
  IceDataSeparator: '|',
  name: 'Tablet' }
Sending candidate to:  Tablet
{ MessageType: 3,
  Data:
   'candidate:3455568122 1 tcp 1518280447 192.168.1.25 50110 typ host tcptype passive generation 0 ufrag 881S network-id 1 network-cost 10|1|1',
  IceDataSeparator: '|',
  name: 'Tablet' }
Sending candidate to:  Tablet
{ MessageType: 3,
  Data:
   'candidate:3455568122 1 tcp 1518280447 192.168.1.25 50111 typ host tcptype passive generation 0 ufrag 881S network-id 1 network-cost 10|2|2',
  IceDataSeparator: '|',
  name: 'Tablet' }
Sending candidate to:  Tablet

**Comment by astaikos316** [comment]
It was the VP8 issue.  Once I set it on both apps, it is working as expected.  Thanks for pointing me in the right direction.  I believe it is the same issue that I had been asking on the Android build.
