### ISSUE TITLE
Cannot stream my webcam

### ISSUE THREAD

**Issue by amfdeluca** [microsoft/MixedReality-WebRTC#222]
I managed to establish a connection between two scenes in Unity through the node.dss server, the default material (green with purple shades) appears on the display and the node.dss server detects a connection between two instances. The problem is that I can't get the second scene to input and then stream what it gets from the webcam. I'm a little tired, I don't want the problem to be some kind of permission on the Unity side to get the webcam input.

Thanks for your attention.

**Comment by djee-ms** [comment]
Hi @amfdeluca,

- What are the 2 peers? Unity Editor cannot run multiple instances, so are you using a standalone build? For which platform (Desktop, UWP, ...)?
- Are the 2 peers on the same machine? Do you have 2 webcams? You cannot use the same webcam from multiple peers/tracks.

**Comment by amfdeluca** [comment]
Hi, thank's for yuor reply. One is builded as Desktop and the other one is in editor.
I have the 2 peer on the same machine but What i'm doing is trying to send from a peer (called Scanner) to another that only takes the stream. I've tryied to open my old project , that worked, but the problem persists, so i don't know if the issue is caused by something different. Now i'm working from home so i don't know if i had something different on my old pc like some permission or other.
For the webcam i'm using obs-virtualcam to simulate it 'cause i don't have any webcam.

![Screenshot (39)](https://user-images.githubusercontent.com/56428422/76625315-3e3ccc80-6537-11ea-852a-902b5f1d48d4.png)

**Comment by djee-ms** [comment]
I see that the 2 peers are connected to the `node-dss` server, that's good.

Let's try to break down the issue: is the problem on the peer capturing the webcam and sending the video, or during the SDP session negotiation, or is it on the peer receiving it?
- On the peer which adds the local video track, can you see the video? Can you set a breakpoint inside the [I420ALocalVideoFrameReady](https://github.com/microsoft/MixedReality-WebRTC/blob/e00a24429318dd1cc22edc598873577d64d023cf/libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Media/LocalVideoSource.cs#L323) callback (or some logging) to make sure it's called?
- Can you please paste the SDP offer and SDP answer messages, if any?
- On the peer which receives the remote video, can you set a breakpoint inside the [I420ARemoteVideoFrameReady](https://github.com/microsoft/MixedReality-WebRTC/blob/e00a24429318dd1cc22edc598873577d64d023cf/libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Media/RemoteVideoSource.cs#L200) callback (or some logging) to make sure it's called?

**Comment by amfdeluca** [comment]
- Hi, I tried with a debug log and with a breakpoint but nothing, it seems not to enter the method. I share what is debugged in the console so perhaps to have an idea of ​​the operations that take place and where it stops instead. I tried to put everything I thought useful on the screen.

![Screenshot (41)](https://user-images.githubusercontent.com/56428422/76632530-a72a4180-6543-11ea-9eb4-4fa28d7335ce.png)

- Now the SDPs

From the Scanner scene (pics above)
_case Message.WireMessageType.Answer >>>> msg.MessageType = Answer , msg = Microsoft.MixedReality.WebRTC.Unity.Signaler+Message, msg.Data =v=0_
From the MR scene
_case Message.WireMessageType.Offer >>>> msg.MessageType = Offer , msg = Microsoft.MixedReality.WebRTC.Unity.Signaler+Message, msg.Data =v=0_

- No way I420ARemoteVideoFrameReady is not called

 Thank you for your attention and sorry for the incompetence but I am quite junior ":)

**Comment by djee-ms** [comment]
All setups look ok to me. If the local peer doesn't show the video in the `MediaPlayer` (which is configured correctly I think) then it's most likely an issue with the video capture. This is confirmed by the fact `I420ALocalVideoFrameReady` is never called, which means the WebRTC implementation doesn't receive any video data.

I see that the logs show the 4 OBS webcams are enumerated, so I think the implementation sees them. Not sure why it would fail to use them though. But I am not familiar with OBS.
- Can you please try to enumerate the capture formats on one of the devices, to see if the implementation can access it? Something like this:
  ```cs
  var devices = await GetVideoCaptureDevicesAsync();
  foreach (var device in devices)
  {
      Debug.Log($"Device: {device.name} ({device.id}):");
      var formats = await WebRTC.PeerConnection.GetVideoCaptureFormatsAsync(device.id);
      foreach (var format in formats)
      {
          Debug.Log($"+ format: {format.width}x{format.height}@{format.framerate} ({format.fourcc})");
      }
  }
  ```
  You can for example put it in `OnPostInitialize()` in `PeerConnection.cs` at the end before or after `OnInitialized.Invoke();` (and make `OnPostInitialize()` async for the `await` calls to compile).
- Can you check with some breakpoint or logging if the track is created correctly? The camera is opened by the call to [AddLocalVideoTrackAsync()](https://github.com/microsoft/MixedReality-WebRTC/blob/master/libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Media/LocalVideoSource.cs#L300).

**Comment by amfdeluca** [comment]
Sorry for the late answer, what i found is that my LocalVideoSource.cs file is different, mine arrives at only 286 line, your is 326. After a small check i founded out that, probably if i don't have mess anything, the page https://github.com/microsoft/MixedReality-WebRTC/releases has a SourceCode.zip under Assets (in 1.0.3) that doesn't contain the script you linked me, now i pulled the latest version and all is fine (326 line).

It may be I am tired and I may have made a mistake, despite having just done a check at: _MixedReality-WebRTC/libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Media/LocalVideoSource.cs_

Don't know if that is the solution to my problem but now i'm reimporting all, also the dll 1.0.3 from the nuget page

**Comment by amfdeluca** [comment]
After reimporting everything, then taking the latest version of WebRTC from the last push on the /Release/1.0 branch. I tried to run a simple stream of the webcam locally but the screen remains green, the node.dss server, however, detects a connection is precisely as if the panel did not refresh with the video received as input. As I said in the previous comment, looking at the script I miss that function on line 300 because the script in this version stops on line 285. Do you have any advice on how to debug to understand where the hitch is?

**Comment by amfdeluca** [comment]
I was able to test the project remotely on the office PC and I could see that all the webrtc part works, it is not yet clear to me how it is possible that with the home PC the connection does not take place but I would close the report as the problem could be precisely due to factors X not attributable directly to the WebRTC, I apologize for the inconvenience.

**Comment by djee-ms** [comment]
No worry at all! For context on Desktop the video capture module is the built-in one written by Google, which uses the very outdated DirectShow API. I know some newer devices may have issues with it (and conversely older devices can have issues with the new MediaFoundation API we use on UWP) so it is entirely possible we are unlucky here and the OBS camera doesn't work with DirectShow. Going forward we plan to transition to a new unified video capture module based on MediaFoundation, so hopefully that will at least remove any discrepancy between Desktop and UWP. However A/V capture is hard, there are many things that can fail from hardware to driver to media API to WebRTC, and our error logging is pretty poor at the moment, so things are difficult to debug. Anyway please feel free to reopen if you want to investigate further.
