### ISSUE TITLE
My PC can receive Offer from hololens but won't Send Answer(Unity Project)??

### ISSUE THREAD

**Issue by zhuangce** [microsoft/MixedReality-WebRTC#223]
I have a strange problem right now, and I don't have a clue.
  In most cases, my demo can be used normally. There is no problem for hololens and hololens to connect with each other, and there is no problem for Windows client and Windows client to connect with each other.
  However, the Windows client(or unity editor) did not send an answer after receiving the offer from the hololens client, and the reverse is ok.
  I used the unity project in release1.0.
  I don't have any ideas. and I hope someone can help me out.

**Comment by zhuangce** [comment]
oh , I just realize that reason is the desktop don't support h264 after i  read the readme.md file carefully .All i need to do is set video codec to vp8/vp9  in my hololens  project . 
   Maybe someone will come up  against the issue ,I hope this issue can give some help .

**Comment by djee-ms** [comment]
Yes many users are hitting that issue, we tried our best to show it in the README but it's not enough. I have started adding more hints and warnings directly in Unity, hopefully that will help. And we are working to find a plan to get H.264 support on Desktop too.

**Comment by mahadevans87** [comment]
@djee-ms I would be very interested in this. Currently we are trying to combine Unity Renderstream with MRTK WebRTC hoping to render in Unity and transmit them over WebRTC to be played in the HL2.  The problem that we have is that I assume Unity Renderstream uses H264 encoding for the data coming out of NVidia Cuda. So there is no option for us to switch to VP8/VP9 here.

**Comment by djee-ms** [comment]
Not sure I understand the problem, if Unity Renderstream uses H.264 on Desktop and HL2 is UWP so MixedReality-WebRTC (not MRTK) supports H.264 too, where is the issue, and why would you want to switch to VP8/VP9?
