### ISSUE TITLE
 Several missing namespace or assembly references 

### ISSUE THREAD

**Issue by amfdeluca** [microsoft/MixedReality-WebRTC#237]
I've tryed different times following the guides on https://microsoft.github.io/MixedReality-WebRTC/manual/gettingstarted.html.

The problem is that every time I open Unity, after I have followed all the steps, all these errors appear in the console. I have tried to perform the procedure several times but every time I have these errors. The problem is that if I actually go to analyze the errors, there are errors like "VideoProfileKind" where the Intellisense suggests me to simply add one "using Microsoft.MixedReality.WebRTC.PeerConnection;" while other errors refer to non-existent scripts. I'm afraid the problem is due to .dll.

![Screenshot (59)](https://user-images.githubusercontent.com/56428422/77636063-d1243080-6f53-11ea-9698-be1349522571.png)

_I'm working on Unity 2019.2.21f1, Visual Studio 2019, NuGet 1.0.3, WebRTC Master branch of 23 Mar 2020._

Here I report the operations that I carried out step by step so you can possibly help me and tell me which point I'm wrong or if I skip some fundamental step.

**1.** With Unity closed I opened the VS solution and installed the following packages through the NuGet package manager window:
- Microsoft.MixedReality.WebRTC
- Microsoft.MixedReality.WebRTC.UWP
- Microsoft.MixedReality.WebRTC.Native.Desktop
- Microsoft.MixedReality.WebRTC.Native.UWP

**2.** After that I then cloned the WebRTC project aligning with the last commit of the Master branch.
From that project I then copied from this _libs / Microsoft.MixedReality.WebRTC.Unity / Assets / _ folder the following folders:
- Microsoft.MixedReality.WebRTC.Unity
- Microsoft.MixedReality.WebRTC.Unity.Editor
- Plugins
inside the _Assets / _ folder of my project.

**3.** Then I downloaded from the following links 
- https://www.nuget.org/packages/Microsoft.MixedReality.WebRTC and
- https://www.nuget.org/packages/Microsoft.MixedReality.WebRTC.UWP
the .dll to be associated with the .meta files present in the _Plugins_ folder.
I then meticulously followed this association of .dll and .meta files as reported in this table https://www.nuget.org/packages/Microsoft.MixedReality.WebRTC.UWP. After that I then copied the last .dll file as reported here https://www.nuget.org/packages/Microsoft.MixedReality.WebRTC.UWP. Then taking it from the folder previously downloaded from the NuGet website.

After that I opened Unity and I found all those errors in the console.
Thank you very much for your attention and availability. I sincerely hope to be able to deal with it :)

**Comment by djee-ms** [comment]
Hi @amfdeluca,

You are copying the C++ and C# library DLLs by extracting them from the NuGet packages (version 1.0.3, compiled from `release/1.0`) and using the Unity C# scripts from `master`, is that correct? I am pretty sure this is the case since `ExternalVideoTrackSource` does not exist on `release/1.0`.

If so then this is the issue, the C++ and C# DLLs you are copying are from a different branch than the Unity scripts, and therefore don't have the same API. You need to use:

- either `release/1.0` with NuGet DLLs;
- or if you want to use `master` to have the latest API features then recompile those DLLs with the provided solution.

But you cannot mix those approaches.

**Comment by djee-ms** [comment]
See the **Download** section of the [README.md](https://github.com/microsoft/MixedReality-WebRTC/tree/master/):

>NuGet packages are available for stable releases (`release/*` branches). See the Release page on GitHub.
>
> Note: The `master` branch contains the code for the next release, and therefore sometimes contains breaking API changes from the latest stable release. It is therefore not guaranteed to work with NuGet packages, which are only available for stable releases. In particular, the Unity integration scripts are only guaranteed to be compatible with NuGet packages if copied from a `release/*` branch.

**Comment by amfdeluca** [comment]
Thanks a lot for your quick reply

I understand very well, possibly to not have to compile the .dll, one way to solve the problem could be to pull the 1.0.3 version of WebRTC and take the C # scripts from there. Can I ask for confirmation on the version to be pulled, i.e. that of 6 Mar 2020 of the origin / release / 1.0 _Fix CHANGELOG.md for v1.0.3_ branch or from the Master branch the commit _Update NuGet core dependencies to 1.0.3_ of 3 Mar 2020?

Sorry for the question, perhaps a little silly, I ask for confirmation. In any case I will discard the changes on the project in order to start again from 0 reimporting everything to be clear.

**Comment by djee-ms** [comment]
Yes, if you don't want to build then copy [the Unity scripts from `release/1.0`](https://github.com/microsoft/MixedReality-WebRTC/tree/release/1.0/libs/Microsoft.MixedReality.WebRTC.Unity/Assets).

**Comment by amfdeluca** [comment]
Ok solved, thank you very much and sorry but I had missed the Download section in the Readme, I had concentrated only on the user manual page.

**Comment by djee-ms** [comment]
No worry, we know this is confusing, we are looking at a better distribution method for Unity which would avoid this kind of confusion, but these things take time, so please bear with us in the meantime 😃

**Comment by zxubian** [comment]
Stumbled into this issue today as well.
I believe the docs could state this more clearly:

> If so then this is the issue, the C++ and C# DLLs you are copying are from a different branch than the Unity scripts, and therefore don't have the same API. You need to use:
> 
> either release/1.0 with NuGet DLLs;
> or if you want to use master to have the latest API features then recompile those DLLs with the provided solution.
> But you cannot mix those approaches.

Specifically it might be worth mentioning that in order to use the NuGet packages people need to check out the commit with the same release tag.
