### ISSUE TITLE
LocalVideoSource error missing namespace in UWP Build

### ISSUE THREAD

**Issue by amfdeluca** [microsoft/MixedReality-WebRTC#238]
Hi, when I try to build for in UWP for hololens in console I get several errors regarding the LocalVideoSource namespace, I can ask which step I skipped or if I am missing some reference in the project. 

![Screenshot (94)](https://user-images.githubusercontent.com/56428422/77756755-17e75880-7030-11ea-8cec-c39bfb56b962.png)

- Unity 2019.2.21f1, VS 2019, NuGet packages 1.0.3, WebRTC sources from latest release branch, MRTK 2.3.0

_Thank you so much for your attention, availability and patience_

**Comment by djee-ms** [comment]
See #165, this was fixed on `master` with 243e629b506982cdafaac62f4a6157134b9807f3.

**Comment by amfdeluca** [comment]
Thanks a lot, problem solved. Also I wanted to apologize, next time I will try better before making a duplicate of the same issue.

**Comment by djee-ms** [comment]
Not to worry. It's easier for me to know it's a duplicate than for you to search for it 😉
