### ISSUE TITLE
怎么样才能推自己的图像数据出去 How to push out my own image data

### ISSUE THREAD

**Issue by yangjieshao** [microsoft/MixedReality-WebRTC#240]
在net core3.1 
作为服务器端 （命令行程序） As a server (command line program)
视频源是通过第三方提供的数据接口获取的帧画面
The video source is the frame obtained through the data interface provided by the third party
怎么样才能把这个帧画面推送出去呢
How to push this frame out

另外
````
var config = new PeerConnectionConfiguration
{
    IceServers = new List<IceServer> {
            //new IceServer{ Urls = { "stun:stun.l.google.com:19302" } }
        }
};
 await pc.InitializeAsync(config);
````
程序直接崩溃，返回值是  -1073740791 (0xc0000409)

**Comment by djee-ms** [comment]
Hi @yangjieshao,

If I understand what you want, in order to use a custom video source instead of a webcam you need to use [`ExternalVideoTrackSource`](https://microsoft.github.io/MixedReality-WebRTC/api/Microsoft.MixedReality.WebRTC.ExternalVideoTrackSource.html), which is only available on `master` so needs to be [built from sources](https://microsoft.github.io/MixedReality-WebRTC/manual/building.html).

I have no idea about the block of code nor the error you pasted, I will need some more context or some translation.

**Comment by yangjieshao** [comment]
这些是我从例子上复制的代码，并使用nuget安装了Microsoft.MixedReality.WebRTC.1.0.3
These are the code I copied from the example, And use nuget to install Microsoft. Mixedreality. Webrtc. 1.0.3

````
var deviceList = await PeerConnection.GetVideoCaptureDevicesAsync();
// For example, print them to the standard output
foreach (var device in deviceList)
{
        Console.WriteLine($"Found webcam {device.name} (id: {device.id})");
}

// Create a new peer connection automatically disposed at the end of the program
using var pc = new PeerConnection();

 // Initialize the connection with a STUN server to allow remote access
 var config = new PeerConnectionConfiguration
{
        IceServers = new List<IceServer> {
                 // new IceServer{ Urls = { "stun:stun.l.google.com:19302" } }
         }
};
await pc.InitializeAsync(config);
Console.WriteLine("Peer connection initialized.");
````
在await pc.InitializeAsync(config); 等待了一段时间后程序就崩溃了
After waiting for "await pc.initializeasync (config);"  the program crashes

exit code:  -1073740791 (0xc0000409)。

**Comment by yangjieshao** [comment]
I try to clone the repository ,
but there was some error 

![webrtc](https://user-images.githubusercontent.com/3275834/77822700-169d5500-7130-11ea-97a5-0b0d0ff9b8b7.png)

and I can not find how can I send bitmap by ExternalVideoTrackSource

**Comment by yangjieshao** [comment]
I try to clone all modules 
However, due to network reasons, downloading always fails
I try to rebuild the solution but 
![image](https://user-images.githubusercontent.com/3275834/77869087-d7761d80-726f-11ea-9640-50d8133beaad.png)
If you can, can you zip the all the external folder

**Comment by djee-ms** [comment]
This file is downloaded from nuget.org, from one of the `Microsoft.MixedReality.WebRTC.Native.Core.*` packages such as [this one](https://www.nuget.org/packages/Microsoft.MixedReality.WebRTC.Native.Core.UWP.ARM.Release).

The `external` folder on my machine is 25GB, no I cannot ZIP it. If you cannot download from nuget.org then there's nothing we can do, this is a critical piece of package publishing that we assume all users have access to.

**Comment by yangjieshao** [comment]
Thank you 
I find that the reason why I can't find the file is that the default platform is ARM
After I changed it to x64 ，Sample program can run
But there still some question

on the TestReceiveAV
I don't have an SSL certificate，So I commented out the code
![Snipaste_2020-03-30_20-53-40](https://user-images.githubusercontent.com/3275834/77915166-90b51180-72c9-11ea-90c4-a53734d265fa.png)
Then I start the program
When I start the camera on th web, Th program crash
![Snipaste_2020-03-30_20-52-58](https://user-images.githubusercontent.com/3275834/77915292-cc4fdb80-72c9-11ea-944a-bfb49d05fc7a.png)
![Snipaste_2020-03-30_20-51-53](https://user-images.githubusercontent.com/3275834/77915300-ceb23580-72c9-11ea-9858-a7e4fbaf1d6a.png)


So I try to run TestNetCoreConsole
It crash  at  "await pc.InitializeAsync(config);"
![22  Snipaste_2020-03-30_20-56-07](https://user-images.githubusercontent.com/3275834/77915443-133dd100-72ca-11ea-8b3b-a9442cd6ffad.png)

In case because I can't connect to goole, I removed the configuration of Google's iceserver
![Snipaste_2020-03-30_21-07-58](https://user-images.githubusercontent.com/3275834/77915741-8e9f8280-72ca-11ea-827d-dbce153e5f87.png)
But it's still crash

**Comment by yangjieshao** [comment]
![Snipaste_2020-03-30_21-16-13](https://user-images.githubusercontent.com/3275834/77916596-e1c60500-72cb-11ea-8e63-4df2a30383e8.png)
![Snipaste_2020-03-30_21-17-06](https://user-images.githubusercontent.com/3275834/77916600-e2f73200-72cb-11ea-9d86-f9ebac9bdbd1.png)
![Snipaste_2020-03-30_21-17-21](https://user-images.githubusercontent.com/3275834/77916607-e4c0f580-72cb-11ea-8536-0f0e21c68cbb.png)

**Comment by yangjieshao** [comment]
I found TestReceiveAV is default 
````
<PackageReference Include="Microsoft.MixedReality.WebRTC" Version="1.0.2" />
````
so I changed it to
````
 <ProjectReference Include="..\..\libs\Microsoft.MixedReality.WebRTC\Microsoft.MixedReality.WebRTC.csproj" />
````
then copy` Microsoft.MixedReality.WebRTC.dll` and` Microsoft.MixedReality.WebRTC.Native.dll`  to `TestReceiveAV\bin\Debug`

change
`session.pc.AddIceCandidate((string)jsonMsg["sdpMLineindex"], (int)jsonMsg["sdpMid"], (string)jsonMsg["candidate"]);`
to
`session.pc.AddIceCandidate((string)jsonMsg["sdpMid"], (int)jsonMsg["sdpMLineindex"],  (string)jsonMsg["candidate"]);`at line 85

then  I run the program 
when I start the webcamera
![Snipaste_2020-03-30_22-00-23](https://user-images.githubusercontent.com/3275834/77921131-f1484c80-72d1-11ea-8714-7d4432ed90d2.png)
![Snipaste_2020-03-30_22-00-39](https://user-images.githubusercontent.com/3275834/77921138-f3121000-72d1-11ea-99e5-7e2c756a7f98.png)
![Snipaste_2020-03-30_22-00-49](https://user-images.githubusercontent.com/3275834/77921146-f4dbd380-72d1-11ea-8fd4-57dc68c745f1.png)

**Comment by djee-ms** [comment]
You have an audio capture device (webcam, laptop microphone, ...) that doesn't work with Windows Core Audio. The Google implementation of the Audio Device Module (ADM; this is the `adm()` assert you have) requires that ALL devices that capture audio work. This is a known "limitation" (bug) of the Google implementation. See for example #140 and #141, and [the Google bug](https://bugs.chromium.org/p/webrtc/issues/detail?id=11081). You need to find which device it is and remove it (if USB) or disable it via the device manager (if built-in). At the moment this is the only workaround.

For the `TestReceiveAV` dependency on `1.0.2` we should probably fix it, thanks for the feedback!

**Comment by djee-ms** [comment]
I logged #242 so we can fix or workaround that Core Audio issue, which is causing so much pain to many users.

**Comment by djee-ms** [comment]
Note also, as you already noticed, that the Google STUN server is a default value but you can replace it, and you can also not use any STUN server if you don't need NAT traversal (for example during testing on local LAN network or on the same machine).

**Comment by yangjieshao** [comment]
thank you 
I think I found the device
It's a microphone interface extended by USB
Maybe it's not good for USB expansion device support
