### ISSUE TITLE
Update the C# tutorials to use the new multi-track API

### ISSUE THREAD

**Issue by djee-ms** [microsoft/MixedReality-WebRTC#244]
This is a TODO task to update the C# tutorials (.NET Core 3 and UWP) to use the new multi-track API. The Unity tutorial has already been updated.

**Comment by AtosNicoS** [comment]
Is the example for UWP up to date? Even if there is no tutorial, can I safely use the example as orientation?

Is it to be expected that the documentation will be adapted promptly?

**Comment by djee-ms** [comment]
I am not sure I understand any of those questions. Isn't that just answered above? If not can you please detail what you want to know?

>Is the example for UWP up to date? 
>> This is a TODO task to update the C# tutorials (.NET Core 3 and **UWP**) 

So, no.

>Even if there is no tutorial,
>> to update the C# **tutorials**

What examples do you want to use?

>Is it to be expected that the documentation will be adapted promptly?
>>This is a **TODO task** 

Yes, that is why we logged that task. This is a mandatory TODO before we can release.

**Comment by AtosNicoS** [comment]
I am using version 1.0.3 of the library, and refer to the examples in https://github.com/microsoft/MixedReality-WebRTC/tree/release/1.0/examples/TestAppUwp

So for 1.0.3 the currently online available tutorial is correct? I am a bit confused now, as it seems the website is already using docs for 2.x but there is no release yet? I am sorry, that this is not clear to me, I am new to this library.

**Comment by djee-ms** [comment]
Yes, the docs for `release/1.0` are correct for the NuGet packages 1.0.x, and are [here](https://microsoft.github.io/MixedReality-WebRTC/versions/release/1.0/). And the TestAppUWP example as you linked it is also correct.

The docs for `master` on the other hand (see [here](https://microsoft.github.io/MixedReality-WebRTC/)) use the new API present on `master` which will be released later as NuGet packages 2.0 once we are ready with that milestone (see [roadmap here](https://github.com/microsoft/MixedReality-WebRTC/issues/142)).

You have a drop-down control to select the version of the docs you want at the top right of the documentation webpage on github.io. Docs for 1.0 are titles as such, and docs for master don't have a version associated with them. The default is for `master` because the default branch is `master`.

![image](https://user-images.githubusercontent.com/49064175/80598491-57cfa000-8a21-11ea-91da-dcec7bcd3d30.png)

![image](https://user-images.githubusercontent.com/49064175/80598496-59996380-8a21-11ea-8d0a-2b5900ed5234.png)

**Comment by AtosNicoS** [comment]
Thanks a lot for clarifying!

(1) So the 2.0 tutorial (on the website) is not ready yet. How up to date is the corresponding example on master? https://github.com/microsoft/MixedReality-WebRTC/tree/master/examples/TestAppUwp

(2) The [readme](https://github.com/microsoft/MixedReality-WebRTC#known-issues) states:
> H.264 is not currently available on Desktop at all (even in software). Only VP8 and VP9 are available instead (software encoding/decoding).

while the roadmap states:

> Now that 1.0 is out with decent H.264 hardware encoding support [...]

Is that note outdated?

(3) I see the roadmap is very long, so I can assume 2.x will be available by the end of the year at the earliest?

**Comment by djee-ms** [comment]
1. TestAppUWP is mostly up-to-date with recent changes, as we use it heavily for testing changes.

2. *decent H.264 support on UWP. We cannot add support on Desktop at the moment, but hope to get it later when switching to WinRTC. So the note is not outdate, rather not very precise.

3. I hope much sooner. The big features are essentially there. We might get some preview packages before summer.
