### ISSUE TITLE
error CS0433: The type 'ICloneable' exists in both 'Microsoft.Windows.MixedReality.DotNetWinRT, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

### ISSUE THREAD

**Issue by tjhappy** [microsoft/MixedReality-WebRTC#258]
I use websocket in bestHTTP to send messages. But I get the following error during compilation. How can I solve it?
error:
Assets\Best HTTP (Pro)\BestHTTP\SecureProtocol\x509\store\IX509Selector.cs(11,11): error CS0433: The type 'ICloneable' exists in both 'Microsoft.Windows.MixedReality.DotNetWinRT, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

**Comment by djee-ms** [comment]
Hi @tjhappy,

We are not defining any `ICloneable` type in this project, so I have no idea. Note that the error is in `Microsoft.**Windows**.MixedReality`, not `Microsoft.MixedReality`, so both namespaces here are unrelated with this project.

https://stackoverflow.com/questions/1757289/where-does-error-cs0433-type-x-already-exists-in-both-a-dll-and-b-dll-come suggests to do a clean build, which would also be my first try.

If that doesn't work, reading from [the nuget.org package](https://www.nuget.org/packages/Microsoft.Windows.MixedReality.DotNetWinRT) it seems that `Microsoft.Windows.MixedReality.DotNetWinRT` is used by MRTK, so I suggest to [open an issue with them instead](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/new/choose), they might be more familiar with it and some known issues around that package. I have never seen nor heard about that error, so there is little chance we can do something about it ourselves unfortunately.

**Comment by tjhappy** [comment]
I use websocket in bestHTTP to send messages. But I get the following error during compilation. How can I solve it?
error:
Assets\Best HTTP (Pro)\BestHTTP\SecureProtocol\x509\store\IX509Selector.cs(11,11): error CS0433: The type 'ICloneable' exists in both 'Microsoft.Windows.MixedReality.DotNetWinRT, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

**Comment by tjhappy** [comment]
Thanks for your reply. It should be a problem of MRTK, I will submit this question over there
