### ISSUE TITLE
PeerConnection.InitializePluginAsync() fails to Initialize native plugin.

### ISSUE THREAD

**Issue by shaddadjr** [microsoft/MixedReality-WebRTC#261]
Hello, 

I am trying to follow the instructions on the Windows Mixed Reality WebRTC setup for Unity. I am using 1.0.3 release of the DLLs along with the the 1.0 version of the Unity plugin. In the VideoChatDemo scene I get the following exception: 

```
WebRTC plugin initializing failed. See full log for exception details.
AggregationException: One or more errors occurred.
```

I running out of the Unity Editor. The exception is occuring the the native plugin initialization function PeerConnection.InitializePluginAsync()

I tried searching other issues  and I couldn't really find a similar problem. As best I can tell I have all the appropriate 1.0.3 native DLLs in my project with the proper meta configuration values per https://microsoft.github.io/MixedReality-WebRTC/manual/helloworld-unity-importwebrtc.html

I am using Unity 2019.2.11f1

**Comment by djee-ms** [comment]
Hi @shaddadjr,

What's the rest of the exception? You can expand the lower part of the Unity console window to show more lines. Because this is not telling much, there's nothing I can do with this information.

**Comment by shaddadjr** [comment]
Hi @djee-ms thanks for the rapid response. Unfortunately this is all that is outputted into the console window, which doesn't seem to indicate much:
```
WebRTC plugin initializing failed. See full log for exception details.
AggregationException: One or more errors occurred.
Exception: Microsoft.MixedReality.WebRTC.Native.dll
UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.WebRTC.Unity.PeerConnection:OnError_Listener(String) (at Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/PeerConnection.cs:552)
UnityEngine.Events.UnityEvent`1:Invoke(String)
Microsoft.MixedReality.WebRTC.Unity.<>c__DisplayClass23_1:<InitializePluginAsync>b__1() (at Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/PeerConnection.cs:457)
Microsoft.MixedReality.WebRTC.Unity.PeerConnection:Update() (at Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/PeerConnection.cs:361)
```
Its in the InitializePluginAsync() method of PeerConnection.cs. 

I extracted the plugins from the downloaded nuget v1.0.3 packages, and renamed them from the Microsoft.MixedReality.WebRTC.Native.dll to mrwebrtc.dll. I also made sure the meta files matched what is here: https://microsoft.github.io/MixedReality-WebRTC/manual/helloworld-unity-importwebrtc.html

**Comment by djee-ms** [comment]
The docs you are linking is for the `master` branch. The one for the `release/1.0` is [here](https://microsoft.github.io/MixedReality-WebRTC/versions/release/1.0/manual/helloworld-unity-importwebrtc.html). You can access it via the top right drop-down list in the documentation website.
 
Renaming to `mrwebrtc.dll` is a `master`-only thing, this is the reason why the initializing fails : the C# library doesn't find the native DLL since you renamed it. The NuGet packages contain only code from `release/1.0` and on that branch the DLL was not renamed; the rename change came later on `master` only, and is for the upcoming 2.0 version.
