### ISSUE TITLE
VideoChatDemo Compile Errors in Unity 2019.2.6f1 (Error CS0246)

### ISSUE THREAD

**Issue by NirabhraDas013** [microsoft/MixedReality-WebRTC#265]
Hi I am trying to build the VideoChatDemo to run on Hololens 2 Emulator, but I am getting the following errors in the attached txt file. 

[MRWebRTC_Missing_Assembly_Errors.txt](https://github.com/microsoft/MixedReality-WebRTC/files/4450468/MRWebRTC_Missing_Assembly_Errors.txt)

I copied the plugins folder as instructed. Then, copied the individual mrwebrtc.dll in proper position before opening Unity. I downloaded from nuget.org and the files were named _**Microsoft.MixedReality.WebRTC.Native.dll**_. I renamed them as per instruction to **_mrwebrtc.dll_** I also double checked before opening unity if any of the meta files are missing or misplaced. They were not. 

Interestingly, The import settings of the dll files are in place properly once I started up Unity. Is it because the meta files were present or is that an indicator that something has gone wrong.

I also just noticed, all the _mrwertc.dll.meta_ files are modified to today's date. The only meta file that is not modified is the _Microsoft.MixedReality.WebRTC.dll.meta._

The meta files I received from the git project was last modified on 06/04/2020. When I run Unity, the meta files are showing last modified date of today. Could that be a reason for the problem

Please help. I am very new to WebRTC and UWP projects.

***edit***

Windows SDK version: 10.0.18362.628

**Comment by djee-ms** [comment]
Same error as #264 I'd guess? "rename mrwebrtc.dll" + "download NuGet" can't work together, see #264 for the explanations.

**Comment by NirabhraDas013** [comment]
Oh thank you for the clarification. I did not realize that would be the case. I did try the v1.0 documentation yesterday. While deploying to HoloLens 2 Emulator, I was getting the following error. 

![MR_WebRTC_Error_v1 0](https://user-images.githubusercontent.com/54432376/78789452-c85b4200-79ca-11ea-9054-3460be3f5c94.png)


After this, I started following the tutorial in the master branch. I understand that the pdb file is used for debugging. But as of that point I did not change anything. Just loaded the VideoChatDemo scene and built it. Any advice why this error would be happening?

**Comment by djee-ms** [comment]
I can't tell anything from that screenshot unfortunately. Without the PDBs we won't get any info from the callstack. Maybe try to check first the Output window of Visual Studio, see if there's anything of interest; usually WebRTC outputs lots of info there, and we might see what caused the error.

**Comment by NirabhraDas013** [comment]
> I can't tell anything from that screenshot unfortunately. Without the PDBs we won't get any info from the callstack. Maybe try to check first the Output window of Visual Studio, see if there's anything of interest; usually WebRTC outputs lots of info there, and we might see what caused the error.

Okay. I will try to do that today. I am very new in using Visual Studio to build/run a program. On Unity side I know a fair bit but this is my first project that requires Visual Studio to run.

**Comment by NirabhraDas013** [comment]
Hi, I recreated the project following v1.0 documentation and received the same error. Below txt file contains all information from the output window.

[MR_WebRTC_VCD_PDB_Not_Found_Error.txt](https://github.com/microsoft/MixedReality-WebRTC/files/4454107/MR_WebRTC_VCD_PDB_Not_Found_Error.txt)

I tried to continue from the above error breakpoint. The next error I found is excptptr.cpp not found.
Below is the information from the output window when I received that error.

[MR_WebRTC_VCD_excptptr_Not_Found_Error.txt](https://github.com/microsoft/MixedReality-WebRTC/files/4454129/MR_WebRTC_VCD_excptptr_Not_Found_Error.txt)

Sorry if these two files have some information common. This is really my first time ever trying to use Visual Studio to run a project built by Unity. And thank you for all your help.

**Comment by djee-ms** [comment]
```
WinRT originate error - 0xC00DABE0 : 'No capture devices are available.'.
WinRT originate error - 0x80070005 : 'Access is denied.'.
```

There is "no video capture device", which for HoloLens since we know there is a camera device means that you didn't allow the app access to it. So the OS is refusing access, and the app cannot use the camera, and fails to initialize the video track. You need to allow access to your app in the App Permissions settings in Windows. Same for the microphone.

**Comment by NirabhraDas013** [comment]
Oh thank you so much for the clarification.

Could you please guide me how to allow the required permission in the HoloLens 2 Emulator? I'm sorry I am completely new to this and such a newb. I have added these permissions in the player settings from Unity. Is there something I am missing?

![image](https://user-images.githubusercontent.com/54432376/78875409-76b6c400-7a6b-11ea-9a26-2532b89cdef1.png)

**Comment by djee-ms** [comment]
> You need to allow access to your app **in the App Permissions settings in Windows**.

This is not in Unity. See _e.g._ https://support.microsoft.com/en-us/help/10557/windows-10-app-permissions. This is in the Settings menu of Windows 10 inside HoloLens, in the privacy settings. Normally if you deploy **the first time** the app, Windows should pop up a dialog asking the user for permission, but I know there's a bug and occasionally that dialog doesn't show up and the OS straight refuses the permission. Once you allowed the app it will keep the settings, and on next run you don't need to allow again. This is the same kind of permission you have for camera/microphone on _e.g._ an Android phone or on iPhone. You can also try to completely uninstall and reinstall the app (clean deploy), that should pop up the dialog again too.

**Comment by NirabhraDas013** [comment]
Hi, I looked at the settings>privacy screen inside the hololens emulator and I don't know how to uninstall and reinstall app as I am using the green run button to run the loaded .sln directly into HoloLens 2 Emulator. 

But I restarted the system and run it again. The error is the same but the output information is a bit different I am copying and pasting the bit that's different for comparison. 

**_Output info from earlier run_**
```
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

NodeDSS remote peer ID : 
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
NodeDssSignalerUI:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

'MR_WebRTC_UWP.exe' (Win32): Loaded 'C:\Windows\SysWOW64\mfcore.dll'. 
'MR_WebRTC_UWP.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ksuser.dll'. Symbols loaded.
'MR_WebRTC_UWP.exe' (Win32): Loaded 'C:\Windows\SysWOW64\mfperfhelper.dll'. Symbols loaded.
'MR_WebRTC_UWP.exe' (Win32): Loaded 'C:\Windows\SysWOW64\CompPkgSup.dll'. Symbols loaded.
Exception thrown at 0x76E73602 (KernelBase.dll) in MR_WebRTC_UWP.exe: WinRT originate error - 0xC00DABE0 : 'No capture devices are available.'.
'MR_WebRTC_UWP.exe' (Win32): Loaded 'C:\Windows\SysWOW64\CapabilityAccessManagerClient.dll'. Symbols loaded.
Exception thrown at 0x76E73602 (KernelBase.dll) in MR_WebRTC_UWP.exe: WinRT originate error - 0x80070005 : 'Access is denied.'.
Setting up 1 worker threads for Enlighten.
  Thread -> id: 12b8 -> priority: 1 
The thread 0x880 has exited with code 0 (0x0).
avcore\audiocore\client\audioclient\audioclientcore.cpp(1536)\AUDIOSES.DLL!67E8F346: (caller: 67E766EE) ReturnHr(1) tid(1778) 887C005E Exception thrown at 0x76E73602 in MR_WebRTC_UWP.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x10329E10.
```

**_Output info after system restart_**
```
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

'MR_WebRTC_UWP.exe' (Win32): Loaded 'C:\Windows\SysWOW64\MFCaptureEngine.dll'. Symbols loaded.
NodeDSS remote peer ID : 
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
NodeDssSignalerUI:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

'MR_WebRTC_UWP.exe' (Win32): Loaded 'C:\Windows\SysWOW64\mfcore.dll'. 
avcore\audiocore\client\audioclient\audioclientcore.cpp(1536)\AUDIOSES.DLL!674FF346: (caller: 674E66EE) ReturnHr(1) tid(1204) 887C005E Exception thrown at 0x76613602 in MR_WebRTC_UWP.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x0E629A48.
```

As always, thank you so much for your help. I am learning a lot how to debug and fix problems in Visual Studio.

**Comment by djee-ms** [comment]
Nothing changed. You need to fix this permission issue in your emulator. Restarting the system won't change anything, permission settings are saved forever unless you uninstall the app, similar to Android and iOS apps on phones.

You can use the Device Portal ([docs here](https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-windows-device-portal)) to access the installed apps, and uninstall from there. You can also from inside the device/emulator do a long-press on an app icon in the main HoloLens menu and select uninstall, see explanations associated with the ["I'm getting low disk space error"](https://docs.microsoft.com/en-us/hololens/hololens-faq#im-getting-a-low-disk-space-error) question. Finally you can check tutorials on Windows 10 permissions like [this one](https://www.youtube.com/watch?v=QNWndw5Im9U) (disclaimer: it's a third-party link to a user not affiliated with Microsoft).

**Comment by NirabhraDas013** [comment]
> Nothing changed. You need to fix this permission issue in your emulator. Restarting the system won't change anything, permission settings are saved forever unless you uninstall the app, similar to Android and iOS apps on phones.
> 
> You can use the Device Portal ([docs here](https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-windows-device-portal)) to access the installed apps, and uninstall from there. You can also from inside the device/emulator do a long-press on an app icon in the main HoloLens menu and select uninstall, see explanations associated with the ["I'm getting low disk space error"](https://docs.microsoft.com/en-us/hololens/hololens-faq#im-getting-a-low-disk-space-error) question. Finally you can check tutorials on Windows 10 permissions like [this one](https://www.youtube.com/watch?v=QNWndw5Im9U) (disclaimer: it's a third-party link to a user not affiliated with Microsoft).

Thank you so much for all the help. I noticed everytime I am restarting my HoloLens Emulator, the deployed app is gone. So rather than runnign it directly from VS, I used Build>Deploy then accessed the permission. below screenshots are for deploy and camera permission.

![MR_WebRTC_Deployed](https://user-images.githubusercontent.com/54432376/78891171-a45c3700-7a84-11ea-8dc9-4c8aabe3cf58.PNG)
![MR_WebRTC_Camera Access](https://user-images.githubusercontent.com/54432376/78891190-ad4d0880-7a84-11ea-818b-b4e9ce71f149.PNG)

But what I have found is that there is no entry for MR_WebRTC_UWP (My app name) in the microphone access. Screenshot below.
![image](https://user-images.githubusercontent.com/54432376/78891396-20567f00-7a85-11ea-9850-e3d5e4d73f20.png)

Also, the app runs but gives audio/video error. I am guessing that is due to the missing microphone permission? Screenshot of running app below.

![image](https://user-images.githubusercontent.com/54432376/78891644-935ff580-7a85-11ea-9c05-a57a33c7f20e.png)

Again, lots and lots of thanks for helping me out.

**Comment by djee-ms** [comment]
There might be an issue with the emulator itself, I never tried to be honest. Looking at the screenshot above it doesn't look like the track is created at all since the "Load Present Skip" texts are still untouched, which means the video didn't start. Also, I assume the emulator will try to use your webcam, so the emulator itself also probably needs permission to access the webcam, but this time from the Windows 10 of the hosting PC where the emulator runs. Same for the microphone. I'm assuming you don't see a permission for the microphone because the code throws an exception on the camera first, and never execute the microphone code.

**Comment by NirabhraDas013** [comment]
I tried that last just about half an hour ago but there is no entry for the emulator in Settings>Privacy and also when I tried to go through the app features, there wasn't the advanced features button available. I am attaching the screenshots.

![image](https://user-images.githubusercontent.com/54432376/78910979-4a1e9e80-7aa3-11ea-9d0b-f40d9a34dfcd.png)
![image](https://user-images.githubusercontent.com/54432376/78911013-5571ca00-7aa3-11ea-81e0-522d074c66b9.png)
![image](https://user-images.githubusercontent.com/54432376/78911053-66bad680-7aa3-11ea-8955-265d69c458cd.png)
![image](https://user-images.githubusercontent.com/54432376/78911083-72a69880-7aa3-11ea-9923-d8bcd64a39cc.png)
![image](https://user-images.githubusercontent.com/54432376/78911166-94078480-7aa3-11ea-8247-f08af867e28c.png)
![image](https://user-images.githubusercontent.com/54432376/78911186-9b2e9280-7aa3-11ea-8123-7f7278c8dd62.png)

**Comment by NirabhraDas013** [comment]
Hi, I did some more fiddling around and searching in google. I found the below link. I don't know if this is correct information. Could you verify and let me know please? I am not getting much information about it in Google search

https://stackoverflow.com/questions/55861060/web-cam-support-in-hololens-emulator

**Comment by djee-ms** [comment]
Yes this info is correct, so you are out of luck here. I asking internally and at this time the emulator cannot use a webcam connected to the host PC. See this other answer on SO by Paul Barnett who is a Microsoft employee knowledgeable about this topic: https://stackoverflow.com/questions/59772861/is-it-possible-to-use-my-desktop-pcs-webcam-with-the-hololens-2-emulator/59777788.

**Comment by NirabhraDas013** [comment]
Okay, Thank you so so much for all your help. Even if the webcam does not work, I learned a lot of things about the emulator and making builds and debugging in Visual Studio.

Closing this issue now. Again, lots and lots of thanks.
