### ISSUE TITLE
Video capture on HoloLens 2 not working

### ISSUE THREAD

**Issue by fibann** [microsoft/MixedReality-WebRTC#273]
The video capture module from WinRTC doesn't seem to be working on HoloLens 2 (logs report no devices found, but I haven't investigated further).

**Comment by lust0yixiong** [comment]
I had met the same issue, did you solved this problem?

**Comment by fibann** [comment]
@lust0yixiong this issue is relative to the `experimental/undock` branch (see "undock" label) and not to the release/master version of MR-WebRTC. If you are indeed using the `undock` branch, note that - as the name says - it is experimental and not supported at the moment, this issue is mainly for tracking work.

If you are using a release/master version, please open a new issue using the "Bug report" template and specify the full context of the issue you are having.

**Comment by fibann** [comment]
WinRTC should have fixed bugs/limitations on their end. What's missing here is filtering profiles on our end through the API that has just been added (https://github.com/microsoft/winrtc/pull/35).

**Comment by fibann** [comment]
Should be fixed by #440
