### ISSUE TITLE
Create wrong offer after add local video track 

### ISSUE THREAD

**Issue by HenryCui1979** [microsoft/MixedReality-WebRTC#281]
I tried to create offer after call "localVideoTrack = await _peerConnection.AddLocalVideoTrackAsync();"
The offer sdp show like this 
"a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli"

"a=recvonly" was wrong instead of "a=sendrecv"
the video of camera can not be sent to remote.What should I do to solve this problem.

I tried to create offer after call "var source1 = ExternalVideoTrackSource.CreateFromI420ACallback(CustomI420AFrameCallback);
            var track1 = _peerConnection.AddCustomLocalVideoTrack("custom_i420a", source1);"
The video of I420 source can be sent to remote

**Comment by HenryCui1979** [comment]
I add local video track as follow:
"var trackConfig = new LocalVideoTrackSettings
            {
                trackName = "local_camera_video",
                videoDevice = videoCaptureDevice,
                videoProfileId = string.Empty,
                videoProfileKind = VideoProfileKind.Unspecified,
                width = 640,
                height = 480,
                framerate = 15,
                enableMrc = false // for test
            };
            localVideoTrack = await _peerConnection.AddLocalVideoTrackAsync(trackConfig);"

**Comment by djee-ms** [comment]
Is the video track actually created? If not then that would make sense. I see you're constraining the width, height, and framerate, which can lead to over-constraining and failing to find a suitable capture format. In particular, the framerate looks hard-coded instead of picking one from the list of supported formats enumerated at runtime; if the device returns 15.00001 for the framerate then your 15.0 will mismatch.

**Comment by HenryCui1979** [comment]
> Is the video track actually created? If not then that would make sense. I see you're constraining the width, height, and framerate, which can lead to over-constraining and failing to find a suitable capture format. In particular, the framerate looks hard-coded instead of picking one from the list of supported formats enumerated at runtime; if the device returns 15.00001 for the framerate then your 15.0 will mismatch.

I tried to get the video frame of camera from local video track by this "localVideoTrack.I420AVideoFrameReady += LocalVideoTrack_I420AVideoFrameReady;".
In the callback LocalVideoTrack_I420AVideoFrameReady,I printed the width and height of the frame correctly
"private void LocalVideoTrack_I420AVideoFrameReady(I420AVideoFrame frame)
        {
            Debug.WriteLine("LocalVideoTrack_I420AVideoFrameReady,frame.width:" + frame.width+ ",frame.height:" + frame.height);
        }"
Can this show that camera has been opend successful?

**Comment by djee-ms** [comment]
Yes if you get a callback and you get some non-zero width/height then the camera has been opened successfully.

**Comment by HenryCui1979** [comment]
> Yes if you get a callback and you get some non-zero width/height then the camera has been opened successfully.

Thanks for your reply.If camera was opened and local video track was active,why "recvonly" was set in the sdp for video?What should I do to solve it?

**Comment by djee-ms** [comment]
Are you making the offer on the same peer that opened the camera?

**Comment by HenryCui1979** [comment]
> Are you making the offer on the same peer that opened the camera?

Yes, I made offer on the peer that opened the camera

**Comment by djee-ms** [comment]
Ok I have no idea then, this is the first time I see this. Are you using Unity or not? Either way, any chance you connect the Visual Studio debugger and grab the Output debug logs that the internal implementation is printing? That would help I think figure out what is going on.

**Comment by HenryCui1979** [comment]
> Ok I have no idea then, this is the first time I see this. Are you using Unity or not? Either way, any chance you connect the Visual Studio debugger and grab the Output debug logs that the internal implementation is printing? That would help I think figure out what is going on.

Hi，I find the problem and solve it thanks for your reply.I call add video tarck after create offer.I will close this issue

**Comment by djee-ms** [comment]
Ok thanks for getting back with an answer, glad it's solved.
