### ISSUE TITLE
WebRTC plugin Initializing failed in UnityEditor - Exception: mrsPeerConnectionRegisterIceGatheringStateChangedCallback

### ISSUE THREAD

**Issue by robibkuiper** [microsoft/MixedReality-WebRTC#282]
When walking throught the documentation to for unity i am at the step to create a local video stream (using the project on the master branche). When testing if setup works the quad stays black (the tutorial states it should be pink) and there is an error in the log. 

The log shows this:
WebRTC plugin initializing failed. See full log for exception details.
AggregationException: One or more errors occurred.
Exception: mrsPeerConnectionRegisterIceGatheringStateChangedCallback
UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.WebRTC.Unity.PeerConnection:OnError_Listener(String) (at Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/PeerConnection.cs:603)
UnityEngine.Events.UnityEvent`1:Invoke(String)
Microsoft.MixedReality.WebRTC.Unity.<>c__DisplayClass25_1:<InitializePluginAsync>b__1() (at Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/PeerConnection.cs:502)
Microsoft.MixedReality.WebRTC.Unity.PeerConnection:Update() (at Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/PeerConnection.cs:389)

When pressing play de dss local server does get logs from the client.

I am using Unity 2018.4.21f1 configured for windows standalone. I did not manage to build the libraries myself so i added the prebuild libraries from nuget in the correct folders before opening the Unity project. The libraries seem to have the correct settings and there are no compiler errors.

Does this have to do with a version mismatch? meanwhile i'll try building the libraries from my pc to make sure the versions are correct.

**Comment by djee-ms** [comment]
If you copied the DLLs from the NuGet packages then you need to use the `release/1.0` branch from where those NuGet packages were built, otherwise the API will mismatch and likely fail to load or crash later.
