### ISSUE TITLE
Building for Android:

### ISSUE THREAD

**Issue by HyperLethalVector** [microsoft/MixedReality-WebRTC#312]
I'm unable to build for android, I've setup according to the scattered READMEs across the build folder.
configuring the libwebrtc project using 

> ./config.sh -d /mnt/d/build_webrtc -b branch-heads/71 -t android -c arm64 

However compiling leads to:
![image](https://user-images.githubusercontent.com/8954571/80688983-ce48cc80-8b0b-11ea-90b6-2c8abee5130d.png)

have I pulled from the wrong branch head?

**Comment by djee-ms** [comment]
I'm guessing you're not using Python 2.7, which Google insists on using for all their tooling. Can you please try with that?

**Comment by HyperLethalVector** [comment]
Both python 2.7 and python 3 are installed on my system, with the defaults selecting python 2.7 first when I check version in terminal. I believe the 

Would there be any reason the build scripts are choosing python 3? 

Building from the master branch in config works fine. But I then come across another problem with it later when I compile the library from Android 

(See https://github.com/microsoft/MixedReality-WebRTC/pull/193#discussion_r407267088 for details)

**Comment by HyperLethalVector** [comment]
I tried running the file manually and came across this:

`python: can't open file '../../../../build/android/gyp/ijar.py': [Errno 2] No such file or directory`

**Comment by HyperLethalVector** [comment]
I've setup a separate machine with ubuntu 18.04, and compiling seems to have worked, seems this issue might be WSL related, but I'll close this anyways
