### ISSUE TITLE
Problem building - 'Could not copy the file "C:\mr-webrtc\bin\UWP\ARM\Debug\Microsoft.MixedReality.WebRTC.Native.dll" because it was not found'

### ISSUE THREAD

**Issue by retallicka** [microsoft/MixedReality-WebRTC#32]
I followed the instructions over at https://microsoft.github.io/MixedReality-WebRTC/manual/building.html
I encountered a problem using Visual Studio 2019 then I saw an Issue (#14) which seemed to suggest only Visual Studio 2017 was supported so I tried with Visual Studio 2017 after resetting my git status

Trying to build with VS 2017 v15.9.13 I get these three errors

`Could not copy the file "C:\mr-webrtc\bin\UWP\ARM\Debug\Microsoft.MixedReality.WebRTC.Native.dll" because it was not found.	Microsoft.MixedReality.WebRTC.TestAppUWP`
			
`Could not copy the file "C:\mr-webrtc\bin\UWP\ARM\Debug\Microsoft.MixedReality.WebRTC.Native.pdb" because it was not found.	Microsoft.MixedReality.WebRTC.TestAppUWP`
			
`Cannot open include file: 'cryptopp/allocatorwithnul.h': No such file or directory	Microsoft.MixedReality.WebRTC.Native.UWP	c:\mr-webrtc\external\webrtc-uwp-sdk\webrtc\xplatform\zslib-eventing\zslib\eventing\types.h	40	`

**Comment by djee-ms** [comment]
Hi @retallicka, thanks for logging those.

- The first issue with missing DLL/PDB is Visual Studio being picky about some build order compiling and some reference inside the project. I have yet to understand exactly what happens, but if you compile a second time that `TestAppUWP` project after the `Native.UWP` was compiled it should find the file. I am not sure why it doesn't find it the first time. We suspect that there is a problem with this DLL being a direct reference in the csproj, maybe there is a better mechanism.

- I just hit yesterday the second issue about `cryptopp` on a new machine. I will have a fix soon; this is just I think a matter of adding an include path to `external/webrtc-uwp-sdk/webrtc/xplatform` where `cryptopp` is.

**Comment by djee-ms** [comment]
Fixed the `cryptopp` build error with 945c967e8d9db6411ad6a4b91fa3d1e59230b688 on `master`.

**Comment by djee-ms** [comment]
Hopefully fixed the `TestAppUWP` build not finding the native DLL with 4efd7122a95ac8f712452c4d80ff5a99d5a127ce on `master`, can you please give it a try @retallicka? I suggest cleaning and rebuilding the entire solution to test it doesn't work just thanks to a previous build. I just did that on x64 Debug and it works on my machine.

**Comment by retallicka** [comment]
@djee-ms the build works now, thanks for fixing so quickly 👍

**Comment by djee-ms** [comment]
Great, thanks! I need to add a unit test to avoid breaking the solution; logged #33.
