### ISSUE TITLE
Can't find absl/*

### ISSUE THREAD

**Issue by jonlindeheim** [microsoft/MixedReality-WebRTC#332]
I get this when trying to build Microsoft.MixedReality.WebRTC.sln (latest master):

Cannot open include file: 'absl/types/optional.h': No such file or directory c:\code\mixedreality-webrtc\external\webrtc-uwp-sdk\webrtc\xplatform\webrtc\api\audio_codecs\audio_decoder_factory.h

Anyone recognize this error?

**Comment by djee-ms** [comment]
Did you clone recursively?

**Comment by jonlindeheim** [comment]
No. Closing...
