### ISSUE TITLE
"CreateOffer()" from Hololens2 can't get answer?

### ISSUE THREAD

**Issue by lust0yixiong** [microsoft/MixedReality-WebRTC#358]
I am testing the connection between Hololens2 with PC, when createoffer from pc, the connection is normal(video and audio data); but whten i createoffer from Hololens2, the connection can't be established.
The node server can find both peer, and the pc also received the offer from Hololens2, but Hololens2 receiving nothing from remotePC. I guess may be the answer info was blocked by firewall, but where can i set the firewall in Hololens2?
 The debug log in UnityEditor is attached as follow:
![log](https://user-images.githubusercontent.com/4714775/82276626-5eb25880-99b8-11ea-947c-4826cad6aefb.jpg)

**Comment by lust0yixiong** [comment]
Plus: the Hololens2 Project works normal in UnityEditor(connection will be established ), but won't work while deployed in Hololens2 device.

**Comment by lust0yixiong** [comment]
Just found the solution in issue#223 by **jacob zhuang**, quote as follow: "_that reason is the desktop don't support h264 after i read the readme.md file carefully .All i need to do is set video codec to vp8/vp9 in my hololens project_ ."
May be this can give some help for others.

**Comment by djee-ms** [comment]
I'm also a bit skeptical seeing that the first message you receive is an ICE candidate, even before the offer. Did you try restarting the `node-dss` server? I suspect there are some pending messages from a previous failed connection, and when try a new time the old messages are delivered and confuse the peer connection which was not expecting ICE candidates at this time.

**Comment by djee-ms** [comment]
Closing as invalid; the H.264 limitation is unfortunate and confusing, but is stated in the README and various other places. We'll hopefully get rid of it soon.
