### ISSUE TITLE
UWP video capture requests audio capture by mistake, forcing the need for the "microphone" capability

### ISSUE THREAD

**Issue by djee-ms** [microsoft/MixedReality-WebRTC#360]
**Describe the bug**
When using UWP, the video capture module requests both the audio and video capture permissions by mistake instead of the video only. This forces the application to request both the "microphone" and "webcam" UWP capabilities, otherwise access will be denied and the video capture module will crash.

**To Reproduce**
1. Remove the audio access request from `PeerConnection.cs`, leaving only the video one.
2. Deploy on UWP without the "microphone" capability.

**Expected behavior**
Only the "webcam" capability is needed if using only video tracks and not audio tracks.

**Environment**
 - Platform: UWP
 - Architecture: all
 - Unity version: all
 - Target device: all UWP devices

**Additional context**
See https://github.com/webrtc-uwp/webrtc-apis/blob/0f64d6c5072b583981ed0c514c62829f4849f99c/windows/wrapper/impl_webrtc_VideoCapturer.cpp#L925; the `StreamingCaptureMode` property is not assigned, likely defaulting to `AudioAndVideo`.

**Comment by djee-ms** [comment]
Actually even fixing `impl_webrtc_VideoCapturer.cpp` the bug remains because the audio engine is initialized at startup and always tries to initialize the microphone, and the WASAPI implementation on UWP doesn't check authorizations and just tries to start microphone capture.

**Comment by JacopoMarullo** [comment]
> Actually even fixing `impl_webrtc_VideoCapturer.cpp` the bug remains because the audio engine is initialized at startup and always tries to initialize the microphone, and the WASAPI implementation on UWP doesn't check authorizations and just tries to start microphone capture.

So for UWP we can consider this bug fixed?

**Comment by fibann** [comment]
@JacopoMarullo IIRC if the app doesn't have audio permission the audio code will produce a number of failures ofc, but WebRTC won't crash, so I guess we can consider this fixed. Unless I am misremembering and/or you notice more issues, in which case please reopen.

**Comment by fibann** [comment]
I see that you have opened https://github.com/microsoft/MixedReality-WebRTC/issues/638, will investigate and update that.
