### ISSUE TITLE
Missing Prefab in WebrtcSinglePeerExample.unity

### ISSUE THREAD

**Issue by derekfreed** [microsoft/MixedReality-WebRTC#37]
![image](https://user-images.githubusercontent.com/10147303/63057380-f077bd00-be9e-11e9-84b0-80e144509c94.png)
I made sure to clean my libraries when I noticed this. Not sure if the issue is on my end or in the source. Is there some dependency not checked into the source?

**Comment by djee-ms** [comment]
Hi @derekfreed,

I need to have a look. This is an old example scene that I am not sure I will keep; you'd better have a look at the `VideoChatDemo` scene instead. Sorry for the confusion.

That being said, the prefab is [checked in here (WebrtcSinglePeerExample.prefab)](https://github.com/microsoft/MixedReality-WebRTC/blob/master/libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity.Examples/WebrtcSinglePeerExample.prefab), so I'm not sure why Unity is not finding it. I will investigate.

**Comment by djee-ms** [comment]
Confirmed the Prefab reference is wrong. Also there is nothing of interest in that scene, this is a legacy one which is superseded by the VideoChatDemo sample. Will delete.
