### ISSUE TITLE
api/audio_codecs/builtin_audio_decoder_factory.h: No such file or directory

### ISSUE THREAD

**Issue by dw8869** [microsoft/MixedReality-WebRTC#376]
mrwebrtc-win32 build error message
: api/audio_codecs/builtin_audio_decoder_factory.h: No such file or directory.

How can i build this project?

**Comment by djee-ms** [comment]
Hi @dw8869,

You most likely didn't clone with `--recursive` so you're missing some files.

**Comment by dw8869** [comment]
@djee-ms  Thanks.
One more question.

I'm building an Android plug-in for Unity.

can i use this ?
implementation 'org.webrtc:google-webrtc:1.0.+'

**Comment by djee-ms** [comment]
If you're asking about Google's prebuilt Android binaries, they are deprecated and can't be used.

**Comment by dw8869** [comment]
Can you provide a guide for building chromium in Windows?

**Comment by djee-ms** [comment]
Building Chromium? No, I have no idea, you should ask Google. We're not building Chromium for this project.

Building `libwebrtc`? I don't think you need it, but just in case there's [Building the Core dependencies from sources](https://microsoft.github.io/MixedReality-WebRTC/manual/building-core.html) in the documentation. But this is fairly involved so unless there's a good reason to do so I'd strongly recommend against doing that.

**Comment by dw8869** [comment]
@djee-ms 

Don't I need **libwebrtc** to build **libwebrtc.aar**, **mrwebrtc.aar**?
