### ISSUE TITLE
VideoChatDemo not working in Android (Unity)

### ISSUE THREAD

**Issue by mcfly3001** [microsoft/MixedReality-WebRTC#381]
Hi,

I am trying to get the VideoChatDemo running to stream from PC to an Android device. I am using the 1.0.3 release and followed the installation instructions accordingly.
When switching the build platform in Unity to Android and I press Play in the UnityPlayer I receive the following error:

```shell
NullReferenceException: Object reference not set to an instance of an object
Microsoft.MixedReality.WebRTC.Unity.PeerConnection.InitializeAsync (System.Threading.CancellationToken token) (at Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/PeerConnection.cs:259)
Microsoft.MixedReality.WebRTC.Unity.PeerConnection.Start () (at Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/PeerConnection.cs:346)
```

Furthermore, when trying to deploy to an Android phone I have another problem distributing the correct Microsoft.MixedReality.WebRTC.Native.dll. In the LogCat the following error appears:

```console
2020-05-26 16:05:13.110 7788-7929/com.dt.webrtc E/Unity: Unable to find Microsoft.MixedReality.WebRTC.Native.dll
2020-05-26 16:05:13.163 7788-7853/com.dt.webrtc E/Unity: AndroidJavaException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.dt.webrtc-sAQS-BMU0W8W3mb_6qzHrw==/base.apk"],nativeLibraryDirectories=[/data/app/com.dt.webrtc-sAQS-BMU0W8W3mb_6qzHrw==/lib/arm, /data/app/com.dt.webrtc-sAQS-BMU0W8W3mb_6qzHrw==/base.apk!/lib/armeabi-v7a, /system/lib, /hw_product/lib]]] couldn't find "libjingle_peerconnection_so.so"
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.dt.webrtc-sAQS-BMU0W8W3mb_6qzHrw==/base.apk"],nativeLibraryDirectories=[/data/app/com.dt.webrtc-sAQS-BMU0W8W3mb_6qzHrw==/lib/arm, /data/app/com.dt.webrtc-sAQS-BMU0W8W3mb_6qzHrw==/base.apk!/lib/armeabi-v7a, /system/lib, /hw_product/lib]]] couldn't find "libjingle_peerconnection_so.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1668)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
    	at com.uni
2020-05-26 16:05:14.146 7788-7853/com.dt.webrtc E/Unity: NullReferenceException: Object reference not set to an instance of an object
      at Microsoft.MixedReality.WebRTC.Unity.NodeDssSignaler+<CO_GetAndProcessFromServer>d__15.MoveNext () [0x001ef] in D:\Projects\MRWebRTC\MRWebRTC\Assets\Microsoft.MixedReality.WebRTC.Unity\Scripts\Signaling\NodeDssSignaler.cs:237 
      at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00027] in <d71499eab75645c19df09ba17af9a506>:0 
```

It seems to me that I am doing something wrong with the Assets/Plugin DLLs. I followed the instructions which state that I need to close the Unity project, copy the Plugins folder of the git-repo (relase 1.0.3) and then manually copying the DLL files downloaded from nuget (release 1.03). 
When reopening the unity project though and trying to create an Android build I immediatly reveived an error warning that multiple DLLs "Microsoft.MixedReality.WebRTC.Native.dll" are colliding. I fixed this error by manully activating Android only for the DLL in "Assets/Plugins/WSA/ARM" in the inspector editor of Unity.

I was able to get the Demo running on PC standalone though I had to manually copy the native-DLL to the root of the exe-file (according to issue #77).
I am struggeling to get things to work in Android. Which DLL needs to be set for the Android build (is it Plugins/WSA/ARM?)? What could be the reason for the error in the PeerConnection script?

Any help would be great! Thanks!

**Comment by djee-ms** [comment]
Hi @mcfly3001,

> 1.0.3 release and followed the installation instructions accordingly.
When switching the build platform in Unity to Android...

I stop you right there : Android support doesn't even exist in 1.0.3, it was added much later. You cannot use the NuGet packages (which are built from `release/1.0` and use the v1 API) with the Android support (added on `master`, supports only the v2 API).

There is also no prebuilt Android binaries; the `mrwebrtc.aar` Android archive needs to be built from sources, see `tools/build/libwebrtc` then `tools/build/android` (in that order). This is why Unity complains.

Finally, we are working on a v2.0 release which will provide NuGet packages for the v2 API for native and C# on Windows platforms (Desktop and UWP), but until then your only option is to build from sources using the `master` branch so that your PC app uses the same API as the one the Android library uses. See [instructions here](https://microsoft.github.io/MixedReality-WebRTC/manual/building.html).

**Comment by mcfly3001** [comment]
Hi djee,

thanks for clarifying that Android is not supported by default. Then I missunderstood the main readme which states that

> MixedReality-WebRTC is currently available for Windows 10 Desktop and UWP, with or without Unity, and Android (Unity only).

Maybe it might make sense to have a table in the readme telling which release supports which platform.

I also recently tried to use the master branch but had some errors about an invalid "package.json" when trying to add the repo as additional package to Unity. Could be though that I was doing something wrong.
 
I will then give it a try once more and try to build the Android sources manually. There is also a branch "unity_android_build". Would this be branch to use? Or are the main features already in the master branch?
If I find more problems when trying to create an android build, is it usual to open a ticket here for asking for help (of course I would first search in all existing tickets). Or is there some kind of forum available?

Thanks again!
