### ISSUE TITLE
Error in AAR LibWebRTC merge.

### ISSUE THREAD

**Issue by rygo6** [microsoft/MixedReality-WebRTC#393]
I am trying to run the build process for android and am having an issue when it gets to this new code that was added here:
https://github.com/microsoft/MixedReality-WebRTC/commit/25dd9b5dd00794571febeada7b2269a425440345

This is my resulting error:

```
$ ./gradlew.bat assembleRelease

> Task :webrtc-native:externalNativeBuildRelease
Build mrwebrtc arm64-v8a
ninja: no work to do.

> Task :webrtc-native:mergeLibwebrtcArchive FAILED
./merge-archives.sh exited with code 1. Run with -v to get more info.
ERROR: input archive C:\Developer\MixedReality-WebRTC      ooluildndroid\webrtc-native/build/outputs/aar/mrwebrtc.aar is not a file

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':webrtc-native:mergeLibwebrtcArchive'.
> Process 'command 'bash'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
25 actionable tasks: 2 executed, 23 up-to-date
```

The path to the .aar seems a bit garbled from the echo -e output. But I checked in the merge-archives.sh and the actual path under $MRWEBRTC_AAR is not garbled and does point to a file.

Not sure if this new sh script needs debugging or if something else could be wrong? The android build process was working before this.

**Comment by djee-ms** [comment]
Hi @rygo6,

What's the actual path that gets garbled? I have no issue myself locally. You are compiling on Windows with WSL2, right? I tested only with an actual Linux machine.

**Comment by rygo6** [comment]
I am trying to compile with msys on windows. Should I be doing this with WSL2?

The actual path is this:
C:\Developer\MixedReality-WebRTC\tools\build\android\webrtc-native\build\outputs\aar\mrwebrtc.aar

I tried just hardcoding that path and also:
/c/Developer/MixedReality-WebRTC/tools/build/android/webrtc-native/build/outputs/aar/mrwebrtc.aar

Both had the same issue.

**Comment by rygo6** [comment]
File definitely exists and the test command works in msys just fine to find the file.

```
$ test -f /c/Developer/MixedReality-WebRTC/tools/build/android/webrtc-native/build/outputs/aar/mrwebrtc.aar && echo exists
exists
```

This also fails when I try to 'Make Project' in Android Studio.

**Comment by rygo6** [comment]
Found out the path passed into the shell script needs to be:
`"/mnt/c/Developer/MixedReality-WebRTC/tools/build/android/webrtc-native/build/outputs/aar/mrwebrtc.aar"`
In order to work with msys.

**Comment by djee-ms** [comment]
I never tried but @eanders-MS said that only WSL2 works, and Google officially only supports an actual Linux distribution, not any Linux-on-Windows environment. So no MSYS is not supported, and I doubt it will work even if you manage to get over that error. Or did you say it was working for you before?

**Comment by rygo6** [comment]
It is working now. It was just that path issue. Shell script needs to replace C;\ with a /mnt/c. 

Mrwebrtc builds for android just fine on windows with msys or powershell. It is only libwebrtc that needs WSL2.

**Comment by djee-ms** [comment]
I don't see how the shell script can replace anything, otherwise it will break Linux. The path is specific to your system.

**Comment by rygo6-MS** [comment]
I created PR #399 with the fix I added to the shell script if you would like to pull it back to master. I will close this issue now.

**Comment by rygo6** [comment]
I created PR #399 with the fix I added to the shell script if you would like to pull it back to master. That resolved the issue for me, so I will close this now. Thank you.
