### ISSUE TITLE
Please use /MD instead of /MT runtime library

### ISSUE THREAD

**Issue by ETLang** [microsoft/MixedReality-WebRTC#394]
Honestly this isn't a bug per se, but it's problematic enough that from my perspective it might as well be one.

webrtc.lib is compiled with static runtime linking (/MT) instead of dynamic (/MD). The problem with this is that all the .libs I'm importing into my project must match in order for it to successfully link.

Conventionally, /MD is preferred over /MT because /MT is prone to linker conflicts that are difficult to resolve (when multiple imported .libs use the same runtime libraries) and tends to bloat the size of the output executable.

In any case, I've got other libraries I'm using that are compiled with /MD, and I need a build of webrtc.lib that is as well. Thank you!

Evan

**Comment by djee-ms** [comment]
`webrtc.lib` is owned by Google, please ask them. We have no control over what they do. They always use static library for Chromium and WebRTC because as far as I know it avoids another entire class of errors. But I cannot speak for them. I don't think there's a simple way to switch to dynamic CRT.
