### ISSUE TITLE
VideoChatDemo Build Errors in Unity 2019.1.0f2

### ISSUE THREAD

**Issue by astaikos316** [microsoft/MixedReality-WebRTC#40]
I have been trying to build the VideoChatDemo in Unity to run on a Hololens but have been getting the following errors:

Assets\Microsoft.MixedReality.WebRTC.Unity\Scripts\Media\RemoteVideoSource.cs(187,48): error CS0246: The type or namespace name 'I420AVideoFrame' could not be found (are you missing a using directive or an assembly reference?)
Assets\Microsoft.MixedReality.WebRTC.Unity\Scripts\Media\LocalVideoSource.cs(125,47): error CS0246: The type or namespace name 'I420AVideoFrame' could not be found (are you missing a using directive or an assembly reference?)
Assets\Microsoft.MixedReality.WebRTC.Unity\Scripts\Media\VideoSource.cs(34,16): error CS0246: The type or namespace name 'VideoFrameQueue<>' could not be found (are you missing a using directive or an assembly reference?)
Assets\Microsoft.MixedReality.WebRTC.Unity\Scripts\Media\VideoSource.cs(34,32): error CS0246: The type or namespace name 'I420VideoFrameStorage' could not be found (are you missing a using directive or an assembly reference?)
Assets\Microsoft.MixedReality.WebRTC.Unity\Scripts\Media\MediaPlayer.cs(64,16): error CS0246: The type or namespace name 'VideoFrameQueue<>' could not be found (are you missing a using directive or an assembly reference?)
Assets\Microsoft.MixedReality.WebRTC.Unity\Scripts\Media\MediaPlayer.cs(64,32): error CS0246: The type or namespace name 'I420VideoFrameStorage' could not be found (are you missing a using directive or an assembly reference?)
Assets\Microsoft.MixedReality.WebRTC.Unity\Scripts\Signaling\Signaler.cs(14,53): error CS0246: The type or namespace name 'ISignaler' could not be found (are you missing a using directive or an assembly reference?)
Assets\Microsoft.MixedReality.WebRTC.Unity\Scripts\PeerConnection.cs(106,23): error CS0234: The type or namespace name 'PeerConnection' does not exist in the namespace 'Microsoft.MixedReality.WebRTC' (are you missing an assembly reference?)
Assets\Microsoft.MixedReality.WebRTC.Unity\Scripts\PeerConnection.cs(219,40): error CS0234: The type or namespace name 'PeerConnection' does not exist in the namespace 'Microsoft.MixedReality.WebRTC' (are you missing an assembly reference?)
Assets\Microsoft.MixedReality.WebRTC.Unity\Scripts\Signaling\Signaler.cs(28,29): error CS0246: The type or namespace name 'SignalerMessage' could not be found (are you missing a using directive or an assembly reference?)
Assets\Microsoft.MixedReality.WebRTC.Unity\Scripts\Signaling\Signaler.cs(39,47): error CS0246: The type or namespace name 'SignalerMessage' could not be found (are you missing a using directive or an assembly reference?)
Assets\Microsoft.MixedReality.WebRTC.Unity\Scripts\Signaling\NodeDssSignaler.cs(71,47): error CS0246: The type or namespace name 'SignalerMessage' could not be found (are you missing a using directive or an assembly reference?)
Assets\Microsoft.MixedReality.WebRTC.Unity\Scripts\Signaling\Signaler.cs(48,26): error CS0234: The type or namespace name 'PeerConnection' does not exist in the namespace 'Microsoft.MixedReality.WebRTC' (are you missing an assembly reference?)
Assets\Microsoft.MixedReality.WebRTC.Unity\Scripts\Signaling\NodeDssSignaler.cs(160,42): error CS0246: The type or namespace name 'SignalerMessage' could not be found (are you missing a using directive or an assembly reference?)
Assets\Microsoft.MixedReality.WebRTC.Unity\Scripts\PeerConnection.cs(208,24): error CS0234: The type or namespace name 'PeerConnection' does not exist in the namespace 'Microsoft.MixedReality.WebRTC' (are you missing an assembly reference?)
Assets\Microsoft.MixedReality.WebRTC.Unity\Scripts\Signaling\NodeDssSignaler.cs(179,49): error CS0246: The type or namespace name 'SignalerMessage' could not be found (are you missing a using directive or an assembly reference?)

Any ideas what I could be missing?  Demo runs fine in editor.

**Comment by djee-ms** [comment]
Hi @astaikos316

Can you please double-check that you did not start Unity before compiling the libraries?

The repository contains in the `Plugins` directory of the Unity project some `.meta` files for the compiled `.dll`, but not the `.dll` themselves which need to be compiled (see [here](https://github.com/microsoft/MixedReality-WebRTC/tree/master/libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Plugins/WSA/x86) for example for HoloLens 1). If you open Unity first, without the compiled DLLs, Unity unfortunately deletes those `.meta` files thinking they are useless. But they contain important information about which DLL to deploy on which platform. You can refer to the [Importing MixedReality-WebRTC](https://microsoft.github.io/MixedReality-WebRTC/manual/helloworld-unity-importwebrtc.html) section of the Unity tutorial for more details.

Seeing the error messages, I am assuming Unity deleted those files, then re-created some default ones after the DLL were compiled, but those defaults are not configured correctly for UWP. If you `git status` in the repo you should see if there are some changes.

**Comment by astaikos316** [comment]
I decided to start fresh as I couldn't get things to work right.  Now in Visual Studio 2019 when trying to build the solution, i get this build error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Loading assembly "C:\Users\nacre\.nuget\packages\runtime.win10-x86-aot.microsoft.netcore.universalwindowsplatform\6.2.8\runtimes\win10-x86-aot\lib\uap10.0.15138\System.Reflection.TypeExtensions.dll" failed. System.IO.FileNotFoundException: Could not load file or assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at System.Reflection.RuntimeAssembly.GetCustomAttributes(Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttribute(Assembly element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](Assembly element)
   at Microsoft.Build.Tasks.ProcessResourceFiles.ReadAssemblyResources(String name, String outFileOrDir)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].	Microsoft.MixedReality.WebRTC.TestAppUWP

**Comment by djee-ms** [comment]
"win10-x86-aot" -- I think there's a bug around AOT, I remember seeing something similar. Try to disable "Compile with .NET Native toolchain" in the *Build* tab of the C# project which is failing to compile. Or try in Debug, it should be off by default.

**Comment by djee-ms** [comment]
@astaikos316 did you manage to get things building in the end?

**Comment by NirabhraDas013** [comment]
hi I am trying to build from scratch. I copied the plugins folder as instructed. Then, copied the individual mrwebrtc.dll in proper position. Before opening Unity. I also double checked before opening unity if any of the meta files are missing or misplaced. They were not. And still I am getting the same set of errors _CS0246: Type or NameSpace could not be found_. 

Interestingly, The import settings of the dll files are in place properly once I started up Unity. Is it because the meta files were present or is that an indicator that something has gone wrong.

Please help. I am very new to this WebRTC and UWP projects.

**Comment by robibkuiper** [comment]
Having the same issues as NirabhraDas013. did everything like the steps in the documentation as far as i know, the import settings also seem to be fine. Also tried rebuilding everything myself but for some reason my Visual Studio says the 2017 build tools are not installed while they are...

**Comment by djee-ms** [comment]
Yes the `.meta` files shouldn't change, you should use the ones from the git repository, not the ones Unity generates. Also there is no instruction (or it's a mistake I need to fix) telling you to copy some DLL when you build from sources, so I am not sure what you are doing, see [this docs](https://microsoft.github.io/MixedReality-WebRTC/manual/building.html#building-the-libraries):

> On successful build, the binaries will be generated in a sub-directory under bin/, and the relevant DLLs **will be copied by a post-build script** to libs\Microsoft.MixedReality.WebRTC.Unity\Assets\Plugins\ for the Unity integration to consume them.

The copy happens automatically on successful build when using the Visual Studio solution, at least if you are trying to use the sample Unity project; if you have your own Unity project then yes you need to copy manually, obviously, but I wouldn't recommend that as a first try because that will require more setup and be more difficult than using the already configured sample project we provide.

Also for both of you @NirabhraDas013 and @robibkuiper can you please next time open a new issue instead of commenting on closed ones, and [use the issue template](https://github.com/microsoft/MixedReality-WebRTC/issues/new?template=bug_report.md) which asks for information we need to help you, like which version of Unity you're using _etc._, because here I can't provide much more than wild guesses based on the few information I have.
