### ISSUE TITLE
Webcam Source doesn't stream my webcam in Hololens 2

### ISSUE THREAD

**Issue by amfdeluca** [microsoft/MixedReality-WebRTC#401]
**Describe the bug**
Using the Webcam Source component, the panel on which the Hololens 2 stream should be rendered, remains blocked at the first frame received or sometimes totally black. The problem does not exist if I use a Desktop instance, in that case the Webcam source caputure works perfectly.

**To Reproduce**
1. Create a total setup to manage a WebRTC connection
2. Add the Webcam Source component to a component with Quad and the YUVFeedMaterial

**Expected behavior**
Webcam stream on my panel in Hololens 2.

**Screenshots**
![Screenshot (5)](https://user-images.githubusercontent.com/56428422/83890327-ec799c00-a74b-11ea-86df-f14af8deb4c8.png)

**Environment**
 - Platform: UWP
 - Architecture: ARM
 - Unity version: 2019.2.21f1
 - Target device: Hololens 2

**Additional context**
In Desktop everything works fine, the webcam is captured and sent via WebRTC and received correctly

**Comment by djee-ms** [comment]
Hi @amfdeluca,

What commit are you on?

> the panel on which the Hololens 2 stream should be rendered

I assume you mean the `VideoPlayer` prefab that we ship as part of our sample scene? Do you see the statistics texts changing or do they stay the same? If they change this indicates the player starts but doesn't receive frames. If they don't it means the player doesn't start. Different issues.

**Comment by amfdeluca** [comment]
Hello, to be clearer the webrtc transmission takes place via a virtual video camera, I made a control on the panel locally (which I did not see before, and actually the webcam can be seen correctly precisely until I try to make a connection by creating an offer).

On the other hand, looking on the receiver's side I actually see the statistics updating without problems, but precisely I see the same immobile frame of the webcam. (yes, i am using your VideoPlayer)

Commit:

Branch: master
Commit: 2a8215ff6b8296da424fa1736b371f33f504d304 [2a8215f]
Date: 02 June 2020 16:44:10

**Comment by djee-ms** [comment]
Are you saying that the local video is also frozen? If so it sounds like an issue with the virtual video camera rather than WebRTC, no?

**Comment by amfdeluca** [comment]
In addition to the rendering of the webcam, the virtual cam is also framing a text, with a timer, 
which is ok and is aligned between local and remote. (just to check that the problem was not the virtual cam)

**Comment by amfdeluca** [comment]
Hi, at the end of everything I solved the problem using the methods of StartRecording and StopRecording present in the Webcam Source script. I realized that by using them properly, before and after the creation of the offer, you can prevent the freeze of the webcam shot in hololens. I think it is obviously a problem of stability of the webcam hardware, as precisely in the desktop instance all this does not happen.

**Comment by astaikos316** [comment]
I am seeing the same issue I believe with my UWP build for Hololens 2.  Not quite sure how you managed to correct the problem? Is there any chance you can show an example? I trued doing what you said but could not get it to work.
