### ISSUE TITLE
Can't compile solution by VS 2017

### ISSUE THREAD

**Issue by WuHaoDataMesh** [microsoft/MixedReality-WebRTC#41]
I try to compile solution by VS2017, but meet some issue. Many include file can not be found in pch.h. 
![image](https://user-images.githubusercontent.com/26474563/63589339-713f6300-c5db-11e9-9197-22e8654f19ba.png)

I have install all the packages in NuGet (17 packages like Microsoft.MixedReality.WebRTC.Native.****) , and it can not work. 

Do I miss something ? please help me, thanks~~

**Comment by djee-ms** [comment]
Those includes are from the `webrtc-uwp-sdk` submodule. It looks like they are not found on your machine, can you see them on disk in `external\webrtc-uwp-sdk\webrtc\xplatform\webrtc`? Did you clone with the `--recursive` option? You can also do a `git submodule update --init --force --recursive` from the root of the repository.

**Comment by WuHaoDataMesh** [comment]
When I chone all these dependences, it works! Thanks a lot~~
Download these assets is too slow in China! I spend almost whole day to do it... hahaha

**Comment by djee-ms** [comment]
Ok good, I am closing this issue then, thanks for confirming.

Note that you can compile the core dependencies from sources, but between the setup of all dependencies and the actual compiling I am not sure this is any faster. There are instructions [here](https://github.com/microsoft/MixedReality-WebRTC/blob/master/docs/manual/building-core.md).

**Comment by Boo0317** [comment]
hi,can you send me a copy of web-rtc-uwp-sdk , I spent one day trying to clone it  but failed.@WuHaoDataMesh
