### ISSUE TITLE
Way to shrink resulting mrwebrtc.aar?

### ISSUE THREAD

**Issue by rygo6** [microsoft/MixedReality-WebRTC#422]
I noticed my mrwebrtc.aar ends up being about 10mb. Since an aar is already zipped that 10mb does get passed straight into the apk. Which is not huge, but a lot apps can be below 100mb, mine included, and this 10mb can add quite a bit of size to the apk in relation to that.

I am wondering, is there any additional settings that could be put into the libwebrtc compile, or the mrwebrtc compile, whether gradle or cmake files, to potentially shrink the resulting .aar down even more?

**Comment by djee-ms** [comment]
Not that I know of. `libwebrtc` is something like 10 millions lines of code if I recall correctly, handling audio and video encoding/decoding with multiple codecs, networking, encryption and secure handshakes, and more. This is a _lot_ of things to do. If someone finds some optimization I am happy to add them, but we're already using all the common ones we know of, and Google is aware of this so I doubt we will find anything they did not already think about, having a dedicated team larger than us, and doing the same kind of optimization for Chromium (which `libwebrtc` is integrated in). Closing as Won't Fix as we don't have time to do an exploratory investigation without any lead or expectation to find something, and the size is around what is expected from experience on other platforms and from reading around on mailing lists _etc._ about experiences from other implementations.
