### ISSUE TITLE
Missing .gradle file?

### ISSUE THREAD

**Issue by HyperLethalVector** [microsoft/MixedReality-WebRTC#451]
Hi there!

Today I went to re-build the android libraries. but am greeted with the following, why would this be? 
I couldn't find said .gradle file among the master branch?
`Settings file '/home/damien/MixedReality-WebRTC/tools/build/android/settings.gradle' line: 1
A problem occurred evaluating settings 'android'.
Could not read script '/home/damien/MixedReality-WebRTC/tools/build/android/mrwebrtc.gradle' as it does not exist.`

**Comment by djee-ms** [comment]
You need to run `build.sh` again to [generate that file](https://github.com/microsoft/MixedReality-WebRTC/blob/dd4c734f57a375271ac7548be7558ef525e7f82d/tools/build/libwebrtc/build.sh#L106-L115). This was introduced recently and allows the Android Studio project to locate the `libwebrtc` repository to link the `libwebrtc.jar` archive during the build of `mrwebrtc.aar`.

**Comment by djee-ms** [comment]
I'm going to close this as I assume this was the answer you needed. Please feel free to reopen if there's still a problem.
