### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by unicomp21** [microsoft/MixedReality-WebRTC#456]
**Describe the problem**
We should have support for linux, the pieces here could also be used for SFU construction.  Initially, don't worry about rendering, just support rtcpeerconnection for sfu concerns when using linux.

**Describe the solution you'd like**
Support linux.

**Comment by djee-ms** [comment]
Not sure who "we" is but I'm not worrying. We have no plan to support Linux. Thanks.
