### ISSUE TITLE
Crash on Hololens 2 Unity project when Microphone dialog permission is shown

### ISSUE THREAD

**Issue by boozee** [microsoft/MixedReality-WebRTC#466]
It looks like no new project using the MRWebRTC plugin, nor the given Unity samples, actually works on Hololens 2.
The package (master branch latest commit) has been built from source and included into Unity (2019.4.1-4 doesn't behave differently).

Building the tutorial project results into a crash as soon as the Microphone permission dialog shows (like, a second later).
Same happens with the VideoChatDemo.

Crash dumps doesn't seem to give any advice, it just says "The thread tried to read from or write to a virtual address for which it does not have the appropriate access."

I've seen some issues around (#124 ) which look similar but not the same as mine. Moreover, it looks like the PeerConnection is responsible for the crash (even with no audio/video track set) since turning off its GO doesn't trigger the permission request nor the crash.

**Comment by djee-ms** [comment]
Hi @boozee, can you please try again with the latest `master` branch as of today? We've been doing manual testing for the past few days ahead of the 2.0.0 release and have no issue like that. But there has been a lot of activity and small fixes going in over the past week, so just to make sure it's not already fixed, because I think I had something similar recently, though cannot recall the details. Thanks!

**Comment by boozee** [comment]
Thanks @djee-ms, after all it looks like it's a general HL2 issue still active in the 2019 LTS version

https://issuetracker.unity3d.com/issues/enabling-graphics-jobs-in-2019-dot-3-x-results-in-a-crash-or-nothing-rendering-on-hololens-2

Toggling the flag makes the VideoChat sample work as intended.
For reference, with the latest commits the crash happens a bit later (like a few seconds).

**Comment by djee-ms** [comment]
A yes the Graphics Jobs bug I've hit it, I didn't realize this could be it since the bug seemed related to the microphone permission. Closing this then, there's not much we can do about it.
