### ISSUE TITLE
Unity VideoChatDemo not working in Android, (NullReferenceException: Object reference not set to an instance of an object)

### ISSUE THREAD

**Issue by mab09** [microsoft/MixedReality-WebRTC#471]
Hey!
First of all, thank you, this project is really helpful for what I am working on.

Everything works fine in Unity 2019.4.1f1 when I am on the "PC, Mac and Linux Standalone" platform (with the mrwebrtc plugins from the nuget package) but when I switch to android I get the following error (**Note: I did successfully build mrwebrtc.aar for android support**.):

`NullReferenceException: Object reference not set to an instance of an object
NodeDssSignalerUI.<Start>b__5_0 () (at Assets/Microsoft.MixedReality.WebRTC.Unity.Examples/NodeDssSignalerUI.cs:57)
UnityEngine.Events.InvokableCall.Invoke () (at <3dc54541a2574ac7826a004a212a4332>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <3dc54541a2574ac7826a004a212a4332>:0)
UnityEngine.UI.Button.Press () (at C:/Program Files/Unity/Hub/Editor/2019.4.1f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/Button.cs:68)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at C:/Program Files/Unity/Hub/Editor/2019.4.1f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/Button.cs:110)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/Program Files/Unity/Hub/Editor/2019.4.1f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/ExecuteEvents.cs:50)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction 1[T1] functor) (at C:/Program Files/Unity/Hub/Editor/2019.4.1f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/ExecuteEvents.cs:261)
UnityEngine.EventSystems.EventSystem:Update() (at C:/Program Files/Unity/Hub/Editor/2019.4.1f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/EventSystem.cs:377)
`

Similar errors also pop up whenever any of my scripts try to access a `WebRTC.PeerConnection` object from `Signaler.cs` like `_nativepeer` . In the above error it was trying to run `NodeDssSignaler.PeerConnection.Peer.CreateOffer();`

The only thing outside of recommended setup that I did was to build the mrwebrtc.aar with NDK 18.1.5063045, but that was because it was the closest to the NDK used by my Unity editor (NDK 19.0.5232133) and also because NDK 16.1.4479499 was giving multiple build errors.

Thanks,

**Comment by djee-ms** [comment]
Hi,

`Assets/Microsoft.MixedReality.WebRTC.Unity.Examples/NodeDssSignalerUI.cs` -- this path doesn't exist anymore, it seems you have an outdated version of the master branch, and so I have no idea which code you are using. Also the error is probably that some property in NodeDssSignalerUI is not set; you should have a look in the inspector and see if anything looks wrong there.

**Comment by mab09** [comment]
Yes, you are right.
Some of my code was from the nuget packages and not master.
Thanks.
