### ISSUE TITLE
Error in two methods in TestNetCoreConsole ---> C# Tutorial (Desktop)

### ISSUE THREAD

**Issue by EgorPavlovich** [microsoft/MixedReality-WebRTC#493]
**Describe the bug**
"LocalAudioTrack" and "LocalVideoTrack" does not contain a definition for "CreateFromDeviceAsync".

**To Reproduce**
1. Run the code:
`// Record video from local webcam, and send to remote peer
                if (needVideo)
                {
                    Console.WriteLine("Opening local webcam...");             
                    localVideoTrack = await LocalVideoTrack.CreateFromDeviceAsync();
                    videoTransceiver = pc.AddTransceiver(MediaKind.Video);
                    videoTransceiver.DesiredDirection = Transceiver.Direction.SendReceive;
                    videoTransceiver.LocalVideoTrack = localVideoTrack;
                }

                // Record audio from local microphone, and send to remote peer
                if (needAudio)
                {
                    Console.WriteLine("Opening local microphone...");
                    LocalAudioTrack.
                    localAudioTrack = await LocalAudioTrack.CreateFromDeviceAsync();
                    audioTransceiver = pc.AddTransceiver(MediaKind.Audio);
                    audioTransceiver.DesiredDirection = Transceiver.Direction.SendReceive;
                    audioTransceiver.LocalAudioTrack = localAudioTrack;
                }`
2. See errors:
Error CS0117 "LocalAudioTrack" does not contain a definition for "CreateFromDeviceAsync".
Error CS0117 "LocalVideoTrack" does not contain the definition for "CreateFromDeviceAsync".

**Expected behavior**
I wanted to run and debug the code.

**Screenshots**
![image](https://user-images.githubusercontent.com/44481585/89029227-a2212f80-d336-11ea-9b0b-8159fd679fcb.png)
![image](https://user-images.githubusercontent.com/44481585/89029271-b533ff80-d336-11ea-92c9-4c104f59a609.png)
![image](https://user-images.githubusercontent.com/44481585/89029317-d268ce00-d336-11ea-9f8f-a3a99ca7822f.png)
There's not even that method!

**Environment**
 - Platform: [e.g. Windows Desktop]
 - Architecture: [e.g. Debug Any CPU]

**Additional context**
![image](https://user-images.githubusercontent.com/44481585/89029521-515e0680-d337-11ea-9001-a09a23f9f5c5.png)
I have the latest version of the package installed: 2.0.0-preview.1.
If you install any version before that, VERY many methods will not be visible!!!

**Comment by djee-ms** [comment]
Neither the [C# Desktop tutorial](https://microsoft.github.io/MixedReality-WebRTC/manual/cs/helloworld-cs-mediatracks-core3.html) nor the TestNetCoreConsole are using the code you pasted. Where is that from?

This is the old 1.0 API you are trying to use; see the [Migration Guide](https://microsoft.github.io/MixedReality-WebRTC/manual/migration-guide.html) for details.

![image](https://user-images.githubusercontent.com/49064175/89038127-aa2d9f00-d337-11ea-9021-4d3a0bd8a969.png)

https://github.com/microsoft/MixedReality-WebRTC/blob/0b26ccdcd4abaee38e57c0c46c144d05d0793f06/examples/TestNetCoreConsole/Program.cs#L52-L57

**Comment by EgorPavlovich** [comment]
> Ни в [учебнике](https://microsoft.github.io/MixedReality-WebRTC/manual/cs/helloworld-cs-mediatracks-core3.html) по [C # Desktop,](https://microsoft.github.io/MixedReality-WebRTC/manual/cs/helloworld-cs-mediatracks-core3.html) ни в TestNetCoreConsole не используется вставленный вами код. Откуда это?
> 
> Это старый 1.0 API, который вы пытаетесь использовать; подробности смотрите в [Руководстве](https://microsoft.github.io/MixedReality-WebRTC/manual/migration-guide.html) по [миграции](https://microsoft.github.io/MixedReality-WebRTC/manual/migration-guide.html) .
> 
> ![образ](https://user-images.githubusercontent.com/49064175/89038127-aa2d9f00-d337-11ea-9021-4d3a0bd8a969.png)
> 
> https://github.com/microsoft/MixedReality-WebRTC/blob/0b26ccdcd4abaee38e57c0c46c144d05d0793f06/examples/TestNetCoreConsole/Program.cs#L52-L57
I think I figured it out. Thank you for your help :)
![image](https://user-images.githubusercontent.com/44481585/89106580-bc8d0300-d433-11ea-81b7-2229ad99138b.png)
https://microsoft.github.io/MixedReality-WebRTC/manual/cs/helloworld-cs-signaling-core3.html
