### ISSUE TITLE
Builds fail to ARM64

### ISSUE THREAD

**Issue by adrianimajion** [microsoft/MixedReality-WebRTC#50]
When building to ARM64, VS throws the error

LNK1104	cannot open file 'webrtc.lib'	Microsoft.MixedReality.WebRTC.Native.UWP	D:\MixedReality-WebRTC\libs\Microsoft.MixedReality.WebRTC.Native\src\uwp\

The other build targets work fine.

**Comment by adrianimajion** [comment]
I also encounter this error building ARM targeted to Release

**Comment by djee-ms** [comment]
On ARM64 if you're on `master` this is normal, this is not supported. I should have removed that config from the solution to avoid any confusion. It will be available once the upgrade to m75 is merged. But ARM64 is not supported by the UWP wrappers on m71, which is the current milestone `master` is based on.

On ARM Release that should work though, I have no issue myself locally, I use that config often. Can you please check that the NuGet packages have been correctly restored for the solution? You need [Microsoft.MixedReality.WebRTC.Native.Core.UWP.ARM.Release](https://www.nuget.org/packages/Microsoft.MixedReality.WebRTC.Native.Core.UWP.ARM.Release) and [Microsoft.MixedReality.WebRTC.Native.Core.WinRT.ARM.Release](https://www.nuget.org/packages/Microsoft.MixedReality.WebRTC.Native.Core.WinRT.ARM.Release) for the ARM Release config.

**Comment by djee-ms** [comment]
I removed ARM64 from the solution to prevent any confusion.

**Comment by djee-ms** [comment]
@adrianimajion any update on that issue? Did you manage to get things working?

**Comment by djee-ms** [comment]
Closing as no repro on ARM, and removed ARM64 to prevent confusion. Please feel free to reopen if that is still an issue.

**Comment by michalek-marcin** [comment]
@djee-ms When you plan merge m75 (ARM64 support) to master? Last commit on m75 was 5 months ago.

**Comment by michalek-marcin** [comment]
@djee-ms ?

**Comment by djee-ms** [comment]
Ah sorry @michalek-marcin I saw your message and forgot to reply. We have some signal of partners/users wanting ARM64, and we are considering priorities now and whether we will move to m75 or directly to Google's master branch, so this is in standby until then.

In more details, [the m75 branch from WebRTC UWP](https://github.com/webrtc-uwp/webrtc-uwp-sdk/tree/releases/m75) is not very well tested, so although the original plan when creating [the m75 branch on this repo](https://github.com/microsoft/MixedReality-WebRTC/tree/feature/m75) was to move to it, things might change and we might abandon that m75 branch to provide ARM64 in another way (directly via Google's master branch). The m75 is also getting a bit old. In addition, some other features had stronger signal until now so ARM64 was not planned, but we are discussing whether that might change as we got stronger feedback to support it. This is mostly a question of resourcing at this point.

I'll post about our plan forward for ARM64 as soon as I have more information about it. In the meantime the ARM(32) build is still working on HoloLens 1/2. Do you have a particular use for ARM64?

**Comment by michalek-marcin** [comment]
Hi, I have other plugins in project which supports UWP ARM64 only. I asked authors of that plugins to add UWP ARM support, so I have project with some features disabled because of compilation problems.
I hope that ARM64 will appear on your road map soon ;)

Sorry for late answer, I was on a holiday.
