### ISSUE TITLE
Help with android support

### ISSUE THREAD

**Issue by sananbintahir** [microsoft/MixedReality-WebRTC#508]
I am fairly new to these libraries, and I'm having a difficult time understanding how android support works. Since the recent 2.0.0 preview release, the android binaries already included within the UPM package. Doesn't this mean I do not have to go through compiling the base library on Linux to produce the 'mrwebrtc.aar'? 

When I try to switch the platform to android on Unity to run the demo scenes, I am getting errors with 

    Exception: Field currentActivity or type signature  not found
    UnityEngine._AndroidJNIHelper.GetFieldID (System.IntPtr jclass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <38f5bf63e91b4a34816606844fee3a05>:0)
    UnityEngine.AndroidJNIHelper.GetFieldID (System.IntPtr javaClass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <38f5bf63e91b4a34816606844fee3a05>:0)
    UnityEngine._AndroidJNIHelper.GetFieldID[ReturnType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <38f5bf63e91b4a34816606844fee3a05>:0)
    UnityEngine.AndroidJNIHelper.GetFieldID[FieldType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <38f5bf63e91b4a34816606844fee3a05>:0)
    UnityEngine.AndroidJavaObject._GetStatic[FieldType] (System.String fieldName) (at <38f5bf63e91b4a34816606844fee3a05>:0)
    UnityEngine.AndroidJavaObject.GetStatic[FieldType] (System.String fieldName) (at <38f5bf63e91b4a34816606844fee3a05>:0)
    Microsoft.MixedReality.WebRTC.Unity.Android.Initialize () (at Library/PackageCache/com.microsoft.mixedreality.webrtc@2.0.0-preview.1/Runtime/Scripts/Android.cs:37)
    Microsoft.MixedReality.WebRTC.Unity.PeerConnection.InitializeAsync (System.Threading.CancellationToken token) (at Library/PackageCache/com.microsoft.mixedreality.webrtc@2.0.0-preview.1/Runtime/Scripts/PeerConnection.cs:286)
    Microsoft.MixedReality.WebRTC.Unity.PeerConnection.OnEnable () (at Library/PackageCache/com.microsoft.mixedreality.webrtc@2.0.0-preview.1/Runtime/Scripts/PeerConnection.cs:631)`

What am I missing? My target is to create a cross-platform VR communication solution. I can get things working on UWP and understand most of the API, but I can't understand how android works.

**Comment by djee-ms** [comment]
> Doesn't this mean I do not have to go through compiling the base library on Linux to produce the 'mrwebrtc.aar'?

Yes, you do not have to build anything, everything is included in the UPM package.

> When I try to switch the platform to android on Unity to run the demo scenes, I am getting errors...

The Play mode in the Unity Editor is not supported for Android, only the actual deploy. You have to generate an actual Android Studio project with the Build window, and deploy that to an Android device (or emulator possibly works, but camera won't, so you generally want a device). Best is to do your development inside the Unity editor with the PC/Standalone config, and switch to Android when you want to test on device.

**Comment by sananbintahir** [comment]
I see. I've been trying to figure out what was wrong since morning. Thank you! I'll close the issue
