### ISSUE TITLE
PeerConnection component for multiple peer connections?

### ISSUE THREAD

**Issue by sananbintahir** [microsoft/MixedReality-WebRTC#510]
I want to add multiple devices in a session for exchanging video, audio, and data. For now, I don't want to use a media server, and just use WebRTC's peer to peer connections to communicate. Is it possible to use the PeerConnection unity component to implement multiple peer connections (creating a new peer connection for each pair of devices)? If so, would that mean having to initialize a new PeerConnection for each new device that is added to a session?

To my understanding, what I need to do is create a custom Signaler component for a signaling solution that will meet my needs, and then use the PeerConnection component for sending and handling the messages. Is that correct, or will I have to play around with the PeerConnection script too?

**Comment by sananbintahir** [comment]
Also, is there something like a discord chat for this library? Opening issues for small questions (that might potentially save someone like me hours) seems a bit overkill.

**Comment by djee-ms** [comment]
> Is it possible to use the PeerConnection unity component to implement multiple peer connections (creating a new peer connection for each pair of devices)?

Yes, starting from 2.0.0.

> If so, would that mean having to initialize a new PeerConnection for each new device that is added to a session?

Without a media server, yes, one PeerConnection per pair of devices exchanging audio/video/data.

> Is that correct, or will I have to play around with the PeerConnection script too?

Sounds correct, you shouldn't have to touch the PeerConnection script.

> Also, is there something like a discord chat for this library? Opening issues for small questions (that might potentially save someone like me hours) seems a bit overkill.

There's a [Slack channel](https://holodevelopers.slack.com/messages/CN1A7JB3R). But opening an issue on GitHub leaves a written trace that others can search for, and we dev team can go back to when looking at bugs / new features / use cases, so is very much worth it.

**Comment by sananbintahir** [comment]
Sounds good, thank you for the fast response!
