### ISSUE TITLE
Android building broken, missing gradle files.

### ISSUE THREAD

**Issue by rygo6** [microsoft/MixedReality-WebRTC#514]
Hello again, trying to get through the build of Android off the latest master. 

Running gradlew assembleRelease gives me this error:
```
FAILURE: Build failed with an exception.

* Where:
Settings file 'C:\mrwebrtc\tools\build\android\settings.gradle' line: 1

* What went wrong:
A problem occurred evaluating settings 'android'.
> Could not read script 'C:\mrwebrtc\tools\build\android\mrwebrtc.gradle' as it does not exist.
```

Which is because this line:
`apply from: 'mrwebrtc.gradle'`
from `tools/build/android/settings.gradle` 
Is trying to load this file:
`tools/build/android/mrwebrtc.gradle`

But that file is currently in the .gitignore, I assume that was a mistake? Or is there a new additional step that needs to be taken to generate mrwebrtc.gradle?

**Comment by rygo6** [comment]
Or never mind. Discovered you made it so you have to do a rebuild of the whole libwebrtc library to get it to output that file. I've been reusing the same libwebrtc build folder and resulting cmake file from months now. Going through multi-hour rebuild of libwebrtc now

**Comment by djee-ms** [comment]
Sorry @rygo6 yes before I added that file the Android project was actually building using the Google package pulled from some upstream registry, instead of the locally built one. Aside from being a different version, potentially incompatible, that Google package is more importantly now deprecated and unmaintained, so we need to build from source. I added the file to let Gradle know where the local build of `libwebrtc` is, so it can pull some Java files from it we need. The file `mrwebrtc.gradle` is generated by the build script during `build.sh`. I thought it would be generated if you just built incrementally, is it not?

https://github.com/microsoft/MixedReality-WebRTC/blob/e23f475c8cd452b6ef8e350f0c8b185adb67ccb3/tools/build/libwebrtc/build.sh#L106-L115

**Comment by rygo6** [comment]
I ran the checkout script again thinking maybe it would do some incremental update needed for the latest in master. Which I probably shouldn't of done, as it pulled some new things started giving errors on build. So decided to just start fresh. Still waiting on it

**Comment by djee-ms** [comment]
Yes Google doesn't support checkout resume nor multiple runs; their `fetch` script (which we call from `checkout.sh`) needs to run exactly once successfully to checkout their repository, and their official "resume" method is to delete everything and restart from scratch. I was talking about the `build.sh` script, which this one does support incremental build and can will be a no-op if everything is already built. If everything works as intended, this is the one that should generate the `mrwebrtc.gradle` file. It is possible I made a mistake though, or I am reading those scripts wrong.

**Comment by rygo6** [comment]
Trying to run the checkout again through Ubuntu 18.04 with WSL2 I am getting this error now:

```
It produces the following output:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'git' instead of 'git-core'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libglvnd-dev : Depends: libegl1 (= 1.0.0-2ubuntu2.3) but it is not going to be installed
 libwayland-egl1-mesa : Depends: libegl1 but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

You will have to install the above packages yourself.

./checkout.sh exited with code 100. Run with -v to get more info.
```

Have you encountered that yourself?

**Comment by rygo6** [comment]
Which I did `apt-get install libegl1` and it said it was already installed.

**Comment by djee-ms** [comment]
Not this one, but this is the typical Ubuntu shenanigans with broken package dependencies. There's another one with SSL packages we are working around in the Android YAML pipeline:

https://github.com/microsoft/MixedReality-WebRTC/blob/9d1b34cd2047c876fc5af250417114f450865b6b/tools/ci/templates/jobs-libwebrtc-android.yaml#L27-L64

I cannot remember the details but this was annoying to figure out. From what I remember you need to list the dependencies for those packages and try to figure out why `apt` doesn't want to install them. I think often this is a matter of "package X breaks package Y at version N, but if you downgrade to (N-1) that works, however `apt` doesn't downgrade by default so you need to force it".

**Comment by rygo6** [comment]
Thank you, that helped. Ended up getting past it. The solution for errors like this:
`libglvnd-dev : Depends: libegl1 (= 1.0.0-2ubuntu2.3) but it is not going to be installed`
Is to `apt-get remove` all the packages it depends on, this case `libegl1`. Then do `apt-get autoremove` to clean anything residual up. Then run checkout again.

**Comment by rygo6** [comment]
Also should note I needed to edit the path in my resulting `mrwebrtc.gradle` file from:
`gradle.ext.webrtcBinDir = '/mnt/c/build_webrtc/webrtc/src/out/android/arm64'`
to
`gradle.ext.webrtcBinDir = 'C:/build_webrtc/webrtc/src/out/android/arm64'`

**Comment by rygo6** [comment]
So reopening this as still encountering some issues. 

All of the above fixed building of release/2.0 branch for me. However merge in the latest master just now and trying to run this same set of steps again I get this error.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':webrtc-native:externalNativeBuildRelease'.
> Build command failed.
  Error while executing process C:\Users\Ryan\AppData\Local\Android\Sdk\cmake\3.10.2.4988404\bin\cmake.exe with arguments {--build C:\mrwebrtc\tools\build\android\webrtc-native\.externalNativeBuild\cmake\release\arm64-v8a --target mrwebrtc}
  [1/11] Building CXX object CMakeFiles/mrwebrtc.dir/jni_onload.cpp.o
  [2/11] Building CXX object CMakeFiles/mrwebrtc.dir/C_/mrwebrtc/libs/mrwebrtc/src/pch.cpp.o
  [3/11] Building CXX object CMakeFiles/mrwebrtc.dir/C_/mrwebrtc/libs/mrwebrtc/src/mrs_errors.cpp.o
  [4/11] Building CXX object CMakeFiles/mrwebrtc.dir/C_/mrwebrtc/libs/mrwebrtc/src/utils.cpp.o
  [5/11] Building CXX object CMakeFiles/mrwebrtc.dir/C_/mrwebrtc/libs/mrwebrtc/src/video_frame_observer.cpp.o
  [6/11] Building CXX object CMakeFiles/mrwebrtc.dir/C_/mrwebrtc/libs/mrwebrtc/src/tracked_object.cpp.o
  [7/11] Building CXX object CMakeFiles/mrwebrtc.dir/C_/mrwebrtc/libs/mrwebrtc/src/interop/global_factory.cpp.o
  FAILED: CMakeFiles/mrwebrtc.dir/C_/mrwebrtc/libs/mrwebrtc/src/interop/global_factory.cpp.o
  C:\Users\Ryan\AppData\Local\Android\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android24 --gcc-toolchain=C:/Users/Ryan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/Ryan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot  -Dmrwebrtc_EXPORTS -IC:/mrwebrtc/tools/build/android/webrtc-native/src/main/cpp/../../../../../../../libs/mrwebrtc/include -IC:/mrwebrtc/tools/build/android/webrtc-native/src/main/cpp/../../../../../../../libs/mrwebrtc/src -IC:/build_webrtc/webrtc/src -IC:/build_webrtc/webrtc/src/third_party/abseil-cpp -IC:/build_webrtc/webrtc/src/third_party/libyuv/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -std=c++14 -DANDROID_STL=c++_shared -DMRS_USE_STR_WRAPPER -DMR_SHARING_ANDROID -DWEBRTC_POSIX -DWEBRTC_ANDROID -O2 -DNDEBUG  -fPIC -MD -MT CMakeFiles/mrwebrtc.dir/C_/mrwebrtc/libs/mrwebrtc/src/interop/global_factory.cpp.o -MF CMakeFiles\mrwebrtc.dir\C_\mrwebrtc\libs\mrwebrtc\src\interop\global_factory.cpp.o.d -o CMakeFiles/mrwebrtc.dir/C_/mrwebrtc/libs/mrwebrtc/src/interop/global_factory.cpp.o -c C:/mrwebrtc/libs/mrwebrtc/src/interop/global_factory.cpp
  In file included from C:/mrwebrtc/libs/mrwebrtc/src/interop/global_factory.cpp:6:
  In file included from C:/mrwebrtc/tools/build/android/webrtc-native/src/main/cpp/../../../../../../../libs/mrwebrtc/src\pch.h:8:
  In file included from C:/Users/Ryan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\functional:504:
  C:/Users/Ryan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\memory:2334:19: error: invalid application of 'sizeof' to an incomplete type 'webrtc::ScopedCOMInitializer'
      static_assert(sizeof(_Tp) > 0,
                    ^~~~~~~~~~~
  C:/Users/Ryan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\memory:2593:7: note: in instantiation of member function 'std::__ndk1::default_delete<webrtc::ScopedCOMInitializer>::operator()' requested here
        __ptr_.second()(__tmp);
        ^
  C:/mrwebrtc/libs/mrwebrtc/src/interop/global_factory.cpp:374:27: note: in instantiation of member function 'std::__ndk1::unique_ptr<webrtc::ScopedCOMInitializer, std::__ndk1::default_delete<webrtc::ScopedCOMInitializer> >::reset' requested here
    worker_com_initializer_.reset();
                            ^
  C:/mrwebrtc/tools/build/android/webrtc-native/src/main/cpp/../../../../../../../libs/mrwebrtc/src\interop/global_factory.h:11:7: note: forward declaration of 'webrtc::ScopedCOMInitializer'
  class ScopedCOMInitializer;
        ^
  1 error generated.
  [8/11] Building CXX object CMakeFiles/mrwebrtc.dir/C_/mrwebrtc/libs/mrwebrtc/src/toggle_audio_mixer.cpp.o
  [9/11] Building CXX object CMakeFiles/mrwebrtc.dir/C_/mrwebrtc/libs/mrwebrtc/src/sdp_utils.cpp.o
  [10/11] Building CXX object CMakeFiles/mrwebrtc.dir/C_/mrwebrtc/libs/mrwebrtc/src/peer_connection.cpp.o
  ninja: build stopped: subcommand failed.
```

Looks like this could be related to #513, just for Android building instead?

**Comment by rygo6** [comment]
Enabling tests here:
https://github.com/microsoft/MixedReality-WebRTC/blob/9d1b34cd2047c876fc5af250417114f450865b6b/tools/build/libwebrtc/lib.sh#L284

Gives a new build error about needing roboelectric.

**Comment by rygo6** [comment]
Whatever this was is fixed in latest master.
