### ISSUE TITLE
Error when building from sources

### ISSUE THREAD

**Issue by eirikhollis** [microsoft/MixedReality-WebRTC#515]
**Describe the bug**
Pulling from master and building from sources with the new build scripts causes a couple of errors that stops my progress.
Firstly, the build scripts are not digitally signed, and will throw the following error.
```
.\build.ps1 : File C:\mr-webrtc\tools\build\build.ps1 cannot be loaded. The file C:\mr-webrtc\tools\build\build.ps1 is
not digitally signed. You cannot run this script on the current system. For more information about running scripts and
setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ .\build.ps1 -BuildConfig Release -BuildArch x86 -BuildPlatform UWP
+ ~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```
This is rather easily fixed by running the following command in powershell.
```
Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
```

However, trying to run any of the requested build scripts with commands such as 
```
.\build.ps1 -BuildConfig Release -BuildArch ARM -BuildPlatform UWP
or
.\build.ps1 -BuildConfig Release -BuildArch x64 -BuildPlatform Win32
```
results in the error
```
Build-UWPWrappers : Cannot find MSBuild.exe from Visual Studio 2019 install path
At C:\mr-webrtc\tools\build\build.ps1:201 char:5
+     Build-UWPWrappers -BuildConfig $BuildConfig -BuildArch $BuildArch
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Build-UWPWrappers
```

In Visual Studio, I can't progress, since the libraries are not installed correctly
```
C:\mr-webrtc\tools\build\mrwebrtc\uwp\mrwebrtc-uwp.vcxproj(246,5): error : The webrtc.lib file was not found for configuration 'Release' platform 'ARM'. This generally indicates that libwebrtc was not built locally.
```

**To Reproduce**
1. Pull latest master branch
2. Try to build with build.ps1 scripts as documented
3. Try to build in Visual Studio

**Expected behavior**
No errors

**Additional Context**
Using Windows Powershell

**Comment by djee-ms** [comment]
> This is rather easily fixed by running the following command in powershell.

This is standard Windows 10 security for all PowerShell scripts, I don't think this has anything to do with our script in particular. I get that message on each new machine as PowerShell script execution is disabled by default. As far as I know there's not much we can do, this should be part of the installation of any developer machine. If that happened suddenly, I guess some group policy may have been pushed on your side that disabled PS execution?

> Build-UWPWrappers : Cannot find MSBuild.exe from Visual Studio 2019 install path

Which version of Visual Studio do you have installed? In particular what's the exact VS 2019 version number? It has happened several times in the past that VS changed its installation folder for some tools; each time any build script trying to do automated discovery needs to be updated. The relevant code is as below, can you please check this path exists and contains MSBuild.exe?

https://github.com/microsoft/MixedReality-WebRTC/blob/7396c454a4f9b21f36846b15f12e74b9a44ad0c1/tools/build/build.ps1#L141-L151

**Comment by eirikhollis** [comment]
>  If that happened suddenly, I guess some group policy may have been pushed on your side that disabled PS execution?

I'm familiar with the case, thought I'd just mention it since I was already on my way to create an issue about the missing MSBuild.exe. I agree that most (if not all) developers should be able to solve this fairly quickly if they encounter it. 

> The relevant code is as below, can you please check this path exists and contains MSBuild.exe?

Found the problem! I only have Visual Studio **_Professional_** installed on my machine, so the path to MSBuild.exe is
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe`
So just adding a path to the professional version should fix the issue.

> Which version of Visual Studio do you have installed?

Probably not that relevant now, but I tried on 16.6.7 and 16.7.0

**Comment by djee-ms** [comment]
Ah, missed one variant 😉 will fix, thanks!

**Comment by eirikhollis** [comment]
I do still have issues building, even though I added the professional path to the build script. Trying to build to Win32, I run the below code for x64 and x86, and both return the same result.
```
PS C:\mr-webrtc\tools\build> ./build.ps1 -BuildConfig Release -BuildArch x64 -BuildPlatform Win32
Windows SDK 1803 10.0.17134 (April 2018)   : OK
Windows SDK 1809 10.0.17763 (October 2018) : OK
```

However, upon building in Visual Studio:
![image](https://user-images.githubusercontent.com/30655189/89635001-98ec1180-d8a6-11ea-900e-3f452f25d2f3.png)

I get these errors:
```
------ Rebuild All started: Project: Microsoft.MixedReality.WebRTC, Configuration: Release Any CPU ------
Microsoft.MixedReality.WebRTC -> C:\mr-webrtc\bin\netstandard2.0\Release\Microsoft.MixedReality.WebRTC.dll

------ Rebuild All started: Project: mrwebrtc-win32, Configuration: Release Win32 ------
C:\mr-webrtc\tools\build\mrwebrtc\win32\mrwebrtc-win32.vcxproj(225,5): error : The webrtc.lib file was not found for configuration 'Release' platform 'x86'. This generally indicates that libwebrtc was not built locally. Run "tools\build\build.ps1 -BuildConfig Release -BuildArch x86 -BuildPlatform Win32" to build it. See https://microsoft.github.io/MixedReality-WebRTC/manual/building-windows.html for more details. Missing file: C:\mr-webrtc\tools\build\mrwebrtc\..\..\..\external\webrtc-uwp-sdk\webrtc\xplatform\webrtc\out\webrtc_win_x86_release\obj\webrtc.lib
Done building project "mrwebrtc-win32.vcxproj" -- FAILED.

------ Rebuild All started: Project: mrwebrtc-win32, Configuration: Release x64 ------
C:\mr-webrtc\tools\build\mrwebrtc\win32\mrwebrtc-win32.vcxproj(227,5): error : The webrtc.lib file was not found for configuration 'Release' platform 'x64'. This generally indicates that libwebrtc was not built locally. Run "tools\build\build.ps1 -BuildConfig Release -BuildArch x64 -BuildPlatform Win32" to build it. See https://microsoft.github.io/MixedReality-WebRTC/manual/building-windows.html for more details. Missing file: C:\mr-webrtc\tools\build\mrwebrtc\..\..\..\external\webrtc-uwp-sdk\webrtc\xplatform\webrtc\out\webrtc_win_x64_release\obj\webrtc.lib
Done building project "mrwebrtc-win32.vcxproj" -- FAILED.

========== Rebuild All: 1 succeeded, 2 failed, 0 skipped ==========
```

Any ideas?

**Comment by djee-ms** [comment]
- Are the files mentioned at the end of the error messages (`webrtc.lib`) present on disk?
- Are the runs of `build.ps1` actually succeeding? (you pasted the first 2 lines, there should be hundreds of them, with the build status at the end). Also please check the first ~20 lines if there's anything looking like an error, I've seen in the past the build script from `webrtc-uwp-sdk` that we use under the hood silently fail and return build success even though it did almost nothing.
- Just in case, do you have Python 2.7 by default in your PATH? (try `python --version`) I think using Python 3.x sometimes causes issues, possibly silent.

**Comment by djee-ms** [comment]
(tagged as Bug for the missing `build.ps1` Visual Studio variant)

**Comment by eirikhollis** [comment]
You were right about Python2.7, which wasn't default. Enabling that produced a lot more text in the log.
Nothing in the logs are red for Win32 x86 and x64, but I still can't build in Visual Studio, with the same issues as mentioned before.

Pasting the first paragraph of output:
```
Windows SDK 1803 10.0.17134 (April 2018)   : OK
Windows SDK 1809 10.0.17763 (October 2018) : OK
[INFO             ] - [System         ] - __updateDepotToolsPath         - Adding depot tools path 'C:\mr-webrtc\external\webrtc-uwp-sdk\scripts\..\.\webrtc\xplatform\depot_tools' to the PATH. (system.py:424)
[WARNING          ] - [System         ] - __determineVisualStudioPath    - Visual studio 2017 is not found at C:\Program Files (x86)\Microsoft Visual Studio\2017. Please install it, or if it is installed, set msvsPath variable in userdef.py to point to correct path. (system.py:473)
[INFO             ] - [Main           ] - main                           - Root logger is created (run.py:275)
[WARNING          ] - [System         ] - checkTools                     - perl is not installed. (system.py:159)
[ERROR            ] - [Utility        ] - getKeyValueFromRegistry        - [Error 2] The system cannot find the file specified (utility.py:686)
[WARNING          ] - [Utility        ] - returnOriginalFile             - C:\mr-webrtc\external\webrtc-uwp-sdk\scripts\..\.\webrtc\xplatform\webrtc\BUILD.gn or its backup doesn't exist. (utility.py:522)
[CRITICAL         ] - [System         ] - stopExecution                  - Script execution has failed (system.py:296)
[ERROR            ] - [System         ] - stopExecution                  - Windows SDK debug tools are missing! (system.py:297)
  File "..\..\external\webrtc-uwp-sdk\scripts\run.py", line 350, in <module>
```

Seems to a bit of everything here, are all errors relevant?

**Comment by djee-ms** [comment]
> Windows SDK debug tools are missing! 

This one is relevant; you need the tools installed. See (outdated but relevant) instructions here : https://microsoft.github.io/MixedReality-WebRTC/manual/building-core.html#core-webrtc

**Comment by eirikhollis** [comment]
> This one is relevant; you need the tools installed. See (outdated but relevant) instructions here : https://microsoft.github.io/MixedReality-WebRTC/manual/building-core.html#core-webrtc

I was missing the `Debugging Tools for Windows` option on the SDK,  so got a little further now.

However, I'm still having issues, now with
```
ERROR at //build/config/win/visual_studio_version.gni:27:7: Script returned non-zero exit code.
      exec_script("../../vs_toolchain.py", [ "get_toolchain_dir" ], "scope")
      ^----------
Current dir: C:/mr-webrtc/external/webrtc-uwp-sdk/webrtc/xplatform/webrtc/out/webrtc_win_x64_release/
Command: C:/Python27/python.exe C:/mr-webrtc/external/webrtc-uwp-sdk/webrtc/xplatform/webrtc/build/vs_toolchain.py get_toolchain_dir
Returned 1.
```

I only have VS2019 installed, is VS2017 a requirement to build the library?

**Comment by eirikhollis** [comment]
Installing VS2017 seemed to fix the final issues. Running the build script in any configuration works without errors.

.\build.ps1 -BuildConfig Release -BuildArch x64 -BuildPlatform Win32
```
ACTION: build
     SUCCESSFUL: webrtc   win   x64   release      execution time: 0:00:25.957000

-------------------------------------------------------------------------------------------
ACTION: prepare
     SUCCESSFUL: webrtc   win   x64   release      execution time: 0:00:06.005000
```

However, in VS2019, when building for x64 or x86 on Win32, the following error appears
```
------ Build started: Project: mrwebrtc-win32, Configuration: Release Win32 ------
LINK : fatal error LNK1104: cannot open file 'atls.lib'
Done building project "mrwebrtc-win32.vcxproj" -- FAILED.

------ Build started: Project: mrwebrtc-win32, Configuration: Release x64 ------
LINK : fatal error LNK1104: cannot open file 'atls.lib'
Done building project "mrwebrtc-win32.vcxproj" -- FAILED.
```

UWP builds work fine. Any ideas?

**Comment by djee-ms** [comment]
> I only have VS2019 installed, is VS2017 a requirement to build the library?
>
> EDIT:
> I should rather ask; is it still a requirement to build the library? I'm guessing the undock will port everything over to VS2019?

Correct, still a requirement. You don't need to install a full VS2017 though, just the v141 toolchain inside VS2019. What's important is to get the compiler not the entire IDE.

> The issue was fixed by installing C++ ATL for v141 build tools (x86 & x64) in Visual Studio Installer for VS2019.

Yes this is also a prerequisite for Google's code for some reason, but seems it's [missing in the list](https://microsoft.github.io/MixedReality-WebRTC/manual/building-core.html#prerequisites).

> Quite a process to setup the environment for building the master branch now. Is this the default approach moving forward now?

Yes, we are not maintaining the old Core NuGet packages anymore. There are many reasons to this, main of which being that we now have prebuilt binaries for all supported platforms/targets so there should be little reason for people to build from source. Most users which used to build from sources were Unity users, who do not necessarily have the C/C++ background to handle the Google build. Also the build times used to be astronomical when we started a year and a half ago (like 2+ hours per variant with huge RAM requirement that simply prevented some users from building) but have been optimized to something like 10-15 min from scratch and much less incrementally. And if you do need to build from sources for some reason, the one-time setup is tedious but once done you are in a much better place for everything including debugging (you have your own set of PDBs for example) and that approach greatly reduces the chances of people doing a mix and match of downloading some binaries from NuGet while compiling other stuffs and ending up with weird undebuggable crashes and a pile of avoidable issues we were losing time on. In short, I appreciate it increases the barrier to entry for building from sources, but we expect most users to never have to cross that barrier.

**Comment by eirikhollis** [comment]
So if I understand it correctly, the only time I will need to run the build.ps1 script is when there are changes to webrtc-uwp-sdk imported into the project?

And if there are changes to webrtc-uwp-sdk, I would have to pull latest master, run `git submodule update --recursive --init`, run `build.ps1` for all configurations I desire, and then build through Visual Studio?

Hopefully I'll be able to provide better bug reports in the future with the extended amount of debugging possible :)

**Comment by djee-ms** [comment]
Yes, but no `--init` argument, that's only for the first time you clone, and only if you didn't clone with `--recursive` but instead manually clone the submodules after cloning the main repository alone.

```sh
git checkout master
git pull
git submodule update --force
build.ps1 -BuildConfig Release -BuildArch x64 -BuildPlatform Win32
```

**Comment by eirikhollis** [comment]
Thanks for the clarification! This issue can probably be closed now :+1:
