### ISSUE TITLE
Unity Build Error:The type 'Object' is defined in an assembly that is not referenced

### ISSUE THREAD

**Issue by Boo0317** [microsoft/MixedReality-WebRTC#53]
Unity Version 2018.3.0f2
It always has error when I build unity project like this:
**Assets\Microsoft.MixedReality.WebRTC.Unity\Scripts\Media\VideoSource.cs(34,32): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.**
I think I have lost something, but I don't know what is missing.
It worked well on Unity Editor.

**Comment by Boo0317** [comment]
![20190902173758](https://user-images.githubusercontent.com/33243304/64105359-ab152400-cda8-11e9-8efc-75bb43636c1a.png)

**Comment by eirikhollis** [comment]
Is your project setup like this?
![image](https://user-images.githubusercontent.com/30655189/64108611-8a83a480-cd7d-11e9-8ead-eace23dede3e.png)
Under Edit -> Project Settings -> Other Settings

**Comment by djee-ms** [comment]
Hi @Boo0317,

The error message points at a missing .NET Standard 2.0 library, which should be installed by Unity if you have the setup that @eirikhollis pointed above.

**Comment by Boo0317** [comment]
Thank you for your quickly reply.I've tried IL2CPP it build successed, but I want to build an Unity C# project so I selected .NET rather than IL2CPP. Does it only support IL2CPP now?

**Comment by djee-ms** [comment]
This is a Unity limitation, see _e.g._ https://forum.unity.com/threads/2018-2-16f1-uwp-net-scripting-backend-net-standard-2-0-build-errors.588733/ 
> We don't support .NET Standard 2.0 on .NET scripting backend. It's only supported when using Mono and IL2CPP. 

The .NET backend is deprecated in 2018.3 and completely removed in 2019.1. There is not much I can do about it, you will have to use IL2CPP.
