### ISSUE TITLE
Cannot open sample scenes in UPM package

### ISSUE THREAD

**Issue by zxubian** [microsoft/MixedReality-WebRTC#530]
**Describe the bug**
Upon trying to open any sample scene, Unity gives the following warning: "It is not allowed to open a scene in a read-only package". As a result, the scene does not open.

**Environment**
 - MR-WebRTC version and Samples v2.0 packages obtained from UPM
 - Architecture: Unity Editor is x64
 - Unity version 2019.4.6f1

**Additional context**
Unity say [here](https://forum.unity.com/threads/cant-save-scenes-into-packages-cant-load-scenes-from-packages.590764/) that they don't support including scenes in packages, and instead recommend adding them to "samples". Currently MixedReality.WebRTC Samples is its own package, but it should perhaps be moved into "samples" for the main package.

**Comment by djee-ms** [comment]
See #526.

**Comment by djee-ms** [comment]
Also the post you linked is almost 2 years old, things have significantly changed.
