### ISSUE TITLE
Unity Test App: CreateOffer button does not update RemotePeerId

### ISSUE THREAD

**Issue by scm2217** [microsoft/MixedReality-WebRTC#54]
The create offer button of NodeDssSignalerUI.cs checks if the entered id is valid but fails to actually assign it to the RemotePeerId variable of NodeDssSignaler.cs

Right now it is easy to workaround by manually entering it in Unity Editor, but I am guessing that the button should be performing that functionality.

**Comment by djee-ms** [comment]
This is a regression; fixed with c4e7d34a8d71909c89d88f49a46f1ed901ff4b7e. Thanks @scm2217!
