### ISSUE TITLE
Question about debugging Unity scripts with IL2CPP

### ISSUE THREAD

**Issue by dl4mmers** [microsoft/MixedReality-WebRTC#542]
Hey!

I'm currently working on switching from WebRTC-UWP-SDK to MixedReality-WebRTC in our HoloLens application. First of all I would like to thank you for this nice SDK. It's much easier to work with this SDK than with WebRTC-UWP-SDK and being able to test in Unity editor is a huge benefit.

Switching the WebRTC SDK forced us to switch from .NET scripting backend to IL2CPP and I don't really understand how to get Unity Debug.Log() printed in the Visual Studio console. We are using Unity 2018.4.26f1 and Visual Studio 2017.

Build window looks like this:

![unitybuildwindow](https://user-images.githubusercontent.com/42814715/90528556-0b94a100-e173-11ea-95c2-545eacf32f6e.png)

I strictly followed this guide (https://docs.microsoft.com/de-de/windows/mixed-reality/managed-debugging-with-unity-il2cpp), but unfortunately no UnityEngine.Debug.Log() showing up, not in Debug- nor in Release-Mode.

When using System.Diagnostics.Debug or System.Diagnostics.Trace, the logs appear in the VS console, but shouldn't it be possible to also get Unity debug logs appear in the console? In the MixedReality-WebRTC Unity scripts like NodeDssSignaller UnityEngine.Debug.Log() are also used.

I've found that the generated IL2CPP VS solution has the following debugger selection, but selecting Managed Only / Script Only / Managed and Native / Script and Native did not make any changes.

![debuggers](https://user-images.githubusercontent.com/42814715/90530594-5adbd100-e175-11ea-96e2-2ee91ea4998b.png)

Is there anything I've missed?

**Comment by djee-ms** [comment]
Hi,

That's a Unity question really, but the only thing that comes to mind is check that the Visual Studio project generated by Unity is built in Debug config. Debugger options should have no influence here as far as I know; in managed you get the message alone, in native you get the message and the entire C# callstack where the message was sent from. But you get it either way. I see on your screenshot that "Build Configuration" is set to Release; I've always ignored that (I think it's irrelevant for generated projects, only for Build&Run) but try Debug just in case.

**Comment by dl4mmers** [comment]
Selecting Debug as Build Configuration in Unity did not make any changes. I will open a thread in Unity forums an ask there. I have found a way without Visual Studio anyway. The Unity console has a dropdown "Editor" where an IP can be entered and if I run the app on HoloLens I can attach the Unity console and get all UnityEngine.Debug.Logs printed there. Don't know why this does not work with Visual Studio "Attach Unity Debugger".

**Comment by djee-ms** [comment]
>  if I run the app on HoloLens
> [...]
> Visual Studio "Attach Unity Debugger"

Those are unrelated and can't work together.
- To run on HoloLens you generate a **C++** Visual Studio project. Once generated, there is no link anymore to Unity or its editor, this is a regular app that you deploy to device, and you should use the Device target to deploy and debug directly with the **native** VS debugger.
- Visual Studio "Attach Unity Debugger" is to attach the **managed (C#)** debugger to the Unity C# runtime running inside the Editor.

What you did with the Editor IP also works, but is unrelated to debuggers, this is a proprietary Unity protocol to communicate between a Unity app and the editor. That works for Debug.Log() but will not show anything else a normal debugger would.
