### ISSUE TITLE
How do I properly turn off the local camera？

### ISSUE THREAD

**Issue by LuZongkuan** [microsoft/MixedReality-WebRTC#545]
Editor: Unity2019.2.4
Platform: Hololens2 
Released: 2.0.0
Example: VideoChatDemo
Question:
The HoloLens app crashes when I release the camera resources.
I want to go back to another scene when I exit the video chat.
How do I properly invoke the method that dispose of the local camera source？

**Comment by LuZongkuan** [comment]
No response? It's a pity.

**Comment by desto12** [comment]
I have the same problem.

**Comment by LuZongkuan** [comment]
> 
> 
> I have the same problem on android but in editor everything works ok.

Hey，buddy! 
Try changing the Unity Editor version: 2019.3.x+（My Editor version: Unity2019.3.0f6）
Some components may be supported. But I still don't know why I succeeded.

Method: 
Disable the local media(Microphone & WebcamSource)
Disable the NodeSignaler

**Comment by desto12** [comment]
Ok it was my fault i had .AAR built 30 days + ago, and this commit helped me a lot #538 problem was with this line `webrtc::GetClass(env, "org/webrtc/UnityUtility");` now works perfectly, thanks guys for fixed this problem :)

**Comment by djee-ms** [comment]
Alright, closing then, thanks!

**Comment by fibann** [comment]
@LuZongkuan I have tried just disabling the WebcamSource in VideoChatDemo built with Unity 2019.4.4f1 on HL2, and it worked as expected. It might have been some quirk with the specific Unity version.

@desto12 can you give more details about the crash you are seeing on Android? E.g. callstack, precise repro steps. I can't remember seeing crashes on Android when disabling the camera but I'll double-check.
