### ISSUE TITLE
Native Exception when no Microphone/headphone is connected

### ISSUE THREAD

**Issue by AtosNicoS** [microsoft/MixedReality-WebRTC#546]
**Describe the bug**
`_peerConnection.InitializeAsync()` crashes with a native exception if no microphone/headset is connected.

**To Reproduce**
1. Create a perr Connection
2. Run InitializeAsync()

**Expected behavior**
It should just work

**Environment**
_Please fill the information for **each peer** if different_
 - MR-WebRTC version 2.0.0
 - Platform: UWP
 - Architecture: x64
 - Target device: Windows Desktop

**Comment by fibann** [comment]
This might be related to the legacy ADM which we have dropped since 2.0.0. Can you check if this works on latest master (which uses ADM 2)?

**Comment by AtosNicoS** [comment]
Is there any preview nuget package I can use?

**Comment by fibann** [comment]
Not at the moment. I'll update this issue when we have one.

**Comment by AtosNicoS** [comment]
We have tried with the latest master, and still see this issue:
![image](https://user-images.githubusercontent.com/37442184/92234107-c205bf00-eeb1-11ea-88ed-db7365f37ea6.png)

**Comment by fibann** [comment]
Thanks for checking @AtosNicoS - so this is an issue with the WebRTC-UWP audio module, we'll see what we can do.
