### ISSUE TITLE
TestAppUwp: Audio not working

### ISSUE THREAD

**Issue by scm2217** [microsoft/MixedReality-WebRTC#55]
Both audio playback and transmission of the TestAppUwp do not work; Video playback works correctly.

Tested by connecting to both another instance of TestAppUwp and the Unity example client. Unity example client is able to both transmit and receive audio when connected to another Unity example client.

**Comment by djee-ms** [comment]
I will have a look. I didn't test that for some time; I generally test audio with the Unity app.

**Comment by djee-ms** [comment]
There was no call to `AddLocalAudioTrackAsync()` so only the video was added. I pushed a very basic fix with 65a59d83e525377d74d2b515bd002624e0c416ba.
