### ISSUE TITLE
Cannot apply remote description: Object not initialized.

### ISSUE THREAD

**Issue by dyhmichail** [microsoft/MixedReality-WebRTC#552]
**Describe the bug**
Hello, I start demo scene with my own signal server.
And see in logs that:
"Initializing WebRTC plugin…"
"WebRTC plugin initialized successfully."
Then I create offer and receive an answer, and at PeerConnection.cs

            try
            {
                await Peer.SetRemoteDescriptionAsync(message);
            }
            catch (Exception ex)
            {
                Debug.LogError($"Cannot apply remote description: {ex.Message}");
            }

I've got error:
Cannot apply remote description: Object not initialized.
UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.WebRTC.Unity.<HandleConnectionMessageAsync>d__23:MoveNext() (at Library/PackageCache/com.microsoft.mixedreality.webrtc@2.0.0-preview.1/Runtime/Scripts/PeerConnection.cs:480)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start(<HandleConnectionMessageAsync>d__23&)
Microsoft.MixedReality.WebRTC.Unity.PeerConnection:HandleConnectionMessageAsync(SdpMessage)

How could it be if it is Initialized at the beginning?

**To Reproduce**
1. Start scene
2. Initialize WebRTC plugin 
3. Send offer
4. Receive answer
5. See error "Cannot apply remote description: Object not initialized."

**Expected behavior**
No error, and set remote description

**Environment**
Unity Editor 2018.6

**Comment by fibann** [comment]
This works in the sample scenes with the NodeDssSignaler. There might be some issue with your signaler/app logic that causes the PeerConnection to be shutdown before it receives the answer. A way to figure out what's happening is to run a debug build of MR-WebRTC and attach a native debugger, that will show you if there are errors with initialization or if the PC is shutdown at some point. Alternatively you can try to make a simple repro project for us to try.

Also I see that you are using the preview package for 2.0.0, I recommend you switch to the latest version.

**Comment by dyhmichail** [comment]
> This works in the sample scenes with the NodeDssSignaler. There might be some issue with your signaler/app logic that causes the PeerConnection to be shutdown before it receives the answer. A way to figure out what's happening is to run a debug build of MR-WebRTC and attach a native debugger, that will show you if there are errors with initialization or if the PC is shutdown at some point. Alternatively you can try to make a simple repro project for us to try.
> 
> Also I see that you are using the preview package for 2.0.0, I recommend you switch to the latest version.

Thx for the advice, I didn't find the latest version at the download page, can you please give me a link to the latest version?

**Comment by fibann** [comment]
See https://github.com/microsoft/MixedReality-WebRTC/releases/tag/v2.0.0

**Comment by dyhmichail** [comment]
During the update problem was solved.
