### ISSUE TITLE
Name of transceivers is empty

### ISSUE THREAD

**Issue by tarukosu** [microsoft/MixedReality-WebRTC#556]
**Describe the bug**

When I received an offer message and call HandleConnectionMessageAsync,
PeerConnection.Peer.Transceivers is updated but the all the names of transceivers are empty string.

```cs
PeerConnection.HandleConnectionMessageAsync(message);
```

```cs
foreach (var transceiver in PeerConnection.Peer.Transceivers)
{
    // name is empty
    Debug.Log(transceiver.Name);
}
```

**Expected behavior**
The name of transceiver is a mid value in a sdp message.

**SDP messages**

<details open><summary>Offer message</summary>
<code>
v=0
o=Shiguredo...Sora-19.04.9 3591338143053790409 0 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 9B:DE:BD:FF:09:F9:78:ED:21:79:C2:49:EE:E4:E6:09:7E:0B:69:05:3D:BC:17:20:C3:17:26:15:1C:57:EF:D4
a=group:BUNDLE audio_8MSfdE video_jaLMR2
a=msid-semantic:WMS *
a=ice-options:trickle
m=audio 9 UDP/TLS/RTP/SAVPF 109
c=IN IP4 0.0.0.0
a=candidate:0 1 UDP 2114002687 52.246.167.126 60106 typ host
a=end-of-candidates
a=recvonly
a=ice-ufrag:JzUNE1OWB9ke
a=ice-pwd:pVjOh5WLsA3ofn916SUP5yTgM5mrooM1mIuR
a=mid:audio_8MSfdE
a=msid:4705360b-0192-4141-bb82-2ad2991560d9 4a316766-518f-4aea-8356-cd5e30fa7d9f
a=rtcp-rsize
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=fmtp:109 maxplaybackrate=48000;stereo=1;sprop-stereo=1;minptime=10;ptime=20;useinbandfec=1;usedtx=0
a=setup:actpass
a=ssrc:2413214740 cname:4705360b-0192-4141-bb82-2ad2991560d9
m=video 9 UDP/TLS/RTP/SAVPF 120 96
c=IN IP4 0.0.0.0
a=candidate:0 1 UDP 2114002687 52.246.167.126 60106 typ host
a=end-of-candidates
a=recvonly
a=ice-pwd:pVjOh5WLsA3ofn916SUP5yTgM5mrooM1mIuR
a=ice-ufrag:JzUNE1OWB9ke
a=mid:video_jaLMR2
a=msid:4705360b-0192-4141-bb82-2ad2991560d9 1dabbd56-026e-485a-8ddf-7567c4207620
a=rtcp-rsize
a=rtcp-mux
a=rtpmap:120 VP8/90000
a=fmtp:120 max-fs=12288;max-fr=60
a=rtcp-fb:120 ccm fir
a=rtcp-fb:120 nack
a=rtcp-fb:120 nack pli
a=rtcp-fb:120 goog-remb
a=rtpmap:96 rtx/90000
a=fmtp:96 apt=120
a=setup:actpass
a=ssrc:665831898 cname:4705360b-0192-4141-bb82-2ad2991560d9
</code>
</details>

**Environment**
 - MR-WebRTC version: v2.0.0
 - Platform: Unity Editor
 - Architecture: x64
 - Unity version (if applicable): 2018.4.15f
 - Target device: HoloLens 2

**Comment by djee-ms** [comment]
As I remember, that indeed does not work very well, and I am not sure there is a way to fix this. That is, the transceiver names are set locally and always available there, but I think there's no guarantee that these names are reliably transferred to the remote peer. I appreciate that there might be an assumption that those names are always synchronized, but that is not the case in practice so you should not assume it.

On top of my head, in the WebRTC protocol there's no such thing as transceiver name, and we (ab)use the `a=msid` field for that, but I can't remember the exact rule nor if there is any guarantee that those fields are in sync on both peers (that is, if the standard doesn't guarantee it, or if there's maybe a bug in the Google implementation). If you rely on transceivers having the same name, I would encourage you to part ways with this and instead use a different custom way, for example using data channels to transmit any info you need on the side.

**Comment by tarukosu** [comment]
I suppose that `a=mid:` is the name (ID) of a transceiver.

https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpTransceiver/mid

**Comment by tarukosu** [comment]
It seems that name is set to mid value.
Why doesn't it work well?

https://github.com/microsoft/MixedReality-WebRTC/blob/49e7bbda5779db420d8e90fd07e90b5c9fc79db8/libs/mrwebrtc/src/peer_connection.cpp#L1117-L1119

**Comment by djee-ms** [comment]
That code is setting the name of a transceiver created by the implementation to the `mid` property of that transceiver as received from the remote peer. That does not mean that the remote peer used `Transceiver.Name` as the value for `mid`. In general `mid` is a GUID-like random identifier.

Looking at the code, we are not setting the name to the transceiver mid property, because there's apparently no API to do so in the Google implementation:
https://github.com/microsoft/MixedReality-WebRTC/blob/49e7bbda5779db420d8e90fd07e90b5c9fc79db8/libs/mrwebrtc/src/peer_connection.cpp#L666-L672

**Comment by djee-ms** [comment]
Reason being the transceiver gets associated with a mid only when an offer or answer is applied, before that its mid is empty.

https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-26

> All MID values MUST be generated in a fashion that does not leak user information, e.g., randomly or using a per-PeerConnection counter, and SHOULD be 3 bytes or less

Google complies with this by [assigning](https://webrtc.googlesource.com/src/+/refs/branch-heads/71/pc/peerconnection.cc#3863) to new transceivers a simple [monotonic sequence of numbers](https://webrtc.googlesource.com/src/+/refs/branch-heads/71/pc/peerconnection.cc#3736). There is no API to change that.

**Comment by tarukosu** [comment]
Thank you so much.
I don't think I understand it completely, but I'm going to try a different way to identify transceivers.
