### ISSUE TITLE
Callback for PeerConnection Disconnected

### ISSUE THREAD

**Issue by codeplay9800** [microsoft/MixedReality-WebRTC#558]
**Describe the problem**
There is no callback\Event for if peerconnection has been disconnected. We can surely handle it by checking isConnected parameter in a thread but a callback for disconnection will be a good feature.

**Describe the solution you'd like**
A callback\Event for Handling PeerConnection Disconnection.

**Describe alternatives you've considered**
Currently, I am running a Coroutine to check if the isConnected parameter returns true.

**Comment by fibann** [comment]
See https://github.com/microsoft/MixedReality-WebRTC/issues/559#issuecomment-687196417 - you can use `PeerConnection.IceStateChanged` instead.
