### ISSUE TITLE
Microsoft.MixedReality.WebRTC.PeerConnection isConnected boolean returns true even after Disconnection.

### ISSUE THREAD

**Issue by codeplay9800** [microsoft/MixedReality-WebRTC#559]
**Describe the bug**
Microsoft.MixedReality.WebRTC.PeerConnection isConnected boolean returns true even after PeerConnection has been Disconnected. 

**To Reproduce**
1. Establish a connection between the offer and answer System.
2. Close either of the application making a forceful disconnection. In my case, I am using Unity Editor
3. Check the value of isConnected boolean of Microsoft.MixedReality.WebRTC.PeerConnection instance.
4. It still returns true.

**Expected behavior**
The boolean should return false after Peer has been forcefully disconnected. I have found that the Unitialise method in PeerConnection class stops the execution as the first Debug.Assert statement fails, which in turn doesn't call OnShutdown.Invoke() callback to trigger. This happens when stop the scene in unity. Might be due to _nativePeer gets uninitialized prior to this method call which doesn't allow code to execute.

**Referenced Code**
        private void Uninitialize()
        {
            Debug.Assert(_nativePeer.Initialized);
            // Fire signals before doing anything else to allow listeners to clean-up,
            // including un-registering any callback from the connection.
            OnShutdown.Invoke();

            // Prevent publicly accessing the native peer after it has been deinitialized.
            // This does not prevent systems caching a reference from accessing it, but it
            // is their responsibility to check that the peer is initialized.
            Peer = null;

            // Detach all transceivers. This prevents senders/receivers from trying to access
            // them during their clean-up sequence, as transceivers are about to be destroyed
            // by the native implementation.
            foreach (var mediaLine in _mediaLines)
            {
                mediaLine.UnpairTransceiver();
            }

            // Close the connection and release native resources.
            _nativePeer.Dispose();
            _nativePeer = null;
        }

**Environment**
 - MR-WebRTC version (2.0)
 - Platform: Unity Editor
 - Architecture: Unity Editor is x64 on Windows
 - Unity version : [2019.3.5f1]
 - Target device: Windows Desktop

**Comment by fibann** [comment]
`PeerConnection.IsConnected` is not indicative of an actual ICE connection being active, and it is set just after an SDP offer/answer exchange has been completed. This diverges a bit from the WebRTC terminology but it is by design.

If you want to listen for network disconnection events you should listen to `PeerConnection.IceStateChanged` instead.
