### ISSUE TITLE
Unity crashes with speaker chosen as default playback device on Windows 10

### ISSUE THREAD

**Issue by eirikhollis** [microsoft/MixedReality-WebRTC#56]
For some reason, when my speaker is chosen as default playback device, the Unity crashes when trying to initialize the peerconnection. No error message is given, and attaching VS to Unity does not hit any exception breakpoints. Unity simply just closes.

![image](https://user-images.githubusercontent.com/30655189/64156242-adbd5b00-ce34-11e9-8217-3642f026f077.png)

This does not happen if any other playback device is chosen, as seen below

![image](https://user-images.githubusercontent.com/30655189/64156334-da717280-ce34-11e9-8ab5-052fb8472108.png)

I'm still investigating the issue, but is there any reason why this should happen?

Unity 2019.1.14
Latest master branch
Windows 10 Build 18362

**Comment by djee-ms** [comment]
No, there is no reason why it would fail with one device. Unless another application is using that device in exclusive mode, or (and I don't know if it does) WebRTC is trying to open the device in exclusive mode but another application is using it in shared mode.

**Comment by eirikhollis** [comment]
That might be the issue, yes. I don't experience this on any other computer using the same code. Weird that it happens on clean restart and no other programs running, but I guess it isn't an issue with the WebRTC code. Other than maybe it should throw an exception instead of silently crashing?

**Comment by djee-ms** [comment]
@eirikhollis if you have some time to pinpoint where it's crashing we can look at adding an exception. But on top of my head with the info above I have no guess where that can happen.

**Comment by eirikhollis** [comment]
We'll leave it for now. I can message you later if I ever do pinpoint it.
