### ISSUE TITLE
Acoustic Echo Cancellation

### ISSUE THREAD

**Issue by sananbintahir** [microsoft/MixedReality-WebRTC#562]
I've got a pretty good working version of this library in my unity project, but when I use my app on the Oculus Quest, I get a lot of audio feedback (echo). This might be a complicated issue, but after doing some research it seems that the Google WebRTC library already takes care of echo cancellation. After seeing #157, it seems this is not automatically supported in MixedReality-WebRTC. Is there a way to go about solving this issue in Unity?

**Comment by fibann** [comment]
Closing this as #157 is already tracking AEC.
