### ISSUE TITLE
Unable to load DLL 'mrwebrtc'

### ISSUE THREAD

**Issue by WilsonDEGithub** [microsoft/MixedReality-WebRTC#569]
**Describe the bug**
It works normally in the unity editor, there is no image displayed in both video players.
This framework does not support HoloLens2 or ARM64?
What should I do to run normally on hololens2
Do you have any examples available？
Thanks!!!
**Screenshots**
_If applicable, add screenshots to help explain your problem._
![image](https://user-images.githubusercontent.com/50014960/92351596-b236e680-f10e-11ea-87f1-f1fe7ac27e61.png)

**Environment**
_Please fill the information for **each peer** if different_
 - MR-WebRTC version (2.0.0)
 - Platform: [UWP]
 - Architecture: [ARM64]
 - Unity version ( 2019.4]
 - Target device: [HoloLens 2]

**Additional context**
_Add any other context about the problem here._

**Comment by djee-ms** [comment]
See #235; ARM64 UWP is not currently supported, you should use the ARM(32) DLL for instead.

**Comment by djee-ms** [comment]
Closing as duplicate, as the work to add ARM64 support is already tracked.

**Comment by WilsonDEGithub** [comment]
@djee-ms I apologize for my recklessness, I'm really sorry. According to your solution, I use ARM32 to build the application, when I use arm(32) to build, I cannot start the program after installing to HoloLens2.

**Comment by djee-ms** [comment]
Why? What is the error?

**Comment by WilsonDEGithub** [comment]
When the program is launched for the first time, a microphone authorization window pops up. I clicked Allow, and then the screen went black. After about 10 seconds, the program returned to standby，The following is a screenshot：
![image](https://user-images.githubusercontent.com/50014960/92371632-6c8a1600-f12e-11ea-8d01-e8db089bd19e.png)

**Comment by WilsonDEGithub** [comment]
This is a screenshot running under the editor. The server started normally, and I changed the IP address to the address of the server. I really don't know what happened. I hope you can help solve it, thank you very much.
![image](https://user-images.githubusercontent.com/50014960/92372282-4749d780-f12f-11ea-8df9-06791bd0d414.png)

**Comment by djee-ms** [comment]
Please generate a Visual Studio project with the Unity Build window, and deploy and launch from VS attaching the debugger, and see if there's more info about why the app doesn't run. It's impossible to tell like this without more info. The timeout for authorization is longer than 10 seconds, and if the window shows up I am assuming this is probably not related (though I'd double-check that CAMERA permission is also in the app capabilities, and that it's allowed on the device). Other than that I have no idea.

**Comment by WilsonDEGithub** [comment]
I will try, thanks.
