### ISSUE TITLE
Build fail for Android archive under Windows 10 WSL2

### ISSUE THREAD

**Issue by prothen** [microsoft/MixedReality-WebRTC#571]
**Describe the bug**
_Android Studio build fails in `merge-archives.sh` with library compiled from master branch under WSL2._

**To Reproduce**
1. Clone repository on master branch in WSL2 Ubuntu 18.04 distro under `/mnt/c/build_webrtc_android`
2. Follow build instructions under `./tools/build/libwebrtc`
3. Open `c:\build_webrtc_android\tools\build\Android` in Android Studio under Windows
4. Change build variant to `Release`
5. Update `mrwebrtc.gradle` replacing `/mnt`-based path  with `gradle.ext.webrtcBinDir = 'c:\\build_webrtc_android\\webrtc\\src\\out\\android\\arm64'`
6. `File -> Project Structure -> Select drop-down recommendation for NDK directory`
7. `Make Project`
8. See error message

**Expected behavior**
_Successful build expected._

**Result and log**
The `C:\build_webrtc_android\tools\build\android\webrtc-native\build\outputs\aar\mrwebrtc.aar` exists. But the output of the merge shell script throws an error both in Android Studio and under the CLI execution with `gradlew.bat assembleRelease`.
 
<details>
<summary>
Android Studio build error output.

</summary>

```bash
> Task :webrtc-native:mergeLibwebrtcArchive FAILED
Caching disabled for task ':webrtc-native:mergeLibwebrtcArchive' because:
  Build cache is disabled
Task ':webrtc-native:mergeLibwebrtcArchive' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Starting process 'command 'bash''. Working directory: C:\build_webrtc_android\tools\build\android\webrtc-native Command: bash ./merge-archives.sh -m C:\build_webrtc_android\tools\build\android\webrtc-native/build/outputs/aar/mrwebrtc.aar -o ./build/outputs/aar/merged/mrwebrtc.aar
Successfully started process 'command 'bash''
:webrtc-native:mergeLibwebrtcArchive (Thread[Execution worker for ':' Thread 4,5,main]) completed. Took 0.131 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':webrtc-native:mergeLibwebrtcArchive'.
> Process 'command 'bash'' finished with non-zero exit value 1
```

</details>

<details>
<summary>
Error message from make Project with default automatic generated mrwebrtc.gradle.

</summary>

With `mrwebrtc.gradle` and directory `gradle.ext.webrtcBinDir = '/mnt/c/build_webrtc_android/webrtc/src/out/android/arm64'
`
```bash
Cannot open a library at 'FileMapping(from=C:\build_webrtc_android\tools\build\android\webrtc-native\mnt\c\build_webrtc_android\webrtc\src\out\android\arm64\Release\lib.java\sdk\android\libwebrtc.jar, to=C:\Users\colma\.gradle\caches\transforms-2\files-2.1\6e52712433a5dc2dc85d22996949cd2b\jetified-libwebrtc.jar)'
```

</details>

**Environment**
 - MR-WebRTC version: -
 - Platform: [Windows]
 - Architecture: [x64 Windows]
 - Unity version (if applicable): [-]
 - Target device: [Android]

**Comment by djee-ms** [comment]
If you're using WSL, maybe see #399, it seems the merge script doesn't handle WSL paths well.

**Comment by prothen** [comment]
Excellent, thanks for the reference.

**Comment by prothen** [comment]
1. For anyone possibly experiencing this issue in the future, the problem was that under Windows the default distribution for wsl was not set and the command `bash` failed silently in Android Studio with the misleading error message ` Process 'command 'bash'' finished with non-zero exit value 1`.
    - `wsl --list --verbose`
    - `wsl --set-default Ubuntu18.04`
    - test with `WIN + R -> cmd -> "bash"`


2. Related it might also easily happen for someone to build under `18.04` while the default distribution could be set to some other distribution. On default configurations without custom '/etc/wsl.conf' mount settings, this should however resolve to the same '/mnt' directory.

While I don't know how to resolve the 2. case and whether this is even worth considering, I have a sed regex based selection for native linux use case separation, that would allow to adapt the path in `merge-archives.sh`.

If you would like to receive a PR please let me know and I can prepare one.

**Comment by djee-ms** [comment]
@prothen To be perfectly honest I am not familiar with WSL/2. What is `wsl --set-default` doing? It doesn't seem like we want to make a user preferences change on behalf of the user just to build this project.

I'd like to understand the actual issue; why is changing that setting having any effect? I thought the issue was that the build script was handling only native Windows path (_e.g._ `C:\...`) instead of WSL/2 ones (_e.g._ `/mnt/c/...`); if so, we can simply add some handling for those too, no? This is I believe what was proposed in the PR in #399, but was not merged because the fix was only handling the C: drive, which would make I think things even more confusing for users using a different drive ("It works on C: but not on D:").

I don't use WSL2, not even sure it's installed; I have a VM instead for Ubuntu to avoid any issue, and unfortunately I don't really have time to go install all of that just for this bug. If you have the setup already and can look at the patch on #399 and make it work with any drive, then I am more than happy to get that merged, that would be extremely useful to everyone! 😄

**Comment by prothen** [comment]
> @prothen To be perfectly honest I am not familiar with WSL/2. What is `wsl --set-default` doing? It doesn't seem like we want to make a user preferences change on behalf of the user just to build this project.
> 

Oh, please excuse the lack of motivating the commands. I want to emphasize that the main problem for me, was a very user setup specific one and not related to this repository at all. I assume that within the Windows Insider Program update to the latest rolling kernel release my default wsl distro setting became misconfigured. I never use powershell or cmd but windows terminal, so I never noticed. The problem then was that Android Studio invokes in a gradle script the commandLine 'bash' command which is equivalent to executing wsl in cmd and normally resolves to the default wsl distro. So in summary, this should be a quite exotic error. Also the mention with the lack of stderror output was also directed towards Android Studio / Gradle. 

> I'd like to understand the actual issue; why is changing that setting having any effect? I thought the issue was that the build script was handling only native Windows path (_e.g._ `C:\...`) instead of WSL/2 ones (_e.g._ `/mnt/c/...`); if so, we can simply add some handling for those too, no? This is I believe what was proposed in the PR in #399, but was not merged because the fix was only handling the C: drive, which would make I think things even more confusing for users using a different drive ("It works on C: but not on D:").
> 
> I don't use WSL2, not even sure it's installed; I have a VM instead for Ubuntu to avoid any issue, and unfortunately I don't really have time to go install all of that just for this bug. If you have the setup already and can look at the patch on #399 and make it work with any drive, then I am more than happy to get that merged, that would be extremely useful to everyone! 😄

The setup I mentioned does what you would like to have. It replaces all backslashes in the merge task of the build.gradle with double backslashes to avoid escaping during the bash invocation. (in native linux there will be no such backslashes in the path and remains naturally unaltered)
Then in merge-archives.sh I condition my script on wsl kernels and then use some regex to keep the drive letter consistent while changing it to /mnt. So it should be stable but would be good to test the pr under native as well.

I will prepare the pr then tonight and maybe its easier to see what I am describing with the git diff output on there.
