### ISSUE TITLE
mrwebrtc could not be found on HL2

### ISSUE THREAD

**Issue by TheRisenPhoenix** [microsoft/MixedReality-WebRTC#574]
**Describe the bug**
When deploying an Unity application with MixedReality-WebRTC included to HL2, an error message pops up that mrwebrtc.dll couldn't be found and thus not loaded.
**_Trying the same project on the emulator works fine._**

**To Reproduce**
1) Create sample application with webRTC included (just like in the guide)
2) Build the project with unity and then build/deploy it to HL2

**Expected behavior**
webRTC should be working, but isn't.

**Environment**
_Please fill the information for **each peer** if different_
 - MR-WebRTC version newest (2.0.0)
 - Platform: Hololens 2 (UWP)
 - Architecture:  ARM64
 - Unity version 2019.4.9f1
 - Target device: HoloLens 2

**Additional context**
It looks like that the mrwebrtc.dll is present in the build folder, along with GameAssembly.dll, AudioPluginMsHRTF.dll, UnityPlayer.dll and the application itself. However, it either isn't deployed to HL2, or hololens can't load it (for some reason)

**Comment by djee-ms** [comment]
UWP ARM64 is not supported.

**Comment by djee-ms** [comment]
See #235 or #414.

**Comment by TheRisenPhoenix** [comment]
Thanks for the hints and sorry for the duplicate.
Is there a raw estimate/roadmap when UWP ARM64 support will be included? (like, are we speaking of weeks, months, years...?)
