### ISSUE TITLE
The peer hangs when added Audio Transceiver - UWP

### ISSUE THREAD

**Issue by Domonap** [microsoft/MixedReality-WebRTC#583]
When I make the offer the Video is working fine both ways. When adding Audio Transceiver the peer hangs.
 
 **The Peer hangs scenario - Logs** 

  Microphone Source was created
  LocalAudioTrack was added.
  AudioTransceiver was created:
  MlineIndex: (mid =#-1)
  DesiredDirection: SendReceive
  LocalAudioTrack microphone_track
  PeerConnection IsConnected: False
 
  Webcam Source was created
  LocalVideoTrack was added. 
  VideoTransceiver was created: 
  MlineIndex: (mid =#-1)
  DesiredDirection: SendReceive
  LocalVideoTrack webcam_track
  PeerConnection IsConnected: False
 

  **Sender Has made an offer to Receiver**

  Sender Sends Ice Candidate Ice to  Receiver
  Data: candidate:1995739850 1 udp 2122260223 192.168.1.65 53539 typ host generation 0 ufrag U4V5 network-id 1 network-cost 10|0|0

  Sender Sends Ice Candidate Ice to  Receiver
  Data: candidate:1995739850 1 udp 2122260223 192.168.1.65 53540 typ host generation 0 ufrag U4V5 network-id 1 network-cost 10|1|1

  Sender Sends Ice Candidate Ice to  Receiver
  Data: candidate:2162486046 1 udp 1686052607 109.252.136.174 53539 typ srflx raddr 192.168.1.65 rport 53539 generation 0 ufrag U4V5 network-id 1 network-cost 10|0|0

  Sender Sends Ice Candidate Ice to  Receiver
  Data: candidate:947351098 1 tcp 1518280447 192.168.1.65 58137 typ host tcptype passive generation 0 ufrag U4V5 network-id 1 network-cost 10|0|0

  Sender Sends Ice Candidate Ice to  Receiver
  Data: candidate:2162486046 1 udp 1686052607 109.252.136.174 53540 typ srflx raddr 192.168.1.65 rport 53540 generation 0 ufrag U4V5 network-id 1 network-cost 10|1|1

  Sender Sends Ice Candidate Ice to  Receiver
  Data: candidate:947351098 1 tcp 1518280447 192.168.1.65 58138 typ host tcptype passive generation 0 ufrag U4V5 network-id 1 network-cost 10|1|1
  
  **Offer message**

    v=0
    o=- 597898464983772993 2 IN IP4 127.0.0.1
    s=-
    t=0 0
    a=group:BUNDLE 0 1
    a=msid-semantic: WMS
    m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
    c=IN IP4 0.0.0.0
    a=rtcp:9 IN IP4 0.0.0.0
    a=ice-ufrag:U4V5
    a=ice-pwd:5GI1VGEBeoALnTAAesYziVfF
    a=ice-options:trickle
    a=fingerprint:sha-256 B9:4F:45:FC:32:B2:86:F9:06:71:10:AB:06:D2:A3:2A:96:C4:15:6C:B5:16:8C:D5:2B:05:A8:99:E0:DA:68:0A
    a=setup:actpass
    a=mid:0
    a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
    a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
    a=sendrecv
    a=msid:- bb95083c-fa21-40ae-813d-0d0dbc055cf1
    a=rtcp-mux
    a=rtpmap:111 opus/48000/2
    a=rtcp-fb:111 transport-cc
    a=fmtp:111 minptime=10;useinbandfec=1
    a=rtpmap:103 ISAC/16000
    a=rtpmap:104 ISAC/32000
    a=rtpmap:9 G722/8000
    a=rtpmap:102 ILBC/8000
    a=rtpmap:0 PCMU/8000
    a=rtpmap:8 PCMA/8000
    a=rtpmap:106 CN/32000
    a=rtpmap:105 CN/16000
    a=rtpmap:13 CN/8000
    a=rtpmap:110 telephone-event/48000
    a=rtpmap:112 telephone-event/32000
    a=rtpmap:113 telephone-event/16000
    a=rtpmap:126 telephone-event/8000
    a=ssrc:3352556778 cname:xuMEriQ8ZrZcv+gq
    a=ssrc:3352556778 msid: bb95083c-fa21-40ae-813d-0d0dbc055cf1
    a=ssrc:3352556778 mslabel:
    a=ssrc:3352556778 label:bb95083c-fa21-40ae-813d-0d0dbc055cf1
    m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 124 125
    c=IN IP4 0.0.0.0
    a=rtcp:9 IN IP4 0.0.0.0
    a=ice-ufrag:U4V5
    a=ice-pwd:5GI1VGEBeoALnTAAesYziVfF
    a=ice-options:trickle
    a=fingerprint:sha-256 B9:4F:45:FC:32:B2:86:F9:06:71:10:AB:06:D2:A3:2A:96:C4:15:6C:B5:16:8C:D5:2B:05:A8:99:E0:DA:68:0A
    a=setup:actpass
    a=mid:1
    a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
    a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
    a=extmap:4 urn:3gpp:video-orientation
    a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
    a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
    a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
    a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
    a=extmap:10 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
    a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
    a=sendrecv
    a=msid:- 64a24f16-17c4-4126-99f8-b91dde060e4e
    a=rtcp-mux
    a=rtcp-rsize
    a=rtpmap:96 VP8/90000
    a=rtcp-fb:96 goog-remb
    a=rtcp-fb:96 transport-cc
    a=rtcp-fb:96 ccm fir
    a=rtcp-fb:96 nack
    a=rtcp-fb:96 nack pli
    a=rtpmap:97 rtx/90000
    a=fmtp:97 apt=96
    a=rtpmap:98 VP9/90000
    a=rtcp-fb:98 goog-remb
    a=rtcp-fb:98 transport-cc
    a=rtcp-fb:98 ccm fir
    a=rtcp-fb:98 nack
    a=rtcp-fb:98 nack pli
    a=fmtp:98 x-google-profile-id=0
    a=rtpmap:99 rtx/90000
    a=fmtp:99 apt=98
    a=rtpmap:100 H264/90000
    a=rtcp-fb:100 goog-remb
    a=rtcp-fb:100 transport-cc
    a=rtcp-fb:100 ccm fir
    a=rtcp-fb:100 nack
    a=rtcp-fb:100 nack pli
    a=fmtp:100 packetization-mode=1
    a=rtpmap:101 rtx/90000
    a=fmtp:101 apt=100
    a=rtpmap:127 red/90000
    a=rtpmap:124 rtx/90000
    a=fmtp:124 apt=127
    a=rtpmap:125 ulpfec/90000
    a=ssrc-group:FID 335510026 2750956389
    a=ssrc:335510026 cname:xuMEriQ8ZrZcv+gq
    a=ssrc:335510026 msid: 64a24f16-17c4-4126-99f8-b91dde060e4e
    a=ssrc:335510026 mslabel:
    a=ssrc:335510026 label:64a24f16-17c4-4126-99f8-b91dde060e4e
    a=ssrc:2750956389 cname:xuMEriQ8ZrZcv+gq
    a=ssrc:2750956389 msid: 64a24f16-17c4-4126-99f8-b91dde060e4e
    a=ssrc:2750956389 mslabel:
    a=ssrc:2750956389 label:64a24f16-17c4-4126-99f8-b91dde060e4e
 

**Answer message Missing, the Receiver has freezes**
 

**New Case when Working Video but no Audio when Audio Transmitter omitted - Logs** 

      Webcam Source was created
      LocalVideoTrack was added. The track is Enabled True.
      VideoTransceiver was created:
      MlineIndex: (mid =#-1)
      DesiredDirection: SendReceive
      LocalVideoTrack webcam_track
      PeerConnection IsConnected: False
      ----------------------------------------------------------------

      An offer was made to Receiver

      Sends Ice Candidate Ice
      Data: candidate:947351098 1 tcp 1518280447 192.168.1.65 58144 typ host tcptype passive generation 0 ufrag fH+U network-id 1 network-cost 10|0|0
   

  
        **Offer:**
        v=0
        o=- 3382752668844678066 2 IN IP4 127.0.0.1
        s=-
        t=0 0
        a=group:BUNDLE 0
        a=msid-semantic: WMS
        m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 124 125
        c=IN IP4 0.0.0.0
        a=rtcp:9 IN IP4 0.0.0.0
        a=ice-ufrag:fH+U
        a=ice-pwd:/HEm2f9hPzPq4vItnZFC1WZb
        a=ice-options:trickle
        a=fingerprint:sha-256 8E:88:DC:46:AC:11:98:06:EE:A0:11:F4:5B:57:D0:16:F7:98:EA:95:42:8E:19:DB:C3:62:1F:BB:78:AE:1F:E6
        a=setup:actpass
        a=mid:0
        a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
        a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
        a=extmap:4 urn:3gpp:video-orientation
        a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
        a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
        a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
        a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
        a=extmap:10 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
        a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
        a=sendrecv
        a=msid:- 14efdb95-2cc1-47d1-87b2-054c0573c9d2
        a=rtcp-mux
        a=rtcp-rsize
        a=rtpmap:96 VP8/90000
        a=rtcp-fb:96 goog-remb
        a=rtcp-fb:96 transport-cc
        a=rtcp-fb:96 ccm fir
        a=rtcp-fb:96 nack
        a=rtcp-fb:96 nack pli
        a=rtpmap:97 rtx/90000
        a=fmtp:97 apt=96
        a=rtpmap:98 VP9/90000
        a=rtcp-fb:98 goog-remb
        a=rtcp-fb:98 transport-cc
        a=rtcp-fb:98 ccm fir
        a=rtcp-fb:98 nack
        a=rtcp-fb:98 nack pli
        a=fmtp:98 x-google-profile-id=0
        a=rtpmap:99 rtx/90000
        a=fmtp:99 apt=98
        a=rtpmap:100 H264/90000
        a=rtcp-fb:100 goog-remb
        a=rtcp-fb:100 transport-cc
        a=rtcp-fb:100 ccm fir
        a=rtcp-fb:100 nack
        a=rtcp-fb:100 nack pli
        a=fmtp:100 packetization-mode=1
        a=rtpmap:101 rtx/90000
        a=fmtp:101 apt=100
        a=rtpmap:127 red/90000
        a=rtpmap:124 rtx/90000
        a=fmtp:124 apt=127
        a=rtpmap:125 ulpfec/90000
        a=ssrc-group:FID 2212701345 1652958511
        a=ssrc:2212701345 cname:SML65bLBI1s5gg54
        a=ssrc:2212701345 msid: 14efdb95-2cc1-47d1-87b2-054c0573c9d2
        a=ssrc:2212701345 mslabel:
        a=ssrc:2212701345 label:14efdb95-2cc1-47d1-87b2-054c0573c9d2
        a=ssrc:1652958511 cname:SML65bLBI1s5gg54
        a=ssrc:1652958511 msid: 14efdb95-2cc1-47d1-87b2-054c0573c9d2
        a=ssrc:1652958511 mslabel:
        a=ssrc:1652958511 label:14efdb95-2cc1-47d1-87b2-054c0573c9d2
 

**Logs:**
Sends Ice Candidate Ice
Data: candidate:1995739850 1 udp 2122260223 192.168.1.65 64500 typ host generation 0 ufrag fH+U network-id 1 network-cost 10|0|0

Sends Ice Candidate Ice
Data: candidate:2162486046 1 udp 1686052607 109.252.136.174 64500 typ srflx raddr 192.168.1.65 rport 64500 generation 0 ufrag fH+U network-id 1 network-cost 10|0|0

 

**Answer:**

  v=0
  o=- 8994332197685438311 2 IN IP4 127.0.0.1
  s=-
  t=0 0
  a=group:BUNDLE 0
  a=msid-semantic: WMS
  m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 124 125
  c=IN IP4 0.0.0.0
  a=rtcp:9 IN IP4 0.0.0.0
  a=ice-ufrag:lYtV
  a=ice-pwd:DMOLNOAa3eQPHmfr+dTDQrwh
  a=ice-options:trickle
  a=fingerprint:sha-256 24:EB:E9:E2:CF:0A:0F:95:56:49:38:F8:2E:9E:2C:DA:8B:0E:5C:52:90:E8:09:6A:52:C5:BE:0B:BE:04:B5:44
  a=setup:active
  a=mid:0
  a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
  a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
  a=extmap:4 urn:3gpp:video-orientation
  a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
  a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
  a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
  a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
  a=extmap:10 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
  a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
  a=sendrecv
  a=msid:- 17f13f0e-ee0a-4f7c-9c62-feb3132dc141
  a=rtcp-mux
  a=rtcp-rsize
  a=rtpmap:96 VP8/90000
  a=rtcp-fb:96 goog-remb
  a=rtcp-fb:96 transport-cc
  a=rtcp-fb:96 ccm fir
  a=rtcp-fb:96 nack
  a=rtcp-fb:96 nack pli
  a=rtpmap:97 rtx/90000
  a=fmtp:97 apt=96
  a=rtpmap:98 VP9/90000
  a=rtcp-fb:98 goog-remb
  a=rtcp-fb:98 transport-cc
  a=rtcp-fb:98 ccm fir
  a=rtcp-fb:98 nack
  a=rtcp-fb:98 nack pli
  a=fmtp:98 x-google-profile-id=0
  a=rtpmap:99 rtx/90000
  a=fmtp:99 apt=98
  a=rtpmap:100 H264/90000
  a=rtcp-fb:100 goog-remb
  a=rtcp-fb:100 transport-cc
  a=rtcp-fb:100 ccm fir
  a=rtcp-fb:100 nack
  a=rtcp-fb:100 nack pli
  a=fmtp:100 packetization-mode=1
  a=rtpmap:101 rtx/90000
  a=fmtp:101 apt=100
  a=rtpmap:127 red/90000
  a=rtpmap:124 rtx/90000
  a=fmtp:124 apt=127
  a=rtpmap:125 ulpfec/90000
  a=ssrc-group:FID 2803839634 1803572327
  a=ssrc:2803839634 cname:FwDIM0dMBLj91eTF
  a=ssrc:1803572327 cname:FwDIM0dMBLj91eTF

 

**Logs**
 
        WireMessage
        MessageType: Ice
        Receiver: gia80
        Data: candidate:1495340180 1 udp 2122260223 192.168.1.76 57966 typ host generation 0 ufrag lYtV network-id 1 network-cost 10|0|0

        WireMessage
        MessageType: Ice
        Receiver: gia80
        Data: candidate:2939252032 1 udp 1686052607 109.252.136.174 57966 typ srflx raddr 192.168.1.76 rport 57966 generation 0 ufrag lYtV network-id 1 network-cost 10|0|0

        PeerConnection: connected.

        ICE state: Checking

        RemoteVideoTrack was added

        WireMessage
        MessageType: Ice
        Receiver: gia80
        Data: candidate:396552292 1 tcp 1518280447 192.168.1.76 53102 typ host tcptype passive generation 0 ufrag lYtV network-id 1 network-cost 10|0|0

        ICE state: Connected

        ICE state: Completed
 

 **Environment**: 
`
  - WebRTC.UWP  Nuget v2
  - Platform: UWP
  Player (UWP)]
  - Architecture: x86, x64,

  - Target device: Windows Desktop

**Comment by fibann** [comment]
What do you mean by "the peer hangs"? Does the process stop inside one of the MR-WebRTC API calls?

**Comment by Domonap** [comment]
When I make an offer to the receiver (Including Audio Transmitter) the receiver hangs, no answer is coming back from the receiver. When the Audio Transmitter is omitted then the peer is connected an the video link is working.
On the receiver I Call the following.  
 
<code>   


         private async Task AddWebCamSource()
        {
            _webcamSource = await DeviceVideoTrackSource.CreateAsync(); 
            _webcamSource.I420AVideoFrameReady += LocalI420AFrameReady; 
        }
 
        private void AddLocalVideoTrack()
        {
            var videoTrackConfig = new LocalVideoTrackInitConfig
            { trackName = "webcam_track"};  
            _localVideoTrack = LocalVideoTrack.CreateFromSource(_webcamSource, videoTrackConfig);  
        }
 
        private void AddVideoTransceiver()
        {
            _videoTransceiver = _peerConnection.AddTransceiver(MediaKind.Video, new TransceiverInitSettings()
            {InitialDesiredDirection = Transceiver.Direction.SendReceive});

            _videoTransceiver.LocalVideoTrack = _localVideoTrack;

        }
 
        private async Task AddMicrophoneSourc()
        {
            _microphoneSource = await DeviceAudioTrackSource.CreateAsync(); 
            
        }
 
        private void AddLocalAudioTrack()
        {
            var audioTrackConfig = new LocalAudioTrackInitConfig
            {trackName = "microphone_track"}; 
            _localAudioTrack = LocalAudioTrack.CreateFromSource(_microphoneSource, audioTrackConfig);  
        }
 
        private void AddAudioTransceiver()
        { 
                _audioTransceiver = _peerConnection.AddTransceiver(MediaKind.Audio, new TransceiverInitSettings()
                { InitialDesiredDirection = Transceiver.Direction.SendReceive});

                _audioTransceiver.LocalAudioTrack = _localAudioTrack; 

        } 
</code>

 I catch the Transmitter
_peerConnection.TransceiverAdded += TransceiverAdded;

<code> 


        private void TransceiverAdded(Transceiver transceiver)
        {
            switch (transceiver.MediaKind)
            {
                case MediaKind.Video:
                    _videoTransceiver = transceiver;
                    transceiver.DesiredDirection = Transceiver.Direction.SendReceive;
                    transceiver.LocalVideoTrack = _localVideoTrack;
                    break;
                case MediaKind.Audio:
                    _audioTransceiver = transceiver;
                    transceiver.DesiredDirection = Transceiver.Direction.SendReceive;
                    transceiver.LocalAudioTrack = _localAudioTrack; 
                    break;
                default:
                    throw new ArgumentOutOfRangeException("Invalid MediaKind");
            } 
        }
</code>

**Comment by Domonap** [comment]
I notice that when I attache Audio Transmitter to the peer in the sender and make a offer to the receiver the receiver freezes when the method ReceiveWireMessage(Message wireMessage) is called in the case WireMessageType.Ice:  _peerConnection.AddIceCandidate(msg)
The Candidate is when this happens is: "candidate:1495340180 1 udp 2122260223 192.168.1.76 61251 typ host generation 0 ufrag biBW network-id 1 network-cost 10"  

The Peer_LocalSdpReadytoSend and Peer_IceCandidateReadytoSend is not called after. 

When the Audio Transmitter is omitted from the peer in the sender the methods is called and Video work fine, but no sound.
Working candidate:
candidate:1495340180 1 udp 2122260223 192.168.1.76 59346 typ host generation 0 ufrag 9L+2 network-id 1 network-cost 10"

**Comment by fibann** [comment]
I am not 100% sure but I would expect that you need to relay the messages in the same order as they are generated (certainly you shouldn't reorder do things like delivering ICE candidates before the offer is received). Can you try enforcing that they are delivered to the peers in order?

FWIW I have never seen freezes in `AddIceCandidate` in normal use cases. It would help if you could provide a callstack of the point where it freezes and/or run a debug build of MR-WebRTC and check the logs for errors.

**Comment by Domonap** [comment]
I can not build MR-WebRTC  i use Nuget MR-WebRTC .UWP and when I dubug AddIceCandidate I see nothing, no Exception, the method only freezes. I have no more ideas. I can do some work around, maybe slow down the transmission of the signal or make some ordered list for receiving messages, but i dont think it is right.  

What I can see is 

On the caller Side 
0). Audio Transceiver Added
1). Video Transceiver Added
2). Send Sdp : Offer
3). Send IceCandidate  
4). Send IceCandidate  
5). Send IceCandidate  
6). Send IceCandidate  
7). Send IceCandidate  
8). Send IceCandidate  

When the App Freeze on the calliee

0). Received Sdp : Offer
1). Audio Transceiver Added
2). Video Transceiver Added
3). RemoteVideoTrack was added
4). Received IceCandidate 
5). PeerConnection: connected.

         "FREEZE"


For the success when Audio Transmitter is not used 
On the caller side
0). Video Transceiver Added
1). Send Sdp : Offer
2). Send IceCandidate  
3). Send IceCandidate  
4). Send IceCandidate  
5). Received Sdp : Answer
6). PeerConnection: connected.
7). ICE state: Checking
8). RemoteVideoTrack was added
9). Received IceCandidate 
10). Received IceCandidate 
11). ICE state: Connected
12). ICE state: Completed
13). Received IceCandidate 

On Callee side

0). Received Sdp : Offer
1). Video Transceiver Added
2). RemoteVideoTrack was added
3). PeerConnection: connected.
4). Send Sdp : Answer
5). Received IceCandidate 
6). Send IceCandidate  
7). Send IceCandidate  
8). ICE state: Checking
9). Received IceCandidate 
10). Received IceCandidate 
11). Send IceCandidate  
12). ICE state: Connected
13). ICE state: Disconnected

**Comment by Domonap** [comment]
If there are possibility to debug MR-WebRtc Lib with my scenario I can provide my project https://github.com/Domonap/WebRtc-UWP.git

**Comment by fibann** [comment]
You can try pausing the Visual Studio debugger after the process has frozen in `AddIceCandidate` and looking at the Callstack/Parallel stack windows - you should be able to see if there are one or more deadlocked thread and where they are waiting. If the deadlock is in native code you will need the mrwebrtc pdbs that you can find at https://github.com/microsoft/MixedReality-WebRTC/releases/download/v2.0.0/mrwebrtc_uwp-2.0.0_pdbs.zip

**Comment by Domonap** [comment]
Yes I have try to pause and load Pdbs, Put on Native debug and Include all Exception, but still I'm not getting any useable information. Obvious I'm doing something wrong with the debugger. I have tried everything that I can with the working environment that I have. To go to bottom with it I would need to compile the Mr-WebRct and Webrct Lib, but for now I don't have the possibility to do that. 
Where strange that it work with node-dss but not with signalR, and it always freezes on the same point. After stopping the flow with the debugger it does work. Some synchronization needs to be done.  
In the coming weeks I will be trying again to make it work.

**Comment by Domonap** [comment]
Hi I Have found the problem. I was calling  AddIceCandidate and SetRemoteDescriptionAsync from another thread that comes from SignalR. The solution was to add   
await Task.Run(() => _peerConnection.AddIceCandidate(candidate));  and   
 await Task.Run(() => _peerConnection.SetRemoteDescriptionAsync(message.Spd));
