### ISSUE TITLE
Conflict with Chrome Remote Desktop connection

### ISSUE THREAD

**Issue by HashimAli09** [microsoft/MixedReality-WebRTC#588]
I have a WPF application that sends video stream for screen sharing to a Web application over WebRTC connection, and i am using MixedReality.WebRTC C# on the WPF side. This is working fine, but the problem occurs when I run the apps on different PCs and before making the web-rtc connection using my apps I connect both PCs via Chrome Remote Desktop connection, and when the apps try to make their web-rtc connection, WPF app crashes right after receiving SDP offer.

From event viewer i can see that the faulting module is _'mrwebrtc.DLL'_, Here is the complete event details:
Faulting application name: Nylytics.exe, version: 1.0.0.0, time stamp: 0xe62ec6ba
Faulting module name: mrwebrtc.DLL, version: 0.0.0.0, time stamp: 0x5f293f90
Exception code: 0xc0000409
Fault offset: 0x00000000005ba01d
Faulting process id: 0x1a74
Faulting application start time: 0x01d690ada54fd0df
Faulting application path: C:\Users\Hashim\AppData\Local\nylytics\app-2.6.0\Nylytics.exe
Faulting module path: C:\Users\Hashim\AppData\Local\nylytics\app-2.6.0\mrwebrtc.DLL
Report Id: c6fe29b3-e546-4a90-a19a-5be18f3b33f2
Faulting package full name: 
Faulting package-relative application ID: 

**Expected behavior**
WPF app shouldn't crash

**Environment**
 - MixedReality-WebRTC C# 2.0.0
 - Platform: [Windows Desktop]
 - Architecture: [x64 Windows 10]

**Comment by fibann** [comment]
Can you attach a debugger and get the crash callstack and/or debug logs?

**Comment by HashimAli09** [comment]
This seems to have been fixed in the newer version, can't recreate this on MixedReality-WebRTC 2.0.1
