### ISSUE TITLE
Android - preferred video codec h264 is not set

### ISSUE THREAD

**Issue by desto12** [microsoft/MixedReality-WebRTC#589]
**Describe the bug**
The main problem of our app on android is downgrading video resolution because of cpu throttling.
Therefore we tried to use h264 instead of VP8 to improve cpu performance.
We used PreferredVideoCodec parameter of peerConnection class - `peerConnection.Peer.PreferredVideoCodec = "H264";`
but sdp offer doesnt contain in a=rtpmap H264

below is our sdp offer

`v=0
o=- 942283493391685704 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic: WMS
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:d+pn
a=ice-pwd:ALBW635LR4KI/XYgy2wZfpTY
a=ice-options:trickle
a=fingerprint:sha-256 C4:E2:D6:D7:56:A4:3D:6E:53:2E:F7:F6:95:24:A8:6A:37:6F:B9:2D:BB:41:E5:AA:42:A5:CA:FE:00:3A:2D:B3
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:- e57961c5-f907-401f-99d2-9674c08846f0
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:3992417582 cname:GIJ9E+SK2iVr2Zgs
a=ssrc:3992417582 msid:- e57961c5-f907-401f-99d2-9674c08846f0
a=ssrc:3992417582 mslabel:-
a=ssrc:3992417582 label:e57961c5-f907-401f-99d2-9674c08846f0
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 124 125
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:d+pn
a=ice-pwd:ALBW635LR4KI/XYgy2wZfpTY
a=ice-options:trickle
a=fingerprint:sha-256 C4:E2:D6:D7:56:A4:3D:6E:53:2E:F7:F6:95:24:A8:6A:37:6F:B9:2D:BB:41:E5:AA:42:A5:CA:FE:00:3A:2D:B3
a=setup:actpass
a=mid:1
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:10 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:- c71167de-3407-4596-841b-2805a9381821
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 multiplex/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 acn=VP9;profile-id=0
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 red/90000
a=rtpmap:124 rtx/90000
a=fmtp:124 apt=127
a=rtpmap:125 ulpfec/90000
a=ssrc-group:FID 4057418195 979744871
a=ssrc:4057418195 cname:GIJ9E+SK2iVr2Zgs
a=ssrc:4057418195 msid:- c71167de-3407-4596-841b-2805a9381821
a=ssrc:4057418195 mslabel:-
a=ssrc:4057418195 label:c71167de-3407-4596-841b-2805a9381821
a=ssrc:979744871 cname:GIJ9E+SK2iVr2Zgs
a=ssrc:979744871 msid:- c71167de-3407-4596-841b-2805a9381821
a=ssrc:979744871 mslabel:-
a=ssrc:979744871 label:c71167de-3407-4596-841b-2805a9381821
`
Do you have any idea to solve this problem? We are not sure if changing codec could improve significantly cpu performance so any advices in this case would be very helpful.

**Expected behavior**
_ using `peerConnection.Peer.PreferredVideoCodec = "H264";` will change codec to H264 instead of vp8_

**Environment**
_Please fill the information for **each peer** if different_
 - MR-WebRTC version: commit e7773933c14d10090ecfb34cd7e777f72bbc10f8   - Fix invalid security alerts in CG report (#551)
 - Platform:  Unity Android Player
 - Architecture: ARM64;
 - Unity version (if applicable): 2019.4.1f1
 - Target device:  Android Phone

**Comment by djee-ms** [comment]
There is no implementation of the H.264 codec for Android in the Google codebase we use under the hood, and we have no plan to add one ourselves unfortunately as this is a very large piece of work. More generally, I am not even sure what hardware codecs Android phones support nowadays, and even if some support hardware H.264 this would become a bottleneck for those who don't, so would not be a reliable workaround unless you have some constraints on the Android device the app will be used on, which further restricts the use cases for users of this library (I am assuming most of which intend to publish their app to public customers with a wide variety of phones). In this context I'm afraid there's not much we can do. I appreciate this may not be a satisfactory answer, but this is the best we can do with our limited resources. You would have to look at a hardware codec implementation yourself I'm afraid, and we cannot provide any official support for this work (but I am happy to answer some questions occasionally if I can be of any help).

**Comment by desto12** [comment]
Thank you very much! Good to know that there is no easy-solution, it helped us a lot because now we know how big problem it is.
