### ISSUE TITLE
Add event with ice connection state or onSuccess negotiation

### ISSUE THREAD

**Issue by eirikhollis** [microsoft/MixedReality-WebRTC#59]
It would be nice to either have the whole [iceConnectionState](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/iceConnectionState) log available as a separate event, or at least a _success_ event fired when iceConnectionState reaches Connected or Completed, and a _failed_ event when iceConnectionState reaches Failed or hangs indefinitely on Checking.

The current event _Connected_ in _PeerConnection_ is fired even though ice candidates are not correctly resolved. I test this by just commenting out the _AddIceCandidate_ method, thus never giving the peer connection any ice candidates to use.

Having these events will allow me to e.g.
- Reconnect internally/automatically to the specific peer that fails
- Develop UI that changes depending on if the peer is connecting vs connected
- Debug reasons why specific connections won't work
- Setup a stress-test, where I auto-reconnect a peer immediately after ice candidates are resolved (and then do this with 10 peers at the same time)

Speaking of Ice negotiation, would it be possible to open up for changing [Ice gathering settings,](https://developer.mozilla.org/en-US/docs/Web/API/RTCConfiguration) such as [_bundlePolicy_ ](https://developer.mozilla.org/en-US/docs/Web/API/RTCConfiguration#RTCBundlePolicy_enum)and [_iceTransportPolicy_](https://developer.mozilla.org/en-US/docs/Web/API/RTCConfiguration#RTCIceTransportPolicy_enum)?
E.g. in my situation, I only need Relay Ice Candidates (usually 1 or 2), and not the ~17 candidates given to me through the _IceCandidateReadytoSend_ event. 
This would be easily fixed by changing _iceTransportPolicy_ to Relay, instead I have to filter out the candidate if it contains the type "host".

**Comment by djee-ms** [comment]
As I understand in m71 the ICE connection start is not available : https://bugs.chromium.org/p/webrtc/issues/detail?id=6145
This is fixed in m73 : https://groups.google.com/forum/#!msg/discuss-webrtc/l0gc3RjBhc0/FsMqOlOSBwAJ

For the connection settings such as the bundle policy and transport policy, those are parameters on the `RTCConfiguration` so it seems easy enough to pass through.

**Comment by eirikhollis** [comment]
The ice connection state was available when I built against m71 on webrtc-uwp-sdk. I used the `OnIceConnectionStateChange` event:
```
PeerConnection.OnIceConnectionStateChange += PeerConnection_OnIceConnectionStateChange;
```
and then since the state is not sent with the event, I fetch it manually.
```
private void PeerConnection_OnIceConnectionStateChange()
{
   RTCIceConnectionState iceState = PeerConnection.IceConnectionState;

   // Do something with iceState
}
```

**Comment by djee-ms** [comment]
Added ICE-related settings with 1205e1f8ef5e39f65c4e56f919b353e39cbbbbfb. `PeerConnection` now takes a `PeerConnectionConfiguration` object for setup, which includes support for multiple ICE servers, each with its own set of URLs and its own credentials.

**Comment by djee-ms** [comment]
Added an `IceStateChanged` event which simply returns the value of the underlying enum, without transformation. This will probably lead to a breaking change down the road when upgrading to a standard-compliant milestone where the ICE state doesn't mix with the DTLS one, but we can review at that point.
