### ISSUE TITLE
Unity3D + Hololens 2: Unable to load DLL 'mrwebrtc.dll': The specified module could not be found

### ISSUE THREAD

**Issue by eshel** [microsoft/MixedReality-WebRTC#591]
When compiling a Unity3D app (v 2019.4.9f1) with the IL2CPP backend, then loading the built solution with VS2019 compiling and launching on HoloLens 2, I receive this error. The error is displayed on a small (barely visible) 'Development Console' window in the bottom-left corner of the deployed Unity3D/H2 app.

This happens with the latest version of the library (2.0.1). imported using the 'Scoped Registry' import method on unity described [here](https://microsoft.github.io/MixedReality-WebRTC/manual/unity/helloworld-unity-importwebrtc.html). Compilation in VS2019 to the Release/ARM64 architecture.

**Comment by TheRisenPhoenix** [comment]
I had the same issue ( #574), arm64 is unfortunately not yet supported.

**Comment by Jason-Chn95** [comment]
Take a look at this blog https://blog.csdn.net/qq_42419143/article/details/108771003

**Comment by eshel** [comment]
Performing these steps allowed my project to launch on a Hololens 2:

1. In *unity* build settings, select UWP / ARM as build target (not ARM64, not x64).
2. In *VS2019*, compilation should also be done in ARM configuration (not ARM64).
3. Disabled 'Graphics Jobs' (related to multi-core rendering), was necessary.

Thanks for the references!

**Comment by eshel** [comment]
The above steps have indeed resolved the issue when attempting to run MixedReality-WebRTC on H2. However, I've hit a wall when attempting to add-in Hololens 2's [Research Mode](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/research-mode) into the mix (which is the recommended way to access various CV cameras and sensors on the device). 

I have raised this in an issue in their repo [Hololens2ForCV#22](https://github.com/microsoft/HoloLens2ForCV/issues/22#issuecomment-704287460).

Thought I'd circle back here and document this here as well.
Any thoughts on the matter will be highly appreciated!

**Comment by djee-ms** [comment]
Where did you see Research Mode was "the recommended way"?
- It's in public preview
- It's only for non-published apps
- It's for accessing extra sensors beyond camera/microphone (or accessing other feeds like depth we never really tested with this project)

**Comment by eshel** [comment]
@djee-ms We are building a non-published app, for research purposes, which requires access to these extra sensors. Did not mean to imply this is the recommended way for all apps, merely for apps working with these extra cameras and sensors.

**Comment by agroenenberg** [comment]
@eshel did you manage to get it working? I only get the RM sensor data by downloading but am looking for a way to stream the data to my PC

**Comment by eshel** [comment]
> @eshel did you manage to get it working? I only get the RM sensor data by downloading but am looking for a way to stream the data to my PC
> 

Afraid not. Due to the circumstances we opted to not use this package alongside RM anymore.

**Comment by spacecheeserocks** [comment]
Just to be clear (this was mentioned further up) - you MUST build for **ARM** (**NOT ARM64**) for HoloLens 2.

There is no ARM64 version of the mrwebrtc available.

**Comment by idearbox** [comment]
WOW~
thanks guys~

@[eshel](https://github.com/eshel)
@[spacecheeserocks](https://github.com/spacecheeserocks)

I just solved my problem, **build ARM,  not ARM64** that's the key!
I just got my local web cam video on 3D object whit hologram objects


![image](https://user-images.githubusercontent.com/10637047/152736714-5eb25dff-fbec-46f8-8fb9-c41325920242.png)

![image](https://user-images.githubusercontent.com/10637047/152737402-844df9b4-2ec8-446a-8330-84949e5619a4.png)
Now log says "WebRTC plugin initialized successfully" !!

it works now~
