### ISSUE TITLE
.meta files of deleted .pdb files in the upm package

### ISSUE THREAD

**Issue by hanseuljun** [microsoft/MixedReality-WebRTC#592]
Thanks a lot for this wonderful piece of software. This is a total life saver for me.

Just one tiny thing is, version 2.0.1 for unity includes .meta files for .pdb files. Since unity considers upm packages from remote repositories as read-only, per each .meta file of a .pdb, they report two errors: one for the existence of it, and another for not being able to delete a read-only file.

While deletion of these .meta files may already make our lives even better than now, in the next release, if possible, I would like to have .pdb files as an option. For example, while I was yesterday having a trouble importing this package due to libwebrtc killing the process when there is an invalid audio input (or no permission for the microphone), it was hard to figure out the issue due to the lack of accessibility to the details of the error. I totally agree with your decision to not have the 100 megabytes includes in the package by default, but would like to see them somewhere if possible.

Again, thanks a lot for all this amazing work! While trying to debug the above bug yesterday and going through libwebrtc, I was really about to give up making my application work outside our lab.

**Comment by djee-ms** [comment]
Hi @hanseuljun,

Why was this issue closed? Is the .meta file issue happening or not?

**Comment by hanseuljun** [comment]
It is happening. I just closed this thinking it was too trivial.

**Comment by Orinion** [comment]
i also get them. The warnings get fired everytime the editor gains focus. They don't break anything and you can hide all warnings, however it makes finding other warnings hard. 
![grafik](https://user-images.githubusercontent.com/12730894/94594731-2128da80-028a-11eb-98fd-4fee279188e1.png)

**Comment by djee-ms** [comment]
Yes I agree this needs to be fixed.

**Comment by djee-ms** [comment]
Fixed in 2.0.2, just published.
