### ISSUE TITLE
H264 offer fails

### ISSUE THREAD

**Issue by mangolas** [microsoft/MixedReality-WebRTC#597]
**Describe the bug**

UWP Unity WebRTC (v2.0.1) running on Hololens 2 is not accepting the sent SDP which tries to send H264 video. Same setup with VP8 works.

I'm trying to forward H264 video through Android device to Hololens 2 with as little latency as possible. I haven't found a way for MR-WebRTC to accept given video directly and only workaround I have managed to get working is to decode H264 video in Android and encode it again as VP8. 

I'm running out of ideas on how to proceed with this.

The error in the logs is:
```
Cannot apply remote description: Value does not fall within the expected range.
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.WebRTC.Unity.<HandleConnectionMessageAsync>d__23:MoveNext()
System.Array:UnsafeStore(T[], Int32, T)
Microsoft.MixedReality.WebRTC.Unity.PeerConnection:HandleConnectionMessageAsync(SdpMessage)
``` 

**Expected behavior**

Accept offer or give more info of the reason given offer is rejected.

**SDP messages**

Failing offer
```
v=0
o=- 6496628148725528191 0 IN IP4 0.0.0.0
s=-
t=0 0
a=ice-options:trickle
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:FCW6kUVB+HUFYaqZg3sNML4ts/plBmGd
a=ice-pwd:RjjZ30BAsLvOxQJbrXFIxPaBkHeMLD+y
a=rtcp-mux
a=rtcp-rsize
a=sendrecv
a=rtpmap:96 H264/90000
a=rtcp-fb:96 nack pli
a=framerate:30
a=fmtp:96 packetization-mode=1;profile-level-id=42001f;sprop-parameter-sets=J0IAH41oBQBboQAAAwABAAADADwPEHqA,KM4ySA==
a=ssrc:986824225 msid:user3946240819@host-b212b7c0 webrtctransceiver0
a=ssrc:986824225 cname:user3946240819@host-b212b7c0
a=mid:video0
a=fingerprint:sha-256 D3:F7:4F:EC:6D:AB:0E:75:3F:18:F8:BC:E1:ED:69:B4:DA:77:85:6F:DF:AC:A9:88:5C:85:E0:F4:8C:0F:92:06
```

**Environment**

Remote video sender:
- Android
- GStreamer Webrtc v1.18

Hololens receiver:
 - MR-WebRTC version 2.0.1
 - Unity WSA Player (UWP)]
 - Architecture: ARM
 - Unity version: 2019.4.6
 - Target device: Hololens 2

**Additional context**

GStreamer gives these details about the original H264:
```
GST_EVENT gstevent.c:847:gst_event_new_caps: creating caps event 
video/x-h264, 
width=(int)960, 
height=(int)720, 
framerate=(fraction)30/1, 
chroma-format=(string)4:2:0, 
bit-depth-luma=(uint)8, 
bit-depth-chroma=(uint)8, 
parsed=(boolean)true, 
stream-format=(string)avc, 
alignment=(string)au, 
profile=(string)baseline, 
level=(string)3.1, 
codec_data=(buffer)0142001fffe100172742001f8d680f016e84000003000400000300f03c41ea01000428ce3248
```

**Comment by djee-ms** [comment]
Is that the same as #303? That one was Gstreamer sending some unsupported H.264 video profile that the underlying Google code used by MixedReality-WebRTC does not know how to handle.

**Comment by mangolas** [comment]
I'm not sure, I suppose it could be the same. 

So in order to get any more info about why the offer is rejected, is the only way to compile debug versions of dll's (via instructions given at https://microsoft.github.io/MixedReality-WebRTC/manual/building-windows.html)?

**Comment by fibann** [comment]
@mangolas yes. If you are lucky the debug logs might contain the reason why the stream is considered unsupported. If they don't you can try debugging `SetRemoteDescription` and look for the place where it is failing. Another thing you can try is tweaking the video capture (if supported) to use the ConstrainedBaseline profile, a lower level or different options.

**Comment by mangolas** [comment]
@fibann Thanks! I'll try to go that route and see if it provides more clues for the rejection reason.

**Comment by mangolas** [comment]
I managed to get the sdp offer accepted by manually changing `a=fmtp:96 packetization-mode=1;profile-level-id=42001f;sprop-parameter-sets=J0IAH41oBQBboQAAAwABAAADADwPEHqA,KM4ySA==` to `a=fmtp:96 packetization-mode=1;profile-level-id=42c01f`, so that is something.

Though the sent video plays very poorly on HL2, and not sure why is that, so investigating more about that. 

Nevertheless will close this issue, would be great if original profile-id would be accepted as it is, but I guess that's the matter of how underlying libraries work.

Anyway thanks for the good work!
