### ISSUE TITLE
LocalAudioTrack.AudioFrameReady event doesn't called.

### ISSUE THREAD

**Issue by koh1019** [microsoft/MixedReality-WebRTC#599]
I'm having trouble transferring audio.
At the Peerconnection on the receiving side, when checking the transferred data (frame.audioData) in the RemoteAudioTrack.AudioFrameReady event , its values are all zero.
At the PeerConnecrion on the sender side, I tried to check the status of the audio capture, LocalAudioTrack.AudioFrameReaqdy event never called.

I think I created a local audio track following the way of C# tutorial, but is there something wrong?

**[Local Side]**

	private AudioTrackSource _localAudioSource = null;
	private LocalAudioTrack _localAudioTrack = null;

	private async void CreateLocalAudioTrack(){
		LocalAudioDeviceInitConfig devconf = new LocalAudioDeviceInitConfig 
		{
			AutoGainControl = true
		};
		_localAudioSource = await DeviceAudioTrackSource.CreateAsync(devconf);

		LocalAudioTrackInitConfig trackconf = new LocalAudioTrackInitConfig
		{
		    trackName = "localTrack"
		};
		_localAudioTrack = LocalAudioTrack.CreateFromSource(_localAudioSource, trackconf);
		_localAudioTrack.AudioFrameReady += _localAudioTrack_AudioFrameReady;
	}

	private void _localAudioTrack_AudioFrameReady(AudioFrame frame)
	{
		Console.WriteLine("_localAudioTrack_AudioFrameReady");　// <= never called
	}

**[RemoteSide]**

    private void OnRemoteAudioTrackAdded(RemoteAudioTrack track)
    {
        track.AudioFrameReady += Track_AudioFrameReady;
    }

    private int counter = 0;
    private void Track_AudioFrameReady(AudioFrame frame)
    {
        ++counter;
        if (counter >= 100)
        {
            byte[] data = new byte[8];
            Marshal.Copy(frame.audioData, data, 0, 8);
            string dump = "";
            for (int i = 0; i < 4; i++)
            {
                dump += data[i].ToString("X2") + " ";
            }
            Console.WriteLine(dump);  // <= Always "00 00 00 00 00 00 00 00"

            counter = 0;
        }
    }

Because the official WebRTC samples and NAudio library can capture audio data correctly, I think there is no problem in audio device environment.
I would appreciate your help.

**Comment by djee-ms** [comment]
> LocalAudioTrack.AudioFrameReady event never called

It's by design, and we can't really do anything about it. The underlying Google code doesn't ever raise this event, therefore we cannot either.

Logged #600 because I can't find a reference in the docs about this; this should have been made prominently clear, sorry about that.

> when checking the transferred data (frame.audioData) in the RemoteAudioTrack.AudioFrameReady event , its values are all zero.

I've heard of other users having similar issues, but never actually reproduced that myself. The fact the callback is invoked at all is already a good sign; it means the connection is established. I would double-check things like the transceiver direction (send/recv) when the callback is called. There's unfortunately no good diagnostic statistics for this kind of issue, so not sure what else to suggest. @fibann any idea maybe?

**Comment by koh1019** [comment]
Thank you for your quick reply.

1. Transceiver Direction

	I checked the transceiver direction at AudioFrameReady event of the receiver side .

	**[Tranceiver Direction Check (RemoteSide - Track_AudioFrameReady event)]**
```
	int counter = 0;
	private void Track_AudioFrameReady(AudioFrame frame)
	{
	    ++counter;
	    if (counter == 100)
	    {
	        Console.WriteLine($"Transceiver Direction = {_remotetrack.Transceiver.NegotiatedDirection}");
	        counter = 0;
	    }
	}
```

	**[Result]**
	Transceiver Direction = ReceiveOnly
	Transceiver Direction = ReceiveOnly
	.........
	.........

2. Aditional question
	The AudioFrameReady event continues to be called on the receiver side, even if the sender side's PeerConnection is destroyed.
	Is it right operation, or strange?

3. Please let me know if you have any other point to check. I'll try to check It with my lacked skills.

**Comment by fibann** [comment]
@koh1019 what version of MR-WebRTC are you using? On what platform are you capturing audio (Windows or other, UWP or Win32, Unity or standalone)?

Note that released versions (including 2.0.x) have known issue #192 which involves silent audio when capturing in a Win32 application. This seemed to be a problem with the legacy ADM and has been changed by https://github.com/microsoft/MixedReality-WebRTC/commit/e839cd78859aa21f858839732e0f4f40d7178b20 which sets ADM 2 as the default. OTOH there have been reports of ADM 2 not capturing any sound where the legacy ADM works (#573). So depending on what version you are using, you might fix your issue by either using a version past e839cd78859aa21f858839732e0f4f40d7178b20 or forcing the legacy ADM at startup (see https://github.com/microsoft/MixedReality-WebRTC/issues/573#issuecomment-690963138).

**Comment by koh1019** [comment]
Thank you for your reply, and I'm sorry for the lack of information.

**[My environment]**
Windows10 Pro 64bit
Windows forms Application (.NET Frame work 4.8) (C #)
MR-WebRTC Version 2.0.2 (from Nuget package manager)

I tried to changed 'UseAudioDeviceModule' to 'Legacy', but it didn't show up that property in Intellisense.
![intellisense](https://user-images.githubusercontent.com/32283170/94919973-5afb1a80-04f0-11eb-8e69-99f5fd08229c.png)


By pressing F12 to show the metadata of Legacy class, I found the information below.

**[VS2019 Library metadeta]**
```
#region Assemply Microsoft.MixedReality.WebRTC, Version = 0.1.0.0, Culture = neutral, PublicKeyToken = null
 C: \ develop \ projects \ RemoteDiagnosis \ RemoteDiagnosisSolution \ packages \ Microsoft.MixedReality.WebRTC.2.0.2 \ lib \ netstandard2.0 \ Microsoft.MixedReality.WebRTC.dll
#endregion
```
![metadata](https://user-images.githubusercontent.com/32283170/94919988-60f0fb80-04f0-11eb-9365-1c84cbab328e.png)

Is it not referenced correctly?

**Comment by fibann** [comment]
See previous comment - at the moment this feature is not in any of the released packages, but only on the master branch. You will have to checkout the master branch and build MR-WebRTC from source (guide [here](https://microsoft.github.io/MixedReality-WebRTC/manual/building.html)).

**Comment by koh1019** [comment]
Thank you for your advice.
I built it from the source code of the master branch and checked the operation, and it worked fine.

I am currently trying to develop an SFU/MCU server.

I'm looking for a server side mechanism to transfer Audio Data received from client to other peers, and looking forward to ExternalAudioTrackSource ([# 345](https://github.com/microsoft/MixedReality-WebRTC/issues/345)).

**Comment by fibann** [comment]
Glad to know that worked!
