### ISSUE TITLE
Help getting in band data channel to negotiate with Janus

### ISSUE THREAD

**Issue by rygo6-MS** [microsoft/MixedReality-WebRTC#602]
I am trying to get MRWebRTC to negotiate a data channel to Janus WebRTC Gateway. 

Currently my Janus server negotiates media and data from [SimplePeer](https://github.com/feross/simple-peer/) without issue. Janus reports this in its log, stating the media and data channels have been negotiated successfully.

The negotiation from MRWebRTC ends up successfully establishing the video and audio. But, Janus does not report the data channel negotiated successfully, and the `Peer.DataChannelAdded` callback is never fired from MRWebRTC .

Comparing these two sources, the only thing I notice is that the data channel SDP going to MRWebRTC looks like this:
`a=sctpmap:5000 webrtc-datachannel 1024`
Where as the data channel sdp going to SimplePeer looks like this:
`m=application 9 UDP/DTLS/SCTP webrtc-datachannel`

Janus also reports that SimplePeer is using what it calls "new-datachan-sdp", whereas MRWebRTC is not. Looking into this it looks like the sdp format for data channels changed a few years ago. 

Is the issue with MRWebRTC related to Janus trying to use the 'old' data channel SDP? Does MRWebRTC not support the old format? 

Or am I missing something else here? I assume if I am trying to negotiate an in-band data channel, then when the data channel is created it should just be created on the MRWebRTC side, and `Peer.DataChannelAdded` should be called, is that correct? Or is there some additional set up I need to do on the MRWebRTC side.

**Comment by djee-ms** [comment]
I don't know of any old/new data channel. MixedReality-WebRTC via Google's WebRTC (m71) uses `m=application`. If you don't see this in the SDP offer/answer then the data channel was not negotiated correctly.

`a=sctpmap` is an additional attribute; that alone does not define a data channel. It should always be accompanied with an `m=application` line preceding it.
https://stackoverflow.com/questions/31666531/understanding-sdp-generated-by-webrtc

**Comment by rygo6-MS** [comment]
Found the solution. For future seekers. MRWebRTC can negotiate both SDP formats of data channels just. This was a nuance of WebRTC backend Janus. It was designed to not open in-band data channels on connecting clients unless the client has a data channel already added by itself.

**Comment by kspark-scott** [comment]
I am trying to do something similar and have not yet got it working.  @rygo6-MS, do you still recall some of the details?  For example:
- How do you control the SDP format for data channel, and which one was interoperable with Janus?
- Were you using the VideoRoom plugin for Janus, or a different one?  Each plugin handles data channels somewhat differently.

I am trying to use the VideoRoom plugin with in-band data channels.  The SDP offer and answer for the publisher connection contains the m=application section, Janus logging confirms that the data channel is negotiated, and the inbound messages sent through this publication connection are received and processed by Janus.  In particular, Janus finds the configured data stream for the negotiated data channel ID.

It is the subscriber connection I am struggling with.  I subscribe to all streams for each publisher, which includes the data stream.  Again the SDP includes m=application sections, but the PeerConnection.DataChannelAdded event is not fired as it is for in-band channels in a P2P connection.

Are my expectations right, that DataChannelAdded should fire for subscriber connections?
Was there a specific step or adjustment required for you to get that part of the negotiation process working?

**Comment by zhuisa** [comment]
@rygo6-MS hi, I'm sorry to have bothered you. I also want to estalish Mixed-Reality-WebRTC with Janus,  in order that I can establish one to more PeerConnection.  But I don't kwon hao to do it. Can you give some help.
