### ISSUE TITLE
[UWP] PeerConnection message ready to send never called

### ISSUE THREAD

**Issue by benjamincoven** [microsoft/MixedReality-WebRTC#606]
**Describe the bug**
Hello, I am following the documentation for a UWP application. However I never receive POST message on dss, only GET polling. I added a breakpoint to my two `PeerConnection.LocalSdpReadytoSend` and `PeerConnection.IceCandidateReadytoSend` but they are never hitted. I did not understand eveything, and I am not sure on what condition these events have to be executed. I have a webcam on my device and I could initialize a video and an audio track. Thank you very much.

**Environment**
 - Platform: UWP
 - Architecture: x86 on Windows
 - Target device:Windows Desktop for testing then HoloLens 2

**Comment by Orinion** [comment]
Do you call CreateOffer?

**Comment by benjamincoven** [comment]
No I did not. I missed it in the documentation. Thank you very much and sorry for the issue.
