### ISSUE TITLE
How to use GetSimpleStatsAsync?

### ISSUE THREAD

**Issue by dyhmichail** [microsoft/MixedReality-WebRTC#607]
Hello, I can't find information about how can I get info about the current connection? Something like resolution, framerate, and so on.
I tried to use GetSimpleStatsAsync
```
            var statsReport = PeerConnection.Peer.GetSimpleStatsAsync();
            statsReport.ContinueWith(_ =>
            {
                foreach (var result in statsReport.Result.GetStats<WebRTC.PeerConnection.StatsReport>())
                {
                    Debug.Log(result);
                }
            });
```
There is nothing in logs. Or maybe I'm doing wrong? Is there any example of using GetSimpleStatsAsync?

Please help.

**Comment by hirschi81** [comment]
This is by no means pretty, but maybe this will help:
<code>
 PeerConnection.StatsReport sp = await lehrerConnection.GetSimpleStatsAsync();                    
                    
                    IEnumerable<PeerConnection.TransportStats> transStats = sp.GetStats<PeerConnection.TransportStats>();
                    ulong v1, v2;
                    using (var sequenceEnum = transStats.GetEnumerator())
                    {
                        while (sequenceEnum.MoveNext())
                        {
                            v1 = sequenceEnum.Current.BytesReceived;
                            v2 = sequenceEnum.Current.BytesSent;
                            _logger.LogInformation("Transport: BR: \t" + v1 + "   BS: \t" + v2);
                        }
                    }
</code>

**Comment by dyhmichail** [comment]
> This is by no means pretty, but maybe this will help:
> 
> PeerConnection.StatsReport sp = await myConnection.GetSimpleStatsAsync();
> IEnumerable transStats = sp.GetStats();
> ulong v1, v2;
> using (var sequenceEnum = transStats.GetEnumerator())
> {
>      while (sequenceEnum.MoveNext())
>      {
>          v1 = sequenceEnum.Current.BytesReceived;
>          v2 = sequenceEnum.Current.BytesSent;
>          _logger.LogInformation("Transport: BR: \t" + v1 + "   BS: \t" + v2);
>      }
> }

Sorry, but it's not works. There is an error at sp.GetStats();
![image](https://user-images.githubusercontent.com/15686923/96584474-f1984b80-12e6-11eb-9fa8-fe79635754e4.png)

**Comment by hirschi81** [comment]
Sorry, but Github swallowed parts of my example code. Since I'm new on this platform, these mistakes unfortunately happen. ;)

<code><T></code> has to be specified. Here is a example for the transport statistics:
<code>IEnumerable<PeerConnection.TransportStats> transStats = sp.GetStats<PeerConnection.TransportStats>();</code>

**Comment by dyhmichail** [comment]
> Sorry, but Github swallowed parts of my example code. Since I'm new on this platform, these mistakes unfortunately happen. ;) I corrected my first comment. But just to be sure:
> 
> `<T>` has to be specified. Here is a example for the transport statistics:
> `IEnumerable<PeerConnection.TransportStats> transStats = sp.GetStats<PeerConnection.TransportStats>();`

Yes, thx, It's much more than nothing and may help a lot.
