### ISSUE TITLE
SetRemoteDescriptionAsync cause Value does not fall within the expected range exception

### ISSUE THREAD

**Issue by Qualcuno** [microsoft/MixedReality-WebRTC#610]
Hi.
I am setting up a communication between a Hololens peer and an SFU server. Communication happens in this steps:

1 The SFU server sends the offer sdp to Hololens,
2 Hololens responds with his sdp answer,
3 The SFU server sends a new offer with the updated ssrc ( becouse offer add sources in a second moment ).

So i call the method `SetRemoteDescriptionAsync ` 2 times. 
The first time is at the first offer and everything works fine.
But the second time i call it when i get the second offer and here i get the exception `Value does not fall within the expected range`.

What's wrong with the second offer?

<details open><summary>First offer message</summary>
<code>
v=0
o=- 1603712581697 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
m=audio 1 RTP/SAVPF 111 103 104 126
c=IN IP4 0.0.0.0
a=rtcp:1 IN IP4 0.0.0.0
a=ice-ufrag:7hd4f1elibfvt8
a=ice-pwd:7d5pplc95e1t23dsdgg182asrl
a=fingerprint:sha-256 68:D4:EA:00:84:1C:5B:F6:BC:1D:98:B8:AF:1A:7F:87:22:34:FD:5D:82:AF:FD:19:3B:50:D5:DF:E9:3D:11:47
a=setup:actpass
a=mid:audio
a=candidate:1 1 udp 2130706431 10.156.15.203 10000 typ host generation 0
a=candidate:2 1 udp 1694498815 34.107.6.190 10000 typ srflx raddr 10.156.15.203 rport 10000 generation 0
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10; useinbandfec=1
a=rtcp-fb:111 transport-cc
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:126 telephone-event/8000
a=rtcp-fb:* transport-cc
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=ssrc:2465937035 cname:mixed
a=ssrc:2465937035 label:mixedlabelaudio0
a=ssrc:2465937035 msid:mixedmslabel mixedlabelaudio0
a=ssrc:2465937035 mslabel:mixedmslabel
m=video 1 RTP/SAVPF 100 107 101 96 97 99
c=IN IP4 0.0.0.0
a=rtcp:1 IN IP4 0.0.0.0
a=ice-ufrag:7hd4f1elibfvt8
a=ice-pwd:7d5pplc95e1t23dsdgg182asrl
a=fingerprint:sha-256 68:D4:EA:00:84:1C:5B:F6:BC:1D:98:B8:AF:1A:7F:87:22:34:FD:5D:82:AF:FD:19:3B:50:D5:DF:E9:3D:11:47
a=setup:actpass
a=mid:video
a=candidate:1 1 udp 2130706431 10.156.15.203 10000 typ host generation 0
a=candidate:2 1 udp 1694498815 34.107.6.190 10000 typ srflx raddr 10.156.15.203 rport 10000 generation 0
a=sendrecv
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=fmtp:100 x-google-start-bitrate=800
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 transport-cc
a=rtpmap:107 H264/90000
a=fmtp:107 x-google-start-bitrate=800; profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1;
a=rtcp-fb:107 ccm fir
a=rtcp-fb:107 nack
a=rtcp-fb:107 nack pli
a=rtcp-fb:107 transport-cc
a=rtpmap:101 VP9/90000
a=fmtp:101 x-google-start-bitrate=800
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 transport-cc
a=rtpmap:96 rtx/90000
a=fmtp:96 apt=100
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=101
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=107
a=rtcp-fb:* ccm fir
a=rtcp-fb:* nack
a=rtcp-fb:* nack pli
a=rtcp-fb:* transport-cc
a=rtcp-fb:* ccm fir
a=rtcp-fb:* nack
a=rtcp-fb:* nack pli
a=rtcp-fb:* transport-cc
a=rtcp-fb:* ccm fir
a=rtcp-fb:* nack
a=rtcp-fb:* nack pli
a=rtcp-fb:* transport-cc
a=rtcp-fb:* ccm fir
a=rtcp-fb:* nack
a=rtcp-fb:* nack pli
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=ssrc:3173912414 cname:mixed
a=ssrc:3173912414 label:mixedlabelvideo0
a=ssrc:3173912414 msid:mixedmslabel mixedlabelvideo0
a=ssrc:3173912414 mslabel:mixedmslabel
</code>
</details>
<details open><summary>Second offer message</summary>
<code>
 v=0
o=- 1603712581697 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
m=audio 1 RTP/SAVPF 111 103 104 126
c=IN IP4 0.0.0.0
a=rtcp:1 IN IP4 0.0.0.0
a=ice-ufrag:7hd4f1elibfvt8
a=ice-pwd:7d5pplc95e1t23dsdgg182asrl
a=fingerprint:sha-256 68:D4:EA:00:84:1C:5B:F6:BC:1D:98:B8:AF:1A:7F:87:22:34:FD:5D:82:AF:FD:19:3B:50:D5:DF:E9:3D:11:47
a=setup:actpass
a=mid:audio
a=candidate:1 1 udp 2130706431 10.156.15.203 10000 typ host generation 0
a=candidate:2 1 udp 1694498815 34.107.6.190 10000 typ srflx raddr 10.156.15.203 rport 10000 generation 0
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10; useinbandfec=1
a=rtcp-fb:111 transport-cc
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:126 telephone-event/8000
a=rtcp-fb:* transport-cc
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=ssrc:2465937035 cname:mixed
a=ssrc:2465937035 label:mixedlabelaudio0
a=ssrc:2465937035 msid:mixedmslabel mixedlabelaudio0
a=ssrc:2465937035 mslabel:mixedmslabel
a=ssrc:2135030752 cname:CP8aHk6b27Ewtp-6
a=ssrc:2135030752 msid:94cc2474-5b27-4b76-9bd1-c03c408e5752-6 ae636ca5-c0a8-416d-a9e3-7d9e72370a4f-6
m=video 1 RTP/SAVPF 100 107 101 96 97 99
c=IN IP4 0.0.0.0
a=rtcp:1 IN IP4 0.0.0.0
a=ice-ufrag:7hd4f1elibfvt8
a=ice-pwd:7d5pplc95e1t23dsdgg182asrl
a=fingerprint:sha-256 68:D4:EA:00:84:1C:5B:F6:BC:1D:98:B8:AF:1A:7F:87:22:34:FD:5D:82:AF:FD:19:3B:50:D5:DF:E9:3D:11:47
a=setup:actpass
a=mid:video
a=candidate:1 1 udp 2130706431 10.156.15.203 10000 typ host generation 0
a=candidate:2 1 udp 1694498815 34.107.6.190 10000 typ srflx raddr 10.156.15.203 rport 10000 generation 0
a=sendrecv
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=fmtp:100 x-google-start-bitrate=800
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 transport-cc
a=rtpmap:107 H264/90000
a=fmtp:107 x-google-start-bitrate=800; profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1;
a=rtcp-fb:107 ccm fir
a=rtcp-fb:107 nack
a=rtcp-fb:107 nack pli
a=rtcp-fb:107 transport-cc
a=rtpmap:101 VP9/90000
a=fmtp:101 x-google-start-bitrate=800
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 transport-cc
a=rtpmap:96 rtx/90000
a=fmtp:96 apt=100
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=101
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=107
a=rtcp-fb:* ccm fir
a=rtcp-fb:* nack
a=rtcp-fb:* nack pli
a=rtcp-fb:* transport-cc
a=rtcp-fb:* ccm fir
a=rtcp-fb:* nack
a=rtcp-fb:* nack pli
a=rtcp-fb:* transport-cc
a=rtcp-fb:* ccm fir
a=rtcp-fb:* nack
a=rtcp-fb:* nack pli
a=rtcp-fb:* transport-cc
a=rtcp-fb:* ccm fir
a=rtcp-fb:* nack
a=rtcp-fb:* nack pli
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=ssrc:3173912414 cname:mixed
a=ssrc:3173912414 label:mixedlabelvideo0
a=ssrc:3173912414 msid:mixedmslabel mixedlabelvideo0
a=ssrc:3173912414 mslabel:mixedmslabel
a=ssrc-group:FID 2405092774 36120482
a=ssrc:2405092774 cname:CP8aHk6b27Ewtp-6
a=ssrc:2405092774 msid:f5d176c3-ce31-46e2-88e5-399e9282478d-6 8cbaf0e2-437b-4c9d-9717-34acb56a339e-6
a=ssrc:36120482 cname:CP8aHk6b27Ewtp-6
a=ssrc:36120482 msid:f5d176c3-ce31-46e2-88e5-399e9282478d-6 8cbaf0e2-437b-4c9d-9717-34acb56a339e-6
</code>
</details>

**Environment**
 - MR-WebRTC 2.0
 - Platform: Unity Editor in UWP platform
 - Architecture: Unity Editor is x64 on Windows
 - Unity version (if applicable): [e.g. 2018.4, 2019.1]
 - Target device: UWP - Hololens

**Comment by fibann** [comment]
The second offer is trying to stream a H.264 video, and H.264 encoding/decoding is not currently supported on Win32 (so in the Unity editor). If you want to stream to/from your project running in the Unity editor you will need to temporarily switch to VP8. H.264 will work fine on the deployed UWP app.

It's unfortunate that the error message is so generic (the "value" is H.264 and it is "out of range" because the only supported value is VP8) but this is what the WebRTC implementation returns!
