### ISSUE TITLE
Cannot clone repo

### ISSUE THREAD

**Issue by sundarhigher** [microsoft/MixedReality-WebRTC#613]
Cloning on windows with recursive fails!

Cloning into 'C:\mr-webrtc'...
remote: Enumerating objects: 160, done.
remote: Counting objects: 100% (160/160), done.
remote: Compressing objects: 100% (125/125), done.
remote: Total 18478 (delta 83), reused 63 (delta 33), pack-reused 18318
Receiving objects: 100% (18478/18478), 29.08 MiB | 1.46 MiB/s, done.
Resolving deltas: 100% (15007/15007), done.
Submodule 'external/webrtc-uwp-sdk' (https://github.com/webrtc-uwp/webrtc-uwp-sdk.git) registered for path 'external/webrtc-uwp-sdk'
Cloning into 'C:/mr-webrtc/external/webrtc-uwp-sdk'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 2020 (delta 16), reused 21 (delta 9), pack-reused 1991
Receiving objects: 100% (2020/2020), 231.21 KiB | 420.00 KiB/s, done.
Resolving deltas: 100% (992/992), done.
fatal: remote error: upload-pack: not our ref d07b52bc3cc5ea0eb41ae738b018e48043ce4d8f
Fetched in submodule path 'external/webrtc-uwp-sdk', but it did not contain d07b52bc3cc5ea0eb41ae738b018e48043ce4d8f. Direct fetching of that commit failed.
PS C:\Users\Sundar> git clone --recursive https://github.com/microsoft/MixedReality-WebRTC.git -b master C:\mr-webrtc
Cloning into 'C:\mr-webrtc'...
remote: Enumerating objects: 160, done.
remote: Counting objects: 100% (160/160), done.
remote: Compressing objects: 100% (125/125), done.
remote: Total 18478 (delta 83), reused 63 (delta 33), pack-reused 18318
Receiving objects: 100% (18478/18478), 29.08 MiB | 2.01 MiB/s, done.
Resolving deltas: 100% (15008/15008), done.
Submodule 'external/webrtc-uwp-sdk' (https://github.com/webrtc-uwp/webrtc-uwp-sdk.git) registered for path 'external/webrtc-uwp-sdk'
Cloning into 'C:/mr-webrtc/external/webrtc-uwp-sdk'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 2020 (delta 16), reused 21 (delta 9), pack-reused 1991
Receiving objects: 100% (2020/2020), 231.21 KiB | 412.00 KiB/s, done.
Resolving deltas: 100% (992/992), done.
fatal: remote error: upload-pack: not our ref d07b52bc3cc5ea0eb41ae738b018e48043ce4d8f
Fetched in submodule path 'external/webrtc-uwp-sdk', but it did not contain d07b52bc3cc5ea0eb41ae738b018e48043ce4d8f. Direct fetching of that commit failed.

**Comment by fibann** [comment]
Thanks for reporting, repos got out of sync due to some mishap. Should be fixed by a8948e5b1144c61a2dd9ed01d2749ba0add59386.
