### ISSUE TITLE
Using local VP8 compressed video file instead of raw camera stream?

### ISSUE THREAD

**Issue by hirschi81** [microsoft/MixedReality-WebRTC#614]
Instead of a video stream coming from a camera, I want to use a local video file.
My idea was to use [ExternalVideoTrackSource](https://microsoft.github.io/MixedReality-WebRTC/api/Microsoft.MixedReality.WebRTC.ExternalVideoTrackSource.html) with the CustomI420AFrameCallback function for every frame in order to stream random video data, as you did in [your testing routines](https://github.com/microsoft/MixedReality-WebRTC/blob/master/tests/Microsoft.MixedReality.WebRTC.Tests/VideoTrackSourceTests.cs). I might be able to provide the video data as I420AVideoFrame but this makes me uneasy for two reasons:
1. VP8 is a mandatory video codec for WebRTC non-browsers [[Link]](https://tools.ietf.org/html/rfc7742#section-5)
2. I'm able to encode my local video file in VP8 as a preprocessing step via FFMPEG.

My understanding is, that there should be a way to just send VP8 frames as local videotrack to other peers, without having to encode the whole thing. Do you have any inkling how I can use the compressed frames instead of the raw I420 frames. This way there would be nearly no processing, because it's only relaying VP8 frames from the file. Processing all in a raw format would mean approx. 100 times more data to handle and doing decoding and encoding on top of it.

Maybe  a new video frame struct like IVP8VideoFrame is the way to go?

**Comment by fibann** [comment]
It's possible in theory, but far from trivial to implement. The WebRTC implementation we use only supports a handful of input frame types (all uncompressed) out of the box. It has an option to pass opaque "native" frames, but I think that requires adding your own encoder to the WebRTC code that handles native frames and passes them through (plus all the work necessary at SDP-level to match your encoder to VP8 decoders). So I wouldn't recommend it unless the decoding and re-encoding overhead is a blocker for your application.
