### ISSUE TITLE
The video screen displays all layer levels, how can it only display a fixed level of gameobject

### ISSUE THREAD

**Issue by qazqaz12378** [microsoft/MixedReality-WebRTC#623]
The video screen shows all layer levels, how can it be the same as Camera cullingMask?
![image](https://user-images.githubusercontent.com/4353931/98798576-edeb7680-2405-11eb-81d7-b54394ce30fc.png)
hideModel does not show
This is because I opened the PV camera, this will render all layers

**Comment by fibann** [comment]
This seems a Unity issue/question rather than being related to MR-WebRTC.
