### ISSUE TITLE
[Question] SetRemoteDescriptionAsync cause Value does not fall within the expected range exception on sparse request

### ISSUE THREAD

**Issue by codymartin2005** [microsoft/MixedReality-WebRTC#626]
Hello,

I have a fairly simple unity project I'm hoping to convert over to MR-WebRTC that includes a small webrtc connect script and websocket signal server.

On connected when attempting the "SetRemoteDescriptionAsync" I get the "value does not fall within the expected range exception". I've seen others mention h264, but in this case I'm only using a connect with a single data channel(required by my backend--an audio transceiver will come later).
 
First attempt, no transceiver:

Offer 
`
v=0\r\no=- 2565041824535602967 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic: WMS local_av_stream\r\nm=application 9 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:CPYI\r\na=ice-pwd:7IVXnqYrDK6SywZZsij/I/Gb\r\na=ice-options:trickle\r\na=fingerprint:sha-256 2A:1D:86:0A:4D:C0:F6:32:89:0D:FD:68:05:80:52:F2:50:6D:CA:B2:59:AB:40:64:2A:09:83:56:DF:E5:08:1D\r\na=setup:actpass\r\na=mid:0\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n`

Answer 
`v=0\r\no=- 1605875536352919 1 IN IP4 172.19.0.2\r\ns=AudioBridge 2\r\nt=0 0\r\na=group:BUNDLE\r\na=msid-semantic: WMS janus\r\nm=application 0 DTLS/SCTP 0\r\nc=IN IP4 172.19.0.2\r\na=inactive\r\n`

All of the sdp events fire and the ice candidates even get sent over after this, however the "Connected" event never occurs (I believe because of the above).

Any ideas on how to resolve this?

Thanks
Cody

Environment

MR-WebRTC 2.0
Platform: Unity Editor in UWP platform
Architecture: Unity Editor is x64 on Windows
Unity version (if applicable): 2020.1.13f1
Target device: Standalone Player

**Comment by codymartin2005** [comment]
After pull the repo and compiling I was able to see the issue had to the do with the difference in the sdp offer/answer m-lines.

I'm not able to offer/answer successfully and working on the ICE functionality.

**Comment by fibann** [comment]
> the issue had to the do with the difference in the sdp offer/answer m-lines

What difference exactly?

**Comment by codymartin2005** [comment]
The Janus server was dropping the data channel in the response. This caused the "difference in m-lines" message to be thrown.
