### ISSUE TITLE
Android platform architecture 

### ISSUE THREAD

**Issue by Dav151** [microsoft/MixedReality-WebRTC#635]
Hello,

The architecture for UWP and desktop is clear on the "overall architecture" diagram:
C# App call "Microsoft.MixedReality.WebRTC" (c#) --> call "mrwebrtc"(c/c++) ---> call "google libwebrtc" (windows SDK c/c++)

for android, I am sure which cases below is correct?
**Case 1:**
C# App call "Microsoft.MixedReality.WebRTC" (c#) --> call "mrwebrtc"(c/c++) ---> call "google libwebrtc" (java and jni) --> call "google libwebrtc" (NDK c/c++)

**Case 2:**
C# App call "Microsoft.MixedReality.WebRTC" (c#) --> call "mrwebrtc"(c/c++) ---> call "google libwebrtc" (NDK c/c++)

As I see under \MixedReality-WebRTC-release-2.0\MixedReality-WebRTC-release-2.0\libs\unity\library\Runtime\Scripts\Android.cs
The code call  AndroidJavaClass webrtcClass = new AndroidJavaClass("org.webrtc.PeerConnectionFactory"); to initialize the under layer java class

If case 1 is correct, which folder contains the code (mrwebrtc, call java API from C/C++) 

Thanks
Dav

**Comment by fibann** [comment]
It's basically "2", but there are some places where we call the Java/JNI API for things like initialization (like you noticed) or device management. See also the code in tools\build\android\webrtc-native.
