### ISSUE TITLE
 C# tutorial is out of date.

### ISSUE THREAD

**Issue by SID9-HoneyBee** [microsoft/MixedReality-WebRTC#640]
In the "Createing A Project" session of the C# tutorial

List<VideoCaptureDevice> deviceList =
        await DeviceVideoTrackSource.GetCaptureFormatsAsync();

Throws an error.

IReadOnlyList<VideoCaptureDevice> deviceList =
                    await DeviceVideoTrackSource.GetCaptureDevicesAsync();

Isn't this a better way to do it?

I am newly learning.

If you follow the tutorial
I keep getting a debugging window.

Could you give me a hint on how to fix it?

![image](https://user-images.githubusercontent.com/76090330/102844822-981bdc80-444f-11eb-8329-2953680034e3.png)

![image](https://user-images.githubusercontent.com/76090330/102845091-1d06f600-4450-11eb-8922-06bb9d793ee8.png)

**Comment by fibann** [comment]
There was a section of the tutorial that had that problem but it has been fixed IIRC, can you clarify what file it is and what version?

The crash you are having seems to be in native code, you can get more information about it by enabling native debugging before launching your project from Visual Studio. This will show you the callstack where the error is happening and hopefully narrow down the issue.

**Comment by SID9-HoneyBee** [comment]
https://microsoft.github.io/MixedReality-WebRTC/manual/cs/helloworld-cs-setup-uwp.html

You can check it here.

`private async void OnLoaded(object sender, RoutedEventArgs e)
{
    // Request access to microphone and camera
    var settings = new MediaCaptureInitializationSettings();
    settings.StreamingCaptureMode = StreamingCaptureMode.AudioAndVideo;
    var capture = new MediaCapture();
    await capture.InitializeAsync(settings);

    // Retrieve a list of available video capture devices (webcams).
    **List<VideoCaptureDevice> deviceList =
        await DeviceVideoTrackSource.GetCaptureFormatsAsync();** 

    // Get the device list and, for example, print them to the debugger console
    foreach (var device in deviceList)
    {
        // This message will show up in the Output window of Visual Studio
        Debugger.Log(0, "", $"Webcam {device.name} (id: {device.id})\n");
    }
}`

**Comment by djee-ms** [comment]
Yes this needs to be fixed to use `IReadOnlyList<>` instead of `List<>`. I thought we had fixed them all, good catch!

**Comment by djee-ms** [comment]
Turns out this was already fixed : https://github.com/microsoft/MixedReality-WebRTC/commit/39939b60a35f2cf0bc7036dc8dcd3d11ed97a96d
But for some reason CI didn't regenerate the docs.

**Comment by djee-ms** [comment]
I've forced CI to run, the docs are now correct.
