### ISSUE TITLE
Use of CustomVideoSource

### ISSUE THREAD

**Issue by astaikos316** [microsoft/MixedReality-WebRTC#648]
**Describe the bug**
This relates to #450 that I opened several months ago.  I was finally able to get ARFoundation video frames to pass to ARGB32FeedMaterial on an Android tablet using XRCpuImages API available in ARFoundation.  When trying to run a test call using this video as the source in a custom scene set up running an ARFoundation app with WebRTC (I have added PeerConnection, local and remote video and audio components and NodeDSS signaling to the custom scene) and the VideoChatDemo scene running in the Unity Editor on my Windows machine, I have come across the problem that when starting the call, I see the offer messages leave the Windows machine and they arrive on the Android tablet, but the Android tablet does not send out an Answer message upon receipt.  I also tried starting the call on the Android side and see the offer and candidate messages arrive on the Windows editor side, but not answer messages are created and sent.  I went back and built the VideoChatDemo scene for Android and loaded it on the same tablet I am using and that works without any issues.  Is there something special that I need to add to the CustomVideoSource I am trying to use to make the call function correctly?  Am I missing a function call? I made sure NodeDSS gameobject is configured correctly on both sides.  No errors are reported on either side and when running the Android app with debugging through Android Studio, there is no errors or crashes that point me to any direction.

**Expected behavior**
Using a CustomVideoSource from an Android tablet running ARFoundation, should be able to start a call with a remote Windows device running the VideoChatDmeo scene with audio and video flowing bi-directionally.   

**SDP messages**
These are the SDP messages using my customvideosource on android tablet to windows unity editor peer:

dss:body {"MessageType":3,"Data":"candidate:211232335 1 udp 2122129151 172.16.80.1 55248 typ host generation 0 ufrag NmdR network-id 3|0|0","IceDataSeparator":"|"} +0ms
  dss POST /data/android 200 - - 5.864 ms +387ms
  dss:body {"MessageType":3,"Data":"candidate:1002984303 1 udp 2121998079 192.168.1.24 55250 typ host generation 0 ufrag NmdR network-id 5 network-cost 10|0|0","IceDataSeparator":"|"} +6ms
  dss POST /data/android 200 - - 3.101 ms +4ms
  dss:body {"MessageType":3,"Data":"candidate:3054232416 1 udp 2122194687 169.254.80.80 55247 typ host generation 0 ufrag NmdR network-id 2|0|0","IceDataSeparator":"|"} +4ms
  dss POST /data/android 200 - - 2.703 ms +6ms
  dss:body {"MessageType":3,"Data":"candidate:3054232416 1 udp 2122194687 169.254.80.80 55252 typ host generation 0 ufrag NmdR network-id 2|1|1","IceDataSeparator":"|"} +5ms
  dss POST /data/android 200 - - 1.166 ms +3ms
  dss:body {"MessageType":3,"Data":"candidate:3257970329 1 udp 2122260223 172.24.192.1 55251 typ host generation 0 ufrag NmdR network-id 1|1|1","IceDataSeparator":"|"} +2ms
  dss POST /data/android 200 - - 1.393 ms +3ms
  dss:body {"MessageType":3,"Data":"candidate:3257970329 1 udp 2122260223 172.24.192.1 55246 typ host generation 0 ufrag NmdR network-id 1|0|0","IceDataSeparator":"|"} +3ms
  dss POST /data/android 200 - - 1.072 ms +3ms
  dss:body {"MessageType":3,"Data":"candidate:4091847356 1 udp 2122063615 169.254.123.7 55254 typ host generation 0 ufrag NmdR network-id 4|1|1","IceDataSeparator":"|"} +3ms
  dss POST /data/android 200 - - 10.407 ms +12ms
  dss:body {"MessageType":3,"Data":"candidate:1002984303 1 udp 2121998079 192.168.1.24 55255 typ host generation 0 ufrag NmdR network-id 5 network-cost 10|1|1","IceDataSeparator":"|"} +13ms
  dss POST /data/android 200 - - 1.269 ms +3ms
  dss:body {"MessageType":3,"Data":"candidate:211232335 1 udp 2122129151 172.16.80.1 55253 typ host generation 0 ufrag NmdR network-id 3|1|1","IceDataSeparator":"|"} +3ms
  dss POST /data/android 200 - - 1.531 ms +3ms
  dss:body {"MessageType":3,"Data":"candidate:4091847356 1 udp 2122063615 169.254.123.7 55249 typ host generation 0 ufrag NmdR network-id 4|0|0","IceDataSeparator":"|"} +4ms
  dss POST /data/android 200 - - 5.049 ms +8ms
  dss:body {"MessageType":1,"Data":"v=0\r\no=- 4768719655932440219 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic: WMS\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:NmdR\r\na=ice-pwd:jcpB4u+AFtwPNy+7U2VKbD4e\r\na=ice-options:trickle\r\na=fingerprint:sha-256 69:5C:6F:D3:0A:AD:0E:7C:5E:96:FF:5D:1E:22:EC:A9:F7:3A:E2:74:85:7B:CE:2C:29:A1:2C:2C:21:D8:9A:8E\r\na=setup:actpass\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=sendrecv\r\na=msid:- 7edf45e1-9bd1-49bf-8a16-695c548a9ccc\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:102 ILBC/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\na=ssrc:4248827374 cname:qkJ40UShmdVK5fjM\r\na=ssrc:4248827374 msid: 7edf45e1-9bd1-49bf-8a16-695c548a9ccc\r\na=ssrc:4248827374 mslabel:\r\na=ssrc:4248827374 label:7edf45e1-9bd1-49bf-8a16-695c548a9ccc\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 124 125\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:NmdR\r\na=ice-pwd:jcpB4u+AFtwPNy+7U2VKbD4e\r\na=ice-options:trickle\r\na=fingerprint:sha-256 69:5C:6F:D3:0A:AD:0E:7C:5E:96:FF:5D:1E:22:EC:A9:F7:3A:E2:74:85:7B:CE:2C:29:A1:2C:2C:21:D8:9A:8E\r\na=setup:actpass\r\na=mid:1\r\na=extmap:2 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:4 urn:3gpp:video-orientation\r\na=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:10 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07\r\na=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=sendrecv\r\na=msid:- d4eb383a-9a40-436e-8523-2b8c8485520a\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:98 VP9/90000\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=fmtp:98 x-google-profile-id=0\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:100 multiplex/90000\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=fmtp:100 acn=VP9;x-google-profile-id=0\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:127 red/90000\r\na=rtpmap:124 rtx/90000\r\na=fmtp:124 apt=127\r\na=rtpmap:125 ulpfec/90000\r\na=ssrc-group:FID 3988494207 2494793301\r\na=ssrc:3988494207 cname:qkJ40UShmdVK5fjM\r\na=ssrc:3988494207 msid: d4eb383a-9a40-436e-8523-2b8c8485520a\r\na=ssrc:3988494207 mslabel:\r\na=ssrc:3988494207 label:d4eb383a-9a40-436e-8523-2b8c8485520a\r\na=ssrc:2494793301 cname:qkJ40UShmdVK5fjM\r\na=ssrc:2494793301 msid: d4eb383a-9a40-436e-8523-2b8c8485520a\r\na=ssrc:2494793301 mslabel:\r\na=ssrc:2494793301 label:d4eb383a-9a40-436e-8523-2b8c8485520a\r\n","IceDataSeparator":""} +7ms
  dss POST /data/android 200 - - 16.732 ms +4ms
  dss GET /data/PC 404 - - 0.059 ms +2ms
  dss:body {"MessageType":3,"Data":"candidate:3453495995 1 udp 1685790463 96.242.51.241 55250 typ srflx raddr 192.168.1.24 rport 55250 generation 0 ufrag NmdR network-id 5 network-cost 10|0|0","IceDataSeparator":"|"} +6ms
  dss POST /data/android 200 - - 4.669 ms +7ms
  dss:body {"MessageType":3,"Data":"candidate:3453495995 1 udp 1685790463 96.242.51.241 55255 typ srflx raddr 192.168.1.24 rport 55255 generation 0 ufrag NmdR network-id 5 network-cost 10|1|1","IceDataSeparator":"|"} +6ms
  dss POST /data/android 200 - - 3.696 ms +5ms
  dss:body {"MessageType":3,"Data":"candidate:2360562281 1 tcp 1518280447 172.24.192.1 13446 typ host tcptype passive generation 0 ufrag NmdR network-id 1|0|0","IceDataSeparator":"|"} +25ms
  dss POST /data/android 200 - - 1.896 ms +23ms
  dss:body {"MessageType":3,"Data":"candidate:2360562281 1 tcp 1518280447 172.24.192.1 13451 typ host tcptype passive generation 0 ufrag NmdR network-id 1|1|1","IceDataSeparator":"|"} +16ms
  dss POST /data/android 200 - - 1.410 ms +16ms
  dss:body {"MessageType":3,"Data":"candidate:1967894431 1 tcp 1518018303 192.168.1.24 13450 typ host tcptype passive generation 0 ufrag NmdR network-id 5 network-cost 10|0|0","IceDataSeparator":"|"} +3ms
  dss POST /data/android 200 - - 1.220 ms +3ms
  dss:body {"MessageType":3,"Data":"candidate:4169670544 1 tcp 1518214911 169.254.80.80 13452 typ host tcptype passive generation 0 ufrag NmdR network-id 2|1|1","IceDataSeparator":"|"} +3ms
  dss POST /data/android 200 - - 0.895 ms +2ms
  dss:body {"MessageType":3,"Data":"candidate:3177668172 1 tcp 1518083839 169.254.123.7 13454 typ host tcptype passive generation 0 ufrag NmdR network-id 4|1|1","IceDataSeparator":"|"} +2ms
  dss POST /data/android 200 - - 1.324 ms +2ms
  dss:body {"MessageType":3,"Data":"candidate:4169670544 1 tcp 1518214911 169.254.80.80 13447 typ host tcptype passive generation 0 ufrag NmdR network-id 2|0|0","IceDataSeparator":"|"} +3ms
  dss POST /data/android 200 - - 6.486 ms +8ms
  dss:body {"MessageType":3,"Data":"candidate:1108662975 1 tcp 1518149375 172.16.80.1 13448 typ host tcptype passive generation 0 ufrag NmdR network-id 3|0|0","IceDataSeparator":"|"} +8ms
  dss POST /data/android 200 - - 0.937 ms +3ms
  dss:body {"MessageType":3,"Data":"candidate:3177668172 1 tcp 1518083839 169.254.123.7 13449 typ host tcptype passive generation 0 ufrag NmdR network-id 4|0|0","IceDataSeparator":"|"} +3ms
  dss POST /data/android 200 - - 1.152 ms +4ms
  dss:body {"MessageType":3,"Data":"candidate:1108662975 1 tcp 1518149375 172.16.80.1 13453 typ host tcptype passive generation 0 ufrag NmdR network-id 3|1|1","IceDataSeparator":"|"} +3ms
  dss POST /data/android 200 - - 1.611 ms +3ms
  dss:body {"MessageType":3,"Data":"candidate:1967894431 1 tcp 1518018303 192.168.1.24 13455 typ host tcptype passive generation 0 ufrag NmdR network-id 5 network-cost 10|1|1","IceDataSeparator":"|"} +4ms

These are the SDP messages when running videochatdemo on android tablet and windows unity editor:
 dss:body {"MessageType":3,"Data":"candidate:3054232416 1 udp 2122194687 169.254.80.80 50488 typ host generation 0 ufrag R6zw network-id 2|0|0","IceDataSeparator":"|"} +0ms
  dss POST /data/android 200 - - 4.303 ms +84ms
  dss:body {"MessageType":3,"Data":"candidate:4091847356 1 udp 2122063615 169.254.123.7 50490 typ host generation 0 ufrag R6zw network-id 4|0|0","IceDataSeparator":"|"} +2ms
  dss POST /data/android 200 - - 0.826 ms +2ms
  dss:body {"MessageType":3,"Data":"candidate:1002984303 1 udp 2121998079 192.168.1.24 50496 typ host generation 0 ufrag R6zw network-id 5 network-cost 10|1|1","IceDataSeparator":"|"} +1ms
  dss POST /data/android 200 - - 0.625 ms +1ms
  dss:body {"MessageType":3,"Data":"candidate:4091847356 1 udp 2122063615 169.254.123.7 50495 typ host generation 0 ufrag R6zw network-id 4|1|1","IceDataSeparator":"|"} +9ms
  dss POST /data/android 200 - - 0.643 ms +9ms
  dss:body {"MessageType":3,"Data":"candidate:3054232416 1 udp 2122194687 169.254.80.80 50493 typ host generation 0 ufrag R6zw network-id 2|1|1","IceDataSeparator":"|"} +11ms
  dss POST /data/android 200 - - 0.782 ms +11ms
  dss:body {"MessageType":3,"Data":"candidate:3257970329 1 udp 2122260223 172.24.192.1 50492 typ host generation 0 ufrag R6zw network-id 1|1|1","IceDataSeparator":"|"} +2ms
  dss POST /data/android 200 - - 0.484 ms +1ms
  dss:body {"MessageType":3,"Data":"candidate:1002984303 1 udp 2121998079 192.168.1.24 50491 typ host generation 0 ufrag R6zw network-id 5 network-cost 10|0|0","IceDataSeparator":"|"} +1ms
  dss POST /data/android 200 - - 0.668 ms +2ms
  dss:body {"MessageType":3,"Data":"candidate:3257970329 1 udp 2122260223 172.24.192.1 50487 typ host generation 0 ufrag R6zw network-id 1|0|0","IceDataSeparator":"|"} +2ms
  dss POST /data/android 200 - - 0.717 ms +2ms
  dss:body {"MessageType":3,"Data":"candidate:211232335 1 udp 2122129151 172.16.80.1 50494 typ host generation 0 ufrag R6zw network-id 3|1|1","IceDataSeparator":"|"} +2ms
  dss POST /data/android 200 - - 0.392 ms +1ms
  dss:body {"MessageType":1,"Data":"v=0\r\no=- 2221782856235947336 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic: WMS\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:R6zw\r\na=ice-pwd:hjMRY1pPsXfS1GDfBpVleixI\r\na=ice-options:trickle\r\na=fingerprint:sha-256 C3:5B:D9:82:96:F2:9A:B8:C5:98:60:E2:01:60:29:0D:AC:71:26:F3:74:14:58:94:4A:9D:3F:3C:00:CC:AF:B4\r\na=setup:actpass\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=sendrecv\r\na=msid:- f2dd6c8e-8b9a-49a8-978e-3cccf99ef1d8\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:102 ILBC/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\na=ssrc:4076296544 cname:1wMYJMoDwlU1U05/\r\na=ssrc:4076296544 msid: f2dd6c8e-8b9a-49a8-978e-3cccf99ef1d8\r\na=ssrc:4076296544 mslabel:\r\na=ssrc:4076296544 label:f2dd6c8e-8b9a-49a8-978e-3cccf99ef1d8\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 124 125\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:R6zw\r\na=ice-pwd:hjMRY1pPsXfS1GDfBpVleixI\r\na=ice-options:trickle\r\na=fingerprint:sha-256 C3:5B:D9:82:96:F2:9A:B8:C5:98:60:E2:01:60:29:0D:AC:71:26:F3:74:14:58:94:4A:9D:3F:3C:00:CC:AF:B4\r\na=setup:actpass\r\na=mid:1\r\na=extmap:2 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:4 urn:3gpp:video-orientation\r\na=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:10 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07\r\na=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=sendrecv\r\na=msid:- ba489bab-5ee5-4f8d-a6ca-0a2a74c732ef\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:98 VP9/90000\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=fmtp:98 x-google-profile-id=0\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:100 multiplex/90000\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=fmtp:100 acn=VP9;x-google-profile-id=0\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:127 red/90000\r\na=rtpmap:124 rtx/90000\r\na=fmtp:124 apt=127\r\na=rtpmap:125 ulpfec/90000\r\na=ssrc-group:FID 565547137 1959032432\r\na=ssrc:565547137 cname:1wMYJMoDwlU1U05/\r\na=ssrc:565547137 msid: ba489bab-5ee5-4f8d-a6ca-0a2a74c732ef\r\na=ssrc:565547137 mslabel:\r\na=ssrc:565547137 label:ba489bab-5ee5-4f8d-a6ca-0a2a74c732ef\r\na=ssrc:1959032432 cname:1wMYJMoDwlU1U05/\r\na=ssrc:1959032432 msid: ba489bab-5ee5-4f8d-a6ca-0a2a74c732ef\r\na=ssrc:1959032432 mslabel:\r\na=ssrc:1959032432 label:ba489bab-5ee5-4f8d-a6ca-0a2a74c732ef\r\n","IceDataSeparator":""} +1ms
  dss POST /data/android 200 - - 7.483 ms +7ms
  dss:body {"MessageType":3,"Data":"candidate:211232335 1 udp 2122129151 172.16.80.1 50489 typ host generation 0 ufrag R6zw network-id 3|0|0","IceDataSeparator":"|"} +8ms
  dss POST /data/android 200 - - 1.119 ms +3ms
  dss:body {"MessageType":3,"Data":"candidate:3453495995 1 udp 1685790463 96.242.51.241 50491 typ srflx raddr 192.168.1.24 rport 50491 generation 0 ufrag R6zw network-id 5 network-cost 10|0|0","IceDataSeparator":"|"} +3ms
  dss POST /data/android 200 - - 1.700 ms +4ms
  dss:body {"MessageType":3,"Data":"candidate:3453495995 1 udp 1685790463 96.242.51.241 50496 typ srflx raddr 192.168.1.24 rport 50496 generation 0 ufrag R6zw network-id 5 network-cost 10|1|1","IceDataSeparator":"|"} +4ms
  dss POST /data/android 200 - - 8.544 ms +11ms
  dss:body {"MessageType":3,"Data":"candidate:1108662975 1 tcp 1518149375 172.16.80.1 14338 typ host tcptype passive generation 0 ufrag R6zw network-id 3|0|0","IceDataSeparator":"|"} +52ms
  dss POST /data/android 200 - - 2.803 ms +46ms
  dss:body {"MessageType":3,"Data":"candidate:2360562281 1 tcp 1518280447 172.24.192.1 14336 typ host tcptype passive generation 0 ufrag R6zw network-id 1|0|0","IceDataSeparator":"|"} +8ms
  dss POST /data/android 200 - - 1.226 ms +6ms
  dss:body {"MessageType":3,"Data":"candidate:2360562281 1 tcp 1518280447 172.24.192.1 14341 typ host tcptype passive generation 0 ufrag R6zw network-id 1|1|1","IceDataSeparator":"|"} +2ms
  dss POST /data/android 200 - - 1.011 ms +2ms
  dss:body {"MessageType":3,"Data":"candidate:4169670544 1 tcp 1518214911 169.254.80.80 14342 typ host tcptype passive generation 0 ufrag R6zw network-id 2|1|1","IceDataSeparator":"|"} +8ms
  dss POST /data/android 200 - - 1.158 ms +8ms
  dss:body {"MessageType":3,"Data":"candidate:3177668172 1 tcp 1518083839 169.254.123.7 14344 typ host tcptype passive generation 0 ufrag R6zw network-id 4|1|1","IceDataSeparator":"|"} +2ms
  dss POST /data/android 200 - - 1.348 ms +3ms
  dss:body {"MessageType":3,"Data":"candidate:1108662975 1 tcp 1518149375 172.16.80.1 14343 typ host tcptype passive generation 0 ufrag R6zw network-id 3|1|1","IceDataSeparator":"|"} +3ms
  dss POST /data/android 200 - - 1.174 ms +2ms
  dss:body {"MessageType":3,"Data":"candidate:3177668172 1 tcp 1518083839 169.254.123.7 14339 typ host tcptype passive generation 0 ufrag R6zw network-id 4|0|0","IceDataSeparator":"|"} +3ms
  dss POST /data/android 200 - - 7.534 ms +10ms
  dss:body {"MessageType":3,"Data":"candidate:4169670544 1 tcp 1518214911 169.254.80.80 14337 typ host tcptype passive generation 0 ufrag R6zw network-id 2|0|0","IceDataSeparator":"|"} +9ms
  dss POST /data/android 200 - - 1.674 ms +3ms
  dss:body {"MessageType":3,"Data":"candidate:1967894431 1 tcp 1518018303 192.168.1.24 14345 typ host tcptype passive generation 0 ufrag R6zw network-id 5 network-cost 10|1|1","IceDataSeparator":"|"} +4ms
  dss POST /data/android 200 - - 1.334 ms +3ms
  dss:body {"MessageType":3,"Data":"candidate:1967894431 1 tcp 1518018303 192.168.1.24 14340 typ host tcptype passive generation 0 ufrag R6zw network-id 5 network-cost 10|0|0","IceDataSeparator":"|"} +4ms
  dss POST /data/android 200 - - 6.295 ms +9ms
  dss GET /data/android 200 - - 0.368 ms +110ms
  dss GET /data/android 200 - - 0.074 ms +34ms
  dss GET /data/android 200 - - 0.061 ms +30ms
  dss GET /data/android 200 - - 0.055 ms +34ms
  dss GET /data/android 200 - - 0.109 ms +33ms
  dss GET /data/android 200 - - 0.057 ms +33ms
  dss GET /data/PC 404 - - 0.049 ms +22ms
  dss GET /data/android 200 - - 0.094 ms +13ms
  dss GET /data/android 200 - - 0.061 ms +40ms
  dss GET /data/android 200 - - 0.057 ms +26ms
  dss GET /data/android 200 - - 0.072 ms +33ms
  dss GET /data/android 200 - - 0.071 ms +115ms
  dss:body {"MessageType":2,"Data":"v=0\r\no=- 3200494356193055136 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic: WMS\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:B4os\r\na=ice-pwd:q9kKABsebBu4ifd64m2zYSTw\r\na=ice-options:trickle\r\na=fingerprint:sha-256 53:7A:D9:D7:DE:BF:0C:70:D8:3D:2D:53:61:55:D1:55:EA:F5:1E:91:0E:1D:7F:44:46:C1:9F:42:11:8E:53:3C\r\na=setup:active\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=sendrecv\r\na=msid:- c760b535-11e6-43db-a45d-52cbead9c50e\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:102 ILBC/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\na=ssrc:798853533 cname:9qMC9qGbguvhp4Xz\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 124 125\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:B4os\r\na=ice-pwd:q9kKABsebBu4ifd64m2zYSTw\r\na=ice-options:trickle\r\na=fingerprint:sha-256 53:7A:D9:D7:DE:BF:0C:70:D8:3D:2D:53:61:55:D1:55:EA:F5:1E:91:0E:1D:7F:44:46:C1:9F:42:11:8E:53:3C\r\na=setup:active\r\na=mid:1\r\na=extmap:2 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:4 urn:3gpp:video-orientation\r\na=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:10 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07\r\na=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=sendrecv\r\na=msid:- 944c0898-5e49-434a-9156-728bc275675a\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:98 VP9/90000\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=fmtp:98 profile-id=0\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:100 multiplex/90000\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=fmtp:100 acn=VP9;profile-id=0\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:127 red/90000\r\na=rtpmap:124 rtx/90000\r\na=fmtp:124 apt=127\r\na=rtpmap:125 ulpfec/90000\r\na=ssrc-group:FID 3645779081 2700919573\r\na=ssrc:3645779081 cname:9qMC9qGbguvhp4Xz\r\na=ssrc:2700919573 cname:9qMC9qGbguvhp4Xz\r\n","IceDataSeparator":""} +554ms
  dss POST /data/PC 200 - - 9.746 ms +27ms
  dss:body {"MessageType":3,"Data":"candidate:2311777672 1 udp 2122260223 192.168.1.30 42145 typ host generation 0 ufrag B4os network-id 3 network-cost 10|0|0","IceDataSeparator":"|"} +4ms
  dss POST /data/PC 200 - - 6.377 ms +9ms
  dss GET /data/android 200 - - 0.102 ms +3ms
  dss GET /data/android 200 - - 0.105 ms +39ms
  dss:body {"MessageType":3,"Data":"candidate:2145031260 1 udp 1686052607 96.242.51.241 42145 typ srflx raddr 192.168.1.30 rport 42145 generation 0 ufrag B4os network-id 3 network-cost 10|0|0","IceDataSeparator":"|"} +55ms

**Environment**
 - MR-WebRTC version: Lasted Master
 - Platform: Windows Unity Editor (2019.4.8f1), Samsung Galaxy Tab 5Se (SM-T720) running Android 10
 - Architecture: Windows (x64), Android (ARM64)
 - Unity version (if applicable): 2019.4.8f1
 - Target device: Windows and Android

**Comment by astaikos316** [comment]
Figured out the issue I was having.  Turns out the order of transceivers was causing a problem.  Have also figured out how to integrate with ARFoundation to get augmented video to flow between an Android tablet and windows build.

**Comment by djee-ms** [comment]
@astaikos is there anything we could have added for easier/faster debugging of this issue? Like some warning somewhere? Am I correct if I describe the issue as "You had one peer with transceivers ordered as (0=audio, 1=video) and the other peer as (0=video, 1=audio) and therefore the connection couldn't match them"? It sounds like we could have detected that in Unity, and in fact I thought we did (there is [a check here](https://github.com/microsoft/MixedReality-WebRTC/blob/master/libs/unity/library/Runtime/Scripts/Media/MediaLine.cs#L69) for example).

**Comment by dhaminitinAltran** [comment]
Hi, I am facing the same issue on android My feed is running fine on the android device i.e the ar camera feed start but unable to start the call yet.
can you provide any insights on how did you solved it?
