### ISSUE TITLE
Are there plans to support Hololens2 ARM64

### ISSUE THREAD

**Issue by qiaofuwenlu** [microsoft/MixedReality-WebRTC#650]
**Describe the problem**
It not supports Hololens2 ARM64 for now.

**Describe the solution you'd like**
Many performance problems can be solved if it supports Hololens2 ARM64.

**Describe alternatives you've considered**
Please let me know if there will be this plan to support Hololens2 ARM64 in the future，If there is such a plan, when will it can use? So that we can properly plan the follow-up projects. 

 Thanks

**Comment by djee-ms** [comment]
Duplicate #414
