### ISSUE TITLE
UWP ARM build error

### ISSUE THREAD

**Issue by RumiaSultanova** [microsoft/MixedReality-WebRTC#660]
**Describe the bug**
I'm trying to build latest master branch of MR WebRTC for HoloLens 2 (UWP ARM), but I'm facing the issue with perl assembler preprocessor. The x86 and amd64 versions are building fine, the problem only appears when I try to compile ARM version.

**To Reproduce**
1. Setup environment
2. Clone the repository
3. Build
According to https://microsoft.github.io/MixedReality-WebRTC/manual/building-windows.html

**Expected behavior**
Builded plugin

**Screenshots**
![image](https://user-images.githubusercontent.com/9822301/106014564-a6a08800-60ce-11eb-8777-7d6981603667.png)

**Environment**
 - MR-WebRTC master  branch
 - Architecture: UWP ARM
 - Target device: HoloLens 2

**Comment by djee-ms** [comment]
I have never seen this I think but I'd say you have a missing dependency. Please check the dependency lists [here](https://microsoft.github.io/MixedReality-WebRTC/manual/building-windows.html) and [here](https://github.com/webrtc-uwp/webrtc-uwp-sdk/blob/master/README.md). Which variant of Perl do you have installed? I only ever tried with [Strawberry Perl](https://strawberryperl.com/).

**Comment by kspark-scott** [comment]
FWIW, I think Jerome is right on target.  I recently did a build on a newly installed dev machine on which I had neglected to install Perl.  It appears to be needed only for the ARM build.  I don't remember the exact errors, but they were similar to those reported here.  I installed Strawberry Perl and all was well.

**Comment by RumiaSultanova** [comment]
Thank you very much!
Install Strawberry Perl helped me.

**Comment by djee-ms** [comment]
Yes it's only for the ARM build and I'll be honest I know nothing about Perl and never tried anything else than just installing that distribution. Glad it worked! I'm closing the issue, feel free to reopen if there's still a problem.
