### ISSUE TITLE
Rendering Local Video on Unity

### ISSUE THREAD

**Issue by jyhUVC** [microsoft/MixedReality-WebRTC#662]
I was following the unity tutorial and found out that there is no source section that I can input the webcamsource.

Any Idea how to fix this problem? I tried to run it Unity, it won't work.
 

**Screenshots**
![image](https://user-images.githubusercontent.com/76935658/106415814-50976000-6493-11eb-91da-240f37115479.png)

**Environment**
_Please fill the information for **each peer** if different_
 - MR-WebRTC version  2.0.2
 - Platform:  Unity Android Player
 - Architecture:  x64 on Windows
 - Unity version 2019.4
 - Target device: [e.g. Windows Desktop,2, Android Phone]

**Comment by djee-ms** [comment]
It looks like the docs where not updated, see https://microsoft.github.io/MixedReality-WebRTC/manual/unity/unity-mediaplayer.html for instructions.
