### ISSUE TITLE
Support string in DataChannel.SendMessage 

### ISSUE THREAD

**Issue by torepaulsson** [microsoft/MixedReality-WebRTC#673]
I've tested to implement this somewhat in this draft PR: https://github.com/microsoft/MixedReality-WebRTC/pull/675

**Describe the problem**
I'm not 100% sure about this, but, once a DataChannel is setup there is these two methods to send raw bytes over the data channel:
```csharp
SendMessage(IntPtr message, ulong size)
SendMessage(byte[] message)
```

The only way to send messages right now is using raw bytes, but there should be another alternative according to the RFC (https://tools.ietf.org/html/rfc8831). The RFC states that the Payload Protocol Identifier (PPID) used in the data channel can be used to indicate raw bytes or UTF8 encoded data.

It would be great to have this available in the package as well, and might not be much trouble if the underlying support in the library is already there (hopefully).

**Describe the solution you'd like**
Overload the SendMessage method with another alternative:
```csharp
DataChannel.SendMessage(string message)
```
This would UTF8 encode the message and send it by with the PPID flag.

**Describe alternatives you've considered**
I see no other way to make this happen, there is no way to send the raw bytes as a UTF8 message since it is set by the underlying protocol, I think?

**Comment by torepaulsson** [comment]
I've checked the C++ code and found the following in data_channel.cpp
![image](https://user-images.githubusercontent.com/10498076/108224422-315b2c80-713b-11eb-9b34-7114ed56a96a.png)

I don't have Visual Studio 2017 (yet) and am not that familiar with C++, but it seems this boolean is what I'm looking for!

**Comment by torepaulsson** [comment]
Closed issue since the library now supports the flag using the SendMessageEx method and the MessageReceivedEx event.

**Comment by mikhaylo1** [comment]
@torepaulsson would you mind to publish **mrwebrtc.dll** with that fix ? 
I have the same problem you described - the peer I am connecting to doesn't accept blob DataChannel messages from MixedReality-WebRTC 2.0.2 and expects text only

It looks like there is only win32-x64-Debug version published https://dev.azure.com/aipmr/MixedReality-WebRTC-CI/_build/results?buildId=19141&view=artifacts&pathAsName=false&type=publishedArtifacts

Very interested in win32-x64-Release build and failed to build it myself

**Comment by torepaulsson** [comment]
@mikhaylo1, I'm sorry but I'm not the owner of this repository and unsure how it is published. I've built mine locally instead, it would be great if we could get a official release though. Maybe @djee-ms can help with that, if the release pipeline still functions.

**Comment by mikhaylo1** [comment]
I am looking for Win32 Release build, as far as I see there is only a Release artifact for UWP build generated with that change in DataChannels

@djee-ms Is there any chance to run the pipeline and generate artifacts for the current master repository ?
