### ISSUE TITLE
Video stream to multiple peers

### ISSUE THREAD

**Issue by jgaarsdal** [microsoft/MixedReality-WebRTC#68]
Hi,

Do you know what it would take to be able to stream your local video to several remote peers?
So a Peer A and Peer B both receiving video from Peer C. Is it supported at the moment, and if not will it be in the future?

A quick test with your Unity sample didn't seem to work, but I might be missing a step or two.

Thanks in advance.

**Comment by djee-ms** [comment]
Hi @jgaarsdal,

What your are asking for, multi-peer support, is not supported natively by WebRTC. WebRTC itself is intrinsically peer-to-peer only. However other technologies are building upon WebRTC to provide this feature. Namely you are looking for:
- a naive mesh topology, with a single peer connection per couple of peers : very simple, but not economical in terms of bandwidth for example;
- a [Selective Forwarding Unit (SFU)](https://webrtcglossary.com/sfu/) server which dispatches the tracks as needed between the peers;
- a [Multipoint Conferencing Unit (MCU)](https://webrtcglossary.com/mcu/) server which mixes several tracks into a single one.

There are several third-party offers out there. The Microsoft [Mixed Reality docs](https://docs.microsoft.com/en-us/windows/mixed-reality/shared-experiences-in-mixed-reality#share-1st-person-perspective) mention FreeSwitch for example. I have not tried myself, but these essentially require adapting the signaling solution to be compatible with the server.

**Comment by jgaarsdal** [comment]
Hi @djee-ms 

Thanks for the detailed answer.
This definitely gives me something to work with :)
I will close the issue.
