### ISSUE TITLE
Possibility to set credentials for each TURN server instead of just one credentials for all TURN servers

### ISSUE THREAD

**Issue by salinhard** [microsoft/MixedReality-WebRTC#69]
I have 3 TURN servers with 3 different credentials, but actually I can use only one TURN because I can set only on credential in the component

**Comment by djee-ms** [comment]
Fixed by 1205e1f8ef5e39f65c4e56f919b353e39cbbbbfb. `PeerConnection` now takes a `PeerConnectionConfiguration` object for setup, which includes support for multiple ICE servers, each with its own set of URLs and its own credentials.
