### ISSUE TITLE
About android support

### ISSUE THREAD

**Issue by songuyen1816** [microsoft/MixedReality-WebRTC#692]
Hi, first sorry for my bad English, just a small question.
To now, is Mixed Reality-WebRTC only support Android through Unity development? 
Can u give me a confirmation, because User manual made me confused. Thanks and regards

**Comment by djee-ms** [comment]
Yes, Android only via Unity deployment.

What part of the docs confused you? We can clarify it.

**Comment by songuyen1816** [comment]
Thanks for your response, 
Here [https://github.com/microsoft/MixedReality-WebRTC/tree/master/tools/build/android
](url) 
When read this page, I thought I would build a library for Android Studio project, it's my mistake because haven't read it carefully. Is there a way to use this library for Android Studio project? I use MR-WebRTC for UWP application, or will it fine if I use Google-WebRTC on Android and connect them?

**Comment by djee-ms** [comment]
Right. Technically there is nothing preventing you from using the library on Android without Unity. But we are not officially supporting this, so we might not be able to help if you encounter difficulties. The statement about "not supported" is a resourcing question more than a technical one (although there might be technical issues, but we don't know as we never tried).

That being said, WebRTC is a standard and all implementations _should_ be compatible with each other. In practice there are sometimes some small issues, but I know some users are using MixedReality-WebRTC with a browser for example, or another WebRTC implementation. So you should feel free to try something else on Android if that's a better match for your use case.

**Comment by songuyen1816** [comment]
Thanks @djee-ms, your response so helpful, I have understood more about Mixed-Reality WebRTC and WebRTC in general. I'll close this ticket.
Best regards.

**Comment by dhaminitinAltran** [comment]
Hi Same query but need a bit more specific so that means that when I try to connect two different clients via a call i.e one Android Build with unity and another on windows build with unity and using this plugin my clients would be able to start a call without any issue right?

**Comment by spacecheeserocks** [comment]
> Hi Same query but need a bit more specific so that means that when I try to connect two different clients via a call i.e one Android Build with unity and another on windows build with unity and using this plugin my clients would be able to start a call without any issue right?

In general, yes. WebRTC itself works cross platform.

You should test the apps with a few different devices and scenarios however. Specifically with the Windows Desktop version of this library, there is no H.264 video support (only VP8 video), so you will need to ensure that your Android client can send/receive VP8 video.
