### ISSUE TITLE
Offer SDPs between mr-webrtc 1.0.3 and 2.0.2 are not the same

### ISSUE THREAD

**Issue by KarthikRichie** [microsoft/MixedReality-WebRTC#694]
**Describe the bug**
I'm making a audio call from UWP app and the call is attended in iOS/Android devices. Now, when a user enables his/her video in android and the same is done in UWP app next. 

When the user enables the video in UWP app, in 2.0.2, the uwp video is not visible to the remote user (android/iOS). However, the same works perfectly fine in 1.0.3.

I had a look at the below SDP's and the difference that I'm seeing is in "msid:","mslocal:" and "local:" params which is available in 1.0.3 but missing in 2.0.2. Trying updating the SDP to resonate with that in 1.0.3 but still didn't work.  Any thoughts?

The offer SDP generated from 1.0.3 looks like below

> v=0
> o=- 4947663911116876344 3 IN IP4 127.0.0.1
> s=-
> t=0 0
> a=group:BUNDLE 0 1
> a=msid-semantic: WMS local_av_stream
> m=audio 37150 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
> c=IN IP4 119.81.194.156
> a=rtcp:9 IN IP4 0.0.0.0
> a=candidate:3298200058 1 udp 2122260223 112.20.19.9 59544 typ host generation 0 network-id 3 network-cost 10
> a=candidate:1841890863 1 udp 1686052607 106.208.71.177 2159 typ srflx raddr 112.10.10.9 rport 5934 generation 0 network-id 3 network-cost 10
> a=candidate:2316662026 1 tcp 1518280447 102.20.10.9 64581 typ host tcptype passive generation 0 network-id 3 network-cost 10
> a=candidate:1218638837 1 udp 41885695 119.81.194.156 37150 typ relay raddr 116.138.71.177 rport 29 generation 0 network-id 3 network-cost 10
> a=candidate:102829829 1 udp 25108223 130.81.194.116 39156 typ relay raddr 100.120.71.177 rport 260 generation 0 network-id 3 network-cost 10
> a=ice-ufrag:r5TM
> a=ice-pwd:Q6w1XR7hRLFYttJYF4tIDLrN
> a=ice-options:trickle
> a=fingerprint:sha-256 2A:A5:F1:BE:A2:1B:77:A4:66:57:B6:03:50:D5:C9:B3:07:0D:1A:5F:E7:29:B1:5A:A2:1A:B5:E4:0B:E2:25:EF
> a=setup:passive
> a=mid:0
> a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
> a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
> a=sendrecv
> a=msid:local_av_stream 0133cef4-f5da-4254-b37e-1487df30b7cd
> a=rtcp-mux
> a=rtpmap:111 opus/48000/2
> a=rtcp-fb:111 transport-cc
> a=fmtp:111 minptime=10;useinbandfec=1
> a=rtpmap:103 ISAC/16000
> a=rtpmap:104 ISAC/32000
> a=rtpmap:9 G722/8000
> a=rtpmap:102 ILBC/8000
> a=rtpmap:0 PCMU/8000
> a=rtpmap:8 PCMA/8000
> a=rtpmap:106 CN/32000
> a=rtpmap:105 CN/16000
> a=rtpmap:13 CN/8000
> a=rtpmap:110 telephone-event/48000
> a=rtpmap:112 telephone-event/32000
> a=rtpmap:113 telephone-event/16000
> a=rtpmap:126 telephone-event/8000
> a=ssrc:1845543973 cname:IjFgsqT9EIZuxy7t
> a=ssrc:2458819902 msid:local_av_stream local_audio
> a=ssrc:2458819902 mslabel:local_av_stream
> a=ssrc:2458819902 label:local_audio
> m=video 9 UDP/TLS/RTP/SAVPF 96
> c=IN IP4 0.0.0.0
> a=rtcp:9 IN IP4 0.0.0.0
> a=ice-ufrag:r5TM
> a=ice-pwd:Q6w1XR7hRLFYttJYF4tIDLrN
> a=ice-options:trickle
> a=fingerprint:sha-256 2A:A5:F1:BE:A2:1B:77:A4:66:57:B6:03:50:D5:C9:B3:07:0D:1A:5F:E7:29:B1:5A:A2:1A:B5:E4:0B:E2:25:EF
> a=setup:passive
> a=mid:1
> a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
> a=extmap:13 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
> a=extmap:3 urn:3gpp:video-orientation
> a=extmap:2 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
> a=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
> a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
> a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
> a=extmap:8 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
> a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
> a=sendrecv
> a=msid:local_av_stream f257bb6b-e02b-4b50-ad8f-1c91abefac3f
> a=rtcp-mux
> a=rtcp-rsize
> a=rtpmap:96 VP8/90000
> a=rtcp-fb:96 goog-remb
> a=rtcp-fb:96 transport-cc
> a=rtcp-fb:96 ccm fir
> a=rtcp-fb:96 nack
> a=rtcp-fb:96 nack pli
> a=ssrc-group:FID 2292661653 1067296865
> a=ssrc:3015084024 cname:IjFgsqT9EIZuxy7t
> a=ssrc:2292661653 msid:local_av_stream eea53889-c798-4e98-8c8b-9ba4b05b3c85
> a=ssrc:2292661653 mslabel:local_av_stream
> a=ssrc:2292661653 label:eea53889-c798-4e98-8c8b-9ba4b05b3c85
> a=ssrc:1067296865 cname:yJNEpIEswHXXkIV5
> a=ssrc:1067296865 msid:local_av_stream eea53889-c798-4e98-8c8b-9ba4b05b3c85
> a=ssrc:1067296865 mslabel:local_av_stream
> a=ssrc:1067296865 label:eea53889-c798-4e98-8c8b-9ba4b05b3c85
> 

The same offer SDP generated from 2.0.2 looks like below,

> v=0
> o=- 3198287353594344609 3 IN IP4 127.0.0.1
> s=-
> t=0 0
> a=group:BUNDLE 0 1
> a=msid-semantic: WMS local_av_stream
> m=audio 47583 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
> c=IN IP4 119.81.194.149
> a=rtcp:9 IN IP4 0.0.0.0
> a=candidate:3013953624 1 udp 2122260223 490.161.1.110 23036 typ host generation 0 network-id 3 network-cost 10
> a=candidate:854413036 1 udp 1686052607 163.16.12.97 63136 typ srflx raddr 192.168.1.100 rport 23131 generation 0 network-id 3 network-cost 10
> a=candidate:4247172264 1 tcp 1518280447 102.118.1.100 53861 typ host tcptype passive generation 0 network-id 3 network-cost 10
> a=candidate:1916830594 1 udp 41885695 199.81.121.149 47583 typ relay raddr 157.16.22.97 rport 93026 generation 0 network-id 3 network-cost 10
> a=candidate:1019445106 1 udp 25108223 199.81.194.149 10868 typ relay raddr 203.16.42.97 rport 23820 generation 0 network-id 3 network-cost 10
> a=ice-ufrag:C8f/
> a=ice-pwd:YwK8a+Pzv0Q7yCpDKCnuP2OL
> a=ice-options:trickle
> a=fingerprint:sha-256 9E:85:42:6D:4E:F7:29:84:B0:85:18:A6:73:BD:EE:93:8C:A0:66:49:AD:0C:A4:9A:1C:B5:18:42:1D:74:18:03
> a=setup:passive
> a=mid:0
> a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
> a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
> a=sendrecv
> a=msid:local_av_stream f60885df-62d9-4fd6-baf4-092942ca755e
> a=rtcp-mux
> a=rtpmap:111 opus/48000/2
> a=rtcp-fb:111 transport-cc
> a=fmtp:111 minptime=10;useinbandfec=1
> a=rtpmap:103 ISAC/16000
> a=rtpmap:104 ISAC/32000
> a=rtpmap:9 G722/8000
> a=rtpmap:102 ILBC/8000
> a=rtpmap:0 PCMU/8000
> a=rtpmap:8 PCMA/8000
> a=rtpmap:106 CN/32000
> a=rtpmap:105 CN/16000
> a=rtpmap:13 CN/8000
> a=rtpmap:110 telephone-event/48000
> a=rtpmap:112 telephone-event/32000
> a=rtpmap:113 telephone-event/16000
> a=rtpmap:126 telephone-event/8000
> a=ssrc:2287751253 cname:aR4ErgWSvwYXjA6a
> m=video 9 UDP/TLS/RTP/SAVPF 100
> c=IN IP4 0.0.0.0
> a=rtcp:9 IN IP4 0.0.0.0
> a=ice-ufrag:C8f/
> a=ice-pwd:YwK8a+Pzv0Q7yCpDKCnuP2OL
> a=ice-options:trickle
> a=fingerprint:sha-256 9E:85:42:6D:4E:F7:29:84:B0:85:18:A6:73:BD:EE:93:8C:A0:66:49:AD:0C:A4:9A:1C:B5:18:42:1D:74:18:03
> a=setup:passive
> a=mid:1
> a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
> a=extmap:13 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
> a=extmap:3 urn:3gpp:video-orientation
> a=extmap:2 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
> a=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
> a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
> a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
> a=extmap:8 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
> a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
> a=sendrecv
> a=msid:local_av_stream d601c1d6-f590-4e42-8807-a5c59d4105da
> a=rtcp-mux
> a=rtcp-rsize
> a=rtpmap:100 VP8/90000
> a=rtcp-fb:100 goog-remb
> a=rtcp-fb:100 transport-cc
> a=rtcp-fb:100 ccm fir
> a=rtcp-fb:100 nack
> a=rtcp-fb:100 nack pli
> a=ssrc:3035223504 cname:aR4ErgWSvwYXjA6a
>

**Comment by djee-ms** [comment]
The only difference I see from the SDP messages is the stream (msid/mslabel/etc.) which I think you can add with [`Transceiver.StreamIDs`](https://microsoft.github.io/MixedReality-WebRTC/api/Microsoft.MixedReality.WebRTC.Transceiver.html#Microsoft_MixedReality_WebRTC_Transceiver_StreamIDs). But I am skeptical this is the reason why the video is not shown. What's your Unity setup, especially for transceivers? There are many differences between v1 and v2 so it's quite difficult to compare.

**Comment by KarthikRichie** [comment]
This is how my set up looks like,

        > private async void _Connection_TransceiverAdded(Transceiver transceiver)
>         {
>             if (transceiver.DesiredDirection == Transceiver.Direction.ReceiveOnly)
>             {
>                 if (transceiver.MediaKind == MediaKind.Audio)
>                 {
>                     _audioTransceiver = transceiver;
>                     transceiver.DesiredDirection = Transceiver.Direction.SendReceive;
>                     await ModifyAudioTrack(true, true);
>                 }
>                 else if (transceiver.MediaKind == MediaKind.Video)
>                 {
>                     //bool isEnableLocalVideo = _videoTransceiver != null;
>                     _videoTransceiver = transceiver;
>                     transceiver.DesiredDirection = Transceiver.Direction.SendReceive;
>                     //CreateVideoTransceiver();
>                     await ModifyVideoTrack(true, true);
>                 }
>             }
>         }

		

> 		private void SubscribeEvents()
>         {
>             _Connection.LocalSdpReadytoSend += ProcessLocalSdpReadytoSend;
>             _Connection.Connected += RTCConnected;
>             _Connection.IceCandidateReadytoSend += ProcessIceCandidateReadytoSend;
>             _Connection.VideoTrackAdded += _Connection_VideoTrackAdded;
>             _Connection.IceStateChanged += _Connection_IceStateChanged;
>             _Connection.TransceiverAdded += _Connection_TransceiverAdded;
>         }
> 

>         private void _Connection_VideoTrackAdded(RemoteVideoTrack track)
>         {
>             if (_remoteVideoTrack != null)
>             {
>                 _remoteVideoTrack.I420AVideoFrameReady -= _Connection_I420RemoteVideoFrameReady;
>             }
>             _remoteVideoTrack = track;
>             _remoteVideoTrack.I420AVideoFrameReady += _Connection_I420RemoteVideoFrameReady;
>             _remoteVideoTrack.Argb32VideoFrameReady += _remoteVideoTrack_Argb32VideoFrameReady;
>         }
> 

>         internal override async Task<bool> Initialize(string callId)
>         {
>             try
>             {
>                 _Connection = new PeerConnection();
>                 SubscribeEvents();
> 
>                 await _Connection.InitializeAsync(new PeerConnectionConfiguration()
>                 {
>                     IceServers = _IceServers,
>                     IceTransportType = IceTransportType.All,
>                 });
> 
>                 //_Connection.PreferredVideoCodec = "VP9";
>                 return true;
>             }
>             catch (Exception e)
>             {
>                 return false;
>             }
> 
>         }
> 

		
	

> 	internal async Task ModifyVideoTrack(bool add, bool enabled)
>         {
>             if (add)
>             {
>                 if (_localVideoTrack == null)
>                 {
>                     _webcamSource = await DeviceVideoTrackSource.CreateAsync();
>                     _webcamSource.Name = "uwpwebcamsource";
>                     _localVideoTrack = LocalVideoTrack.CreateFromSource(_webcamSource, new LocalVideoTrackInitConfig() { trackName = "uwpvideotrack" });
>                     _localVideoTrack.I420AVideoFrameReady += HandleI420LocalVideoFrameReady;
>                 }
>                 CreateVideoTransceiver();
>             }
>             else
>             {
>                 ResetLocalVideoTrack();
>             }
>         }
> 		
> 		 private void CreateVideoTransceiver()
>         {
>             if (_videoTransceiver == null)
>             {
>                 _videoTransceiver = _Connection.AddTransceiver(MediaKind.Video, new TransceiverInitSettings() { InitialDesiredDirection = Transceiver.Direction.SendReceive, StreamIDs = new List<string>() { "local_av_stream" } });
>             }
>             _videoTransceiver.LocalVideoTrack = _localVideoTrack;
>         }
> 

        

> private void ResetLocalVideoTrack()
>         {
>             if (_localVideoTrack != null)
>             {
>                 _localVideoTrack.I420AVideoFrameReady -= HandleI420LocalVideoFrameReady;
>                 _localVideoTrack = null;
>             }
>             if (_videoTransceiver != null)
>             {
>                 _videoTransceiver.LocalVideoTrack = null;
>             }
>         }

**Comment by KarthikRichie** [comment]
I tried the same scenario while attending a call from web. 

a) Call initiated from UWP app
b) Call attended in web browser
c) Video shared by user in web
d) Then video shared by user in uwp

It works fine while taken from web. So, the transceiver set up in my side should be good I guess. But only when I replace the same scenario mentioned above in iOS/Android, video enabled from uwp is not rendered in mobile devices.

uwp -> web browser :- Sdp when the video track in enabled in uwp app 
v=0
o=- 4859221105330353416 3 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic: WMS local_av_stream
m=audio 37718 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 119.81.194.156
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:2702239670 1 udp 2122260223 112.168.1.113 521606 typ host generation 0 network-id 3 network-cost 10
a=candidate:542695682 1 udp 1686052607 113.16.11.97 55606 typ srflx raddr 192.118.1.103 rport 58606 generation 0 network-id 3 network-cost 10
a=candidate:4019395398 1 tcp 1518280447 112.168.1.103 50457 typ host tcptype passive generation 0 network-id 3 network-cost 10
a=candidate:1218638837 1 udp 41885695 114.81.114.116 31718 typ relay raddr 103.16.15.97 rport 52606 generation 0 network-id 3 network-cost 10
a=candidate:102829829 1 udp 25108223 119.81.194.156 38194 typ relay raddr 103.16.12.97 rport 50456 generation 0 network-id 3 network-cost 10
a=ice-ufrag:oIQf
a=ice-pwd:w7aIoiYv33Bs7kM6gu4cCANE
a=ice-options:trickle
a=fingerprint:sha-256 5B:6B:8F:13:57:8C:B9:0F:28:D2:F7:2D:E1:C8:09:AA:98:AA:30:0F:65:68:91:65:FF:BB:C9:A4:54:F2:22:3C
a=setup:passive
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:local_av_stream 06220dcb-d64e-4377-ba5d-b5c61a671007
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:1926845038 cname:IkywXxHohqQDZzPi
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 125 107 114 115 116
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:oIQf
a=ice-pwd:w7aIoiYv33Bs7kM6gu4cCANE
a=ice-options:trickle
a=fingerprint:sha-256 5B:6B:8F:13:57:8C:B9:0F:28:D2:F7:2D:E1:C8:09:AA:98:AA:30:0F:65:68:91:65:FF:BB:C9:A4:54:F2:22:3C
a=setup:passive
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:local_av_stream 4ab8bcc2-d24d-4d12-81e2-d547e860c8e5
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 x-google-profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:125 H264/90000
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 packetization-mode=1;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=125
a=rtpmap:114 red/90000
a=rtpmap:115 rtx/90000
a=fmtp:115 apt=114
a=rtpmap:116 ulpfec/90000
a=ssrc-group:FID 4170604269 3408438260
a=ssrc:4170604269 cname:IkywXxHohqQDZzPi
a=ssrc:3408438260 cname:IkywXxHohqQDZzPi

**Comment by KarthikRichie** [comment]
@djee-ms Any thoughts on this issue ? I’m I missing something here ?

**Comment by SergioMasson** [comment]
I am also having this problem. I have added the following code to make it work, but I am not quite sure why it worked at all. 

```
private string EnsureSemanticGrouping(string sdpMessage)
{
    //Checks if the msid semantic group has been set in the message.
    if (!sdpMessage.Contains("msid-semantic: WMS\r"))
        return sdpMessage;

    //Creates a semantic group called local_av_stream and adds it to both video and audio streams.
    return sdpMessage.Replace("msid-semantic: WMS\r", "msid-semantic: WMS local_av_stream\r")
                                   .Replace("msid:-", "msid:-local_av_stream")
                                   .Replace("mslabel:\r", "mslabel:local_av_stream\r");
}
```

Than I just apply this to all my sdp messages:

```
public override Task SendMessageAsync(SdpMessage message)
{
    var messageType = message.Type == SdpMessageType.Offer ? SDPType.Offer : SDPType.Answer;

    var messageBody = EnsureSemanticGrouping(message.Content);

    return _signalingClient.SendSDPMessage(messageBody, messageType);
}
```

This has fixed the video problem for now, but I`m having some problems with the audio.

**Comment by KarthikRichie** [comment]
@SergioMasson Is the video working for [this](https://github.com/microsoft/MixedReality-WebRTC/issues/734) case

**Comment by KarthikRichie** [comment]
For iOS and Android, I've fixed this problem. Any folks facing the similar problem can try out these
iOS:- https://github.com/microsoft/MixedReality-WebRTC/issues/734
Android:- https://github.com/microsoft/MixedReality-WebRTC/issues/699
