### ISSUE TITLE
Enable "Allow 'unsafe' code" in Player Settings with custom MediaPlayer

### ISSUE THREAD

**Issue by pablomarcos** [microsoft/MixedReality-WebRTC#71]
When creating my own MediaPlayer for rendering the Video stream on UI instead of in a Renderer Unity makes me enable "Allow 'unsafe' code" in Player Settings because the script is using the `unsafe` statement.
Instead, when I use the MediaPlayer provided with the example it is not necessary to enable this option on Player Settings.
Are you using any external or additional file on Assets folder for avoiding this error with your MediaPlayer.cs script? Why I need to enable it when using it on my script but not when using yours?
Thanks

**Comment by djee-ms** [comment]
The `Microsoft.MixedReality.WebRTC.Unity` assembly has "Allow unsafe" set:

https://github.com/microsoft/MixedReality-WebRTC/blob/de1db215f390524d5d8fd576b274c74fdcc362e2/libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Microsoft.MixedReality.WebRTC.Unity.asmdef#L7

When you use that assembly, your own assembly consumes it as a dependency, so no need for yours to also have that option (unless your code also uses `unsafe`). However when you write your own variant of `MediaPlayer`, the `unsafe` now appears in your own assembly, which now needs that option. This is pretty standard C# rules as far as I know (I am not a C# expert, maybe I am missing something here?).

**Comment by djee-ms** [comment]
@pablomarcos did that answer your question? Can we close this issue?

**Comment by pablomarcos** [comment]
Absolutely! Sorry, I forgot to answer you. Thanks a lot!
