### ISSUE TITLE
Can't build Windows sources with ARM build architecture

### ISSUE THREAD

**Issue by Kawottex** [microsoft/MixedReality-WebRTC#712]
Hello,
I am trying to build Windows sources following this tutorial (https://microsoft.github.io/MixedReality-WebRTC/manual/building-windows.html) and got no problem win x64/win32 but when I try to build in ARM for UWP, I got this error:

[1/2584] ACTION //common_audio:compile_common_audio_c_arm_assembly(//build/toolchain/win:uwp_arm)
FAILED: gen/common_audio/complex_bit_reverse_arm.S.obj
C:/Python27/python.exe ../../webrtc/build/Win_ARM_Tools/run_arm_asm_compiler.py -s ../../webrtc/build/gas-preprocessor/gas-preprocessor.pl -i ../../common_audio/signal_processing/complex_bit_reverse_arm.S -o D:/mr-webrtc/external/webrtc-uwp-sdk/webrtc/xplatform/webrtc/out/webrtc_winuwp_arm_release/gen/common_audio/complex_bit_reverse_arm.S.obj -p environment.store_arm -l ../../ -a arm

'cpp' not recognised as an internal or external command, operable program or batch file

Traceback (most recent call last):
  File "../../webrtc/build/Win_ARM_Tools/run_arm_asm_compiler.py", line 36, in <module>
    subprocess.check_call(['perl', options.script, '-arch', options.arch, '-as-type', asm_type, '-force-thumb', '--', arm_compiler, '-oldit', '-I' + options.include, options.input, '-o', options.output ], env=dict(kvs))
  File "C:\Python27\lib\subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['perl', '../../webrtc/build/gas-preprocessor/gas-preprocessor.pl', '-arch', 'arm', '-as-type', 'armasm', '-force-thumb', '--', 'armasm.exe', '-oldit', '-I../../', '../../common_audio/signal_processing/complex_bit_reverse_arm.S', '-o', 'D:/mr-webrtc/external/webrtc-uwp-sdk/webrtc/xplatform/webrtc/out/webrtc_winuwp_arm_release/gen/common_audio/complex_bit_reverse_arm.S.obj']' returned non-zero exit status 1

This error repeat multiple times and then the script stops.
I don't have this error building x64 for UWP.
I've checked and it seems that my environment is correctly setup (got VS 2019 with UWP dev module, .NET desktop dev module, C++ desktop dev module and MSVC v141 VS 2017 C++ ARM Build Toold & x64/x86 Build Tools.

Thank you for your help,
Kevin

**Comment by djee-ms** [comment]
Do you have Perl installed? Which version/distribution? We only tested with Strawberry Perl. I know someone reported trying another distribution and it didn't work. I am not familiar enough with Perl to tell you why though.

**Comment by Kawottex** [comment]
I've got perl 5, version 28, subversion 1 (v5.28.1) built for MSWin32-x64-multi-thread

**Comment by Kawottex** [comment]
> 
> 
> Do you have Perl installed? Which version/distribution? We only tested with Strawberry Perl. I know someone reported trying another distribution and it didn't work. I am not familiar enough with Perl to tell you why though.

Ok it was indeed because I used ActivePerl and not Strawberry Perl. You may add it to the "Environment and tooling" part of the documentation. Thank you for you help 😄

**Comment by djee-ms** [comment]
Well frankly I have no idea why ActivePerl doesn't work, and I know Strawberry Perl works but that is by no mean a requirement, any version of Perl should work in theory. It seems this is more a question of how the distribution configures the environment, and I have no idea what the requirements are. Also Strawberry Perl is called out from the docs already : https://microsoft.github.io/MixedReality-WebRTC/manual/building-core.html

**Comment by Kawottex** [comment]
> 
> 
>  Also Strawberry Perl is called out from the docs already : https://microsoft.github.io/MixedReality-WebRTC/manual/building-core.html

Oh indeed, I didn't see that part, my blame. Thank you anyway for your help ^^
