### ISSUE TITLE
Is there a way to add multiple LocalVideoTrack in Transceiver?

### ISSUE THREAD

**Issue by KarthikRichie** [microsoft/MixedReality-WebRTC#715]
I've a scenario where I need to send local screen capture video and web cam video to the remote peer. While looking at the documentation, I see Transceiver.LocalVideoTrack where I'm able to attach only one video at a given point of time. How can I add multiple local video track to the transceiver?

Something like below

**Screenshare:-** 

> _screenshareSource = ExternalVideoTrackSource.CreateFromArgb32Callback(WebRTCFrameCallback);
>                     _localScreenTrack = LocalVideoTrack.CreateFromSource(_screenshareSource, new LocalVideoTrackInitConfig() { trackName = "uwpscreensharetrack" });
> 

**Webcam:-**

>                 _webcamSource = await DeviceVideoTrackSource.CreateAsync();
>                 _localVideoTrack = LocalVideoTrack.CreateFromSource(_webcamSource, new LocalVideoTrackInitConfig() { trackName = "uwpvideotrack" });

**Comment by spacecheeserocks** [comment]
If you want to send multiple video tracks, you should add another Video transceiver.

**Comment by KarthikRichie** [comment]
I tried adding another video transceiver, but with no luck. This is what I'm doing. 

> _screenshareSource = ExternalVideoTrackSource.CreateFromArgb32Callback(WebRTCFrameCallback);
> _localScreenTrack = LocalVideoTrack.CreateFromSource(_screenshareSource, new LocalVideoTrackInitConfig() { trackName = "uwpscreensharetrack" });
> 
> _webcamSource = await DeviceVideoTrackSource.CreateAsync();
> _localVideoTrack = LocalVideoTrack.CreateFromSource(_webcamSource, new LocalVideoTrackInitConfig() { trackName = "uwpvideotrack" });
> 
>  _videoTransceiver = _Connection.AddTransceiver(MediaKind.Video, new TransceiverInitSettings() { InitialDesiredDirection = Transceiver.Direction.SendReceive });
> _videoTransceiver.LocalVideoTrack = localVideoTrack;
> 
>  _otherVideoTransceiver = _Connection.AddTransceiver(MediaKind.Video, new TransceiverInitSettings() { InitialDesiredDirection = Transceiver.Direction.SendReceive });
> _otherVideoTransceiver .LocalVideoTrack = _localScreenTrack ;

SDP offer :-
v=0
o=- 1673403826453382226 3 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic: WMS local_av_stream local_av_stream
m=audio 42551 UDP/TLS/RTP/SAVPF 109 9 0 8 101
c=IN IP4 119.81.194.149
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:2530088836 1 udp 2122260223 192.168.1.106 58679 typ host generation 0 network-id 3 network-cost 10
a=candidate:394662192 1 udp 1686052607 103.16.12.97 58679 typ srflx raddr 192.168.1.106 rport 58679 generation 0 network-id 3 network-cost 10
a=candidate:3628985204 1 tcp 1518280447 192.168.1.106 57923 typ host tcptype passive generation 0 network-id 3 network-cost 10
a=candidate:1916830594 1 udp 41885695 119.81.194.149 42551 typ relay raddr 103.16.12.97 rport 58679 generation 0 network-id 3 network-cost 10
a=candidate:1019445106 1 udp 25108223 119.81.194.149 43792 typ relay raddr 103.16.12.97 rport 57922 generation 0 network-id 3 network-cost 10
a=ice-ufrag:ZwJq
a=ice-pwd:Ee9L6YuXAJ34cURXzBmmM/F7
a=ice-options:trickle
a=fingerprint:sha-256 B4:86:8F:A6:E6:81:C0:73:FE:B2:3E:B1:D7:82:DB:45:68:7E:61:42:66:1F:52:48:52:0A:AD:60:FE:40:20:AC
a=setup:active
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:local_av_stream 21f05543-4733-4143-b6a0-168580c09e0f
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=fmtp:109 minptime=10;useinbandfec=1
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=ssrc:1966771190 cname:obg1pKuTkxaHgcZK
m=video 9 UDP/TLS/RTP/SAVPF 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:ZwJq
a=ice-pwd:Ee9L6YuXAJ34cURXzBmmM/F7
a=ice-options:trickle
a=fingerprint:sha-256 B4:86:8F:A6:E6:81:C0:73:FE:B2:3E:B1:D7:82:DB:45:68:7E:61:42:66:1F:52:48:52:0A:AD:60:FE:40:20:AC
a=setup:active
a=mid:1
a=extmap:5 urn:ietf:params:rtp-hdrext:toffset
a=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:7 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:local_screen_av_stream 7bf461b5-76a9-4fc4-a399-819be85c5983
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:126 H264/90000
a=rtcp-fb:126 goog-remb
a=rtcp-fb:126 transport-cc
a=rtcp-fb:126 ccm fir
a=rtcp-fb:126 nack
a=rtcp-fb:126 nack pli
a=fmtp:126 packetization-mode=1;profile-level-id=42e01f
a=ssrc:2724353480 cname:obg1pKuTkxaHgcZK

SDP as well doesn't seem to reflect two video tracks. I'm I missing something here

**Comment by spacecheeserocks** [comment]
Your code looks correct to me. 

It's possible that the media was not ready at the time the SDP was created. If this is the case, then you will likely find that a renegotiation is needed - that new SDP should have the second m=video line in it.

A quick hack if you don't want to handle renegotiation would just be to introduce a short delay after adding the second transceiver and creating the offer (5 seconds is more than enough).

I have previously found that even with one webcam, if the webcam is not ready at the time the offer is created, the first SDP offer does not negotiate video.
