### ISSUE TITLE
A NodedssSignaler Implementation for the .Net Core Sample Application. 

### ISSUE THREAD

**Issue by aatd** [microsoft/MixedReality-WebRTC#731]
As far as I unterstood the Samples, it is not possible to let the C# .NET Core interoperate with the other Samples for they are using the NodeDssSignaler as a Connection Base. 

If not I would appreciate it if someone could help me letting the .net Core Sample and the Unity Sample communicate wiht each other. 

Best regards!

**Comment by djee-ms** [comment]
Those samples are showing various options and signaling methods. There's no plan to be exhaustive here. These are samples.
