### ISSUE TITLE
How do I set `Transceiver.StreamIDs` to change the offer (a=msid-semantic) of HoloLens 2

### ISSUE THREAD

**Issue by ylsislove** [microsoft/MixedReality-WebRTC#732]
Hi

I try to use web browser and HoloLens 2 for video communication, and this is the execution flow I follow:
```
1.- Web client enters the conversation.
2.- Hololens client enters and sends the offer.
3.- Web client receives it, sets the SDP and generates the answer.  It is sent to the Hololens.
4.- The Hololens receives it, and saves the SDP.  
5.- Both clients send ICE candidates and receive them.  They complete the ICE gathering.
```

Now, I can see the browser video stream on HoloLens 2, but can't get Hololens 2 stream on browser. I checked the HoloLens 2's offer and the browser's answer, and found the `a=msid-semantic` of HoloLens 2's offer may be different. like this:

This is part of the HoloLens 2's offer:
```
a=group:BUNDLE 0 1
a=msid-semantic: WMS
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 125 104
a=mid:0
a=sendrecv
a=msid:- f583a0a9-2f80-4d85-b6af-ef7ba83ed13d
a=ssrc-group:FID 2667659048 3959474471
a=ssrc:2667659048 cname:CWYsPV9tCmupNHSl
a=ssrc:2667659048 msid: f583a0a9-2f80-4d85-b6af-ef7ba83ed13d
a=ssrc:2667659048 mslabel:
a=ssrc:2667659048 label:f583a0a9-2f80-4d85-b6af-ef7ba83ed13d
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 9 102 0 8 105 13 110 113 126
a=mid:1
a=sendrecv
a=msid:- a69056ce-f68f-49d0-a376-d2012b6ad755
a=ssrc:1498154044 cname:CWYsPV9tCmupNHSl
a=ssrc:1498154044 msid: a69056ce-f68f-49d0-a376-d2012b6ad755
a=ssrc:1498154044 mslabel:
a=ssrc:1498154044 label:a69056ce-f68f-49d0-a376-d2012b6ad755
```

This is part of the browser's answer
```
a=group:BUNDLE 0 1
a=msid-semantic: WMS egMOeAUXRITlOTOaE3PRZZoftadyBOOhMNxy
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 125 104
a=mid:0
a=sendrecv
a=msid:egMOeAUXRITlOTOaE3PRZZoftadyBOOhMNxy dceec5bc-426f-4869-9727-f4df48c98818
a=ssrc-group:FID 300348358 243777033
a=ssrc:300348358 cname:Sqg5iBI1faqe3I0w
a=ssrc:243777033 cname:Sqg5iBI1faqe3I0w
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 9 0 8 105 13 110 113 126
a=mid:1
a=sendrecv
a=msid:egMOeAUXRITlOTOaE3PRZZoftadyBOOhMNxy c30fc5ed-e915-43d5-b189-4326ef006e91
a=ssrc:144003280 cname:Sqg5iBI1faqe3I0w
```

I searched some Issues (see #695 and #657), and found `Transceiver.StreamIDs` may be solve this problem. But I don't know how to set `Transceiver.StreamIDs` and in which script or function. 

Any help will be very appreciated!
Thanks in advance.

**Comment by ylsislove** [comment]
Solve the problem successfully!

I changed the `StartConnection` function of `PeerConnection.cs` script. In line 407, the `StreamIDs` is added to the `TransceiverInitSettings`, like this: 
```csharp
var settings = new TransceiverInitSettings
{
    Name = $"mrsw#{index}",
    InitialDesiredDirection = wantsDir,
    StreamIDs = new List<string>() { "hololens2_stream" }
};
tr = _nativePeer.AddTransceiver(mediaLine.MediaKind, settings);
```

It worked. Now, I can get HoloLens2 stream on browser. Nice~

**Comment by ylsislove** [comment]
I will close this issue.

**Comment by ylsislove** [comment]
Plus, the StreamID should be a UUID string, otherwise there may be some bugs.

**Comment by Rendtime** [comment]
> Plus, the StreamID should be a UUID string, otherwise there may be some bugs.

I also encountered the same problem, but I am using ExternalVideoTrackSource, I don’t know what StreamIDs is set to
我也遇到了同样的问题，使用的是ExternalVideoTrackSource
