### ISSUE TITLE
[Regression] Media Foundation video capture failing on HoloLens 1 and 2

### ISSUE THREAD

**Issue by djee-ms** [microsoft/MixedReality-WebRTC#74]
There is currently a regression issue with the video capture, so far confirmed only on HoloLens 2, where the Media Foundation capture engine successfully open the video capture device and acquires some video samples, but fails to write those video samples to its sink for a yet unknown reason.

Symptoms are, on the remote peer, that the video track coming from HoloLens 2 is negotiated and added (`TrackAdded` signal fired, optionally predated by `RenegotiationNeeded` if appropriate) but no data is sent over the network and consequently the per-frame callback `I420RemoteVideoFrameReady` is never fired, which _e.g._ for TestAppUWP will prevent the media player from starting.

**Comment by fibann** [comment]
After https://github.com/webrtc-uwp/webrtc-windows/pull/66 the streaming starts again. The encoder stalls every once in a while, especially on pipeline reset; we have pinpointed the cause and will fix it soon.

There are a few outstanding issues:
- the initial video quality is very low and stays low for a long time - logged as #107
- most of the CPU time used by capturing and encoding video goes in the round-trip frames go through via main memory and format conversion - we have been trying to reduce the number of copies/conversions, but will only be fixed completely as part of #35

**Comment by djee-ms** [comment]
I will consider this issue fixed since the encoder now reliably starts again. The initial video quality issue has a workaround (see #109), and the optimizations are worked on but will not make it for v1.0.0 anyway. So closing this issue as fixed.
