### ISSUE TITLE
The caller can't see the other person's picture

### ISSUE THREAD

**Issue by tjhappy** [microsoft/MixedReality-WebRTC#745]
**Describe the bug**
I follow the tutorial, “C# tutorial (UWP)”. When the two sides are connected, caller can't see the other person's picture.

**Expected behavior**
_A clear and concise description of what you expected to happen._

**SDP messages**
 Offer =v=0
o=- 212464127989425478 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic: WMS
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:ISha
a=ice-pwd:YOV+XVH3t+LvoO8Y3lPN1vsq
a=ice-options:trickle
a=fingerprint:sha-256 BD:5D:01:BF:30:1D:83:10:A8:C7:7D:C8:38:3A:4B:F9:62:8D:E5:A3:63:F0:15:5C:DA:83:80:C4:FE:4F:0E:5F
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:- 35a637f4-a33e-46d5-82e3-c9331ae16be1
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:458339895 cname:shYgOchhTa5/KxzK
a=ssrc:458339895 msid: 35a637f4-a33e-46d5-82e3-c9331ae16be1
a=ssrc:458339895 mslabel:
a=ssrc:458339895 label:35a637f4-a33e-46d5-82e3-c9331ae16be1
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 124 125
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:ISha
a=ice-pwd:YOV+XVH3t+LvoO8Y3lPN1vsq
a=ice-options:trickle
a=fingerprint:sha-256 BD:5D:01:BF:30:1D:83:10:A8:C7:7D:C8:38:3A:4B:F9:62:8D:E5:A3:63:F0:15:5C:DA:83:80:C4:FE:4F:0E:5F
a=setup:actpass
a=mid:1
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:10 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:- 1659dfae-94fc-4cf5-b83f-95cce57678b0
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 x-google-profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 H264/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 packetization-mode=1
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 red/90000
a=rtpmap:124 rtx/90000
a=fmtp:124 apt=127
a=rtpmap:125 ulpfec/90000
a=ssrc-group:FID 2674265338 851226902
a=ssrc:2674265338 cname:shYgOchhTa5/KxzK
a=ssrc:2674265338 msid: 1659dfae-94fc-4cf5-b83f-95cce57678b0
a=ssrc:2674265338 mslabel:
a=ssrc:2674265338 label:1659dfae-94fc-4cf5-b83f-95cce57678b0
a=ssrc:851226902 cname:shYgOchhTa5/KxzK
a=ssrc:851226902 msid: 1659dfae-94fc-4cf5-b83f-95cce57678b0
a=ssrc:851226902 mslabel:
a=ssrc:851226902 label:1659dfae-94fc-4cf5-b83f-95cce57678b0
***************************
: Answer,v=0
o=- 5305350482668183490 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic: WMS
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:6Ed9
a=ice-pwd:XQ12hIDuX70zxjniaZpHt0Bp
a=ice-options:trickle
a=fingerprint:sha-256 48:B5:0A:4D:2B:E9:8E:B7:D1:18:3F:ED:15:BF:B0:A6:1A:39:DA:C4:4B:67:40:08:8F:9C:9D:5D:CA:F6:9B:5B
a=setup:active
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=recvonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 124 125
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:6Ed9
a=ice-pwd:XQ12hIDuX70zxjniaZpHt0Bp
a=ice-options:trickle
a=fingerprint:sha-256 48:B5:0A:4D:2B:E9:8E:B7:D1:18:3F:ED:15:BF:B0:A6:1A:39:DA:C4:4B:67:40:08:8F:9C:9D:5D:CA:F6:9B:5B
a=setup:active
a=mid:1
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:10 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 x-google-profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 H264/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 packetization-mode=1
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 red/90000
a=rtpmap:124 rtx/90000
a=fmtp:124 apt=127
a=rtpmap:125 ulpfec/90000

**Environment**

MixedReality-WebRTCMixedReality-WebRTC release/2.0
Microsoft Visual Studio Community 2019 ver16.9.0
Windows 10 （19041.928）

**Additional context**

[MainPage.xaml.txt](https://github.com/microsoft/MixedReality-WebRTC/files/6364391/MainPage.xaml.txt)

**Comment by yyanhan** [comment]
I have same problem... 
I have read other's SDP
maybe... the problem is:
in Answer: there are only
"a=recvonly" and "a=recvonly"
but perhaps it should (?) be "a=sendrecv" (tells caller, i want to receive and send)
(but i don't know how to fix it yet)
