### ISSUE TITLE
how to build c# sample Microsoft.MixedReality.WebRTC.TestAppUWP 

### ISSUE THREAD

**Issue by zhuisa** [microsoft/MixedReality-WebRTC#749]
hi! my problem is such like the title: how to build c# sample Microsoft.MixedReality.WebRTC.TestAppUWP? I git clone realse 2 , and open Microsoft.MixedReality.WebRTC.sln by vs 2019 ,and then restore nuget packeges， and select Debug, ARM, and click build. However, I cannot build Microsoft.MixedReality.WebRTC.TestAppUWP. Can you tell me how to deal with? or how to build this sample in correct way. Thank you very much!!!

**Comment by zhuisa** [comment]
I am happy, I know about it. I should shut close my issue.

**Comment by xuhaozheng** [comment]
Hello, can you describe a bit about how to build it? I took the same steps as you described before and also built it in fail.
