### ISSUE TITLE
Can work with ios&android?

### ISSUE THREAD

**Issue by richmonkey** [microsoft/MixedReality-WebRTC#76]
master branch with webrtc-uwp-sdk m71, windows 10
Two question,
1. ios can receive video from unity app which run on pc, but the unity app can't receive video from ios, from wirehshark run on pc,  i known many video data being received, 
but the remote_video_observer_ not be callback, i want to debug the issue,
"
   else if (trackKindStr == webrtc::MediaStreamTrackInterface::kVideoKind) {
    trackKind = TrackKind::kVideoTrack;
    if (auto* sink = remote_video_observer_.get()) {
      rtc::VideoSinkWants sink_settings{};
      sink_settings.rotation_applied =
          true;  // no exposed API for caller to handle rotation
      auto video_track = static_cast<webrtc::VideoTrackInterface*>(track.get());
      video_track->AddOrUpdateSink(sink, sink_settings);
    }
"

2. So i want to build webrtc.lib from webrtc-uwp-sdk (m71), but unfortunately i can't compile it, many compile error, but i can build  webrtc-uwp-sdk(m75), but  MixedReality-WebRTC(feature/m75) can't work now, i don't know how to fix the issue.

anybody test webrtc-uwp with ios?

**Comment by richmonkey** [comment]
How to build webrtc.lib from webrtc-uwp-sdk(m71)?


now project using nuget packages.
  <package id="Microsoft.MixedReality.WebRTC.Native.Core.UWP" version="0.2.0-preview-20190907.1" targetFramework="native" />
  <package id="Microsoft.MixedReality.WebRTC.Native.Core.UWP.ARM.Debug" version="0.2.0-preview-20190907.1" targetFramework="native" />
  <package id="Microsoft.MixedReality.WebRTC.Native.Core.UWP.ARM.Release" version="0.2.0-preview-20190907.1" targetFramework="native" />
  <package id="Microsoft.MixedReality.WebRTC.Native.Core.UWP.x64.Debug" version="0.2.0-preview-20190907.1" targetFramework="native" />
  <package id="Microsoft.MixedReality.WebRTC.Native.Core.UWP.x64.Release" version="0.2.0-preview-20190907.1" targetFramework="native" />
  <package id="Microsoft.MixedReality.WebRTC.Native.Core.UWP.x86.Debug" version="0.2.0-preview-20190907.1" targetFramework="native" />
  <package id="Microsoft.MixedReality.WebRTC.Native.Core.UWP.x86.Release" version="0.2.0-preview-20190907.1" targetFramework="native" />
  <package id="Microsoft.MixedReality.WebRTC.Native.Core.WinRT.ARM.Debug" version="0.2.0-preview-20190907.1" targetFramework="native" />
  <package id="Microsoft.MixedReality.WebRTC.Native.Core.WinRT.ARM.Release" version="0.2.0-preview-20190907.1" targetFramework="native" />
  <package id="Microsoft.MixedReality.WebRTC.Native.Core.WinRT.x64.Debug" version="0.2.0-preview-20190907.1" targetFramework="native" />
  <package id="Microsoft.MixedReality.WebRTC.Native.Core.WinRT.x64.Release" version="0.2.0-preview-20190907.1" targetFramework="native" />
  <package id="Microsoft.MixedReality.WebRTC.Native.Core.WinRT.x86.Debug" version="0.2.0-preview-20190907.1" targetFramework="native" />
  <package id="Microsoft.MixedReality.WebRTC.Native.Core.WinRT.x86.Release" version="0.2.0-preview-20190907.1" targetFramework="native" />

**Comment by djee-ms** [comment]
Hi @richmonkey,

For building the core dependencies there is a build script `tools\build\build.ps1`. You can also find instructions [in the documentation](https://microsoft.github.io/MixedReality-WebRTC/manual/building-core.html). This is generally a bit difficult at first, indeed.

m75 is not currently supported. The `feature/m75` branch is experimental, and frankly I did not work on it recently and do not remember in which state it is, but in any case this is not yet officially supported. I will get back to work on that after the v1.0 release hopefully.

I didn't test MixedReality-WebRTC on iOS. I would like eventually when I have time to add support, but for now this is not a priority. Do you see that call `video_track->AddOrUpdateSink(sink, sink_settings);` being invoked? Or is it also missing a call to the `OnAddTrack()` callback? If the remote video observer is registered correctly then it is very strange that its callback doesn't get called.

**Comment by richmonkey** [comment]
Thanks @djee-ms 

IOS app is official webrtc,  not MixedReality-WebRTC, in theory  MixedReality-WebRTC can work with other platform's webrtc (ios&android&browser).

 Do you see that call video_track->AddOrUpdateSink(sink, sink_settings); being invoked? 
Yes,
I can debug MixedReality-WebRTC solution with installed uwp app, and breakpoint on that line code, 
and add debug.log in 
libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Media/RemoteVideoSource.cs:TrackAdded&TrackAdded functions


webrtc-uwp-sdk(m75) can receive video from ios on uwp, but can't show video on unity3d, 
so i test MixedReality-WebRTC.

MixedReality-WebRTC's design and code is beautiful，i like it.

**Comment by djee-ms** [comment]
Thanks!

Yes, all projects using a standard implementation of WebRTC should be compatible with each other, so I expect apps based on MixedReality-WebRTC to be compatible with other apps based on _e.g._ `webrtc-uwp-sdk` or Google's `libwebrtc`, or any other implementation.

Do you know if the iOS app uses the Unified Plan or the legacy Plan B for the SDP semantic? I believe in m75 the default is Unified Plan. I changed the default of MixedReality-WebRTC yesterday to also be Unified Plan (see 87e15921ab91d16f3e56a888353df11e8faba397). Maybe this is related. You can try reverting to Plan B for testing, using [`PeerConnectionConfiguration.SdpSemantic`](https://microsoft.github.io/MixedReality-WebRTC/api/Microsoft.MixedReality.WebRTC.PeerConnectionConfiguration.html#Microsoft_MixedReality_WebRTC_PeerConnectionConfiguration_SdpSemantic).

Other than that, I have no other guess on top of my head, sorry.

**Comment by richmonkey** [comment]
Still can't work.
ios and  MixedReality-WebRTC both use plan b.
peerconnection only have one video & one audio track, so Unified Plan or plan b is't different. 


the isse like:
https://www.physicsforums.com/threads/cygwin-cant-receive-udp-packet-using-recvfrom.637620/

whireshark view many data, but app receive nothing.

**Comment by richmonkey** [comment]
now it works, 
manual change the project which exported from unity editor


int CALLBACK wWinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPWSTR lpCmdLine, int nCmdShow)
{

	WORD wVersionRequested;
	WSADATA wsaData;
	int err;

	wVersionRequested = MAKEWORD(2, 2);
	err = WSAStartup(wVersionRequested, &wsaData);
	if (err != 0) {
		/* Tell the user that we could not find a usable */
		/* Winsock DLL.                                  */
		printf("WSAStartup failed with error: %d\n", err);
		return 1;
	}

**Comment by djee-ms** [comment]
@richmonkey glad to hear it works, but I am not sure I understand what change you made. I assume you are generating a project from Unity with IL2CPP right? Which version of Unity are you using? And what change did you make exactly? Did you add the WinSock initializing code you pasted?

**Comment by richmonkey** [comment]
Thanks @djee-ms 
my unity editor version:2019.1.14f1

I assume you are generating a project from Unity with IL2CPP right? YES

Did you add the WinSock initializing code you pasted? YES, I manual add the wsastartup in the wWinMain.

Still the app is't work well everytime, i need more test. 
maybe wsastartup is't the keypoint.

Maybe the problem is the performance of the app and machine, when machine is poor and the decoder need power cpu,  cause udp package dropped by app.

**Comment by djee-ms** [comment]
Ok thanks for the details. I am surprised Unity doesn't already initialize the network, maybe we should report that as an issue.

If the machine has some hardware encoder/decoder you can try forcing a video codec with [`PeerConnection.PreferredVideoCodec`](https://microsoft.github.io/MixedReality-WebRTC/api/Microsoft.MixedReality.WebRTC.PeerConnection.html#Microsoft_MixedReality_WebRTC_PeerConnection_PreferredVideoCodec) before calling `CreateOffer()`. I know that on HoloLens 2 this helps a lot.
```
PeerConnection.PreferredVideoCodec = "H264";
```

**Comment by djee-ms** [comment]
Also I just remembered, in Debug the internal WebRTC code sometimes becomes very slow. And IL2CPP on Debug is also very slow depending on what you do, as it outputs a lot of unnecessary code without any optimization. If you didn't try already, you should try the Release config for everything and see if the problem persists.

**Comment by richmonkey** [comment]
thanks, @diee-ms
I test webrtc-uwp with browser(js api), it works.
so the problem is my ios app.
I will do more work to fix the problem of my ios app.

**Comment by djee-ms** [comment]
Ok thanks for the feedback!
