### ISSUE TITLE
HoloLens 2 : Cannot connect to destination host - Bad access 

### ISSUE THREAD

**Issue by alxfigueiredo** [microsoft/MixedReality-WebRTC#769]
Hello everyone,

I followed this MRTK-Webrtc tutorial from Microsoft: https://microsoft.github.io/MixedReality-WebRTC/manual/unity/helloworld-unity.html

Everything goes well, until the HoloLens 2 tries to connect to the node-dss server. The answer in the console is: "Cannot connect to destination host" or "Curl error 7 ... : bad access" to the IP address of my computer.

I tried to deploy the application on a second computer and it worked. The problem seems to come from the deployment on HoloLens 2.

Can someone help me? I have searched many forums and issues on this git without finding the solution. Many people were talking about firewalls (which I tried to disable but without success).

I'm using Unity 2019.4.26f1 and MRTK-Webrtc 2.0.2

Here is a picture of the development console on HoloLens 2 :

![Error_Connexion_MRTK-Webrtc](https://user-images.githubusercontent.com/62652075/121491836-9bdbf500-c9d6-11eb-8897-46ab71d29dc1.jpg)

Thanks a lot !

**Comment by spacecheeserocks** [comment]
Sounds like a firewall issue of some kind to me too.

Assuming you've already tried some basic troubleshooting, some other things to consider are:
- In your HoloLens UWP, **ensure the PrivateNetworkClientServer capability is enabled**.  
  If this is not enabled, the UWP sandbox will prevent traffic to the local network (e.g. it only allows communication to the internet).  
  (This is not normally an issue for production apps, unless you plan your production build to also connect to a local server)
- Try (temporarily) turning off all firewalls on the PC with DSS (if you use a third party firewall/antivirus, you may find that Windows Firewall is also enabled)
- If your DSS server is (for some reason) in some kind of sandbox (e.g. a UWP application), ensure that has InternetClientServer capability. If you are running your DSS server in a VM, WSL, Docker etc, there are similar things to check here (by default, Docker and WSL seem to use the windows firewalls though).
- Consider the internal networking too - does your WiFi Network/Router "isolate" clients (e.g. prevent clients from talking to eachother?) If your desktop uses Ethernet, is it on the same network as the WiFi access point? If it's a corporate network, you may have network-level firewalls between the devices too.

**Comment by alxfigueiredo** [comment]
Hello, thank you for your answer !

Finally i was able to Deploy WEB-RTC to another Unity project.
Having compared the configurations of the two projects, I find no difference. I can't explain why in the first one it doesn't work.

However I suspect that my first project (which does not work) was too far from the root of the C:\ drive and lost some files during compilation. I saw this information on MRTK Documentation : 

<img width="484" alt="MAX_PATH_ENG" src="https://user-images.githubusercontent.com/62652075/122040409-0d051900-cdd8-11eb-8f2f-7b5f67cd0b62.PNG">

And when importing MRTK i was maybe loosing some important files. But I Can't confirm that..
