### ISSUE TITLE
Add Mute/Unmute of local video and audio

### ISSUE THREAD

**Issue by eirikhollis** [microsoft/MixedReality-WebRTC#79]
Enhancement.

Add the possibility to toggle local video/audio on and off.
[It's a simple boolean on the MediaStreamTrack object.](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/enabled)

**Comment by djee-ms** [comment]
That looks easy enough. I will have a look.

**Comment by djee-ms** [comment]
Added [`PeerConnection.SetLocalVideoTrackEnabled()`](https://microsoft.github.io/MixedReality-WebRTC/api/Microsoft.MixedReality.WebRTC.PeerConnection.html#Microsoft_MixedReality_WebRTC_PeerConnection_SetLocalVideoTrackEnabled_System_Boolean_) and [`PeerConnection.IsLocalVideoTrackEnabled()`](https://microsoft.github.io/MixedReality-WebRTC/api/Microsoft.MixedReality.WebRTC.PeerConnection.html#Microsoft_MixedReality_WebRTC_PeerConnection_IsLocalVideoTrackEnabled).

**Comment by djee-ms** [comment]
And 8101f4ecca3fdd2dd6b8545699907deaaf0ec67f adds support for muting the local audio track. Closing as fixed.
