### ISSUE TITLE
Suitable for remote rendering?

### ISSUE THREAD

**Issue by jahnotto** [microsoft/MixedReality-WebRTC#80]
Is this project suitable for remote rendering, or is it meant primarily to communicate between MR devices?

I'm looking for a solution similar to 3D Streaming Toolkit for Hololens 2 use. This project seems like it has better support though.

**Comment by djee-ms** [comment]
Hi @jahnotto,

This project is meant to provide support for Mixed Reality apps, whether it's on an MR device like HoloLens 1/2 or on a PC communicating with it, it doesn't matter. To some extent, it can even be used on any other app not related to MR at all, albeit knowing that developers resourcing for new features etc. will focus primarily on Mixed Reality applications.

On the uses cases, that includes "remote rendering" in the sense of Mixed Reality Capture, that is steaming out the video capture + overlay hologram rendering from HoloLens 1/2 to any remote device, including a PC. That also includes HoloLens to HoloLens for, say, audio and/or video chat. All of these use cases are supported, and more. If you are looking to stream some video or audio out from HoloLens to a PC, even with some extra data, then yes, this project is definitely suitable for your use case.

**Comment by jahnotto** [comment]
Awesome. Thank you @djee-ms !

**Comment by djee-ms** [comment]
You're welcome @jahnotto! If you don't have any other question, can I close this issue?

**Comment by jahnotto** [comment]
Yes, go ahead!
