### ISSUE TITLE
Low FPS while VideoStreaming in HoloLens2

### ISSUE THREAD

**Issue by SilverLive** [microsoft/MixedReality-WebRTC#800]
With one open MediaLine which receives and sends Video content and displays it, I archive a total over all performance of 30 FPS in my deployed HoloLens2 application. Is there a way to enhance this value in terms of WebRTC?  I tried a few other VideoProfileKinds than "Video Conferencing" but it seems like HoloLens2 only supports "Video Conferencing".

**Comment by SilverLive** [comment]
Hi, thanks for answering! This helped me a lot to understand the problem. Yes, I am using MixedRealityCapture. In case, that 30fps are not enough for my usecase... There is no better way of sharing the mixed reality content with an audience without any external tools or miracast, right?

**Comment by djee-ms** [comment]
No software way.

https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/mixed-reality-capture-for-developers

> **What to expect when MRC is enabled on HoloLens**
> The system will throttle the application to 30-Hz rendering. This creates some headroom for MRC to run so the app doesn’t need to keep a constant budget reserve and also matches the MRC video record framerate of 30 fps

**Comment by SilverLive** [comment]
Top, thank you very much! I will close the Question.
