### ISSUE TITLE
Multiple PeerConnections supported?

### ISSUE THREAD

**Issue by eanders-MS** [microsoft/MixedReality-WebRTC#81]
I have a Unity project based on https://github.com/microsoft/MixedReality-WebRTC/tree/master/libs/Microsoft.MixedReality.WebRTC.Unity. I've added additional PeerConnections to play different remote streams simultaneously. Is this a supported scenario? Unity crashes in the WebRTC native DLL when I run the scene. I'm still investigating the cause of the crash, but wanted to check whether or not this is fundamentally supported by the library. Thanks!

**Comment by eanders-MS** [comment]
Here's the callstack in case it's useful:
```
0x00007FFE89931CFB (Microsoft.MixedReality.WebRTC.N) rtc::Thread::InvokeInternal
0x00007FFE89A2705E (Microsoft.MixedReality.WebRTC.N) rtc::Thread::Invoke<void,rtc::MethodFunctor<cricket::PortAllocator,void (__cdecl cricket::PortAllocator::*)(int) __ptr64,void,int> >
0x00007FFE89A40597 (Microsoft.MixedReality.WebRTC.N) webrtc::PeerConnectionFactory::CreatePeerConnection
0x00007FFE89A24E4B (Microsoft.MixedReality.WebRTC.N) webrtc::ReturnType<rtc::scoped_refptr<webrtc::PeerConnectionInterface> >::Invoke<webrtc::PeerConnectionFactoryInterface,rtc::scoped_refptr<webrtc::PeerConnectionInterface> (__cdecl webrtc::PeerConnectionFactoryInterface::*)(webrtc::PeerConnectionInterface::RTCConfiguration const & __ptr64,webrtc::PeerConnectionDependencies) __ptr64,webrtc::PeerConnectionInterface::RTCConfiguration,webrtc::PeerConnectionDependencies>
0x00007FFE89A491A7 (Microsoft.MixedReality.WebRTC.N) webrtc::MethodCall2<webrtc::PeerConnectionFactoryInterface,rtc::scoped_refptr<webrtc::PeerConnectionInterface>,webrtc::PeerConnectionInterface::RTCConfiguration const & __ptr64,webrtc::PeerConnectionDependencies>::OnMessage
0x00007FFE89C19A0C (Microsoft.MixedReality.WebRTC.N) webrtc::internal::SynchronousMethodCall::OnMessage
0x00007FFE899E6870 (Microsoft.MixedReality.WebRTC.N) rtc::MessageQueue::Dispatch
0x00007FFE89932648 (Microsoft.MixedReality.WebRTC.N) rtc::Thread::ProcessMessages
0x00007FFE89932838 (Microsoft.MixedReality.WebRTC.N) rtc::Thread::Run
0x00007FFE89932492 (Microsoft.MixedReality.WebRTC.N) rtc::Thread::PreRun
```

**Comment by djee-ms** [comment]
Hi @eanders-MS,

This should be supported in theory, but realistically I never tried it, and won't have time to in an immediate future. I can help debugging though. I wouldn't be surprised to see some sort of race condition, as I am not sure all systems are well protected for that yet.

Note that webrtc calls are proxied on webrtc threads; the callstack you pasted above is the caller, but it just sends a message to the webrtc thread and wait for it. The actual work is done on the webrtc thread. I am actually surprised if that crashes in that one thread, as it only posts a message and waits; I don't see in the callstack what kind of crash that could be.

**Comment by eanders-MS** [comment]
Ok. It may be a week or so before I have a chance to look at this, but I will take you up on your offer to help debug :)

**Comment by djee-ms** [comment]
I can repro with a second peer connection in Unity, will investigate.

**Comment by djee-ms** [comment]
@eanders-MS the crash you had should be fixed, the peer connection factory is now lazily initialized in a thread-safe way. I dropped a second `PeerConnection` component in the `VideoChatDemo` sample app in Unity and I can Play/Stop several time without any visible issue. I think the other parts of the code don't make use of globals so should be fine working on multiple instances in parallel.

**Comment by eanders-MS** [comment]
It's working now, thank you!

**Comment by Boo0317** [comment]
I'm trying to create multiple peerconnections,but only the first peerconnection can get local video frame from camera.
Did I do something wrong？

**Comment by djee-ms** [comment]
@Boo0317 are you trying to get the same local webcam used for multiple video tracks? This is not possible, the local webcam is opened in exclusive mode, so can be used by at most 1 track (and more generally a single app on your machine). I don't think there is any easy way to use shared mode; in addition of not being currently supported, last I remember there was some issue on UWP when trying to open the webcam in shared mode (but can't remember the details, sorry).

**Comment by Boo0317** [comment]
I'm trying multiple video calling，The ideal approach is to receive multiple remote tracks，but as far as I know, it's not feasible right now.so I try to create another peerconnection , I looked at the source code,found that everytime call AddLocalVideoTrackAsync, it will open the camera once.Do I need to AddLocalVideoTrackAsyncfor every peerconnection?
My English is not good, I don't know if I made myself clear,Thank you.

**Comment by djee-ms** [comment]
You probably cannot send the same webcam video feed to multiple peers, because as you saw they will all try to access exclusively the webcam, which won't work, and there is no possibility to share track sources between multiple peer connections. This simply cannot be done without #152.
