### ISSUE TITLE
Edit Unity Webcam Source

### ISSUE THREAD

**Issue by xuhaozheng** [microsoft/MixedReality-WebRTC#810]
**1. The original Webcam Source will only select the first camera in the list. How can we select the target camera we want in Unity? I think selecting a specific camera should be a very important and necessary function.** 

In UWP/Desktop it's very easy since we could edit the code as we want, but Unity the WebRTC component seems to be unable to change.

**2. Can we edit the Webcam Souce to achieve that?[Can we edit WebRTC script?]**

I've tried to copy the Webcam Source script totally and change the Device id as I want. The camera could work normally on Local Video Player while the modified webcam_source script cannot be recognized as a component by PeerConnection so that the video data cannot be transferred.

**Comment by ChrisTJie** [comment]
Has your problem been solved?

**Comment by xuhaozheng** [comment]
I edited the WebCom.cs to set the device id as I want.
