### ISSUE TITLE
I want to do it so that the four of us can watch the HoloLens2 video.

### ISSUE THREAD

**Issue by nybg** [microsoft/MixedReality-WebRTC#817]
First of all, I'm sorry that I'm using a translator. I don't have any English skills.

The final appearance I think is that I want to send a HoloLens video/voice to four web browser users.

I succeeded in 1:1 communication, but when I try to connect from another web browser, the error below appears. Please tell me a solution or a solution.

![20210908_180723](https://user-images.githubusercontent.com/85145376/132480746-836e1676-67c3-4340-b102-6c962800b63f.png)

**Comment by djee-ms** [comment]
WebRTC is a peer-to-peer 1:1 technology. You cannot do that.

If you really want to connect 4 people, you need to setup a media server, and connect all 4 clients to it. See for example [Janus](https://janus.conf.meetecho.com/) (Disclaimer: I/Microsoft has no affiliation with Jannus; I just know some people had success with it. Other servers should work too, since WebRTC is standardized).

**Comment by nybg** [comment]
Thank you so much for your kind and quick response.

I looked it up and told WebRTC that the SFU method supports 1:N. I don't think this is possible either.

**Comment by djee-ms** [comment]
SFU and MTU require a media server. They're technology that build on top of WebRTC; they're not part of the WebRTC standard itself.

**Comment by nybg** [comment]
@djee-ms 
![image](https://user-images.githubusercontent.com/85145376/132608885-026e07a0-96e4-4219-bada-86eb688da7bc.png)

The Peer to Peer (Mesh) method allows two to three people to exchange data without a server, but can this be applied?

**Comment by djee-ms** [comment]
The mesh method uses 1 peer connection per pair of peers. So here you have 3 peer connections in your example. You can use that, but that scales very poorly. However that doesn't require any media server, true.

**Comment by nybg** [comment]
Thank you so much for your kind reply.

It was a lot of reference and help.

I will end the issue.
