### ISSUE TITLE
When Hololens 2 Connect to Wi-Fi the fps will be drop very low

### ISSUE THREAD

**Issue by Xiink** [microsoft/MixedReality-WebRTC#829]
I have creat a connect to Hololens2 and My PC.
It good work when I use usb connect to PC the FPS always foucs on 30.
But when I let Hololens connect to Wi-Fi the FPS will be drop very low it just 0.5 . 

Maybe the problem is on my network?
Please help me to fix this problem and forgive me for being terrible in my English.

**Comment by spacecheeserocks** [comment]
### If the App itself is running slowly
If you are debugging the app via WiFi (e.g. clicking the green 'Play' button in Visual Studio), the app will run slowly.

Try running the app by launching on HoloLens, or in visual studio, select "Debug > Start without debugging" to see if it runs faster.

### If the video framerate is low
Your WiFi network likely is not fast enough to transmit the video. Try reducing the video resolution of the webcam to get better performance.

**Comment by Xiink** [comment]
> ### If the App itself is running slowly
> If you are debugging the app via WiFi (e.g. clicking the green 'Play' button in Visual Studio), the app will run slowly.
> 
> Try running the app by launching on HoloLens, or in visual studio, select "Debug > Start without debugging" to see if it runs faster.
> 
> ### If the video framerate is low
> Your WiFi network likely is not fast enough to transmit the video. Try reducing the video resolution of the webcam to get better performance.

The problem is indeed that my WiFi network is not fast enough and I had already fixed it.
Thank for your help!
