### ISSUE TITLE
MR WebRTC App crashes on new Windows-Holographic-OS-Version (21H1)

### ISSUE THREAD

**Issue by SilverLive** [microsoft/MixedReality-WebRTC#833]
Hi developers, 

I built an app with the WebRTC Package which works fine with my old HoloLens2 with Windows Holographic Version 10.0.18362.1005. Now, on my new device with Version 21H1(20348.1014) the app crashes straight after App start. The reason for this seems to be, that I build and deploy the app for ARM-Solution-Platform on Visual Studio. If I deploy it with ARM64 the app doesn´t crash, but as far as I know, MR-WebRTC is only supported on ARM. Is there a way to use MR-WebRTC with newer OS-Versions?

**Comment by spacecheeserocks** [comment]
I see this was closed without answer, did you encounter an issue with this OS version?

**Comment by SilverLive** [comment]
No I didn´t get over that problem. I was setting up another Question about this unintentionally. Maybe you can still help me with this?

**Comment by spacecheeserocks** [comment]
I haven't yet tried it on the new OS, I was just generally curious. If I find issues or fixes, I'll reply here or in new issues.

**Comment by SilverLive** [comment]
OK, thank you very much. So I keep this issue open.

**Comment by SilverLive** [comment]
Now I was able to fix it. With one of my Provisioning-Packages I disabled the usage of microphone for mixedReality and it seems like access to those audio-informations is mandatory for MR-WebRTC even if you are not transmitting any audio (no audio media-line) via WebRTC... Maybe this should be mentioned somewhere in the documentation Microsoft!
