### ISSUE TITLE
Compatibility issue with newer Windows Holographic Versions(21H1)? 

### ISSUE THREAD

**Issue by SilverLive** [microsoft/MixedReality-WebRTC#834]
My MR-WebRTC Application which worked on an old OS-Version of my HoloLens2 is now crashing straight after startup if I build it with ARM-compatiblility. On the other hand, if I build it with ARM64 compatibility, it does not crash but MR-WebRTC does not support ARM64. 

Is there a way how to use MR-WebRTC on Windows Holographic Version 21H1 and higher(with ARM-compatibility) and what could be the reason behind the crash?

**Comment by SilverLive** [comment]
Now I was able to fix it. With one of my Provisioning-Packages I disabled the usage of microphone for mixedReality and it seems like access to those audio-informations is mandatory for MR-WebRTC even if you are not transmitting any audio (no audio media-line) via WebRTC. It had nothing to do with the OS-Version. Maybe this should be mentioned somewhere in the documentation Microsoft!

**Comment by spacecheeserocks** [comment]
I have seen this before, it's definitely documented *somewhere* but it's not completely obvious. 

But yes, as you say, microphone is required to init the library, even if you don't plan to use it.
