### ISSUE TITLE
Unreal Engine ARM

### ISSUE THREAD

**Issue by gvindiol** [microsoft/MixedReality-WebRTC#838]
What's the process to go about packaging a Hololens2 Project for ARM32 and not ARM64?

I change the Target Platform to Hololens.
(Target.Platform == UnrealTargetPlatform.HoloLens)

![image](https://user-images.githubusercontent.com/44582391/144400424-c43c4f51-a076-48aa-94ae-50cd9def0947.png)

**Comment by spacecheeserocks** [comment]
There is no ARM64 build for this library (to my knowledge anyway!). Any ARM library you have is for "ARM32".

**Comment by gvindiol** [comment]
When I attempt to package my project for Hololens in Unreal Engine that uses mrwebrtc as a third-party plugins.
`UATHelper: Packaging (HoloLens):   Using ARM64 architecture for deploying to HoloLens device`

**Comment by spacecheeserocks** [comment]
Oh, I understand. I'm not too sure either.

I don't have much experience with Unreal Engine, it's probably best to hunt in their docs to see if there is a way to change the build platform.
