### ISSUE TITLE
Feature request: allow RecordingIndicatorEnabled to be explicitly set

### ISSUE THREAD

**Issue by kspark-scott** [microsoft/MixedReality-WebRTC#96]
When you enable mixed reality capture (`PeerConnection.LocalVideoTrackSettings.enableMrc=true`), the recording indicator is automatically enabled and appears in the HoloLens display as a flashing white video camera icon on a red background.

I believe the low level APIs allow the indicator to be independently enabled, e.g. search either of these for `RecordingIndicatorEnabled`:
- `external/webrtc-uwp-sdk/webrtc/xplatform/webrtc-apis/windows/wrapper/impl_webrtc_MRCVideoEffectDefinition.h`
- https://docs.microsoft.com/en-us/windows/mixed-reality/mixed-reality-capture-for-developers

I have confirmed in a simple `Windows.Media.Capture.MediaCapture` sample app that the indicator can be set on or off via the mrc video effect and am assuming that it would work in the context of WebRTC as well.

While this seems like a small thing, it is a requirement for us that the indicator be disabled.  This is one of the customizations we applied to the m62 build we have been using.  We would be prepared to do our own custom build of this project to disable it by default, but if it could be added as a configuration API option, completely analogous to `LocalVideoTrackSettings.enableMRC`, that would be fantastic.  We could then use the official NuGet packages without modification and our integration of WebRTC would become very simple.

I believe this would require API changes in webrtc-uwp-sdk to export that config option.  Is that potentially in scope for this project?

**Comment by djee-ms** [comment]
Hi @kspark-scott,

Yes that sounds _a priori_ like the kind of thing we'd like to support. Do you have a time constraint for this feature?

**Comment by kspark-scott** [comment]
Excellent news @djee-ms.  I just confirmed with the boss that we do not need this for Ignite (i.e. I wouldn't try to do the customized build just for this).  We are just finalizing a release now, so ideally this would be available for the next one -- we expect it to be our HL2 preview release -- which is tentatively in the late November, early December time frame.

**Comment by djee-ms** [comment]
The build is already running though 😅
NuGet packages should be out today. Turns out it was fairly quick and easy to integrate thanks to your pointers.

**Comment by kspark-scott** [comment]
💯 (Couldn't find a "thunderous applause" emoji)

**Comment by djee-ms** [comment]
Fixed in 08e83d32d061894d5671e98efbdba3701f16a40f.
