### ISSUE TITLE
NullReferenceExcepton  when run on pc as uwp app

### ISSUE THREAD

**Issue by richmonkey** [microsoft/MixedReality-WebRTC#98]
NullReferenceExcpetion occure on 
LocalVideoSource.DoAutoStartActions 

the output:

onecoreuap\drivers\mobilepc\sensors\convergence\api\winrt\public\lib\simpleorientationsensor.cpp(134)\Windows.Devices.Sensors.dll!00007FFBD8622675: (caller: 00007FFBD861F2BF) ReturnHr(1) tid(1ff0) 80070490 找不到元素。
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\windows.applicationmodel.datatransfer.dll'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\coml2.dll'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\iertutil.dll'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\deviceaccess.dll'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\Windows.Shell.ServiceHostBuilder.dll'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\edputil.dll'. Cannot find or open the PDB file.
onecoreuap\xbox\devices\api\winrt\pnpdevice.cpp(506)\Windows.Gaming.Input.dll!00007FFC06ED7AB8: (caller: 00007FFC06ECEBBC) ReturnHr(1) tid(3ba4) 80070005 拒绝访问。
onecoreuap\xbox\devices\api\winrt\pnpdevice.cpp(506)\Windows.Gaming.Input.dll!00007FFC06ED7AB8: (caller: 00007FFC06ECEBBC) ReturnHr(2) tid(3ba4) 80070005 拒绝访问。
onecoreuap\xbox\devices\api\winrt\pnpdevice.cpp(506)\Windows.Gaming.Input.dll!00007FFC06ED7AB8: (caller: 00007FFC06ECEBBC) ReturnHr(3) tid(3ba4) 80070020 另一个程序正在使用此文件，进程无法访问。
Exception thrown at 0x00007FFC0E0BA388 (KernelBase.dll) in Microsoft.MixedReality.WebRTC.Unity.exe: WinRT originate error - 0x8004006A : 'DataPackage 不包含指定格式。请使用 DataPackageView.Contains 或 DataPackageView.AvailableFormats 验证该格式是否存在。'.
onecoreuap\xbox\devices\api\winrt\pnpdevicewatcher.cpp(500)\Windows.Gaming.Input.dll!00007FFC06EDAA93: (caller: 00007FFC06EDA24A) ReturnHr(4) tid(3ba4) 80070020 另一个程序正在使用此文件，进程无法访问。
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\userenv.dll'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\profext.dll'. Cannot find or open the PDB file.
onecoreuap\xbox\devices\api\winrt\pnpdevice.cpp(506)\Windows.Gaming.Input.dll!00007FFC06ED7AB8: (caller: 00007FFC06ECEBBC) ReturnHr(5) tid(3ba4) 80070005 拒绝访问。
onecoreuap\xbox\devices\api\winrt\pnpdevice.cpp(506)\Windows.Gaming.Input.dll!00007FFC06ED7AB8: (caller: 00007FFC06ECEBBC) ReturnHr(6) tid(3ba4) 80070005 拒绝访问。
onecoreuap\xbox\devices\api\winrt\pnpdevice.cpp(506)\Windows.Gaming.Input.dll!00007FFC06ED7AB8: (caller: 00007FFC06ECEBBC) ReturnHr(7) tid(3ba4) 80070005 拒绝访问。
onecoreuap\xbox\devices\api\winrt\pnpdevice.cpp(506)\Windows.Gaming.Input.dll!00007FFC06ED7AB8: (caller: 00007FFC06ECEBBC) ReturnHr(8) tid(3ba4) 80070005 拒绝访问。
onecoreuap\xbox\devices\api\winrt\pnpdevice.cpp(506)\Windows.Gaming.Input.dll!00007FFC06ED7AB8: (caller: 00007FFC06ECEBBC) ReturnHr(9) tid(3ba4) 80070005 拒绝访问。
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\OneCoreCommonProxyStub.dll'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\SensorsNativeApi.dll'. Cannot find or open the PDB file.
ERROR FindDefaultInterface:CM_Get_Device_Interface_List_Size failed:0x00000000, InterfaceListSize = 1 
ERROR SensorOpenByType:Failed to open sensor error:0x00000490
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\wininet.dll'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\sspicli.dll'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\Windows.Media.dll'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Users\jingkangchen\Desktop\nn\build\bin\x64\Release\AppX\Microsoft.MixedReality.WebRTC.Native.dll'. Symbols loaded.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\tokenbinding.dll'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\OnDemandConnRouteHelper.dll'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\winnsi.dll'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\MFCaptureEngine.dll'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\mfcore.dll'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\ksuser.dll'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\CompPkgSup.dll'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\FSClient.dll'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\mfsensorgroup.dll'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\Windows.Media.MediaControl.dll'. Cannot find or open the PDB file.
The thread 0xb68 has exited with code 0 (0x0).
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\CryptoWinRT.dll'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\vidcap.ax'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\Kswdmcap.ax'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.17134.1067_none_5572ed0d2662593b\comctl32.dll'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\mfc42.dll'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\policymanager.dll'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\igdlh64.inf_amd64_14038209c9e5bdbd\igd11dxva64.dll'. Cannot find or open the PDB file.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\CoreMmRes.dll'. Module was built without symbols.
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Unloaded 'C:\Windows\System32\CoreMmRes.dll'
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Loaded 'C:\Windows\System32\CoreMmRes.dll'. Module was built without symbols.
The thread 0x3bf8 has exited with code 0 (0x0).
Exception thrown at 0x00007FFC0E0BA388 in Microsoft.MixedReality.WebRTC.Unity.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x000000A5AF6FF078.
The thread 0x2c60 has exited with code 0 (0x0).
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Unloaded 'C:\Windows\System32\CoreMmRes.dll'
The thread 0x2dec has exited with code 0 (0x0).
The thread 0x2c1c has exited with code 0 (0x0).
The thread 0xe0 has exited with code 0 (0x0).
The thread 0xa68 has exited with code 0 (0x0).
The thread 0x2de8 has exited with code 0 (0x0).
The thread 0x2f60 has exited with code 0 (0x0).
The thread 0x5b0 has exited with code 0 (0x0).
The thread 0x3484 has exited with code 0 (0x0).
The thread 0x9dc has exited with code 0 (0x0).
The thread 0x970 has exited with code 0 (0x0).
The thread 0xe34 has exited with code 0 (0x0).
The thread 0x36d0 has exited with code 0 (0x0).
'Microsoft.MixedReality.WebRTC.Unity.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\igdlh64.inf_amd64_14038209c9e5bdbd\igd11dxva64.dll'
The thread 0x3940 has exited with code 0 (0x0).
The thread 0x25e4 has exited with code 0 (0x0).
The thread 0x1328 has exited with code 0 (0x0).
The thread 0x1e10 has exited with code 0 (0x0).
The thread 0x2214 has exited with code 0 (0x0).
The thread 0x1aec has exited with code 0 (0x0).
The thread 0x1444 has exited with code 0 (0x0).
The thread 0x3224 has exited with code 0 (0x0).
Exception thrown at 0x00007FFC0E0BA388 in Microsoft.MixedReality.WebRTC.Unity.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x000000A5B29FFA28.
Exception thrown at 0x00007FFC0E0BA388 in Microsoft.MixedReality.WebRTC.Unity.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x000000A5B29FF488.
Exception thrown at 0x00007FFC0E0BA388 in Microsoft.MixedReality.WebRTC.Unity.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x000000A5B29FF5D0.
Exception thrown at 0x00007FFC0E0BA388 in Microsoft.MixedReality.WebRTC.Unity.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x000000A5B29FF4E8.
Exception thrown at 0x00007FFC0E0BA388 in Microsoft.MixedReality.WebRTC.Unity.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x000000A5B29FF4E8.
Exception thrown at 0x00007FFC0E0BA388 in Microsoft.MixedReality.WebRTC.Unity.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x000000A5B29FF4B8.
Exception thrown at 0x00007FFC0E0BA388 in Microsoft.MixedReality.WebRTC.Unity.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x000000A5B29FEDA8.
Exception thrown at 0x00007FFC0E0BA388 in Microsoft.MixedReality.WebRTC.Unity.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x000000A5B29FEE38.
Exception thrown at 0x00007FFC0E0BA388 in Microsoft.MixedReality.WebRTC.Unity.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x000000A5B29FEE38.
Exception thrown at 0x00007FFC0E0BA388 in Microsoft.MixedReality.WebRTC.Unity.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x000000A5B29FE8C8.
Exception thrown at 0x00007FFC0E0BA388 in Microsoft.MixedReality.WebRTC.Unity.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x000000A5B29FE928.
Exception thrown at 0x00007FFC0E0BA388 in Microsoft.MixedReality.WebRTC.Unity.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x000000A5AF6FEE58.
The thread 0x2790 has exited with code 0 (0x0).

**Comment by richmonkey** [comment]
Exceptions from log
1. Windows.Gaming.Input.dll can't access 
2. ERROR FindDefaultInterface:CM_Get_Device_Interface_List_Size failed:0x00000000, InterfaceListSize = 1
ERROR SensorOpenByType:Failed to open sensor error:0x00000490

**Comment by richmonkey** [comment]
It works in unity editor, but exception when run as standalone player

**Comment by richmonkey** [comment]
After install Windows Mixed Reality application in the system，the problem fixed.

**Comment by djee-ms** [comment]
Ok glad to hear that issue is solved! :)
